import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
import {createEmptyManualDocument} from '../src/redesign/manual-v2.mjs';
import {createManualState} from '../src/redesign/manual-kernel.mjs';
import {selectManualBlocks,selectManualBlockIds} from '../src/redesign/manual-block-selection.mjs';
const source=readFileSync(process.env.LDS_RANGE_SOURCE||new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8'),require=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url)),{parse}=require('@babel/parser'),ast=parse(source,{sourceType:'module',plugins:['jsx']});let restore,command,eligibility;
function walk(n){if(!n||typeof n!=='object')return;if(n.type==='VariableDeclarator'&&n.id.name==='settleRange')restore=source.slice(n.init.start,n.init.end);if(n.type==='FunctionDeclaration'&&n.id.name==='command')command=source.slice(n.start,n.end);if(n.type==='FunctionDeclaration'&&n.id.name==='deferredFocusEnabled')eligibility=source.slice(n.start,n.end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}walk(ast);
function harness(){const doc=createEmptyManualDocument();doc.pages[0].blocks=['one','two','three'].map(text=>({type:'paragraph',id:crypto.randomUUID(),content:[{type:'text',text}]}));let state=createManualState({document:doc}),dispatches=0;const editor={editable:true,composing:false,dom:{isConnected:true},get state(){return state},dispatch(tr){dispatches++;state=state.applyTransaction(tr).state;},focus(){}};
 const create=new Function('editor','selectManualBlocks','selectManualBlockIds',`${eligibility}\n${command}\n const settleRange=${restore};let disabled=false,ready=true,busy=false,printRequested=false,replacementBusy=false,modal=null,menu=null;const view={current:editor},generation={current:1},replacing={current:false},replacementSaving={current:false},printing={current:false},figureResizeSession={current:null},tableUISession={current:null},tableResizeSession={current:null},ownOutlineSelectSession={current:null},outlineDragSession={current:null},marginDrag={current:null},dragController={current:{isDragging:()=>false}},outlineDragController={current:{isDragging:()=>false}},marqueeController={current:{isDragging:()=>false}},uiApi={current:{deferredFocusEnabled}},dragApi={current:{command}},queue=[];function requestAnimationFrame(fn){queue.push(fn);}function setNotice(){}function scheduleFocus(){}return {settleRange,view,generation,uiApi,refs:{replacing,replacementSaving,printing,figureResizeSession,tableUISession,tableResizeSession,ownOutlineSelectSession,outlineDragSession,marginDrag,dragController,outlineDragController,marqueeController},step(){queue.shift()?.()},flush(){while(queue.length)queue.shift()()}};`);
 return {...create(editor,selectManualBlocks,selectManualBlockIds),editor,ids:doc.pages[0].blocks.map(b=>b.id),get count(){return dispatches}};
}
test('legitimate post-drop contiguous and sparse range restore still selects exact IDs',()=>{for(const sparse of [false,true]){const h=harness(),range={anchorId:h.ids[0],headId:h.ids[1],ids:h.ids.slice(0,2),sparse};h.settleRange(range,h.editor.state.doc);h.flush();assert.equal(h.count,1);assert.deepEqual(h.editor.state.selection.ids,range.ids);}});
for(const flag of ['tableUISession','figureResizeSession','tableResizeSession','ownOutlineSelectSession','outlineDragSession','marginDrag','dragController','outlineDragController','marqueeController','generation','readonly','disconnected'])test(`new ${flag} before second RAF does not overwrite newer selection`,()=>{const h=harness();h.settleRange({anchorId:h.ids[0],headId:h.ids[1]},h.editor.state.doc);h.step();if(flag==='generation')h.generation.current++;else if(flag==='readonly')h.editor.editable=false;else if(flag==='disconnected')h.editor.dom.isConnected=false;else h.refs[flag].current=flag.endsWith('Controller')?{isDragging:()=>true}:{};h.flush();assert.equal(h.count,0);assert.ok(!h.editor.state.selection.manualBlockSelection);});

test('selection-only changes between RAF preserve newer PM selection',()=>{const h=harness();h.settleRange({anchorId:h.ids[0],headId:h.ids[1]},h.editor.state.doc);h.step();selectManualBlocks(h.ids[2])(h.editor.state,h.editor.dispatch);h.flush();assert.equal(h.count,1);assert.deepEqual(h.editor.state.selection.ids,[h.ids[2]]);});
test('a first-frame gesture rejection is final even if session ends before the next frame',()=>{const h=harness();h.settleRange({anchorId:h.ids[0],headId:h.ids[1]},h.editor.state.doc);h.refs.tableUISession.current={};h.step();h.refs.tableUISession.current=null;h.flush();assert.equal(h.count,0);});
