import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {NodeSelection,TextSelection} from '@tiptap/pm/state';
import {createManualState,documentFromState,getManualEditingDocument,findManualObject,selectManualObject,insertManualBlock,updateManualObject,deleteManualObject,executeManualBlockCommand,getManualSlashTrigger} from '../src/redesign/manual-kernel.mjs';
import {captureManualImageRequest,isManualImageRequestCurrent} from '../src/redesign/manual-image-request.mjs';
const require=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url)),{parse}=require('@babel/parser');
const source=readFileSync(process.env.LDS_IMAGE_PARENT_SOURCE||new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8'),nodes=[];
function walk(node){if(!node||typeof node!=='object')return;nodes.push(node);for(const value of Object.values(node))if(Array.isArray(value))value.forEach(walk);else if(value&&typeof value==='object')walk(value);}
walk(parse(source,{sourceType:'module',plugins:['jsx']}));
const functionNames=['objects','selectionIds','command','captureImageRequest','currentImageRequest','pickImage','addImage','chooseBlock'];
const actualFunctions=functionNames.map(name=>{const node=nodes.find(n=>n.type==='FunctionDeclaration'&&n.id?.name===name);assert.ok(node,name);return source.slice(node.start,node.end);}).join('\n');
const input=nodes.find(n=>n.type==='JSXOpeningElement'&&n.name?.name==='input'&&n.attributes.some(a=>a.name?.name==='ref'&&a.value?.expression?.name==='imageInput'));
const onChange=input.attributes.find(a=>a.name?.name==='onChange').value.expression;
const rich=text=>text?[{type:'text',text}]:[];
function harness({replacement=false,drawer=false,pending=false,decodeError=false}={}){
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:[replacement?{id:'image',type:'figure',asset:'assets/old.png',alt:'Keep',caption:rich('Caption'),widthPreset:'reading'}:{id:'after',type:'paragraph',content:[]},{id:'following',type:'paragraph',content:rich('Keep following')}]}]}});
 const editor={get state(){return state;},dispatch:tr=>{state=state.apply(tr);},composing:false},view={current:editor},generation={current:3},imageTarget={current:null},assetsRef={current:{'assets/old.png':'old'}},frames=[],notices=[];
 let chooserClicks=0,resolveDecode;const imageInput={current:{click(){chooserClicks++;}}};
 class Reader{readAsDataURL(){this.result='data:image/png;base64,synthetic';this.onload();}}
 class DecodedImage{decode(){return decodeError?Promise.reject(new Error('Synthetic decode failure')):pending?new Promise(resolve=>{resolveDecode=resolve;}):Promise.resolve();}}
 const deps={view,generation,imageTarget,imageInput,assetsRef,createManualState,getManualEditingDocument,findManualObject,selectManualObject,insertManualBlock,updateManualObject,executeManualBlockCommand,captureManualImageRequest,isManualImageRequestCurrent,FileReader:Reader,Image:DecodedImage,requestAnimationFrame:cb=>frames.push(cb),setNotice:message=>notices.push(message),scheduleFocus:()=>{},showFeedback:()=>{}};
 const factory=new Function(...Object.keys(deps),`let disabled=false,replacementBusy=false,modal=null,menu=null,menuPage=false,inspector=${drawer},inspectorTargetId=null;const replacing={current:false},replacementSaving={current:false},dismissedSlash={current:null},propertyTypes=new Set();function blockAction(){return null;}function blockMenuSelection(){return null;}function setMenu(value){menu=value;}function setAssets(){}function setInspector(value){inspector=value;}function setInspectorTargetId(value){inspectorTargetId=value;} ${actualFunctions} return {chooseBlock,pickImage,addImage,onChange:${source.slice(onChange.start,onChange.end)},get inspector(){return inspector;},get inspectorTargetId(){return inspectorTargetId;},setMenu,disable(){disabled=true;}};`);
 const parent=factory(...Object.values(deps));
 selectManualObject(replacement?'image':'after',{text:true})(state,editor.dispatch);
 if(replacement){const found=findManualObject(state,'image');editor.dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+3)));}
 const flush=()=>{while(frames.length)frames.shift()();};
 const file={type:'image/png',size:1889};
 return {parent,editor,generation,imageTarget,assetsRef,notices,file,flush,get clicks(){return chooserClicks;},get state(){return state;},get document(){return documentFromState(state);},resolve(){resolveDecode();},async complete(files=[file]){const event={target:{files,value:'selected.png'}};parent.onChange(event);assert.equal(event.target.value,'');assert.equal(imageTarget.current,null);await new Promise(resolve=>setImmediate(resolve));},slash(){editor.dispatch(state.tr.insertText('/image'));const trigger=getManualSlashTrigger(state);assert.ok(trigger);parent.setMenu({mode:'slash',trigger});parent.chooseBlock({id:'figure',needsInput:'image'});flush();}};
}
function assertNewSelection(h,id='after'){assert.ok(h.state.selection instanceof NodeSelection);assert.equal(h.state.selection.node.type.name,'figure');assert.equal(h.state.selection.node.attrs.id,id);assert.equal(h.parent.inspector,false);assert.equal(h.parent.inspectorTargetId,id);assert.match(getManualEditingDocument(h.state).pages[0].blocks.find(block=>block.id===id).asset,/^assets\//);}
test('actual slash chooseBlock → picker → file input completion selects reused empty-paragraph figure without opening drawer',async()=>{const h=harness();h.slash();assert.equal(h.clicks,1);assert.equal(h.imageTarget.current.targetId,'after');assert.equal(Object.isFrozen(h.imageTarget.current),true);assert.equal(h.state.selection.$from.parent.type.name,'figureCaption');await h.complete();assertNewSelection(h);assert.equal(h.document.pages[0].blocks[1].id,'following');});
test('actual insert menu completion selects its newly created figure',async()=>{const h=harness();h.parent.setMenu({mode:'insert',targetId:'after'});h.parent.chooseBlock({id:'figure',needsInput:'image'});h.flush();const id=h.imageTarget.current.targetId;await h.complete();assertNewSelection(h,id);});
for(const drawer of [false,true])test(`ordinary replacement preserves caption cursor and drawer=${drawer}`,async()=>{const h=harness({replacement:true,drawer}),selection=h.state.selection.toJSON();h.parent.pickImage('image');h.flush();await h.complete();assert.deepEqual(h.state.selection.toJSON(),selection);assert.equal(h.parent.inspector,drawer);assert.deepEqual(h.document.pages[0].blocks[0].caption,rich('Caption'));assert.equal(h.document.pages[0].blocks[0].alt,'Keep');});
test('direct pasted/dropped file without target still selects new figure',async()=>{const h=harness();await h.parent.addImage(h.file);const id=h.state.selection.node?.attrs.id;assert.ok(id);assertNewSelection(h,id);});
test('cancelled new chooser intent cannot leak into later ordinary replacement',async()=>{const h=harness({replacement:true});h.parent.setMenu({mode:'insert',targetId:'following'});h.parent.chooseBlock({id:'figure',needsInput:'image'});h.flush();await h.complete([]);selectManualObject('image',{text:true})(h.state,h.editor.dispatch);const selection=h.state.selection.toJSON();h.parent.pickImage('image');h.flush();await h.complete();assert.deepEqual(h.state.selection.toJSON(),selection);assert.equal(h.parent.inspector,false);});
for(const cause of ['generation','deleted-target','decode-error'])test(`pending new completion ${cause} leaves document, selection and assets unchanged`,async()=>{const h=harness({pending:cause!=='decode-error',decodeError:cause==='decode-error'});h.slash();const finishing=h.complete();if(cause==='generation')h.generation.current++;if(cause==='deleted-target')deleteManualObject('after')(h.state,h.editor.dispatch);const before=h.state,assets=h.assetsRef.current;if(cause!=='decode-error'){await Promise.resolve();h.resolve();}await finishing;assert.equal(h.state,before);assert.equal(h.assetsRef.current,assets);assert.equal(h.parent.inspector,false);assert.ok(h.notices.some(Boolean));});
test('new completion selects captured figure after caret moves elsewhere while chooser is open',async()=>{const h=harness();h.slash();selectManualObject('following',{text:true})(h.state,h.editor.dispatch);await h.complete();assertNewSelection(h);});
