import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
import {createManualState,documentFromState} from '../src/redesign/manual-kernel.mjs';import {createEmptyManualDocument} from '../src/redesign/manual-v2.mjs';import {saveBeforeReplacement} from '../src/redesign/autosave-controller.mjs';import {createManualFileSession} from '../src/redesign/manual-file-session.mjs';
const {parse}=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url))('@babel/parser'),source=readFileSync(process.env.LDS_REPLACEMENT_SOURCE||new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8');
const wanted=new Set(['save','protect','finishReplacement','saveAndContinue','replacementDownloadCurrent']);let opts,dirty,active;const codes=[];
function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&wanted.has(n.id?.name))codes.push(source.slice(n.start,n.end));if(n.type==='VariableDeclarator'&&['isDirty','activeFileToken'].includes(n.id?.name)){const code='const '+source.slice(n.start,n.end)+';';if(n.id.name==='isDirty')dirty=code;else active=code;}if(n.type==='CallExpression'&&n.callee?.name==='fileSessionFactory')opts=source.slice(n.arguments[0].start,n.arguments[0].end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}walk(parse(source,{sourceType:'module',plugins:['jsx']}));
function harness(mode){
 let state=createManualState({document:createEmptyManualDocument()}),modal=null,moves=0,downloads=0,writes=0,changed=false;const original=state.doc;
 const editor={get state(){return state},editable:true,composing:false};
 const file={name:'synthetic.manual.json',createWritable:async()=>({write:async()=>{writes++;if(mode==='failure')throw new Error('disk failed');},close:async()=>{},abort:async()=>{}})};
 const c={view:{current:editor},editor,generation:{current:1},assetsRef:{current:{}},fileBaseline:{current:null},fileSession:{current:null},normalization:{current:null},pendingAction:{current:null},replacementSaving:{current:false},replacing:{current:false},printing:{current:false},ready:true,busy:false,alive:true,window:mode==='download'?{isSecureContext:false}:{isSecureContext:true,showSaveFilePicker:()=>mode==='cancel'?Promise.reject(Object.assign(new Error('cancel'),{name:'AbortError'})):Promise.resolve(file)},uiApi:{current:{fileReady:true,downloadFileBytes(){downloads++;}}},saveBeforeReplacement,documentFromState,createManualFileSession,setNotice(){},showFeedback(){},setModal(value){modal=typeof value==='function'?value(modal):value;c.modal=modal;},setSaveStatus(){},setReplacementBusy(){},setBubble(){},refresh(){if(changed)return;if(['generation-after-commit','editor-after-commit','pending-after-commit','late-edit'].includes(mode)){changed=true;queueMicrotask(()=>{if(mode==='pending-after-commit'){c.pendingAction.current={action:()=>moves+=100};return;}if(mode==='late-edit'){state=state.apply(state.tr.insertText('Late edit',state.selection.from));return;}state=createManualState({document:createEmptyManualDocument()});if(mode==='generation-after-commit')c.generation.current++;else c.view.current={...editor};c.assetsRef.current={};c.fileBaseline.current=null;c.fileSession.current.reset();});}},modal:null};
 vm.createContext(c);vm.runInContext(codes.join('\n')+'\n'+active+'\n'+dirty+'\nfileSession.current=createManualFileSession('+opts+');',c);
 return {c,editor,original,get modal(){return modal;},get moves(){return moves;},get writes(){return writes;},get downloads(){return downloads;},begin(){c.protect(()=>moves++);},changeDoc(){state=createManualState({document:createEmptyManualDocument()});}};
}
for(const mode of ['failure','cancel','download'])test(`actual Parent/file session ${mode} preserves dirty document and pending replacement`,async()=>{const h=harness(mode);h.begin();await h.c.saveAndContinue();assert.equal(h.moves,0);assert.equal(h.editor.state.doc,h.original);assert.equal(vm.runInContext('isDirty()',h.c),true);assert.equal(h.modal.kind,'unsaved');if(mode==='download'){assert.equal(h.downloads,1);assert.equal(h.c.replacementDownloadCurrent(h.modal.downloadRequest),true);assert.equal(h.c.fileBaseline.current,null);h.changeDoc();assert.equal(h.c.replacementDownloadCurrent(h.modal.downloadRequest),false);}});
test('download save returns false and request context expires with assets/generation/pending owner',async()=>{const h=harness('download');h.begin();assert.equal(await h.c.save(),false);const request=h.modal.downloadRequest;assert.equal(h.c.replacementDownloadCurrent(request),true);h.c.assetsRef.current={};assert.equal(h.c.replacementDownloadCurrent(request),false);h.c.assetsRef.current=request.assets;h.c.generation.current++;assert.equal(h.c.replacementDownloadCurrent(request),false);h.c.generation.current--;h.c.pendingAction.current={};assert.equal(h.c.replacementDownloadCurrent(request),false);});
for(const mode of ['generation-after-commit','editor-after-commit','pending-after-commit'])test(`actual Parent save chain aborts ${mode} without second write or old replacement`,async()=>{const h=harness(mode);h.begin();await h.c.saveAndContinue();assert.equal(h.writes,1);assert.equal(h.moves,0);if(mode==='pending-after-commit')assert.equal(h.c.pendingAction.current!==null,true);else assert.equal(h.c.pendingAction.current,null);});
test('successful file session save permits exactly one replacement',async()=>{const h=harness('success');h.begin();await h.c.saveAndContinue();assert.equal(h.writes,1);assert.equal(h.moves,1);assert.equal(h.modal,null);});
test('same generation late edit saves again before replacing',async()=>{const h=harness('late-edit');h.begin();await h.c.saveAndContinue();assert.equal(h.writes,2);assert.equal(h.moves,1);});
test('unsaved JSX labels download separately and places scoped instruction in role status',()=>{assert.match(source,/fileSaveMode==='download'\?'파일 내려받기':'저장'/);assert.match(source,/replacementDownloadCurrent\(modal.downloadRequest\)&&<p role="status">파일 내려받기를 요청했습니다\. 받은 파일을 확인한 뒤, 계속하려면 ‘저장 안 함’을 선택하세요\.<\/p>/);});
