import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';
import {createManualState,selectManualObject} from '../src/redesign/manual-kernel.mjs';
import {selectManualTableCells} from '../src/redesign/manual-table-selection.mjs';
import {isManualTableMenuTargetCurrent} from '../src/redesign/manual-table-action-menu.mjs';
const {parse}=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url))('@babel/parser');
const readSource=file=>readFileSync(file==='ManualTableSelectionControls.jsx'&&process.env.LDS_TABLE_CLOSE_SOURCE?process.env.LDS_TABLE_CLOSE_SOURCE:new URL('../src/redesign/'+file,import.meta.url),'utf8');const codes=[];let enabled;
function walk(n,source,wanted){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&wanted.includes(n.id?.name))codes.push(source.slice(n.start,n.end));if(n.type==='JSXElement'&&n.openingElement.name.name==='ManualTableSelectionControls'){const attr=n.openingElement.attributes.find(a=>a.name?.name==='isEnabled');enabled=source.slice(attr.value.expression.start,attr.value.expression.end);}for(const v of Object.values(n))if(Array.isArray(v))v.forEach(x=>walk(x,source,wanted));else if(v&&typeof v==='object')walk(v,source,wanted);}
for(const [file,names] of [['ManualTableSelectionControls.jsx',['closeMenu']],['ManualEditor.jsx',['tableSelectionEnabled','tableGestureBaseBlocked','tableGestureBlocked','startTableUISession','endTableUISession']]]){const src=readSource(file);walk(parse(src,{sourceType:'module',plugins:['jsx']}),src,names);}
function harness(){let focus=0;const frames=[];const editor={state:createManualState({document:{schemaVersion:2,id:'d',title:'Synthetic',pages:[{id:'p',title:[],blocks:[{id:'table',type:'table',label:'Synthetic table',headers:['A','B'].map((text,i)=>({id:'head'+i,content:[{type:'text',text}]})),rows:[['C','D'].map((text,i)=>({id:'cell'+i,content:[{type:'text',text}]}))]},{id:'after',type:'paragraph',content:[{type:'text',text:'After'}]}]}]}}),editable:true,composing:false,focus(){focus++;}};editor.dispatch=tr=>editor.state=editor.state.applyTransaction(tr).state;let cellId;editor.state.doc.descendants(n=>{if(!cellId&&n.type.name==='tableCell')cellId=n.attrs.id});assert.equal(selectManualTableCells(cellId,cellId,{mode:'row',revision:editor.state.doc})(editor.state,editor.dispatch,editor),true);
const target={editor,revision:editor.state.doc,generation:1,cellId,tableId:'table',mode:'row'};const c={view:{current:editor},viewRef:{current:editor},generation:{current:1},disabled:false,replacementBusy:false,menu:null,modal:null,uiApi:{current:null},api:{current:null},menuRef:{current:{target}},session:{current:{target}},pagination:{current:{request(){}}},setMenu(){},setActionIndex(){},setMenuKeyboard(){},requestAnimationFrame(fn){frames.push(fn)},isManualTableMenuTargetCurrent};c.viewRef=c.view;for(const name of ['replacing','replacementSaving','printing','dragController','outlineDragController','marqueeController','marginDrag','figureResizeSession','ownOutlineSelectSession','tableResizeSession','tableUISession'])c[name]={current:null};vm.createContext(c);vm.runInContext(codes.join('\n')+'\nglobalThis.actualEnabled='+enabled+';',c);c.uiApi.current={tableGestureBlocked:c.tableGestureBlocked,paginationEnabled:true};c.api.current={isEnabled:c.actualEnabled,getGeneration:()=>c.generation.current,onSessionEnd:c.endTableUISession};c.startTableUISession({target});assert.equal(c.actualEnabled(),false);return {c,editor,target,close(){c.closeMenu()},flush(){while(frames.length)frames.shift()()},get focus(){return focus}};}
test('normal actual close releases Parent session and focuses once',()=>{const h=harness();h.close();assert.equal(h.c.tableUISession.current,null);h.flush();assert.equal(h.focus,1);});
test('selection-only change after close cannot restore editor focus',()=>{const h=harness();h.close();const doc=h.editor.state.doc,selection=h.editor.state.selection;selectManualObject('after',{text:true})(h.editor.state,h.editor.dispatch,h.editor);assert.equal(h.editor.state.doc,doc);assert.equal(selection.eq(h.editor.state.selection),false);assert.equal(isManualTableMenuTargetCurrent(h.target,{editor:h.editor,generation:1,enabled:true}),true);h.flush();assert.equal(h.focus,0);});
const blocked={activeGesture:h=>h.c.figureResizeSession.current={},editor:h=>h.c.view.current={...h.editor},doc:h=>h.editor.state=h.editor.state.apply(h.editor.state.tr.insertText('Edit',h.editor.state.doc.content.size-2)),generation:h=>h.c.generation.current++,parentMenu:h=>h.c.menu={mode:'block'},modal:h=>h.c.modal={kind:'table'},newTableMenu:h=>{h.c.menuRef.current={target:h.target};h.c.session.current={target:h.target};h.c.startTableUISession({target:h.target});},readOnly:h=>h.editor.editable=false,IME:h=>h.editor.composing=true};
for(const [name,change] of Object.entries(blocked))test(`actual close restore rejects ${name}`,()=>{const h=harness();h.close();change(h);h.flush();assert.equal(h.focus,0);});
test('completed gesture without PM changes is invisible to active Parent guards',()=>{const h=harness();h.close();h.c.figureResizeSession.current={};h.c.figureResizeSession.current=null;h.flush();assert.equal(h.focus,1);});
test('local menu ref alone has no close callback guard; production new menu also starts Parent session',()=>{const h=harness();h.close();h.c.menuRef.current={target:h.target};h.flush();assert.equal(h.focus,1);});

test('successful action changed doc and selection before close restores its post-action selection',()=>{const h=harness();selectManualObject('after',{text:true})(h.editor.state,h.editor.dispatch,h.editor);h.editor.state=h.editor.state.apply(h.editor.state.tr.insertText('Action edit',h.editor.state.selection.from));const selection=h.editor.state.selection;h.close();h.flush();assert.equal(h.focus,1);assert.equal(h.editor.state.selection,selection);});
