import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';
import {createManualState} from '../src/redesign/manual-kernel.mjs';import {captureManualTableActionTarget,getManualTableActionAvailability} from '../src/redesign/manual-table-actions.mjs';import {getManualTableActionMenuItems,nextManualTableActionIndex,isManualTableMenuTargetCurrent} from '../src/redesign/manual-table-action-menu.mjs';
const source=readFileSync(process.env.LDS_TABLE_DISABLED_CONTROLS_SOURCE||new URL('../src/redesign/ManualTableSelectionControls.jsx',import.meta.url),'utf8'),{parse}=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url))('@babel/parser');const callbacks=[];let click,hover,initial,reveal;
function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&['choose','menuKey','menuCurrent'].includes(n.id?.name))callbacks.push(source.slice(n.start,n.end));if(n.type==='JSXAttribute'&&n.name?.name==='onClick'&&source.slice(n.start,n.end).includes('onChoose'))click=source.slice(n.value.expression.start,n.value.expression.end);if(n.type==='JSXAttribute'&&n.name?.name==='onPointerMove'&&source.slice(n.start,n.end).includes('onHover'))hover=source.slice(n.value.expression.start,n.value.expression.end);if(n.type==='CallExpression'&&n.callee?.name==='useLayoutEffect'&&source.slice(n.start,n.end).includes('manual-table-action-reason'))reveal=source.slice(n.arguments[0].start,n.arguments[0].end);if(n.type==='CallExpression'&&n.callee?.name==='setActionIndex'&&source.slice(n.arguments[0].start,n.arguments[0].end).includes('initialItems'))initial=source.slice(n.arguments[0].start,n.arguments[0].end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}walk(parse(source,{sourceType:'module',plugins:['jsx']}));
let navigate=nextManualTableActionIndex;if(process.env.LDS_TABLE_DISABLED_HELPER_SOURCE){const helper=readFileSync(process.env.LDS_TABLE_DISABLED_HELPER_SOURCE,'utf8');const n=parse(helper,{sourceType:'module'}).program.body.find(n=>n.type==='ExportNamedDeclaration'&&n.declaration?.id?.name==='nextManualTableActionIndex').declaration;navigate=new Function('return '+helper.slice(n.start,n.end))();}
function harness({allDisabled=false}={}){const state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:[{id:'table',type:'table',label:'Synthetic',headers:[{id:'only-cell',content:[{type:'text',text:'Header'}]}],rows:[]}]}]}}),editor={state,editable:true,composing:false};const target={...captureManualTableActionTarget(state,{tableId:'table',cellId:'only-cell',mode:'row',generation:1}),editor};let actions=0,closed=0;const items=getManualTableActionMenuItems('row',id=>allDisabled?{enabled:false,reason:'Synthetic blocked'}:getManualTableActionAvailability(state,target,id,{generation:1}));assert.equal(items.at(-1).disabled,true);const c={items,initialItems:items,actionIndex:-1,viewRef:{current:editor},menuRef:{current:{target}},api:{current:{getGeneration:()=>1,isMenuEnabled:()=>true,onTableAction(){actions++;return true;}}},nextManualTableActionIndex:navigate,isManualTableMenuTargetCurrent,setActionIndex(value){c.actionIndex=value;},setMenuKeyboard(){},closeMenu(){closed++;}};vm.createContext(c);vm.runInContext(callbacks.join('\n'),c);c.actionIndex=vm.runInContext(initial,c);return {c,items,editor,get actions(){return actions},get closed(){return closed},key(key){c.menuKey({key,preventDefault(){},stopPropagation(){}})},click(){c.item=c.items[c.actionIndex];c.onChoose=c.choose;vm.runInContext('('+click+')()',c)}};}
test('actual initial callback selects first item even when every command is disabled',()=>{const h=harness({allDisabled:true});assert.equal(h.c.actionIndex,0);h.key('End');assert.equal(h.c.actionIndex,4);});
test('last-row delete reason is reachable by actual ArrowDown path but Enter Space and click cannot activate',()=>{const h=harness();assert.equal(h.c.actionIndex,0);for(let i=0;i<4;i++)h.key('ArrowDown');assert.equal(h.c.actionIndex,4);assert.ok(h.items[4].reason);const state=h.editor.state;for(const method of [()=>h.key('Enter'),()=>h.key(' '),()=>h.click()])method();assert.equal(h.actions,0);assert.equal(h.closed,0);assert.equal(h.editor.state,state);});
test('all-disabled items remain navigable and cannot activate',()=>{const h=harness({allDisabled:true});for(let i=0;i<5;i++){h.key('Enter');h.key(' ');h.click();h.key('ArrowDown');}assert.equal(h.actions,0);assert.equal(h.closed,0);});
test('enabled item still activates through actual public click and choose callbacks',()=>{const h=harness();h.key('Home');assert.equal(h.items[h.c.actionIndex].disabled,false);h.click();assert.equal(h.actions,1);assert.equal(h.closed,1);});

test('actual public pointer callback visits disabled item for its reason without activation',()=>{const h=harness();h.c.index=4;h.c.item=h.items[4];h.c.onHover=index=>h.c.actionIndex=index;vm.runInContext('('+hover+')()',h.c);assert.equal(h.c.actionIndex,4);h.click();assert.equal(h.actions,0);});
test('active keyboard reason reveal uses nearest scrolling and leaves pointer mode alone',()=>{assert.ok(reveal);const calls=[];const c={keyboard:true,position:{maxHeight:60},menuDom:{current:{querySelector:selector=>({scrollIntoView:options=>calls.push({selector,...options})})}}};vm.createContext(c);vm.runInContext('('+reveal+')()',c);assert.deepEqual(calls,[{selector:'.manual-table-action-reason',block:'nearest'}]);c.keyboard=false;vm.runInContext('('+reveal+')()',c);assert.equal(calls.length,1);});
