import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';
import {createManualState,selectManualObject,findManualObject} from '../src/redesign/manual-kernel.mjs';
const source=readFileSync(process.env.LDS_PRINT_ISSUE_SOURCE||new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8');const {parse}=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url))('@babel/parser');const codes=[];let close;
function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&['locatePrintIssue','locate','scheduleFocus','deferredFocusEnabled','command'].includes(n.id?.name))codes.push(source.slice(n.start,n.end));if(n.type==='VariableDeclarator'&&n.id.name==='closeModal')close=source.slice(n.init.start,n.init.end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}walk(parse(source,{sourceType:'module',plugins:['jsx']}));
function harness(){const state=createManualState({document:{schemaVersion:2,id:'d',title:'Synthetic',pages:[{id:'p',title:[],blocks:[{id:'a',type:'paragraph',content:[{type:'text',text:'A'}]},{id:'b',type:'paragraph',content:[{type:'text',text:'B'}]}]}]}});let dialogOpen=true,nextModal;const tasks=[],frames=[],calls={titleAttempts:0,titleFocus:0,editorFocus:0,scroll:0};const editor={state,editable:true,composing:false,dom:{isConnected:true},focus(){if(!dialogOpen)calls.editorFocus++;},nodeDOM(){return {scrollIntoView(){calls.scroll++;}}}};editor.dispatch=tr=>editor.state=editor.state.applyTransaction(tr).state;
const c={view:{current:editor},generation:{current:1},document:{id:'d'},titleInput:{current:{isConnected:true,focus(){calls.titleAttempts++;if(!dialogOpen)calls.titleFocus++;}}},ready:true,busy:false,disabled:false,printRequested:false,replacementBusy:false,modal:{kind:'printIssues'},menu:null,uiApi:{current:null},selectManualObject,findManualObject,setModal(value){nextModal=value;},setNotice(){},queueMicrotask(fn){tasks.push(fn)},requestAnimationFrame(fn){frames.push(fn)}};for(const name of ['replacing','replacementSaving','printing','figureResizeSession','tableUISession','tableResizeSession','ownOutlineSelectSession','outlineDragSession','marginDrag','dragController','outlineDragController','marqueeController'])c[name]={current:null};vm.createContext(c);vm.runInContext(codes.join('\n')+'\nconst closeModal='+close+';globalThis.closeModal=closeModal;',c);c.uiApi.current={deferredFocusEnabled:c.deferredFocusEnabled};return {c,editor,calls,click(id){if(c.locatePrintIssue)c.locatePrintIssue(id);else {c.closeModal();c.locate(id)}},render(){c.modal=nextModal;dialogOpen=!!nextModal},flush(){tasks.splice(0).forEach(fn=>fn());while(frames.length)frames.splice(0).forEach(fn=>fn())}};}

test('document issue focuses connected title once only after Dialog removal',()=>{const h=harness();h.click('d');assert.deepEqual(h.calls,{titleAttempts:0,titleFocus:0,editorFocus:0,scroll:0});h.render();h.flush();assert.deepEqual(h.calls,{titleAttempts:1,titleFocus:1,editorFocus:0,scroll:0});});
test('block issue selects actual PM target and restores exactly one focus and scroll',()=>{const h=harness();h.click('b');h.render();h.flush();assert.equal(h.calls.editorFocus,1);assert.equal(h.calls.scroll,1);assert.equal(findManualObject(h.editor.state,'b').pos<=h.editor.state.selection.from,true);});
const changes={generation:h=>h.c.generation.current++,editor:h=>h.c.view.current={...h.editor},doc:h=>h.editor.state=h.editor.state.apply(h.editor.state.tr.insertText('Changed',h.editor.state.selection.from)),selection:h=>selectManualObject('a',{text:true})(h.editor.state,h.editor.dispatch,h.editor),gesture:h=>h.c.tableUISession.current={},figure:h=>h.c.figureResizeSession.current={},readOnly:h=>h.editor.editable=false,ime:h=>h.editor.composing=true,disconnected:h=>h.editor.dom.isConnected=false,newModal:h=>h.c.modal={kind:'table'}};
for(const id of ['d','b'])for(const [name,change] of Object.entries(changes))test(`issue ${id} rejects ${name} before delayed focus and scroll`,()=>{const h=harness();h.click(id);h.render();change(h);h.flush();assert.equal(h.calls.titleFocus,0);assert.equal(h.calls.editorFocus,0);assert.equal(h.calls.scroll,0);});
for(const missing of ['missing','missing-title','detached-title','disabled-title','replaced-title'])test(`issue target ${missing} produces no focus or scroll`,()=>{const h=harness();if(missing==='missing-title')h.c.titleInput.current=null;h.click(missing==='missing'?'missing':'d');h.render();if(missing==='detached-title')h.c.titleInput.current.isConnected=false;if(missing==='disabled-title')h.c.titleInput.current.disabled=true;if(missing==='replaced-title')h.c.titleInput.current={isConnected:true,focus(){throw new Error('wrong new input focus')}};h.flush();assert.equal(h.calls.titleFocus,0);assert.equal(h.calls.editorFocus,0);assert.equal(h.calls.scroll,0);});
test('print issue wiring owns closure and does not invoke generic locate or close restoration',()=>{assert.match(source,/onClick=\{\(\)=>locatePrintIssue\(issue.id\)\}/);});
