import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
import {createManualState} from '../src/redesign/manual-kernel.mjs';import {selectManualBlocks} from '../src/redesign/manual-block-selection.mjs';import {installManualMarqueeSelection} from '../src/redesign/manual-marquee-selection.mjs';
const source=readFileSync(process.env.LDS_MARGIN_SOURCE||new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8'),require=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url)),{parse}=require('@babel/parser'),wanted=new Set(['marginBlocks','marginBlockAt','beginMarginSelection','extendMarginSelection','endMarginSelection','command']);const funcs=[];function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&wanted.has(n.id.name))funcs.push(source.slice(n.start,n.end));for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}walk(parse(source,{sourceType:'module',plugins:['jsx']}));
function harness(){let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:['one','two'].map((text,i)=>({id:`p${i}`,type:'paragraph',content:[{type:'text',text}]}))}]}}),count=0,captures=0,prevented=0,focused=0;
 const editor={editable:true,composing:false,get state(){return state},dispatch(tr){count++;state=state.applyTransaction(tr).state;},focus(){focused++}};
 const blocks=['p0','p1'].map((id,i)=>({dataset:{manualId:id,manualNode:'paragraph'},getBoundingClientRect:()=>({top:50+i*40,bottom:74+i*40,height:24})}));
 const content={getBoundingClientRect:()=>({left:100,right:500,top:30,bottom:150})},page={dataset:{manualNode:'cover'},getBoundingClientRect:()=>({left:60,right:540,top:10,bottom:170}),querySelector:()=>content,contains:el=>blocks.includes(el),closest(selector){return selector==='[data-manual-node="page"],[data-manual-node="cover"]'?this:null;}};
 const document=new EventTarget(),surface=new EventTarget(),writing=new EventTarget();document.defaultView=surface;writing.ownerDocument=document;writing.contains=el=>el===page;writing.setPointerCapture=()=>{captures++};writing.releasePointerCapture=()=>{};const controller=installManualMarqueeSelection({element:writing,getItems:()=>[],getRevision:()=>editor.state.doc,surface});
 const currentTarget={setPointerCapture(){captures++},hasPointerCapture:()=>true,releasePointerCapture(){}};
 const create=new Function('editor','blocks','controller','selectManualBlocks',`${funcs.join('\n')}\nconst view={current:editor},mount={current:{querySelectorAll:()=>blocks}},marginDrag={current:null},marqueeController={current:controller},marqueeBaseline={current:null},generation={current:1},replacing={current:false},replacementSaving={current:false},figureResizeSession={current:null},ownOutlineSelectSession={current:null},tableUISession={current:null},tableResizeSession={current:null},dragController={current:null},outlineDragController={current:null},pagination={current:{request(){}}};let disabled=false,replacementBusy=false,modal=null;function setNotice(){}function scheduleFocus(){}return {beginMarginSelection,extendMarginSelection,endMarginSelection,get drag(){return marginDrag.current}};`);
 const api=create(editor,blocks,controller,selectManualBlocks);return {api,editor,controller,get count(){return count},get captures(){return captures},get prevented(){return prevented},get focused(){return focused},event(extra={}){return {button:0,pointerId:1,pointerType:'mouse',isPrimary:true,clientX:80,clientY:60,target:page,currentTarget,preventDefault(){prevented++},...extra}}};}
for(const props of [{pointerType:'touch'},{pointerType:'pen'},{isPrimary:false},{pointerType:'touch',isPrimary:false},{defaultPrevented:true}])test(`actual Parent fallback rejects ${JSON.stringify(props)} without capture/default prevention/PM mutation`,()=>{const h=harness(),before=h.editor.state,e=h.event(props);h.api.beginMarginSelection(e);h.api.extendMarginSelection({...e,clientY:100});h.api.endMarginSelection(e);assert.equal(h.captures,0);assert.equal(h.prevented,0);assert.equal(h.count,0);assert.equal(h.focused,0);assert.equal(h.editor.state,before);assert.equal(h.api.drag,null);h.controller.dispose();});
test('actual Parent primary mouse cover gutter fallback still selects range and releases session',()=>{const h=harness(),e=h.event();h.api.beginMarginSelection(e);assert.equal(h.captures,1);assert.ok(h.api.drag);h.api.extendMarginSelection({...e,clientY:100});assert.equal(h.count,1);assert.deepEqual(h.editor.state.selection.ids,['p0','p1']);h.api.endMarginSelection(e);assert.equal(h.api.drag,null);assert.equal(h.focused,1);h.controller.dispose();});
