import test from 'node:test';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {undo,redo,undoDepth} from '@tiptap/pm/history';
import {TableMap} from '@tiptap/pm/tables';
import {createManualState,documentFromState,findManualCoverRole} from '../src/redesign/manual-kernel.mjs';
import {captureManualTableActionTarget,getManualTableActionAvailability,executeManualTableAction} from '../src/redesign/manual-table-actions.mjs';
import {getManualCoverProjection,getManualCoverCellProjection} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {getManualTableActionMenuItems} from '../src/redesign/manual-table-action-menu.mjs';
import {describeManualTableTrailingChange,executeManualTableTrailingChange} from '../src/redesign/manual-table-trailing-actions.mjs';
import {getManualTableLayout,setManualTableColumnWidths,setManualTableRowHeight} from '../src/redesign/manual-table-layout.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const text=text=>[{type:'text',text,marks:[{type:'strong'}]}];
function fixture(count=4){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:text('Cover'),metadata:Array.from({length:count},(_,i)=>({id:`entry${i}`,label:text(`Label${i}`),value:text(`Value${i}`),extensions:{vendor:{opaque:i}}})),blocks:[],extensions:{vendor:{opaque:'cover'}}},pages:[{id:'page',title:[],blocks:[{id:'body',type:'paragraph',content:text('Keep')}]}]};}
function harness(count=4){let state=createManualState({document:fixture(count)}),dispatches=0;const dispatch=tr=>{dispatches++;state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,editable:true,composing:false};const table=()=>findManualCoverRole(state,'cover','metadata');return {get state(){return state;},get dispatches(){return dispatches;},dispatch,view,table,pin:mode=>{const t=table();return captureManualTableActionTarget(state,{tableId:t.node.attrs.id,cellId:t.node.lastChild.firstChild.attrs.id,mode,generation:7});},run:(target,action)=>executeManualTableAction(target,action,{generation:7})(state,dispatch,view),command:cmd=>cmd(state,dispatch,view)};}
function roundtrip(h,before,tableId){const after=documentFromState(h.state),node=h.table().node;assert.equal(node.attrs.id,tableId);assert.equal(getManualCoverProjection(node.attrs.meta.extensions).editableTable,true);const loaded=createManualState({document:after});assert.deepEqual(documentFromState(loaded),after);assert.ok(findManualCoverRole(loaded,'cover','metadata').node.eq(node));assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:after,assets:{}})).document,after);assert.equal(undoDepth(h.state),1);assert.equal(h.command(undo),true);assert.deepEqual(documentFromState(h.state),before);assert.equal(h.command(redo),true);assert.deepEqual(documentFromState(h.state),after);assert.deepEqual(after.pages,before.pages);assert.deepEqual(after.cover.extensions.vendor,before.cover.extensions.vendor);return after;}
for(const count of [3,4])for(const mode of ['row','column'])for(const action of ['insert-before','insert-after','duplicate','delete'])test(`${count} entry metadata ${mode} ${action} preserves role, grid codec and one Undo/Redo`,()=>{const h=harness(count),before=documentFromState(h.state),target=h.pin(mode),id=h.table().node.attrs.id,old=TableMap.get(h.table().node);assert.equal(getManualTableActionAvailability(h.state,target,action,{generation:7}).enabled,true);assert.equal(h.run(target,action),true);assert.equal(h.dispatches,1);const map=TableMap.get(h.table().node),delta=action==='delete'?-1:1;assert.equal(map.height,old.height+(mode==='row'?delta:0));assert.equal(map.width,old.width+(mode==='column'?delta:0));assert.ok(!map.problems);const after=roundtrip(h,before,id);if(mode==='row'&&action==='delete')assert.deepEqual(after.cover.metadata.map(entry=>entry.id),['entry0','entry1']);for(const entry of after.cover.metadata)assert.deepEqual(entry.extensions,before.cover.metadata.find(item=>item.id===entry.id).extensions);});
test('duplicated metadata cells retain content but do not bind duplicated IDs to the scalar entries',()=>{const h=harness(),target=h.pin('row'),before=documentFromState(h.state);assert.equal(h.run(target,'duplicate'),true);const table=h.table().node;table.lastChild.forEach(cell=>{assert.equal(getManualCoverCellProjection(cell.attrs.meta?.extensions),null);assert.ok(cell.content.size);});assert.deepEqual(documentFromState(h.state).cover.metadata,before.cover.metadata);const copy=copyManualDocument(documentFromState(h.state));assert.deepEqual(documentFromState(createManualState({document:copy})),copy);assert.notEqual(findManualCoverRole(createManualState({document:copy}),copy.cover.id,'metadata').node.attrs.id,table.attrs.id);});
test('metadata menu and trailing add enable real structural capabilities rather than hidden placeholders',()=>{const h=harness(3),table=h.table().node,target=captureManualTableActionTarget(h.state,{tableId:table.attrs.id,cellId:table.lastChild.lastChild.attrs.id,mode:'column',generation:7});assert.deepEqual(getManualTableActionMenuItems('column',id=>getManualTableActionAvailability(h.state,target,id,{generation:7})).map(i=>i.id),['insert-before','insert-after','duplicate','clear','delete']);const description=describeManualTableTrailingChange(h.state,target,2,{generation:7});assert.equal(description.enabled,true);const before=documentFromState(h.state);assert.equal(executeManualTableTrailingChange(h.view,target,2,{generation:7}),true);assert.equal(TableMap.get(h.table().node).width,6);assert.equal(h.dispatches,1);roundtrip(h,before,table.attrs.id);});

test('saved metadata grid keeps column/row layouts, edited bound content and scalar opaque fields',()=>{
 const h=harness(),id=h.table().node.attrs.id;assert.equal(h.run(h.pin('column'),'insert-after'),true);
 assert.equal(h.command(setManualTableColumnWidths({tableId:id,columnWeights:[1,2,3,4,5],revision:h.state.doc})),true);assert.equal(h.command(setManualTableRowHeight({tableId:id,rowIndex:1,rowMinHeightPx:75,revision:h.state.doc})),true);
 const label=h.table().node.firstChild.firstChild;let position;h.state.doc.descendants((node,pos)=>{if(node.attrs.id===label.attrs.id)position=pos;});h.dispatch(h.state.tr.insertText('Changed',position+1,position+1+label.content.size));
 const saved=documentFromState(h.state),loaded=createManualState({document:saved}),table=findManualCoverRole(loaded,'cover','metadata').node;assert.deepEqual(getManualTableLayout(table).columnWeights,[1,2,3,4,5]);assert.deepEqual(getManualTableLayout(table).rowMinHeightsPx,[null,75]);assert.equal(saved.cover.metadata[0].label.map(run=>run.text).join(''),'Changed');assert.deepEqual(saved.cover.metadata[0].extensions,{vendor:{opaque:0}});assert.deepEqual(documentFromState(loaded),saved);
});
test('metadata trailing destructive preview handles canonical merged physical cells and minimum size',()=>{
 const h=harness(3),table=h.table().node,target=captureManualTableActionTarget(h.state,{tableId:table.attrs.id,cellId:table.lastChild.lastChild.attrs.id,mode:'column',generation:7});
 const description=describeManualTableTrailingChange(h.state,target,-2,{generation:7});assert.equal(description.enabled,true);assert.equal(description.needsConfirmation,true);assert.equal(description.contentCount,2);assert.equal(executeManualTableTrailingChange(h.view,target,-2,{generation:7}),false);assert.equal(h.dispatches,0);
 const before=documentFromState(h.state);assert.equal(executeManualTableTrailingChange(h.view,target,-2,{generation:7,confirmedDeletion:true}),true);assert.equal(TableMap.get(h.table().node).width,2);roundtrip(h,before,table.attrs.id);
});
test('actual public ManualPrint SSR emits the saved metadata grid and layout instead of rebuilding scalar pairs',async()=>{
 const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),runtime=path.resolve(root,'../lk-design-system'),require=createRequire(path.join(runtime,'package.json')),{build}=require('esbuild');
 const compiled=await build({plugins:[{name:'public-theme-url-ssr',setup(build){build.onResolve({filter:/^@lk-design-system\/lds-theme\/assets\/brand\/.*\?url$/},args=>({path:args.path,namespace:'theme-url'}));build.onLoad({filter:/.*/,namespace:'theme-url'},args=>({contents:'export default '+JSON.stringify(args.path),loader:'js'}));}}],entryPoints:[path.join(root,'apps/editor/src/redesign/ManualPrint.jsx')],bundle:true,write:false,platform:'node',format:'cjs',jsx:'automatic',loader:{'.css':'empty'},external:['react','react-dom'],alias:{'@lk-design-system/lds-core/components/status/Callout':path.join(runtime,'packages/core/src/components/status/Callout.jsx'),'@lk-design-system/lds-core/components/content/Blockquote':path.join(runtime,'packages/core/src/components/content/Blockquote.jsx')}});
 const module={exports:{}};new Function('require','module','exports',compiled.outputFiles[0].text)(require,module,module.exports);const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),h=harness(),id=h.table().node.attrs.id;h.run(h.pin('column'),'duplicate');h.command(setManualTableColumnWidths({tableId:id,columnWeights:[1,2,3,4,5],revision:h.state.doc}));h.command(setManualTableRowHeight({tableId:id,rowIndex:1,rowMinHeightPx:70,revision:h.state.doc}));
 const html=renderToStaticMarkup(React.createElement(module.exports.ManualPrint,{document:documentFromState(h.state),assets:{},onIssues:()=>{}}));assert.equal((html.match(/<th /g)||[]).length,5);assert.equal((html.match(/<td /g)||[]).length,5);assert.equal((html.match(/<col /g)||[]).length,5);assert.match(html,/height:70px/);assert.ok(html.includes('Value3'));assert.equal((html.match(new RegExp(' id="'+id+'"','g'))||[]).length,1);
});

test('document copy remaps other-page links into new saved grid cells and preserves scalar entry ID reuse',()=>{
 const h=harness();h.run(h.pin('column'),'duplicate');const saved=documentFromState(h.state),grid=h.table().node,id=grid.lastChild.lastChild.attrs.id;saved.pages[0].blocks[0].content=[{type:'text',text:'Link',marks:[{type:'link',href:'#'+id}]}];
 const copied=copyManualDocument(saved),loaded=createManualState({document:copied}),table=findManualCoverRole(loaded,copied.cover.id,'metadata').node;assert.notEqual(table.lastChild.lastChild.attrs.id,id);assert.equal(copied.pages[0].blocks[0].content[0].marks[0].href,'#'+table.lastChild.lastChild.attrs.id);assert.equal(table.firstChild.firstChild.attrs.id,copied.cover.metadata[0].id);assert.deepEqual(documentFromState(loaded),copied);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:copied,assets:{}})).document,copied);assert.equal(saved.pages[0].blocks[0].content[0].marks[0].href,'#'+id);
});
