import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeOutlinePageSelection,selectOutlinePageTarget,intersectOutlinePageRows,outlineSelectionSources,outlineSelectionContextMatches,installOutlinePageSelection} from '../src/redesign/outline-page-selection.mjs';
const groups=[{id:'cover',pageIds:['cover']},{id:'a',pageIds:['a','tail']},{id:'b',pageIds:['b']},{id:'c',pageIds:['c']}];
const rect=(top,bottom,left=12,right=188)=>({left,right,top,bottom});
test('normalization closes physical tails to logical roots, removes stale IDs and keeps document order',()=>{assert.deepEqual(normalizeOutlinePageSelection(groups,{anchorId:'tail',selectedIds:['c','tail','missing','a']}).selectedIds,['a','c']);assert.equal(normalizeOutlinePageSelection(groups,{anchorId:'tail'}).anchorId,'a');});
test('single and Shift select forward/backward logical ranges including covers',()=>{assert.deepEqual(selectOutlinePageTarget(groups,{},'tail').selectedIds,['a']);const start={anchorId:'c',selectedIds:['c']};assert.deepEqual(selectOutlinePageTarget(groups,start,'cover',{shiftKey:true}).selectedIds,['cover','a','b','c']);assert.equal(selectOutlinePageTarget(groups,start,'a',{shiftKey:true}).anchorId,'c');assert.equal(selectOutlinePageTarget(groups,start,'missing'),null);});
test('Ctrl/Meta toggle retains anchor and selected menu/move sources use the complete logical selection',()=>{const next=selectOutlinePageTarget(groups,{anchorId:'a',selectedIds:['a','c']},'tail',{ctrlKey:true});assert.deepEqual(next,{anchorId:'a',selectedIds:['c']});assert.deepEqual(outlineSelectionSources(groups,next,'c'),['c']);assert.deepEqual(outlineSelectionSources(groups,{selectedIds:['a','c']},'tail'),['a','c']);assert.deepEqual(selectOutlinePageTarget(groups,next,'b',{metaKey:true}).selectedIds,['b','c']);});
test('marquee clips to nav viewport, requires real intersection and expands a hit tail',()=>{const rows=[{id:'cover',rect:rect(-40,-1)},{id:'tail',rect:rect(5,35)},{id:'b',rect:rect(45,75)},{id:'c',rect:rect(95,125)}];assert.deepEqual(intersectOutlinePageRows(groups,rows,{left:0,right:100,top:-50,bottom:75},rect(0,100,0,200)),['a','b']);assert.deepEqual(intersectOutlinePageRows(groups,rows,{left:0,right:12,top:0,bottom:100},rect(0,100,0,200)),[]);});
function target(){const events=new Map();return {addEventListener(name,fn){if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);},removeEventListener(name,fn){events.get(name)?.delete(fn);},emit(name,extra={}){const event={button:0,pointerId:1,isPrimary:true,clientX:3,clientY:3,detail:1,target:{closest:()=>null},preventDefault(){this.prevented=true;},stopPropagation(){},stopImmediatePropagation(){this.stopped=true;},...extra};for(const fn of events.get(name)||[])fn(event);return event;},events};}
function fixture({scrolling=false}={}){const document=target(),surface=target();let context={editor:{},revision:{},generation:1},selection={anchorId:'c',selectedIds:['c']},enabled=true,frameId=0;const frames=new Map(),changes=[],sessions=[],previews=[];Object.assign(surface,{requestAnimationFrame(fn){frames.set(++frameId,fn);return frameId;},cancelAnimationFrame(id){frames.delete(id);}});const container=Object.assign(target(),{ownerDocument:document,scrollTop:0,scrollHeight:200,clientHeight:100,getBoundingClientRect:()=>rect(0,100,0,200),querySelectorAll:()=>[{dataset:{outlinePageRow:'a'},getBoundingClientRect:()=>rect(10-container.scrollTop,30-container.scrollTop)},{dataset:{outlinePageRow:'b'},getBoundingClientRect:()=>rect((scrolling?70:40)-container.scrollTop,(scrolling?95:60)-container.scrollTop)},...(scrolling?[{dataset:{outlinePageRow:'c'},getBoundingClientRect:()=>rect(130-container.scrollTop,160-container.scrollTop)}]:[])],setPointerCapture(){},releasePointerCapture(){}});const controller=installOutlinePageSelection({container,surface,getGroups:()=>groups,getSelection:()=>selection,getContext:()=>context,isEnabled:()=>enabled,onChange(next,meta){selection=next;changes.push({next,meta});},onPreview:value=>previews.push(value),onSessionChange:value=>sessions.push(value)});return {document,surface,container,controller,changes,sessions,previews,flush(){const fns=[...frames.values()];frames.clear();fns.forEach(fn=>fn());},replaceContext(){context={...context,generation:2};},disable(){enabled=false;}};}
test('blank gutter drag activates at 6px, commits selected roots once and suppresses trailing click',()=>{const f=fixture();f.container.emit('pointerdown');f.document.emit('pointermove',{clientX:4,clientY:4});f.flush();assert.equal(f.changes.length,0);f.document.emit('pointermove',{clientX:100,clientY:65});f.flush();assert.deepEqual(f.changes.at(-1).next.selectedIds,['a','b']);f.document.emit('pointerup',{clientX:100,clientY:65});assert.equal(f.changes.filter(x=>x.meta.reason==='marquee-commit').length,1);assert.equal(f.container.emit('click').prevented,true);assert.deepEqual(f.sessions,[true,false]);f.controller.dispose();});
test('row/insertion/control starts are inert and ordinary click-sized blank movement is a no-op',()=>{const f=fixture();f.container.emit('pointerdown',{target:{closest:()=>({})}});assert.equal(f.controller.isSelecting(),false);f.container.emit('pointerdown');f.document.emit('pointerup');assert.equal(f.changes.length,0);assert.deepEqual(f.sessions,[true,false]);f.controller.dispose();});
test('Escape cancels a live preview to baseline; a stale editor generation never restores or commits',()=>{const f=fixture();f.container.emit('pointerdown');f.document.emit('pointermove',{clientX:100,clientY:65});f.flush();f.document.emit('keydown',{key:'Escape'});assert.deepEqual(f.changes.at(-1).next.selectedIds,['c']);assert.equal(f.changes.at(-1).meta.reason,'marquee-cancel');f.container.emit('pointerdown');f.document.emit('pointermove',{clientX:100,clientY:65});f.flush();const count=f.changes.length;f.replaceContext();f.document.emit('pointerup',{clientX:100,clientY:65});assert.equal(f.changes.length,count);assert.equal(f.controller.isSelecting(),false);f.controller.dispose();});
test('disabled/IME/blur/lost capture cancel and disposal detaches listeners without late dispatch',()=>{const f=fixture();f.disable();f.container.emit('pointerdown');assert.equal(f.controller.isSelecting(),false);f.controller.dispose();assert.equal([...f.document.events.values()].reduce((n,v)=>n+v.size,0),0);assert.equal(outlineSelectionContextMatches({editor:1,revision:2,generation:3},{editor:1,revision:2,generation:4}),false);for(const [where,name,event]of [['document','keydown',{isComposing:true}],['surface','blur',{}],['document','lostpointercapture',{pointerId:1}]]){const h=fixture();h.container.emit('pointerdown');h.document.emit('pointermove',{clientX:100,clientY:65});h.flush();h[where].emit(name,event);assert.equal(h.changes.at(-1).meta.reason,'marquee-cancel');h.controller.dispose();}});
import fs from 'node:fs';
import {createRequire} from 'node:module';
const runtimeRequire=createRequire(new URL('../../../../lk-design-system/package.json',import.meta.url));
const {transformSync}=runtimeRequire('esbuild');
function renderOutline(props){const original=fs.readFileSync(new URL('../src/redesign/ManualPageOutline.jsx',import.meta.url),'utf8'),source=original.replace(/^import .*;\n/gm,'').replace('export function ManualPageOutline','function ManualPageOutline');const code=transformSync(source,{loader:'jsx',jsxFactory:'React.createElement'}).code;const React={createElement:(type,props,...children)=>({type,props:props||{},children})},useRef=value=>({current:value}),useState=value=>[value,()=>{}],useEffect=()=>{},useCallback=fn=>fn;const component=new Function('React','useRef','useState','useEffect','useCallback','Icon','Button','inlineText','installOutlinePageDrag','installOutlinePageSelection','normalizeOutlinePageSelection','selectOutlinePageTarget','outlineSelectionSources','outlineSelectionContextMatches',code+';return ManualPageOutline;')(React,useRef,useState,useEffect,useCallback,'Icon','Button',value=>typeof value==='string'?value:'',()=>{},installOutlinePageSelection,normalizeOutlinePageSelection,selectOutlinePageTarget,outlineSelectionSources,outlineSelectionContextMatches);return component(props);}
function nodes(root){return [root,...(root.children||[]).flat(Infinity).filter(value=>value&&typeof value==='object').flatMap(nodes)];}
test('actual transformed Outline preserves default callbacks and distinguishes selected tails from editing current page',()=>{const entries=['cover','a','tail','b','c'].map(id=>({id,title:id})),navigations=[];const plain=nodes(renderOutline({pageEntries:entries,groups,onNavigate:id=>navigations.push(id)}));const button=plain.find(node=>node.type==='button'&&node.props.title==='tail');button.props.onClick({});assert.deepEqual(navigations,['tail']);assert.equal(button.props['aria-pressed'],undefined);const context={editor:{},revision:{},generation:1},controlled=nodes(renderOutline({pageEntries:entries,groups,editingPage:3,selection:{...context,anchorId:'a',selectedIds:['a']},getSelectionContext:()=>context,onSelectionChange(){}}));assert.equal(controlled.find(node=>node.props['data-outline-page-row']==='tail').props['data-outline-page-selected'],true);assert.equal(controlled.find(node=>node.type==='button'&&node.props.title==='b').props['aria-current'],'page');assert.equal(controlled.find(node=>node.type==='button'&&node.props.title==='tail').props['aria-current'],undefined);});
test('actual Outline callbacks keep toggle navigation inert, Shift navigation active and menu batch context pinned',()=>{const context={editor:{},revision:{},generation:1},changes=[],navigations=[],menus=[],tree=nodes(renderOutline({pageEntries:['cover','a','tail','b','c'].map(id=>({id,title:id})),groups,selection:{...context,anchorId:'a',selectedIds:['a','c']},getSelectionContext:()=>context,onSelectionChange:(value,meta)=>changes.push({value,meta}),onNavigate:id=>navigations.push(id),onOpenMenu:(...args)=>menus.push(args)}));const button=tree.find(node=>node.type==='button'&&node.props.title==='b');button.props.onClick({ctrlKey:true});assert.deepEqual(navigations,[]);assert.deepEqual(changes.at(-1).value.selectedIds,['a','b','c']);button.props.onClick({shiftKey:true});assert.deepEqual(navigations,['b']);assert.deepEqual(changes.at(-1).value.selectedIds,['a','b']);const menu=tree.find(node=>node.type==='Button'&&node.props['aria-label']==='3쪽 페이지 작업');menu.props.onClick({});assert.deepEqual(menus[0][2].sourceIds,['a','c']);assert.equal(menus[0][2].context,context);});

test('actual controller autoscroll retains earlier pages and reversing recomputes a shrinking content range',()=>{const f=fixture({scrolling:true});f.container.emit('pointerdown');f.document.emit('pointermove',{clientX:100,clientY:98});for(let i=0;i<12;i++)f.flush();assert.equal(f.container.scrollTop,100);assert.deepEqual(f.changes.at(-1).next.selectedIds,['a','b','c']);assert.equal(f.previews.at(-1).top,0);f.document.emit('pointermove',{clientX:100,clientY:5});f.flush();assert.ok(f.container.scrollTop<100);assert.deepEqual(f.changes.at(-1).next.selectedIds,['a','b']);f.document.emit('pointermove',{clientX:100,clientY:35});f.container.scrollTop=0;f.container.emit('scroll');f.flush();assert.deepEqual(f.changes.at(-1).next.selectedIds,['a']);f.document.emit('pointerup',{clientX:100,clientY:35});assert.deepEqual(f.changes.at(-1).next.selectedIds,['a']);f.controller.dispose();});
