import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createManualState} from '../src/redesign/manual-kernel.mjs';
import {getManualPageGroups} from '../src/redesign/manual-page-groups.mjs';
import {installOutlinePageSelection,normalizeOutlinePageSelection,outlineSelectionContextMatches} from '../src/redesign/outline-page-selection.mjs';
const source=readFileSync(new URL('../src/redesign/ManualEditor.jsx',import.meta.url),'utf8');
const callbacks=source.slice(source.indexOf(' function getOutlineSelectionContext()'),source.indexOf(' function reconcileOutlineSelection('));
function parent(editor){return new Function('editor','getManualPageGroups','normalizeOutlinePageSelection','outlineSelectionContextMatches',`
 const view={current:editor},generation={current:1},outlineSelectionRef={current:null},ownOutlineSelectSession={current:null},outlineSelectionController={current:null};
 const replacing={current:false},replacementSaving={current:false},printing={current:false},dragController={current:null},outlineDragController={current:null},marqueeController={current:null},figureResizeSession={current:null},tableUISession={current:null},tableResizeSession={current:null},marginDrag={current:null};
 const uiApi={current:{paginationEnabled:true}},pagination={current:{request(){}}};let disabled=false,replacementBusy=false,modal=null,menu=null;function setOutlineSelection(){}
 ${callbacks}
 return {getSelection:currentOutlineSelection,getStored:()=>outlineSelectionRef.current,getContext:getOutlineSelectionContext,isEnabled:canSelectOutline,onChange:changeOutlineSelection,onSessionChange:outlineSelectionSessionChanged,seed:()=>storeOutlineSelection({anchorId:'c',selectedIds:['c'],...getOutlineSelectionContext()}),disable:()=>disabled=true,modal:()=>modal='test',readonly:()=>editor.editable=false,ime:()=>editor.composing=true,newDocument:()=>{generation.current++;storeOutlineSelection(null);},attach:controller=>outlineSelectionController.current=controller};
 `)(editor,getManualPageGroups,normalizeOutlinePageSelection,outlineSelectionContextMatches);}
function events(){const listeners=new Map();return {addEventListener(key,fn){if(!listeners.has(key))listeners.set(key,new Set());listeners.get(key).add(fn);},removeEventListener(key,fn){listeners.get(key)?.delete(fn);},emit(key,extra={}){const e={type:key,button:0,pointerId:1,isPrimary:true,clientX:3,clientY:3,detail:1,target:{closest:()=>null},preventDefault(){},stopPropagation(){},...extra};for(const fn of [...listeners.get(key)||[]])fn(e);}};}
function harness(){
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:['a','b','c'].map(id=>({id,title:[],blocks:[]}))}}),transactions=0;const editor={get state(){return state;},editable:true,composing:false,dispatch:tr=>{transactions++;state=state.applyTransaction(tr).state;}};
 const api=parent(editor);api.seed();const document=events(),surface=events(),frames=new Map();let seq=0;surface.requestAnimationFrame=fn=>{frames.set(++seq,fn);return seq;};surface.cancelAnimationFrame=id=>frames.delete(id);document.defaultView=surface;
 const rows=['a','b','c'].map((id,index)=>({dataset:{outlinePageRow:id},getBoundingClientRect:()=>({left:12,right:170,top:10+index*30,bottom:30+index*30})}));const container=Object.assign(events(),{ownerDocument:document,scrollTop:0,scrollLeft:0,scrollHeight:100,clientHeight:100,getBoundingClientRect:()=>({left:0,right:200,top:0,bottom:100}),querySelectorAll:()=>rows,setPointerCapture(){},releasePointerCapture(){}});
 const controller=installOutlinePageSelection({container,surface,getGroups:()=>getManualPageGroups(state.doc),getSelection:api.getSelection,getContext:api.getContext,isEnabled:api.isEnabled,onChange:api.onChange,onSessionChange:api.onSessionChange});api.attach(controller);
 const begin=()=>{container.emit('pointerdown');document.emit('pointermove',{clientX:100,clientY:65});const queue=[...frames.values()];frames.clear();for(const fn of queue)fn();assert.deepEqual(api.getSelection().selectedIds,['a','b']);};
 return {api,editor,controller,document,surface,begin,get state(){return state;},get transactions(){return transactions;},replace(){state=createManualState({document:{schemaVersion:2,id:'new-doc',title:'New synthetic',pages:[{id:'new-page',title:[],blocks:[]}]}});api.newDocument();}};
}
for(const mode of ['pointercancel','blur','Escape'])test(`normal ${mode} actual Parent/controller restores baseline with zero PM transactions`,()=>{const h=harness(),before=h.state;h.begin();if(mode==='blur')h.surface.emit('blur');else if(mode==='Escape')h.document.emit('keydown',{key:'Escape'});else h.document.emit('pointercancel');assert.deepEqual(h.api.getSelection().selectedIds,['c']);assert.equal(h.transactions,0);assert.equal(h.state,before);assert.equal(h.controller.isSelecting(),false);h.controller.dispose();});
for(const mode of ['readonly','ime','modal'])test(`${mode} cancels same-context outline preview and restores original UI selection`,()=>{const h=harness(),before=h.state;h.begin();h.api[mode]();if(mode==='ime')h.document.emit('keydown',{isComposing:true,keyCode:229});else h.controller.cancel();assert.deepEqual(h.api.getSelection().selectedIds,['c']);assert.equal(h.transactions,0);assert.equal(h.state,before);h.controller.dispose();});
test('new document generation cannot restore old outline selection on cancellation',()=>{const h=harness();h.begin();h.replace();const before=h.state;h.controller.cancel();assert.equal(h.api.getStored(),null);assert.deepEqual(h.api.getSelection().selectedIds,[]);assert.equal(h.state,before);assert.equal(h.transactions,0);h.controller.dispose();});
