import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeSelection,TextSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,findManualPageRole,deleteManualObject,duplicateManualObject,selectManualObject,moveManualObject,manualCommands,applyManualPageTitle,getManualPageTitleCommandState,executeManualBlockCommand,getManualSlashTrigger,normalizeManualPastedSlice} from '../src/redesign/manual-kernel.mjs';
import {Fragment,Slice} from '@tiptap/pm/model';
import {getManualPageProjection,projectManualPage,MANUAL_PAGE_PROJECTION_OWNER} from '../src/redesign/manual-page-projection.mjs';
import {withManualPaginationMarker,manualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
import {selectManualBlocks,selectManualBlockIds} from '../src/redesign/manual-block-selection.mjs';
const runs=[{type:'text',text:'Promote',marks:[{type:'strong'},{type:'underline'}]},{type:'hardBreak'},{type:'text',text:'title'}];
const paragraph=(id,content=runs,extensions={vendor:{id}})=>({id,type:'paragraph',content,extensions});
function fixture(){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:[],metadata:[],blocks:[]},pages:[{id:'root',title:[],blocks:[paragraph('source'),paragraph('body',[{type:'text',text:'Body'}])]}, {id:'other',title:[],blocks:[paragraph('foreign')]}]};}
function h(document=fixture()){let state=createManualState({document}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,composing:false,editable:true};return {get state(){return state;},get count(){return count;},get document(){return documentFromState(state);},dispatch,view,run:(command,v=view)=>command(state,dispatch,v),missing(){const title=findManualPageRole(state,'root','title');assert.equal(deleteManualObject(title.node.attrs.id)(state,dispatch),true);return title.node.attrs.id;},select(id){assert.equal(selectManualObject(id)(state,dispatch),true);},boundary(){dispatch(closeHistory(state.tr));}};}
function exact(a){const document=a.document;assert.deepEqual(documentFromState(createManualState({document})),document);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document,assets:{}})).document,document);return document;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
test('missing-title insertion has an actual role, fresh identity, matching dry run and one Undo while existing/current title never dispatch',()=>{
 const a=h(),old=a.missing();a.select('source');a.boundary();const before=a.state,count=a.count,status=getManualPageTitleCommandState(a.state,{mode:'insert'},a.view);assert.equal(status.enabled,true);assert.equal(status.rootPageId,'root');assert.equal(applyManualPageTitle({mode:'insert'})(a.state),true);assert.equal(a.state,before);assert.equal(a.count,count);assert.equal(a.run(applyManualPageTitle({mode:'insert'})),true);assert.equal(a.count,count+1);const title=findManualPageRole(a.state,'root','title');assert.notEqual(title.node.attrs.id,old);assert.equal(title.index,0);assert.equal(a.state.selection.$from.parent.attrs.id,title.node.attrs.id);assert.deepEqual(exact(a).pages[0].title,[]);assert.equal(getManualPageTitleCommandState(a.state,{targetId:title.node.attrs.id}).reason,'current-title');assert.equal(getManualPageTitleCommandState(a.state,{targetId:title.node.attrs.id}).selectedCurrent,true);const current=a.state,mutations=a.count;assert.equal(a.run(applyManualPageTitle({targetId:title.node.attrs.id})),false);assert.equal(a.run(executeManualBlockCommand('pageTitle',{mode:'insert',targetId:'source'})),false);assert.equal(a.state,current);assert.equal(a.count,mutations);undoRedo(a,before);
});
test('turnInto preserves original text identity, marks and opaque namespaces in a pinned scalar role through file copy and page duplicate',()=>{
 const document=fixture();document.pages[0].blocks[0].extensions={manualPageProjection:{owner:'vendor',keep:1},vendor:{nested:{id:'opaque-original'}}};const a=h(document);a.missing();a.select('source');a.boundary();const before=a.state;assert.equal(a.run(executeManualBlockCommand('pageTitle',{mode:'convert',targetId:'source'})),true);const title=findManualPageRole(a.state,'root','title');assert.equal(title.node.attrs.id,'source');assert.equal(title.index,0);const d=exact(a),layout=Object.values(d.pages[0].extensions).find(value=>value.owner===MANUAL_PAGE_PROJECTION_OWNER);assert.deepEqual(layout.pinnedRoles,['title']);assert.equal(layout.roleIds.title,'source');assert.deepEqual(d.pages[0].title,runs);assert.deepEqual(layout.roleExtensions.title,document.pages[0].blocks[0].extensions);assert.equal(findManualPageRole(createManualState({document:d}),'root','title').node.attrs.id,'source');undoRedo(a,before);
 const copied=copyManualDocument(d),b=h(copied),copyTitle=findManualPageRole(b.state,copied.pages[0].id,'title');assert.notEqual(copyTitle.node.attrs.id,'source');assert.deepEqual(getManualPageProjection(copyTitle.node.attrs.meta.extensions).originalInline,runs);assert.deepEqual(copyTitle.node.attrs.meta.extensions.vendor,document.pages[0].blocks[0].extensions.vendor);exact(b);
 assert.equal(a.run(duplicateManualObject('root')),true);const clone=a.document.pages[1],cloneTitle=findManualPageRole(a.state,clone.id,'title');assert.notEqual(cloneTitle.node.attrs.id,'source');assert.deepEqual(clone.title,runs);assert.deepEqual(cloneTitle.node.attrs.meta.extensions.vendor,document.pages[0].blocks[0].extensions.vendor);exact(a);
});
test('tail ordinary text promotion maps to its logical root, syncs distinct derived identities and restores the entire family in one Undo',()=>{
 const document=fixture();document.pages.splice(1,0,{id:'tail',title:[{type:'text',text:'Stale derived title'}],blocks:[paragraph('tail-text'),paragraph('tail-body',[{type:'text',text:'Tail body'}])],...withManualPaginationMarker({}, {kind:'page',rootPageId:'root'})});const a=h(document);a.missing();const oldTail=findManualPageRole(a.state,'tail','title').node.attrs.id;a.select('tail-text');a.boundary();const before=a.state,status=getManualPageTitleCommandState(a.state,{mode:'turnInto',targetId:'tail-text'});assert.equal(status.enabled,true);assert.equal(status.rootPageId,'root');assert.equal(status.physicalPageId,'tail');assert.equal(a.run(applyManualPageTitle({mode:'turnInto',targetId:'tail-text'})),true);const root=findManualPageRole(a.state,'root','title'),tail=findManualPageRole(a.state,'tail','title');assert.equal(root.node.attrs.id,'tail-text');assert.equal(tail.node.attrs.id,oldTail);assert.notEqual(tail.node.attrs.id,root.node.attrs.id);assert.equal(getManualPageProjection(tail.node.attrs.meta.extensions).derivedFrom,'root');assert.equal(a.state.selection.$from.parent.attrs.id,'tail-text');const d=exact(a);assert.equal(d.pages[0].id,'root');assert.equal(d.pages[1].id,'tail');assert.equal(manualPaginationMarker(d.pages[1].extensions,'page').rootPageId,'root');assert.deepEqual(d.pages[0].title,runs);assert.deepEqual(d.pages[1].title,runs);assert.deepEqual(d.pages[1].blocks.map(block=>block.id),['tail-body']);undoRedo(a,before);
});
test('tail insertion restores missing family titles with unique collision-safe derived IDs and selection at the root',()=>{
 const document=fixture();document.pages.splice(1,0,{id:'tail',title:[],blocks:[paragraph('manual-page:tail:title'),paragraph('tail-body')],...withManualPaginationMarker({}, {kind:'page',rootPageId:'root'})});const a=h(document);a.missing();a.run(deleteManualObject(findManualPageRole(a.state,'tail','title').node.attrs.id));a.select('tail-body');a.boundary();const before=a.state;assert.equal(a.run(applyManualPageTitle({mode:'insert'})),true);const root=findManualPageRole(a.state,'root','title'),tail=findManualPageRole(a.state,'tail','title');assert.notEqual(root.node.attrs.id,tail.node.attrs.id);assert.notEqual(tail.node.attrs.id,'manual-page:tail:title');assert.equal(findManualObject(a.state,'manual-page:tail:title').node.type.name,'paragraph');assert.equal(a.state.selection.$from.parent.attrs.id,root.node.attrs.id);exact(a);undoRedo(a,before);
});
test('slash insertion consumes only its trigger and disabled restoration leaves the slash text untouched',()=>{
 const document=fixture();document.pages[0].blocks[0].content=[{type:'text',text:'/page'}];const a=h(document);a.missing();const source=findManualObject(a.state,'source');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,source.pos+1+source.node.content.size)));a.boundary();const before=a.state,trigger=getManualSlashTrigger(a.state);assert.ok(trigger);assert.equal(a.run(executeManualBlockCommand('pageTitle',{mode:'insert',trigger})),true);assert.equal(findManualObject(a.state,'source').node.textContent,'');assert.equal(findManualPageRole(a.state,'root','title').node.textContent,'');exact(a);undoRedo(a,before);
 const b=h(document),found=findManualObject(b.state,'source');b.dispatch(b.state.tr.setSelection(TextSelection.create(b.state.doc,found.pos+1+found.node.content.size)));const current=b.state,count=b.count;assert.equal(b.run(executeManualBlockCommand('pageTitle',{mode:'insert',trigger:getManualSlashTrigger(b.state)})),false);assert.equal(b.state,current);assert.equal(b.count,count);assert.equal(findManualObject(b.state,'source').node.textContent,'/page');
});
test('readOnly, stale, IME, foreign page, cover, nested/fragmented text and derived titles give matching disabled reasons with no dispatch',()=>{
 const a=h();a.missing();a.select('source');const before=a.state,count=a.count;for(const [options,view,reason]of [[{mode:'insert',readOnly:true},a.view,'read-only'],[{mode:'insert',revision:{}},a.view,'stale'],[{mode:'insert',cancelled:true},a.view,'cancelled'],[{mode:'insert'},{composing:true},'composing'],[{mode:'insert'},{editable:false},'read-only'],[{mode:'turnInto',pageId:'root',targetId:'foreign'},a.view,'foreign-page'],[{mode:'insert',targetId:'cover'},a.view,'no-page'],[{mode:'turnInto',targetId:'body',pageId:'missing'},a.view,'no-page']]){assert.equal(getManualPageTitleCommandState(a.state,options,view).reason,reason);assert.equal(a.run(applyManualPageTitle(options),view),false);}assert.equal(a.state,before);assert.equal(a.count,count);
 const document=fixture();document.pages.splice(1,0,{id:'tail',title:[],blocks:[paragraph('tail-source')],...withManualPaginationMarker({}, {kind:'page',rootPageId:'root'})});const b=h(document);b.missing();const derived=findManualPageRole(b.state,'tail','title');assert.equal(getManualPageTitleCommandState(b.state,{mode:'turnInto',targetId:derived.node.attrs.id}).reason,'derived-title');assert.equal(b.run(applyManualPageTitle({mode:'turnInto',targetId:derived.node.attrs.id})),false);
 const fragmented=fixture();fragmented.pages[0].blocks[0]={...fragmented.pages[0].blocks[0],...withManualPaginationMarker(fragmented.pages[0].blocks[0],{kind:'block',rootBlockId:'prior',sourceType:'paragraph'})};const c=h(fragmented);c.missing();assert.equal(getManualPageTitleCommandState(c.state,{mode:'turnInto',targetId:'source'}).reason,'fragmented-text');assert.equal(c.run(applyManualPageTitle({mode:'turnInto',targetId:'source'})),false);
});
test('promoted title ordinary copy, foreign move and format release preserve its ID/content without leaving a scalar binding',()=>{
 const a=h();a.missing();a.select('source');a.run(applyManualPageTitle({mode:'turnInto',targetId:'source'}));const title=findManualPageRole(a.state,'root','title'),slice=normalizeManualPastedSlice(new Slice(Fragment.from(title.node),0,0));assert.equal(slice.content.firstChild.type.name,'heading');assert.equal(getManualPageProjection(slice.content.firstChild.attrs.meta.extensions),null);
 assert.equal(a.run(moveManualObject('source',{parentId:'other',index:1})),true);assert.deepEqual(exact(a).pages[0].title,[]);assert.equal(findManualObject(a.state,'source').node.type.name,'heading');assert.deepEqual(a.document.pages[1].blocks[0].content,runs);assert.equal(getManualPageProjection(a.document.pages[1].blocks[0].extensions),null);
 const b=h();b.missing();b.select('source');b.run(applyManualPageTitle({mode:'turnInto',targetId:'source'}));assert.equal(b.run(executeManualBlockCommand('heading3',{mode:'convert',targetId:'source'})),true);assert.deepEqual(exact(b).pages[0].title,[]);assert.equal(b.document.pages[0].blocks[0].id,'source');assert.equal(b.document.pages[0].blocks[0].level,3);assert.deepEqual(b.document.pages[0].blocks[0].content,runs);
});
test('single-target role API rejects contiguous multi-block, incomplete logical fragments and cross-block text ranges before mutation',()=>{
 const a=h();a.missing();a.run(selectManualBlocks('source','body'));const before=a.state,count=a.count;for(const mode of ['insert','turnInto']){const options={mode,targetId:'source'};assert.equal(getManualPageTitleCommandState(a.state,options).reason,'ineligible-selection');assert.equal(a.run(applyManualPageTitle(options)),false);}assert.equal(a.state,before);assert.equal(a.count,count);
 const document=fixture();document.pages.splice(1,0,{id:'tail',title:[],blocks:[{...paragraph('fragment'),...withManualPaginationMarker({}, {kind:'block',rootBlockId:'source',sourceType:'paragraph'})}],...withManualPaginationMarker({}, {kind:'page',rootPageId:'root'})});const b=h(document);b.missing();b.run(selectManualBlockIds(['source'],{logicalFragments:false}));assert.equal(b.state.selection.manualIncompletePaginationSelection,true);const unchanged=b.state,mutations=b.count;assert.equal(getManualPageTitleCommandState(b.state,{mode:'turnInto',targetId:'source'}).reason,'ineligible-selection');assert.equal(b.run(applyManualPageTitle({mode:'turnInto',targetId:'source'})),false);assert.equal(b.state,unchanged);assert.equal(b.count,mutations);
 const c=h();c.missing();const first=findManualObject(c.state,'source'),last=findManualObject(c.state,'body');c.dispatch(c.state.tr.setSelection(TextSelection.create(c.state.doc,first.pos+1,last.pos+2)));const textBefore=c.state,textCount=c.count;assert.equal(getManualPageTitleCommandState(c.state,{mode:'turnInto',targetId:'source'}).reason,'ineligible-selection');assert.equal(c.run(applyManualPageTitle({mode:'turnInto',targetId:'source'})),false);assert.equal(c.state,textBefore);assert.equal(c.count,textCount);
});
test('one contiguous block remains an eligible turnInto target and one Undo restores the original block selection',()=>{
 const a=h();a.missing();a.run(selectManualBlocks('source'));a.boundary();const before=a.state,options={mode:'turnInto',targetId:'source'};assert.equal(getManualPageTitleCommandState(a.state,options).enabled,true);assert.equal(a.run(applyManualPageTitle(options)),true);assert.equal(findManualPageRole(a.state,'root','title').node.attrs.id,'source');exact(a);undoRedo(a,before);
});
