import test from 'node:test';
import assert from 'node:assert/strict';
import {Fragment,Slice} from '@tiptap/pm/model';
import {NodeSelection,TextSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,getManualEditingDocument,findManualObject,findManualCoverRole,findManualPageRole,getManualCoverInsertCommandState,executeManualCoverInsert,selectManualObject,deleteManualObject,moveManualObject,executeManualBlockCommand,getManualSlashTrigger,manualCommands,manualSchema} from '../src/redesign/manual-kernel.mjs';
import {selectManualBlocks,deleteSelectedManualBlocks,moveSelectedManualBlocks} from '../src/redesign/manual-block-selection.mjs';
import {ordinaryManualPageField} from '../src/redesign/manual-page-shape.mjs';
import {MANUAL_COVER_ELEMENT_ROLES} from '../src/redesign/manual-cover-elements.mjs';
import {projectManualCover,getManualCoverProjection,MANUAL_COVER_PROJECTION_OWNER} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {MANUAL_BRAND_ASSETS} from '../src/redesign/manual-brand-assets.mjs';
import {readManualFigureLayout} from '../src/redesign/manual-figure-layout.mjs';
import {copyManualDocument,validateManualDocument} from '../src/redesign/manual-v2.mjs';
import {getOrderedPageEntries} from '../src/redesign/manual-page-order.mjs';
import {getManualPageGroups,insertManualPageAfter} from '../src/redesign/manual-page-groups.mjs';
import {withManualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';

const runs=text=>[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}];
const paragraph=(id,text=id)=>({id,type:'paragraph',content:runs(text),extensions:{vendor:{id,future:[1,2]}}});
function fixture(){return {schemaVersion:2,id:'doc',title:'Synthetic',extensions:{vendor:{document:true}},pages:[{id:'first',title:[],blocks:[paragraph('first-body')]},{id:'target',title:runs('Original title'),lead:runs('Original lead'),blocks:[paragraph('body'),{id:'box',type:'callout',title:[],tone:'signal',blocks:[paragraph('nested')]}],extensions:{manualCoverProjection:{owner:'foreign',future:1},vendor:{page:true}}},{id:'last',title:[],blocks:[paragraph('last-body')]}]};}
function h(document=fixture()){let state=createManualState({document}),count=0,transactions=[];const dispatch=tr=>{count++;const result=state.applyTransaction(tr);transactions=result.transactions;state=result.state;};return {get state(){return state;},get count(){return count;},get transactions(){return transactions;},get document(){return documentFromState(state);},dispatch,view:{editable:true,composing:false},run(command,view=this.view){return command(state,dispatch,view);},select(id,text=true){return this.run(selectManualObject(id,{text}));},boundary(){dispatch(closeHistory(state.tr));}};}
const roleNodes=a=>{const cover=a.state.doc.content.content.find(node=>node.type.name==='cover'),roles=[];cover?.descendants(node=>{const role=getManualCoverProjection(node.attrs.meta?.extensions);if(role?.coverId===cover.attrs.id&&role.blockId===node.attrs.id)roles.push(role.role);});return roles;};
function exact(a){const d=a.document;assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const ids=[a.state.doc.attrs.meta.id];a.state.doc.descendants(node=>{if(node.attrs.id)ids.push(node.attrs.id);});assert.equal(new Set(ids).size,ids.length);return d;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
function insert(a,role,options={}){a.select('body');a.boundary();const before=a.state,count=a.count;const opt={...options,...(role==='logo'?{logoVariantId:options.logoVariantId||'logo-inline-navy'}:{})};assert.equal(executeManualCoverInsert(role,opt)(a.state),true);assert.equal(a.count,count);assert.equal(a.run(executeManualCoverInsert(role,opt)),true);assert.equal(a.count,count+1);assert.equal(a.transactions.length,1);return before;}

test('each first element converts the same selected physical page without changing page count, order or body identities',()=>{
 for(const role of MANUAL_COVER_ELEMENT_ROLES){const a=h(),original=findManualObject(a.state,'target').node,body=original.content.content.map(ordinaryManualPageField);const before=insert(a,role),d=exact(a);assert.equal(a.state.doc.childCount,3);assert.deepEqual(getOrderedPageEntries(d).map(page=>page.id),['first','target','last']);assert.equal(d.cover.id,'target');assert.deepEqual(d.pages.map(page=>page.id),['first','last']);assert.deepEqual(d.cover.extensions.vendor,{page:true});assert.deepEqual(d.cover.extensions.manualCoverProjection,{owner:'foreign',future:1});assert.deepEqual(roleNodes(a),[role]);let runtimeBody;a.state.doc.descendants(node=>{if(node.type.name==='coverBody')runtimeBody=node;});assert.deepEqual(runtimeBody.content.content.map(node=>node.toJSON()),body.map(node=>node.toJSON()));assert.deepEqual(d.cover.blocks.map(block=>block.id),body.map(node=>node.attrs.id));assert.equal(getManualEditingDocument(a.state).cover.id,'target');const layout=Object.values(d.cover.extensions).find(value=>value.owner===MANUAL_COVER_PROJECTION_OWNER);assert.deepEqual(layout?.omittedRoles||[],['title','metadata','divider'].filter(value=>value!==role));assert.equal(Object.hasOwn(d.cover,'logo'),role==='logo');assert.equal(Object.hasOwn(d.cover,'sectionTitle'),role==='sectionTitle');undoRedo(a,before);}
});

test('all five real roles insert into an existing cover, delete persistently and restore with one Undo without overwriting siblings',()=>{
 const a=h();insert(a,'divider');
 for(const role of MANUAL_COVER_ELEMENT_ROLES.filter(value=>value!=='divider')){const option={coverId:'target',...(role==='logo'?{logoVariantId:'logo-square-navy'}:{})};a.select('body');a.boundary();const before=a.state,count=a.count;assert.equal(a.run(executeManualCoverInsert(role,option)),true);assert.equal(a.count,count+1);assert.equal(a.transactions.length,1);exact(a);undoRedo(a,before);}
 assert.deepEqual(roleNodes(a),MANUAL_COVER_ELEMENT_ROLES);
 for(const role of MANUAL_COVER_ELEMENT_ROLES){const found=findManualCoverRole(a.state,'target',role),id=found.node.attrs.id,other=MANUAL_COVER_ELEMENT_ROLES.filter(value=>value!==role).map(value=>findManualCoverRole(a.state,'target',value).node.toJSON());a.select(id,false);a.boundary();const before=a.state;assert.equal(a.run(deleteManualObject(id)),true);assert.equal(findManualCoverRole(a.state,'target',role),null);const deleted=exact(a);assert.equal([...projectManualCover(deleted.cover).headerBlocks,...projectManualCover(deleted.cover).bodyBlocks].some(block=>getManualCoverProjection(block.extensions)?.role===role),false);assert.deepEqual(MANUAL_COVER_ELEMENT_ROLES.filter(value=>value!==role).map(value=>findManualCoverRole(a.state,'target',value).node.toJSON()),other);undoRedo(a,before);a.select('body');a.boundary();const restoreBefore=a.state,count=a.count;assert.equal(a.run(executeManualCoverInsert(role,{coverId:'target',...(role==='logo'?{logoVariantId:'logo-inline-white'}:{})})),true);assert.equal(a.count,count+1);assert.equal(findManualCoverRole(a.state,'target',role).node.attrs.id,id);exact(a);undoRedo(a,restoreBefore);}
});

test('current/existing role state and commands reject overwrite and preserve the entire document and selection',()=>{
 const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title');a.select(title.node.attrs.id);let before=a.state,count=a.count;assert.equal(getManualCoverInsertCommandState(a.state,{role:'title'}).reason,'current-role');assert.equal(a.run(executeManualCoverInsert('title')),false);assert.equal(a.state,before);assert.equal(a.count,count);a.select('body');before=a.state;count=a.count;assert.equal(getManualCoverInsertCommandState(a.state,{role:'title'}).reason,'role-exists');assert.equal(a.run(executeManualCoverInsert('title')),false);assert.equal(a.state,before);assert.equal(a.count,count);exact(a);
});

test('finite registry logo variants persist asset keys, alt and owned minimum-safe width through reopen and copy',()=>{
 for(const brand of MANUAL_BRAND_ASSETS){const a=h();insert(a,'logo',{logoVariantId:brand.id});const logo=findManualCoverRole(a.state,'target','logo');assert.equal(logo.node.attrs.meta.asset,brand.asset);assert.equal(logo.node.attrs.meta.alt,brand.alt);assert.equal(readManualFigureLayout(logo.node.attrs.meta.extensions).widthPx,brand.defaultWidthPx);assert.ok(brand.defaultWidthPx>=brand.minimumWidthPx);const d=exact(a);assert.deepEqual(d.cover.logo,{src:brand.asset,alt:brand.alt});const copy=copyManualDocument(d),b=h(copy);assert.notEqual(copy.cover.id,d.cover.id);assert.equal(findManualCoverRole(b.state,copy.cover.id,'logo').node.attrs.meta.asset,brand.asset);assert.equal(readManualFigureLayout(findManualCoverRole(b.state,copy.cover.id,'logo').node.attrs.meta.extensions).widthPx,brand.defaultWidthPx);assert.deepEqual(getOrderedPageEntries(copy).map(page=>page.id),[copy.pages[0].id,copy.cover.id,copy.pages[1].id]);exact(b);}
});

test('choice/cancellation, invalid finite asset, stale/readonly/IME and foreign targets dispatch no transaction',()=>{
 const a=h();a.select('body');const before=a.state,count=a.count;
 for(const [role,options,view,reason]of [['logo',{},a.view,'needs-choice'],['logo',{cancelled:true},a.view,'cancelled'],['logo',{logoVariantId:'arbitrary.svg'},a.view,'invalid-logo'],['logo',{logoVariantId:null},a.view,'invalid-logo'],['title',{revision:{}},a.view,'stale'],['title',{readOnly:true},a.view,'read-only'],['title',{}, {editable:false},'read-only'],['title',{}, {composing:true},'composing'],['unknown',{},a.view,'invalid-role'],['title',{targetId:'missing'},a.view,'missing-target'],['title',{pageId:'target',targetId:'last-body'},a.view,'foreign-page'],['title',{pageId:'last'},a.view,'foreign-page'],['title',{pageId:'missing'},a.view,'no-page']]){const status=getManualCoverInsertCommandState(a.state,{...options,role},view);assert.equal(status.reason,reason);if(reason==='needs-choice'){assert.equal(status.choiceRequired,true);assert.equal(status.canChoose,true);}assert.equal(a.run(executeManualCoverInsert(role,options),view),false);assert.equal(a.state,before);assert.equal(a.count,count);}
});

test('caption caret without its own identity resolves the actual current page and preserves every other surface',()=>{
 const source=fixture();source.pages[1].blocks.push({id:'figure',type:'figure',asset:'',alt:'',widthPreset:'full',caption:runs('Caption')});const a=h(source),figure=findManualObject(a.state,'figure');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,figure.pos+2)));a.boundary();assert.equal(a.state.selection.$from.parent.type.name,'figureCaption');assert.equal(a.state.selection.$from.parent.attrs.id,undefined);const before=a.state,status=getManualCoverInsertCommandState(a.state,{role:'divider'});assert.equal(status.enabled,true);assert.equal(status.coverId,'target');assert.equal(a.run(executeManualCoverInsert('divider')),true);assert.equal(a.state.doc.child(0).attrs.id,'first');assert.equal(a.state.doc.child(1).type.name,'cover');assert.equal(a.state.doc.child(1).attrs.id,'target');assert.equal(a.state.doc.child(2).attrs.id,'last');assert.deepEqual(exact(a).cover.blocks.at(-1),source.pages[1].blocks.at(-1));undoRedo(a,before);
});

test('slash commit removes only the verified trigger in the same transaction and cancellation or stale trigger keeps literal text',()=>{
 const source=fixture();source.pages[1].blocks[0].content=[{type:'text',text:'/cover'}];const a=h(source);a.select('body');const body=findManualObject(a.state,'body');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,body.pos+1+body.node.content.size)));a.boundary();const before=a.state,count=a.count,trigger=getManualSlashTrigger(a.state);assert.ok(trigger);assert.equal(a.run(executeManualCoverInsert('divider',{trigger})),true);assert.equal(a.count,count+1);assert.equal(a.transactions.length,1);assert.equal(findManualObject(a.state,'body').node.textContent,'');assert.deepEqual(roleNodes(a),['divider']);exact(a);undoRedo(a,before);
 const b=h(source);b.select('body');const current=findManualObject(b.state,'body');b.dispatch(b.state.tr.setSelection(TextSelection.create(b.state.doc,current.pos+1+current.node.content.size)));const unchanged=b.state,mutations=b.count,live=getManualSlashTrigger(b.state);for(const options of [{trigger:live,cancelled:true},{trigger:{...live,query:'stale'}},{trigger:live}]){const role=options.cancelled||options.trigger.query==='stale'?'title':'logo';assert.equal(b.run(executeManualCoverInsert(role,options)),false);assert.equal(b.state,unchanged);assert.equal(b.count,mutations);}assert.equal(findManualObject(b.state,'body').node.textContent,'/cover');
});

test('cover-only is a valid nonempty surface across file/copy/order/outline/add/delete consumers; the last container remains protected',()=>{
 const source=fixture();source.pages=[source.pages[1]];const a=h(source);insert(a,'sectionTitle');const d=exact(a);assert.deepEqual(d.pages,[]);assert.equal(validateManualDocument(d),d);assert.deepEqual(getManualPageGroups(a.state.doc),[{id:'target',kind:'cover',pageIds:['target']}]);assert.equal(getOrderedPageEntries(d).length,1);const copy=copyManualDocument(d);assert.deepEqual(copy.pages,[]);exact(h(copy));assert.equal(a.run(deleteManualObject('target')),false);let count=a.count;a.dispatch(a.state.tr.delete(0,a.state.doc.content.size));assert.equal(a.count,count+1);assert.equal(a.state.doc.childCount,1);assert.equal(a.state.doc.firstChild.type.name,'cover');a.boundary();const before=a.state;assert.equal(a.run(insertManualPageAfter('target')),true);assert.equal(a.state.doc.childCount,2);const pageId=a.document.pages[0].id;assert.deepEqual(getOrderedPageEntries(a.document).map(page=>page.id),['target',pageId]);exact(a);undoRedo(a,before);assert.equal(a.run(deleteManualObject(pageId)),true);assert.deepEqual(exact(a).pages,[]);assert.equal(a.run(deleteManualObject('target')),false);assert.throws(()=>validateManualDocument({schemaVersion:2,id:'empty',title:'',pages:[]}),/pages/);
});

test('actual cover scalar edits survive file/reopen/copy while normalized original title and lead remain ordinary body',()=>{
 const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title');a.dispatch(a.state.tr.insertText('New title',title.pos+1));assert.deepEqual(exact(a).cover.title,[{type:'text',text:'New title'}]);a.select('body');assert.equal(a.run(executeManualCoverInsert('sectionTitle')),true);const section=findManualCoverRole(a.state,'target','sectionTitle');a.dispatch(a.state.tr.insertText('New section',section.pos+1));const d=exact(a);assert.deepEqual(d.cover.sectionTitle,[{type:'text',text:'New section'}]);assert.equal(d.cover.blocks[0].type,'heading');assert.equal(d.cover.blocks[1].type,'paragraph');assert.deepEqual(d.cover.blocks[0].content,runs('Original title'));assert.deepEqual(d.cover.blocks[1].content,runs('Original lead'));const copy=copyManualDocument(d),b=h(copy);assert.deepEqual(b.document.cover.title,d.cover.title);assert.deepEqual(b.document.cover.sectionTitle,d.cover.sectionTitle);assert.notEqual(findManualCoverRole(b.state,copy.cover.id,'title').node.attrs.id,title.node.attrs.id);exact(b);
});

test('full cover-title block delete/cut/replacement uses normal selection and one Undo; partial inline editing keeps the role',()=>{
 for(const mode of ['delete','cut','replace']){const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title');a.dispatch(a.state.tr.insertText('Editable',title.pos+1));a.run(selectManualBlocks(title.node.attrs.id));a.boundary();const before=a.state;assert.ok(a.state.selection.content().content.size);if(mode==='delete')assert.equal(a.run(deleteSelectedManualBlocks),true);else{const tr=closeHistory(a.state.tr),slice=mode==='replace'?new Slice(Fragment.from(manualSchema.nodes.paragraph.create({id:'replacement',meta:{extensions:{vendor:{replace:1}}}},manualSchema.text('Replacement'))),0,0):Slice.empty;a.state.selection.replace(tr,slice);a.dispatch(tr);}assert.equal(findManualCoverRole(a.state,'target','title'),null);assert.deepEqual(exact(a).cover.title,[]);if(mode==='replace')assert.equal(findManualObject(a.state,'replacement').node.textContent,'Replacement');undoRedo(a,before);}
 const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title');a.dispatch(a.state.tr.insertText('ABCDE',title.pos+1));a.dispatch(a.state.tr.delete(title.pos+2,title.pos+4));assert.equal(findManualCoverRole(a.state,'target','title').node.textContent,'ADE');assert.deepEqual(exact(a).cover.title,[{type:'text',text:'ADE'}]);
});

test('foreign title movement and ordinary format conversion release only the cover role while retaining IDs and content',()=>{
 for(const range of [false,true]){const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title'),id=title.node.attrs.id;a.dispatch(a.state.tr.insertText('Move',title.pos+1));if(range)a.run(selectManualBlocks(id));else a.select(id,false);a.boundary();const before=a.state;assert.equal(a.run(range?moveSelectedManualBlocks({parentId:'last',index:1}):moveManualObject(id,{parentId:'last',index:1})),true);const moved=findManualObject(a.state,id);assert.equal(moved.parent.type.name,'page');assert.equal(moved.node.type.name,'heading');assert.equal(moved.node.textContent,'Move');assert.equal(getManualCoverProjection(moved.node.attrs.meta.extensions),null);assert.equal(findManualCoverRole(a.state,'target','title'),null);assert.deepEqual(exact(a).cover.title,[]);undoRedo(a,before);}
 const a=h();insert(a,'title');const title=findManualCoverRole(a.state,'target','title'),id=title.node.attrs.id;a.dispatch(a.state.tr.insertText('Convert',title.pos+1));a.select(id);a.boundary();const before=a.state;assert.equal(a.run(executeManualBlockCommand('heading3',{targetId:id,mode:'convert'})),true);assert.equal(findManualObject(a.state,id).node.attrs.level,3);assert.equal(getManualCoverProjection(findManualObject(a.state,id).node.attrs.meta.extensions),null);assert.deepEqual(exact(a).cover.title,[]);undoRedo(a,before);
});

test('existing cover elsewhere, incomplete pagination groups and ambiguous multi-selection give explicit zero-mutation reasons',()=>{
 const a=h();insert(a,'divider');a.select('last-body');let before=a.state,count=a.count;assert.equal(getManualCoverInsertCommandState(a.state,{role:'title'}).reason,'cover-exists');assert.equal(a.run(executeManualCoverInsert('title')),false);assert.equal(a.state,before);assert.equal(a.count,count);
 const source=fixture();source.pages.splice(2,0,{id:'tail',title:[],blocks:[paragraph('tail-body')],...withManualPaginationMarker({}, {kind:'page',rootPageId:'target'})});source.pages.push({id:'orphan',title:[],blocks:[paragraph('orphan-body')],...withManualPaginationMarker({}, {kind:'page',rootPageId:'target'})});const b=h(source);for(const id of ['body','tail-body']){b.select(id);before=b.state;count=b.count;assert.equal(getManualCoverInsertCommandState(b.state,{role:'metadata'}).reason,'incomplete-group');assert.equal(b.run(executeManualCoverInsert('metadata')),false);assert.equal(b.state,before);assert.equal(b.count,count);}
 const c=h();c.run(selectManualBlocks('body','box'));before=c.state;count=c.count;assert.equal(getManualCoverInsertCommandState(c.state,{role:'title'}).reason,'ineligible-selection');assert.equal(c.run(executeManualCoverInsert('title')),false);assert.equal(c.state,before);assert.equal(c.count,count);const d=h();d.select('body');const role=findManualPageRole(d.state,'target','title');d.dispatch(d.state.tr.setSelection(TextSelection.create(d.state.doc,role.pos+1,findManualObject(d.state,'body').pos+2)));assert.equal(getManualCoverInsertCommandState(d.state,{role:'divider'}).reason,'ineligible-selection');
});
