import test from 'node:test';
import assert from 'node:assert/strict';
import {Fragment,Slice} from '@tiptap/pm/model';
import {Selection,TextSelection,NodeSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createEmptyManualDocument,copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {createManualState,documentFromState,findManualObject,manualCommands,normalizeManualPastedSlice,setManualLink,replaceManualSelection} from '../src/redesign/manual-kernel.mjs';
import {ManualBlockSelection} from '../src/redesign/manual-block-selection.mjs';
import {decodeDocumentFile,encodeDocumentFile} from '../src/redesign/document-store.mjs';
import {manualPaginationMarker,withManualPaginationMarker,remapManualPaginationMeta,MANUAL_PAGINATION_OWNER} from '../src/redesign/manual-pagination-meta.mjs';
import {planManualPagination,createManualPaginationTransaction,paginateManualDocument,MAX_MANUAL_PAGINATION_PASSES} from '../src/redesign/manual-pagination.mjs';
const id=()=>crypto.randomUUID(),p=text=>({id:id(),type:'paragraph',content:text?[{type:'text',text,marks:[{type:'strong'}]}]:[],extensions:{vendor:{keep:true}}});
function harness(document){let state=createManualState({document});const dispatch=tr=>state=state.applyTransaction(tr).state;return {get state(){return state;},get document(){return documentFromState(state);},dispatch,run:command=>command(state,dispatch),select(blockId,offset=0){const found=findManualObject(state,blockId);dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+1+offset)));},boundary:()=>dispatch(closeHistory(state.tr))};}
function measure(state,heights,capacity=100,splits={}){
 const pages=[];let index=0;state.doc.forEach(page=>{if(page.type.name!=='page')return;const blocks=[];page.forEach(node=>{if(['pageTitle','pageLead'].includes(node.type.name))return;blocks.push({id:node.attrs.id,height:heights[index]?.[blocks.length]??10,...(splits[node.attrs.id]?{splits:splits[node.attrs.id]}:{})});});pages.push({id:page.attrs.id,capacity:Array.isArray(capacity)?capacity[index]:capacity,blocks});index++;});return {doc:state.doc,revision:7,pages};
}
function flow(h,measurement,options={}){const plan=planManualPagination(h.state,measurement,options);assert.equal(plan.status,'ready');const tr=createManualPaginationTransaction(h.state,plan,options);assert.ok(tr,JSON.stringify(plan.action));h.dispatch(tr);return {plan,tr};}
function structuralIds(value){const found=[];const visit=v=>{if(!v||typeof v!=='object')return;if(v.id)found.push(v.id);for(const [key,child]of Object.entries(v))if(key!=='extensions')Array.isArray(child)?child.forEach(visit):visit(child);};visit(value);return found;}
function fixture(){const d=createEmptyManualDocument(),first=p('첫째'),second=p('둘째'),last=p('셋째');d.pages[0].title=[{type:'text',text:'작성 제목',marks:[{type:'underline'}]}];d.pages[0].lead=[{type:'text',text:'소개'}];d.pages[0].extensions={page:'keep'};d.pages[0].blocks=[first,second,last];return {d,first,second,last};}
test('pull spacing is validated and charged to both whole-block and split backfill',()=>{
 const d=createEmptyManualDocument(),first=p('앞'),second=p('ABCDEF');d.pages[0].blocks=[first,second];const h=harness(d);flow(h,measure(h.state,[[60,70]]));
 const whole=measure(h.state,[[60],[40]]);whole.pages[0].pullGap=4;assert.equal(planManualPagination(h.state,whole).status,'stable');whole.pages[0].pullGap=0;assert.equal(planManualPagination(h.state,whole).action.type,'pull');
 const split=measure(h.state,[[60],[70]],100,{[second.id]:[{kind:'text',at:3,headHeight:40,tailHeight:30}]});split.pages[0].pullGap=4;assert.equal(planManualPagination(h.state,split).status,'stable');split.pages[1].blocks[0].splits[0].headHeight=36;assert.equal(planManualPagination(h.state,split).action.type,'pull');assert.equal(planManualPagination(h.state,split).action.split.at,3);
 for(const invalid of [-1,NaN,Infinity,'4',null]){split.pages[0].pullGap=invalid;assert.equal(planManualPagination(h.state,split).status,'invalid');}assert.deepEqual(h.document.pages.flatMap(page=>page.blocks),[first,second]);
});
test('overflow moves an intact suffix into a derived continuation before the next explicit page; caret and one undo round trip',()=>{
 const {d,first,second,last}=fixture(),explicit=createEmptyManualDocument().pages[0];explicit.title=[{type:'text',text:'다른 과업'}];explicit.blocks=[p('다른 페이지')];d.pages.push(explicit);d.cover={id:id(),title:[],metadata:[],blocks:[p('표지')],extensions:{cover:'keep'}};
 const h=harness(d);h.select(second.id,1);h.boundary();const before=h.state,measurement=measure(h.state,[[40,70,20],[20]]),plan=planManualPagination(h.state,measurement);assert.equal(paginateManualDocument(measurement)(h.state),true);assert.equal(h.state,before);const tr=createManualPaginationTransaction(h.state,plan);assert.ok(tr);assert.equal(tr.steps.length,1);h.dispatch(tr);
 const after=h.document,auto=after.pages[1];assert.deepEqual(after.pages[0],{...d.pages[0],blocks:[first]});assert.deepEqual(auto.title,d.pages[0].title);assert.equal(Object.hasOwn(auto,'lead'),false);assert.deepEqual(auto.blocks,[second,last]);assert.equal(manualPaginationMarker(auto.extensions,'page').rootPageId,d.pages[0].id);assert.deepEqual(after.pages[2],explicit);assert.deepEqual(after.cover,d.cover);assert.equal(h.state.selection.$from.parent.attrs.id,second.id);assert.equal(h.state.selection.$from.parentOffset,1);assert.equal(createManualPaginationTransaction(h.state,plan),null);
 assert.equal(h.run(manualCommands.undo),true);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.redo),true);assert.deepEqual(h.document,after);
});
test('overflow prepends to an existing auto page instead of appending after its contents',()=>{
 const {d,first,second,last}=fixture();d.pages[0].blocks=[first,second];const auto={id:id(),title:d.pages[0].title,blocks:[last],...withManualPaginationMarker({}, {kind:'page',rootPageId:d.pages[0].id})};d.pages.push(auto);const h=harness(d);h.select(second.id,1);flow(h,measure(h.state,[[40,70],[20]]));assert.deepEqual(h.document.pages[0].blocks,[first]);assert.equal(h.document.pages[1].id,auto.id);assert.deepEqual(h.document.pages[1].blocks,[second,last]);assert.equal(h.state.selection.$from.parent.attrs.id,second.id);
});
test('a paragraph splits on a measured grapheme boundary with marks, hard breaks, metadata and caret preserved, then backfills to the exact original',()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ab😀',marks:[{type:'strong'}]},{type:'hardBreak'},{type:'text',text:'cd́EF',marks:[{type:'link',href:'https://example.invalid'},{type:'underline'}]}];block.extensions={manualPagination:{vendor:'keep'},extra:{keep:true}};const h=harness(d);h.select(block.id,8);h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.underline.create()]));h.boundary();const before=h.state;
 flow(h,measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at:5,headHeight:80,tailHeight:80}]}));const after=h.document,head=after.pages[0].blocks[0],tail=after.pages[1].blocks[0];assert.equal(head.id,block.id);assert.deepEqual(head.extensions,block.extensions);assert.deepEqual(head.content,block.content.slice(0,2));assert.deepEqual(tail.content,block.content.slice(2));assert.equal(manualPaginationMarker(tail.extensions,'block').rootBlockId,block.id);assert.deepEqual(tail.extensions.manualPagination,block.extensions.manualPagination);assert.equal(h.state.selection.$from.parent.attrs.id,tail.id);assert.equal(h.state.selection.$from.parentOffset,3);assert.deepEqual(h.state.storedMarks,before.storedMarks);
 h.run(manualCommands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);flow(h,measure(h.state,[[80],[80]],200));assert.deepEqual(h.document,d);assert.equal(h.state.selection.$from.parent.attrs.id,block.id);assert.equal(h.state.selection.$from.parentOffset,8);
});
for(const at of [3,7])test(`paragraph refuses unsafe grapheme offset ${at} and reports an oversize block without adding pages`,()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ab😀\ncd́EF'}];const h=harness(d),before=h.state,measurement=measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at,headHeight:80,tailHeight:80}]});const plan=planManualPagination(h.state,measurement);assert.equal(plan.status,'blocked');assert.equal(plan.diagnostics[0].blockId,block.id);assert.equal(paginateManualDocument(measurement)(h.state,h.dispatch),false);assert.equal(h.state,before);
});
for(const type of ['list','procedure','table'])test(`${type} splits only at measured children, preserves descendant IDs and numbering, and merges exactly on backfill`,()=>{
 const d=createEmptyManualDocument(),block=type==='list'?{id:id(),type,ordered:true,start:7,items:[1,2,3].map(n=>({id:id(),blocks:[p(`항목 ${n}`)],extensions:{item:n}}))}:type==='procedure'?{id:id(),type,start:4,steps:[1,2,3].map(n=>({id:id(),title:[{type:'text',text:`단계 ${n}`,marks:[{type:'strong'}]}],blocks:[p(`설명 ${n}`)],extensions:{step:n}}))}:{id:id(),type,label:'표 제목',headers:[{id:id(),content:[{type:'text',text:'열',marks:[{type:'underline'}]}],extensions:{header:'keep'}}],rows:[1,2,3].map(n=>[{id:id(),content:[{type:'text',text:`행 ${n}`}],extensions:{cell:n}}])};block.extensions={container:{keep:true}};d.pages[0].blocks=[block];const h=harness(d);const childId=type==='list'?block.items[2].blocks[0].id:type==='procedure'?block.steps[2].blocks[0].id:block.rows[2][0].id;h.select(childId,1);h.boundary();const before=h.state,at=type==='table'?1:2;
 flow(h,measure(h.state,[[150]],100,{[block.id]:[{kind:'child',at,headHeight:80,tailHeight:70}]}));const after=h.document,head=after.pages[0].blocks[0],tail=after.pages[1].blocks[0];assert.equal(head.id,block.id);assert.deepEqual(head.extensions,block.extensions);assert.equal(h.state.selection.$from.parent.attrs.id,childId);assert.equal(h.state.selection.$from.parentOffset,1);assert.equal(new Set(structuralIds(after)).size,structuralIds(after).length);assert.ok(structuralIds(block).every(value=>structuralIds(after).includes(value)));
 if(type==='list'){assert.equal(tail.start,9);assert.deepEqual(head.items,block.items.slice(0,2));assert.deepEqual(tail.items,block.items.slice(2));}else if(type==='procedure'){assert.equal(tail.start,6);assert.deepEqual(head.steps,block.steps.slice(0,2));assert.deepEqual(tail.steps,block.steps.slice(2));}else{assert.deepEqual(head.headers,block.headers);assert.deepEqual(head.rows,block.rows.slice(0,1));assert.deepEqual(tail.rows,block.rows.slice(1));assert.notEqual(tail.headers[0].id,block.headers[0].id);assert.deepEqual(tail.headers[0].content,block.headers[0].content);assert.deepEqual(tail.headers[0].extensions,block.headers[0].extensions);}
 h.run(manualCommands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);flow(h,measure(h.state,[[80],[70]],200));assert.deepEqual(h.document,d);assert.equal(h.state.selection.$from.parent.attrs.id,childId);
});
test('multiple page flows append to the original input history event and one undo/redo restores all IDs and selection',()=>{
 const d=createEmptyManualDocument();d.pages[0].blocks=[p('A'),p('B'),p('C'),p('D')];const h=harness(d);h.select(d.pages[0].blocks[3].id,1);h.boundary();const before=h.state,input=h.state.tr.insertText('x');h.dispatch(input);
 for(let pass=0;pass<3;pass++){const heights=h.document.pages.map(page=>page.blocks.map(()=>60));flow(h,measure(h.state,heights),{historyTransaction:input,pass});}
 const after=h.document,selection=h.state.selection;assert.equal(after.pages.length,4);assert.equal(planManualPagination(h.state,measure(h.state,after.pages.map(page=>page.blocks.map(()=>60)))).status,'stable');assert.equal(h.run(manualCommands.undo),true);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.undo),false);assert.equal(h.run(manualCommands.redo),true);assert.deepEqual(h.document,after);assert.ok(h.state.selection.eq(selection));
});
test('backfill removes empty automatic pages, leaves explicit empty pages and restores the original page metadata',()=>{
 const {d}=fixture(),explicit=createEmptyManualDocument().pages[0];explicit.blocks=[];d.pages.push(explicit);const h=harness(d);flow(h,measure(h.state,[[40,70,20],[]]));flow(h,measure(h.state,[[40],[70,20],[]],300));flow(h,measure(h.state,[[40,70],[20],[]],300));assert.deepEqual(h.document,d);
 const empty={id:id(),title:d.pages[0].title,blocks:[],...withManualPaginationMarker({}, {kind:'page',rootPageId:d.pages[0].id})};const copy=structuredClone(d);copy.pages.splice(1,0,empty);const blank=harness(copy);flow(blank,measure(blank.state,[[40,70,20],[],[]],300));assert.deepEqual(blank.document,d);
});
test('derived titles update while the root title, lead, metadata and all contents remain unchanged',()=>{
 const {d}=fixture(),h=harness(d);flow(h,measure(h.state,[[40,70,20]]));const auto=h.document.pages[1];const title=findManualObject(h.state,d.pages[0].id).pos+2;h.dispatch(h.state.tr.insertText('새 ',title));const root=h.document.pages[0],before=h.document;const {plan}=flow(h,measure(h.state,[[40],[70,20]]));assert.equal(plan.action.type,'title');assert.deepEqual(h.document.pages[0],root);assert.deepEqual(h.document.pages[1].title,root.title);assert.deepEqual(h.document.pages[1].blocks,before.pages[1].blocks);assert.equal(h.document.pages[1].id,auto.id);
});
test('stale, incomplete, invalid, composed and limited measurements never dispatch; an unsplittable first block makes bounded progress for its suffix',()=>{
 const d=createEmptyManualDocument();d.pages[0].blocks=[{id:id(),type:'figure',asset:'assets/a.png',alt:'큰 이미지',caption:[],widthPreset:'full',extensions:{image:'keep'}},p('뒤 문단')];const h=harness(d),measurement=measure(h.state,[[250,20]]),before=h.state;
 assert.equal(planManualPagination(h.state,{...measurement,doc:createManualState({document:d}).doc}).status,'stale');assert.equal(planManualPagination(h.state,{...measurement,pages:[]}).status,'invalid');assert.equal(planManualPagination(h.state,measurement,{pass:MAX_MANUAL_PAGINATION_PASSES}).status,'limit');assert.equal(planManualPagination(h.state,measurement,{maxPasses:Infinity}).status,'invalid');assert.equal(planManualPagination(h.state,measurement,{maxAutoPages:0}).status,'limit');assert.equal(paginateManualDocument(measurement)(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);
 const {plan}=flow(h,measurement);assert.equal(plan.diagnostics[0].reason,'oversize-unsplittable');assert.deepEqual(h.document.pages[0].blocks,[d.pages[0].blocks[0]]);const stable=planManualPagination(h.state,measure(h.state,[[250],[20]]));assert.equal(stable.status,'blocked');assert.equal(stable.diagnostics.length,1);
});
test('forged explicit deletion, wrong root title updates and nonadjacent page pushes cannot bypass page protection',()=>{
 const {d}=fixture(),explicit=createEmptyManualDocument().pages[0];explicit.blocks=[];d.pages.push(explicit);const h=harness(d),before=h.state;for(const action of [{type:'remove-empty',pageId:explicit.id},{type:'title',pageId:explicit.id,rootPageId:d.pages[0].id},{type:'push',pageId:d.pages[0].id,blockId:d.pages[0].blocks[1].id,nextPageId:explicit.id}])assert.equal(createManualPaginationTransaction(h.state,{status:'ready',doc:h.state.doc,action}),null);assert.equal(h.state,before);
 const orphan={id:id(),title:[],blocks:[],...withManualPaginationMarker({}, {kind:'page',rootPageId:'missing'})};d.pages.splice(1,0,orphan);const other=harness(d);assert.equal(createManualPaginationTransaction(other.state,{status:'ready',doc:other.state.doc,action:{type:'remove-empty',pageId:orphan.id}}),null);
});
test('whole-document and clipboard group copies remap only known pagination IDs; orphan fragments lose only the marker',()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ABCDEF'}];block.extensions={opaque:{rootBlockId:block.id}};const h=harness(d);flow(h,measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at:3,headHeight:80,tailHeight:80}]}));const source=h.document,copy=copyManualDocument(source),root=copy.pages[0];assert.equal(manualPaginationMarker(copy.pages[1].extensions,'page').rootPageId,root.id);assert.equal(manualPaginationMarker(copy.pages[1].blocks[0].extensions,'block').rootBlockId,root.blocks[0].id);assert.deepEqual(root.blocks[0].extensions.opaque,block.extensions.opaque);const copied=harness(copy);flow(copied,measure(copied.state,[[80],[80]],200));assert.deepEqual(copied.document.pages[0].blocks[0].content,block.content);
 const head=h.state.doc.child(0).lastChild,tail=h.state.doc.child(1).lastChild,group=normalizeManualPastedSlice(new Slice(Fragment.fromArray([head,tail]),0,0));assert.equal(manualPaginationMarker(group.content.child(1).attrs.meta.extensions,'block').rootBlockId,group.content.child(0).attrs.id);const orphan=normalizeManualPastedSlice(new Slice(Fragment.from(tail),0,0)).content.firstChild;assert.equal(manualPaginationMarker(orphan.attrs.meta.extensions,'block'),null);assert.deepEqual(orphan.attrs.meta.extensions.opaque,block.extensions.opaque);
});
test('file encode/decode retains the pagination plan, provenance, figure asset references and exact bytes',()=>{
 const {d}=fixture(),asset='assets/a.png',bytes='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZasAAAAASUVORK5CYII=';d.pages[0].blocks[1]={id:id(),type:'figure',asset,alt:'그림',caption:[{type:'text',text:'설명'}],widthPreset:'full',extensions:{figure:'keep'}};const h=harness(d);flow(h,measure(h.state,[[40,70,20]]));const document=h.document,record=decodeDocumentFile(encodeDocumentFile({document,assets:{[asset]:bytes}}));assert.deepEqual(record.document,document);assert.deepEqual(record.assets,{[asset]:bytes});const reopened=harness(record.document);assert.equal(planManualPagination(reopened.state,measure(reopened.state,[[40],[70,20]])).status,'stable');
});
for(const selectionKind of ['node','block range'])test(`splitting preserves the full ${selectionKind} as a range of both fragments and undo restores its exact original kind`,()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ABCDEF'}];const h=harness(d),pos=findManualObject(h.state,block.id).pos;h.dispatch(h.state.tr.setSelection(selectionKind==='node'?NodeSelection.create(h.state.doc,pos):new ManualBlockSelection(h.state.doc,block.id)));h.boundary();const before=h.state;
 flow(h,measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at:3,headHeight:80,tailHeight:80}]}));assert.equal(h.state.selection.manualBlockSelection,true);assert.deepEqual(h.state.selection.ids,h.document.pages.flatMap(page=>page.blocks.map(node=>node.id)));h.run(manualCommands.undo);assert.ok(h.state.selection.eq(before.selection));assert.deepEqual(h.document,d);
});
test('empty extension objects survive split, backfill and orphan copying exactly',()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ABCDEF'}];block.extensions={};const h=harness(d);flow(h,measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at:3,headHeight:80,tailHeight:80}]}));const tail=h.state.doc.child(1).lastChild,orphan=normalizeManualPastedSlice(new Slice(Fragment.from(tail),0,0)).content.firstChild;assert.deepEqual(orphan.attrs.meta.extensions,{});flow(h,measure(h.state,[[80],[80]],200));assert.deepEqual(h.document,d);
});
test('a forged marker key never aliases a generic extension, and marker ownership cannot be overridden',()=>{
 const marker={owner:MANUAL_PAGINATION_OWNER,version:1,kind:'block',rootBlockId:'old',sourceType:'paragraph',key:'vendor'},meta={extensions:{actual:marker,vendor:{keep:true}}};assert.equal(manualPaginationMarker(meta.extensions,'block').key,'actual');const remapped=remapManualPaginationMeta(meta,new Map([['old','new']]));assert.equal(remapped.extensions.actual.rootBlockId,'new');assert.deepEqual(remapped.extensions.vendor,meta.extensions.vendor);assert.deepEqual(remapManualPaginationMeta(meta,new Map()).extensions,{vendor:{keep:true}});assert.deepEqual(meta.extensions.actual,marker);const inserted=withManualPaginationMarker({}, {...marker,owner:'other',version:900});assert.equal(manualPaginationMarker(inserted.extensions,'block').owner,MANUAL_PAGINATION_OWNER);
});
for(const kind of ['node','block range'])test(`partial backfill maps a selected ${kind} through merging and keeps the remaining tail selected`,()=>{
 const d=createEmptyManualDocument(),block=d.pages[0].blocks[0];block.content=[{type:'text',text:'ABCDEF'}];const h=harness(d);flow(h,measure(h.state,[[160]],100,{[block.id]:[{kind:'text',at:3,headHeight:80,tailHeight:80}]}));const tail=h.document.pages[1].blocks[0],found=findManualObject(h.state,tail.id);h.dispatch(h.state.tr.setSelection(kind==='node'?NodeSelection.create(h.state.doc,found.pos):new ManualBlockSelection(h.state.doc,tail.id)));h.boundary();const before=h.state,beforeDoc=h.document;
 const {plan}=flow(h,measure(h.state,[[70],[80]],100,{[tail.id]:[{kind:'text',at:2,headHeight:20,tailHeight:60}]}));assert.equal(plan.action.type,'pull');assert.equal(h.document.pages[0].blocks[0].content[0].text,'ABCDE');assert.equal(h.document.pages[1].blocks[0].content[0].text,'F');assert.deepEqual(h.state.selection.ids,h.document.pages.flatMap(page=>page.blocks.map(node=>node.id)));h.run(manualCommands.undo);assert.deepEqual(h.document,beforeDoc);assert.ok(h.state.selection.eq(before.selection));
});
for(const type of ['callout','quote','toggle'])for(const nested of [false,true])test(`${type} ${nested?'splits its long inner paragraph':'splits at a body child'} with repeated title, caret, exact backfill and one undo preserved`,()=>{
 const d=createEmptyManualDocument(),first=p('앞 문단'),body=p('ab😀\ncd́EF'),last=p('뒤 문단');body.content=[{type:'text',text:'ab😀',marks:[{type:'strong'}]},{type:'hardBreak'},{type:'text',text:'cd́EF',marks:[{type:'link',href:'https://example.invalid'},{type:'underline'}]}];const block={id:id(),type,blocks:[first,body,last],extensions:{container:{keep:true}},...(type==='quote'?{}:{title:[{type:'text',text:'제목',marks:[{type:'strong'}]}]}),...(type==='callout'?{tone:'cautionary'}:type==='toggle'?{open:true}:{})};d.pages[0].blocks=[block];const h=harness(d);h.select(body.id,8);h.boundary();const before=h.state,split=nested?{kind:'nested-text',childIndex:1,at:5,headHeight:80,tailHeight:70}:{kind:'child',at:1,headHeight:50,tailHeight:100};
 flow(h,measure(h.state,[[150]],100,{[block.id]:[split]}));const after=h.document,head=after.pages[0].blocks[0],tail=after.pages[1].blocks[0];assert.equal(head.id,block.id);assert.deepEqual(head.extensions,block.extensions);assert.equal(manualPaginationMarker(tail.extensions,'block').rootBlockId,block.id);if(type!=='quote'){assert.deepEqual(head.title,block.title);assert.deepEqual(tail.title,block.title);assert.equal(manualPaginationMarker(tail.extensions,'block').repeatedTitle,true);}assert.equal(new Set(structuralIds(after)).size,structuralIds(after).length);assert.ok(structuralIds(block).every(value=>structuralIds(after).includes(value)));
 if(nested){assert.deepEqual(head.blocks.slice(0,1),[first]);assert.equal(head.blocks[1].id,body.id);assert.deepEqual(head.blocks[1].content,body.content.slice(0,2));assert.deepEqual(tail.blocks[0].content,body.content.slice(2));assert.deepEqual(tail.blocks[1],last);assert.equal(h.state.selection.$from.parent.attrs.id,tail.blocks[0].id);assert.equal(h.state.selection.$from.parentOffset,3);}else{assert.deepEqual(head.blocks,[first]);assert.deepEqual(tail.blocks,[body,last]);assert.equal(h.state.selection.$from.parent.attrs.id,body.id);assert.equal(h.state.selection.$from.parentOffset,8);}
 h.run(manualCommands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);flow(h,measure(h.state,[[split.headHeight],[split.tailHeight]],200));assert.deepEqual(h.document,d);assert.equal(h.state.selection.$from.parent.attrs.id,body.id);assert.equal(h.state.selection.$from.parentOffset,8);
});
test('editing a repeated container title prevents a destructive backfill merge',()=>{
 const d=createEmptyManualDocument(),first=p('A'),second=p('B'),block={id:id(),type:'callout',tone:'signal',title:[{type:'text',text:'원래 제목'}],blocks:[first,second]};d.pages[0].blocks=[block];const h=harness(d);flow(h,measure(h.state,[[150]],100,{[block.id]:[{kind:'child',at:1,headHeight:80,tailHeight:70}]}));const tail=h.document.pages[1].blocks[0],pos=findManualObject(h.state,tail.id).pos;h.dispatch(h.state.tr.insertText('바꾼 ',pos+2));const edited=h.document.pages[1].blocks[0];flow(h,measure(h.state,[[80],[70]],200));assert.equal(h.document.pages.length,1);assert.deepEqual(h.document.pages[0].blocks,[{...block,blocks:[first]},edited]);
});
function selectedText(state){return state.selection.ranges.map(range=>state.doc.textBetween(range.$from.pos,range.$to.pos)).join('');}
function textRangeFixture(reverse=false,nested=false){
 const d=createEmptyManualDocument(),body=p('ABCDEF');d.pages[0].title=[{type:'text',text:'TITLE',marks:[{type:'underline'}]}];const container=nested?{id:id(),type:'callout',tone:'signal',title:[{type:'text',text:'CALLOUT'}],blocks:[body],extensions:{container:'keep'}}:body;d.pages[0].blocks=[container];const h=harness(d),from=findManualObject(h.state,body.id).pos+2,to=from+4;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,reverse?to:from,reverse?from:to)));h.boundary();const before=h.state,split=nested?{kind:'nested-text',childIndex:0,at:3,headHeight:80,tailHeight:80}:{kind:'text',at:3,headHeight:80,tailHeight:80};flow(h,measure(h.state,[[160]],100,{[container.id]:[split]}));return {d,h,body,container,before};
}
for(const reverse of [false,true])for(const nested of [false,true])test(`flow text selection ${reverse?'reverse':'forward'} ${nested?'inside callout':'in paragraph'} excludes derived headers from ranges/content and survives JSON, bookmark, mapping and one undo`,()=>{
 const {h,before}=textRangeFixture(reverse,nested),after=h.document,selection=h.state.selection;assert.equal(selection.manualPaginationTextSelection,true);assert.equal(selectedText(h.state),'BCDE');assert.deepEqual(selection.content().toJSON(),before.selection.content().toJSON());assert.equal(selection.anchor>selection.head,reverse);assert.ok(Selection.fromJSON(h.state.doc,selection.toJSON()).eq(selection));assert.ok(selection.getBookmark().resolve(h.state.doc).eq(selection));
 const tr=h.state.tr.insertText('z',findManualObject(h.state,h.document.pages[0].blocks[0].id).pos+1+(nested?h.state.doc.firstChild.lastChild.firstChild.nodeSize+1:0));const mapped=selection.getBookmark().map(tr.mapping).resolve(tr.doc);assert.ok(mapped.eq(selection.map(tr.doc,tr.mapping)));assert.equal(mapped.content().content.textBetween(0,mapped.content().content.size),'BCDE');
 h.run(manualCommands.undo);assert.deepEqual(h.document,documentFromState(before));assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);assert.ok(h.state.selection.eq(selection));
});
for(const action of ['underline','link'])test(`flow text selection ${action} affects original content only and leaves repeated page/container titles untouched`,()=>{
 const {h}=textRangeFixture(false,true);h.boundary();const before=h.state,beforeDoc=h.document;assert.equal(h.run(action==='link'?setManualLink('https://selected.invalid'):manualCommands.underline),true);const after=h.document;assert.deepEqual(after.pages.map(page=>page.title),beforeDoc.pages.map(page=>page.title));assert.deepEqual(after.pages.map(page=>page.blocks[0].title),beforeDoc.pages.map(page=>page.blocks[0].title));assert.equal(selectedText(h.state),'BCDE');const content=h.state.selection.content().content;assert.equal(content.textBetween(0,content.size),'BCDE');content.descendants(node=>{if(node.isText)assert.ok(node.marks.some(mark=>mark.type.name===action));});h.run(manualCommands.undo);assert.deepEqual(h.document,beforeDoc);assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);
});
for(const text of ['','X'])test(`flow text selection ${text?'replacement':'deletion'} preserves headers and one undo/redo after automatic backfill`,()=>{
 const {h,body}=textRangeFixture(true,true);h.boundary();const before=h.state,beforeDoc=h.document;let input;assert.equal(replaceManualSelection(text)(h.state,tr=>{input=tr;h.dispatch(tr);}),true);assert.deepEqual(h.document.pages.map(page=>page.title),beforeDoc.pages.map(page=>page.title));assert.deepEqual(h.document.pages.map(page=>page.blocks[0].title),beforeDoc.pages.map(page=>page.blocks[0].title));flow(h,measure(h.state,[[20],[20]]),{historyTransaction:input});const after=h.document;assert.equal(after.pages.length,1);assert.equal(after.pages[0].blocks[0].blocks[0].id,body.id);assert.equal(after.pages[0].blocks[0].blocks[0].content.map(run=>run.text||'').join(''),text?'AXF':'AF');const selection=h.state.selection;h.run(manualCommands.undo);assert.deepEqual(h.document,beforeDoc);assert.ok(h.state.selection.eq(before.selection));h.run(manualCommands.redo);assert.deepEqual(h.document,after);assert.ok(h.state.selection.eq(selection));
});
test('flow preserves an existing explicit title selection and its normal native selection class',()=>{
 const {d}=fixture(),h=harness(d),page=h.state.doc.firstChild;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,2,2+page.firstChild.content.size)));h.boundary();const before=h.state;flow(h,measure(h.state,[[40,70,20]]));assert.equal(h.state.selection.manualPaginationTextSelection,undefined);assert.equal(selectedText(h.state),selectedText(before));assert.deepEqual(h.state.selection.content().toJSON(),before.selection.content().toJSON());h.run(manualCommands.undo);assert.ok(h.state.selection.eq(before.selection));
});
for(const includeBody of [false,true])test(`title-only sync preserves a directly selected existing repeated callout title${includeBody?' and body':''}`,()=>{
 const d=createEmptyManualDocument(),first=p('First'),second=p('Second'),block={id:id(),type:'callout',tone:'signal',title:[{type:'text',text:'ABCDEF'}],blocks:[first,second]};d.pages[0].title=[{type:'text',text:'ROOT'}];d.pages[0].blocks=[block];const h=harness(d);flow(h,measure(h.state,[[150]],100,{[block.id]:[{kind:'child',at:1,headHeight:80,tailHeight:70}]}));const tail=h.document.pages[1].blocks[0],pos=findManualObject(h.state,tail.id).pos,from=pos+3,to=includeBody?findManualObject(h.state,second.id).pos+4:pos+7;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,from,to)));h.dispatch(h.state.tr.insertText('X',2));h.boundary();const before=h.state,content=before.selection.content().toJSON();const {plan}=flow(h,measure(h.state,[[80],[70]]));assert.equal(plan.action.type,'title');assert.equal(h.state.selection.manualPaginationTextSelection,undefined);assert.deepEqual(h.state.selection.content().toJSON(),content);assert.equal(h.state.selection.$anchor.parentOffset,before.selection.$anchor.parentOffset);assert.equal(h.state.selection.$head.parentOffset,before.selection.$head.parentOffset);h.run(manualCommands.undo);assert.ok(h.state.selection.eq(before.selection));
});
test('a new flow excludes only newly repeated headers while preserving an already directly selected repeated title and body',()=>{
 const d=createEmptyManualDocument(),first=p('First'),second=p('uvwxyzAB'),block={id:id(),type:'callout',tone:'signal',title:[{type:'text',text:'ABCDEF'}],blocks:[first,second]};d.pages[0].title=[{type:'text',text:'ROOT'}];d.pages[0].blocks=[block];const h=harness(d);flow(h,measure(h.state,[[150]],100,{[block.id]:[{kind:'child',at:1,headHeight:80,tailHeight:70}]}));const tail=h.document.pages[1].blocks[0],pos=findManualObject(h.state,tail.id).pos;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,pos+3,findManualObject(h.state,second.id).pos+6)));h.boundary();const before=h.state,content=before.selection.content().toJSON();flow(h,measure(h.state,[[80],[180]],100,{[tail.id]:[{kind:'nested-text',childIndex:0,at:3,headHeight:90,tailHeight:90}]}));assert.equal(h.state.selection.manualPaginationTextSelection,true);assert.equal(selectedText(h.state),'BCDEFuvwxy');assert.deepEqual(h.state.selection.content().toJSON(),content);h.run(manualCommands.undo);assert.ok(h.state.selection.eq(before.selection));
});
