import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeSelection} from '@tiptap/pm/state';
import {closeHistory,undoDepth} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,manualCommands,updateManualObject} from '../src/redesign/manual-kernel.mjs';
import {readManualFigureLayout,withManualFigureWidth,withoutManualFigureWidth,setManualFigureWidth,resetManualFigureWidth,manualFigureWidthStyle} from '../src/redesign/manual-figure-layout.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
import {createManualComponents} from '../../../src/components.mjs';
const crop={x:5,y:8,width:150,height:90,sourceWidth:240,sourceHeight:180},caption=[{type:'text',text:'Caption',marks:[{type:'strong'},{type:'underline'}]}];
function fixture(extensions){return {schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:[],blocks:[{id:'image',type:'figure',asset:'assets/synthetic.png',alt:'Synthetic',caption,widthPreset:'reading',crop,...(extensions===undefined?{}:{extensions})}]}]};}
function h(document=fixture()){let state=createManualState({document}),transactions=[];const dispatch=tr=>{transactions.push(tr);state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,editable:true,composing:false,props:{}};return {get state(){return state;},get document(){return documentFromState(state);},dispatch,transactions,run:(command,v=view)=>command(state,dispatch,v)};}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
test('owned figure width preserves foreign namespaces, unknown fields and explicit empty extensions on reset',()=>{
 const original={extensions:{manualFigureLayout:{owner:'vendor',widthPx:10},vendor:{keep:1}}},sized=withManualFigureWidth(original,240);assert.deepEqual(original,{extensions:{manualFigureLayout:{owner:'vendor',widthPx:10},vendor:{keep:1}}});assert.equal(readManualFigureLayout(sized.extensions).key,'manualFigureLayout2');assert.equal(readManualFigureLayout(sized.extensions).widthPx,240);sized.extensions.manualFigureLayout2.future={keep:2};const reset=withoutManualFigureWidth(sized);assert.deepEqual(reset.extensions.manualFigureLayout,original.extensions.manualFigureLayout);assert.deepEqual(reset.extensions.vendor,original.extensions.vendor);assert.deepEqual(reset.extensions.manualFigureLayout2.future,{keep:2});assert.equal(readManualFigureLayout(reset.extensions).widthPx,undefined);assert.deepEqual(withoutManualFigureWidth(withManualFigureWidth({extensions:{}},240)),{extensions:{}});assert.deepEqual(withoutManualFigureWidth(withManualFigureWidth({},240)),{});
});
test('public resize changes metadata once, preserves node/caption/asset/crop/selection, and survives save/load with one Undo',()=>{
 const a=h(fixture({vendor:{keep:true}})),found=findManualObject(a.state,'image');a.dispatch(a.state.tr.setSelection(NodeSelection.create(a.state.doc,found.pos)).setStoredMarks([a.state.schema.marks.emphasis.create()]));const before=a.state,count=a.transactions.length;assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx:241.5,revision:before.doc,minWidthPx:32,maxWidthPx:680})),true);assert.equal(a.transactions.length,count+1);const image=a.document.pages[0].blocks[0];assert.equal(readManualFigureLayout(image.extensions).widthPx,241.5);for(const key of ['id','asset','alt','caption','crop','widthPreset'])assert.deepEqual(image[key],fixture().pages[0].blocks[0][key]);assert.deepEqual(a.state.storedMarks,before.storedMarks);assert.ok(a.state.selection.eq(before.selection));assert.deepEqual(documentFromState(createManualState({document:a.document})),a.document);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:a.document,assets:{}})).document,a.document);undoRedo(a,before);
});
test('invalid, bounded, stale, readonly, IME, cancelled and live-host blocked widths are mutation-free',()=>{
 const a=h();for(const widthPx of [0,-1,NaN,Infinity,'200'])assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx})),false);for(const options of [{figureId:'missing'},{figureId:'page'},{minWidthPx:32,widthPx:20},{maxWidthPx:100,widthPx:101},{cancelled:true},{readOnly:true},{revision:createManualState({document:a.document}).doc}]){const before=a.state;assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx:200,...options})),false);assert.equal(a.state,before);}for(const view of [{editable:false},{composing:true},{props:{manualFigureResizeEnabled:false}},{props:{manualFigureResizeEnabled:()=>false}}]){const before=a.state;assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx:200}),view),false);assert.equal(a.state,before);}assert.equal(a.run(resetManualFigureWidth({figureId:'image'})),false);
});
test('reset and selecting the same existing preset clear custom width in one Undo and preserve opaque metadata',()=>{
 const a=h(fixture({vendor:{keep:1}}));a.run(setManualFigureWidth({figureId:'image',widthPx:200}));const before=a.state;assert.equal(a.run(updateManualObject('image',{widthPreset:'reading'})),true);assert.equal(readManualFigureLayout(a.document.pages[0].blocks[0].extensions),null);assert.deepEqual(a.document.pages[0].blocks[0].extensions,{vendor:{keep:1}});assert.equal(a.run(manualCommands.undo),true);assert.equal(readManualFigureLayout(a.document.pages[0].blocks[0].extensions).widthPx,200);a.dispatch(closeHistory(a.state.tr));const resetBefore=a.state;assert.equal(a.run(resetManualFigureWidth({figureId:'image'})),true);undoRedo(a,resetBefore);
});
test('resizing separates prior typing history and repeating the same width adds no transaction',()=>{
 const a=h(),found=findManualObject(a.state,'image');a.dispatch(closeHistory(a.state.tr).insertText('X',found.pos+2));const typed=a.state,depth=undoDepth(a.state);assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx:200})),true);assert.equal(undoDepth(a.state),depth+1);const after=a.state,count=a.transactions.length;assert.equal(a.run(setManualFigureWidth({figureId:'image',widthPx:200})),false);assert.equal(a.state,after);assert.equal(a.transactions.length,count);assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(typed.doc));
});
test('bound canonical logo supports width resize and reset while preserving its role and one Undo',()=>{
 const d=fixture();d.cover={id:'cover',title:[],metadata:[],logo:{src:'@lk-design-system/lds-theme/assets/brand/lk-logo-inline-navy.svg',alt:'LK'},blocks:[]};const a=h(d),logo=findManualCoverRole(a.state,'cover','logo'),before=a.state;
 assert.equal(a.run(setManualFigureWidth({figureId:logo.node.attrs.id,widthPx:300})),true);
 const resized=findManualCoverRole(a.state,'cover','logo');assert.equal(resized.node.attrs.id,logo.node.attrs.id);assert.equal(readManualFigureLayout(resized.node.attrs.meta.extensions).widthPx,300);assert.equal(resized.node.attrs.meta.asset,logo.node.attrs.meta.asset);assert.ok(resized.node.content.eq(logo.node.content));undoRedo(a,before);
 const resizedState=a.state;assert.equal(a.run(resetManualFigureWidth({figureId:logo.node.attrs.id})),true);assert.equal(findManualCoverRole(a.state,'cover','logo').node.attrs.id,logo.node.attrs.id);assert.equal(readManualFigureLayout(findManualCoverRole(a.state,'cover','logo').node.attrs.meta.extensions),null);undoRedo(a,resizedState);
});
test('public ManualFigure renderer uses the same pixel width/clamp and keeps image/crop aspect and caption',()=>{
 const React={createElement:(type,props,...children)=>({type,props,children})},{ManualFigure}=createManualComponents(React,()=>{}),plain=ManualFigure({src:'asset',alt:'A',caption:'Caption',widthPx:240}),cropped=ManualFigure({src:'asset',alt:'A',caption:'Caption',widthPx:240,crop});assert.deepEqual(plain.props.style,{...manualFigureWidthStyle(240),marginLeft:'auto',marginRight:'auto'});assert.deepEqual(plain.children[0],{type:'img',props:{src:'asset',alt:'A'},children:[]});assert.equal(plain.children[1].type,'figcaption');assert.equal(cropped.children[0].props.viewBox,'5 8 150 90');assert.deepEqual(cropped.props.style,plain.props.style);assert.deepEqual(ManualFigure({src:'asset',alt:'A'}).props.style,{marginLeft:'auto',marginRight:'auto'});assert.equal(manualFigureWidthStyle(0),null);
});
