import test from 'node:test';import assert from 'node:assert/strict';
const {createManualState,documentFromState,findManualObject,manualCommands}=await import(`../src/redesign/manual-kernel.mjs`);
const {applyManualPageGroupAction,MANUAL_PAGE_GROUP_ACTION_RESULT}=await import(`../src/redesign/manual-page-group-actions.mjs`);
const {getManualCoverProjection,getManualCoverCellProjection,withEditableManualCoverTableMeta}=await import(`../src/redesign/manual-cover-legacy-projection.mjs`);
const {withManualPaginationMarker,manualPaginationMarker}=await import(`../src/redesign/manual-pagination-meta.mjs`);
const {getManualDocumentCovers,getOrderedPageEntries,withManualPageOrder}=await import(`../src/redesign/manual-page-order.mjs`);
const {encodeDocumentFile,decodeDocumentFile}=await import(`../src/redesign/document-store.mjs`);
const {withManualCoverFlowProvenance,readManualCoverFlowProvenance}=await import(`../src/redesign/manual-cover-flow-provenance.mjs`);
const {normalizeManualCoverTableCommand}=await import(`../src/redesign/manual-cover-table-shape.mjs`);
const {TextSelection}=await import('@tiptap/pm/state');
function findCopiedBody(copy){let found;copy.descendants(n=>{if(n.type.name==='paragraph'&&n.attrs.meta?.extensions?.vendor?.id==='cover-body')found=n;});return found;}
const t=(text,href)=>[{type:'text',text,marks:[{type:'strong'},...(href?[{type:'link',href}]:[])]}],p=(id,href)=>({id,type:'paragraph',content:t(id,href),extensions:{vendor:{id}}});
function h({mixed=false,tail=false,multi=false,coverOnly=false,layout=false,editable=false}={}){
 const cover={id:'cover',title:t('Title','#cover-body'),sectionTitle:t('Section'),metadata:[{id:'entry',label:t('Label'),value:t('Value','#cover-body'),extensions:{vendor:{keep:1}}}],blocks:[p('cover-body','#manual-cover:cover:title')],extensions:{vendor:{cover:1}}};
 cover.extensions=withManualCoverFlowProvenance({extensions:cover.extensions},{coverId:'cover',records:[{id:'historic-page',type:'page',reason:'flow',attrs:{id:'historic-page',opaque:{id:'cover-body'}},content:{id:'historic-body'}}]}).extensions;
 if(layout)cover.extensions.packet={owner:'@lk-design-system/manual-cover-projection',version:1,kind:'layout',headerOrder:['manual-cover:cover:metadata','manual-cover:cover:title','manual-cover:cover:divider'],bodyOrder:['manual-cover:cover:sectionTitle','cover-body'],roleIds:{metadata:'manual-cover:cover:metadata',title:'manual-cover:cover:title',divider:'manual-cover:cover:divider',sectionTitle:'manual-cover:cover:sectionTitle'},future:{id:'opaque-do-not-remap'}};
 const d={schemaVersion:2,id:'doc',title:'',cover,pages:[{id:'page',title:t('Page'),blocks:[p('page-body','#cover-body')]}]};
 if(tail){const pg={id:'tail',title:[],blocks:[p('tail-body')]};pg.extensions=withManualPaginationMarker({}, {kind:'page',rootPageId:'cover'}).extensions;pg.blocks[0].extensions=withManualPaginationMarker({extensions:pg.blocks[0].extensions},{kind:'block',rootBlockId:'cover-body',sourceType:'paragraph'}).extensions;d.pages.unshift(pg);}
 if(multi){d.covers=[{id:'other-cover',title:t('Other'),metadata:[],blocks:[p('other-cover-body')]},cover];delete d.cover;}
 if(coverOnly)d.pages=[];
 const order=[...(['cover']),...(tail?['tail']:[]),...(coverOnly?[]:['page']),...(multi?['other-cover']:[])];let state=createManualState({document:withManualPageOrder(d,order)}),count=0,last;
 const dispatch=tr=>{count++;last=tr;state=state.applyTransaction(tr).state;};if(editable){
  let table;state.doc.descendants(n=>{if(getManualCoverProjection(n.attrs.meta?.extensions)?.role==='metadata')table=n;});
  assert.equal(normalizeManualCoverTableCommand(state,dispatch,null,table.attrs.id,()=>true,{preserveMetadataRole:true}),true);
  const found=findManualObject(state,table.attrs.id),meta=structuredClone(found.node.attrs.meta);getManualCoverProjection(meta.extensions).blockId='custom-table';let tr=state.tr.setNodeMarkup(found.pos,undefined,{...found.node.attrs,id:'custom-table',meta});
  found.node.descendants((n,off)=>{if(n.type.name==='tableCell'){const cm=structuredClone(n.attrs.meta);getManualCoverCellProjection(cm.extensions).tableId='custom-table';cm.extensions.rowLayout={owner:'@lk-design-system/manual-table-layout',version:1,kind:'cell-layout',rowMinHeightPx:55};tr.setNodeMarkup(found.pos+1+off,undefined,{...n.attrs,meta:cm});}});dispatch(tr);
 }
 const cb=findManualObject(state,'cover-body');dispatch(state.tr.setSelection(TextSelection.create(state.doc,cb.pos+2)));
 const before=state,original=documentFromState(state),sourceIds=mixed?['page','cover']:['cover'];assert.equal(applyManualPageGroupAction({action:'duplicate',sourceIds,revision:before.doc})(state,dispatch),true);
 return {get state(){return state;},before,original,dispatch,last,get count(){return count;},result:last.getMeta(MANUAL_PAGE_GROUP_ACTION_RESULT)};
}
for(const config of [{coverOnly:true},{mixed:true},{tail:true},{multi:true,mixed:true},{layout:true},{editable:true}])test(`copied cover roles stay bound to fresh root ${JSON.stringify(config)}`,()=>{
 const a=h(config),copyId=a.result.rootIds[0],copy=findManualObject(a.state,copyId).node,oldIds=new Set();a.before.doc.descendants(n=>{if(n.attrs.id)oldIds.add(n.attrs.id);});let roles=0,cells=0;copy.descendants(n=>{if(n.attrs.id)assert.equal(oldIds.has(n.attrs.id),false);const r=getManualCoverProjection(n.attrs.meta?.extensions),c=getManualCoverCellProjection(n.attrs.meta?.extensions);if(r){roles++;assert.equal(r.coverId,copyId);assert.equal(r.blockId,n.attrs.id);}if(c){cells++;assert.equal(c.coverId,copyId);assert.equal(c.cellId,n.attrs.id);assert.equal(findManualObject(a.state,c.tableId)?.node.type.name,'table');if(c.entry)assert.equal(c.entry.value[0].marks.find(m=>m.type==='link')?.href,'#'+findCopiedBody(copy).attrs.id);}});assert.ok(roles>=3);assert.ok(cells>=2);
});
for(const config of [{coverOnly:true},{mixed:true},{tail:true},{multi:true,mixed:true},{layout:true},{editable:true}])test(`copy preserves semantic fields physical IDs links family and Undo/codec ${JSON.stringify(config)}`,()=>{
 const a=h(config),copyId=a.result.rootIds[0],copy=findManualObject(a.state,copyId).node;const all=[];a.state.doc.descendants(n=>{if(n.attrs.id)all.push(n.attrs.id);});assert.equal(new Set(all).size,all.length);const d=documentFromState(a.state);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);assert.deepEqual(getOrderedPageEntries(d).map(x=>x.id),Array.from({length:a.state.doc.childCount},(_,i)=>a.state.doc.child(i).attrs.id));assert.deepEqual(getManualDocumentCovers(d).find(x=>x.id==='cover'),getManualDocumentCovers(a.original).find(x=>x.id==='cover'));
 const origCover=getManualDocumentCovers(a.original).find(c=>c.id==='cover'),copiedCover=getManualDocumentCovers(d).find(c=>c.id===copyId),copyBody=findCopiedBody(copy);
 const remapRuns=runs=>runs.map(r=>({...r,marks:r.marks?.map(m=>m.type==='link'&&m.href==='#cover-body'?{...m,href:'#'+copyBody.attrs.id}:m)}));
 assert.deepEqual(copiedCover.title,remapRuns(origCover.title));assert.deepEqual(copiedCover.sectionTitle,origCover.sectionTitle);assert.equal(copiedCover.metadata.length,1);assert.notEqual(copiedCover.metadata[0].id,origCover.metadata[0].id);assert.deepEqual(copiedCover.metadata[0].label,origCover.metadata[0].label);assert.deepEqual(copiedCover.metadata[0].value,remapRuns(origCover.metadata[0].value));assert.deepEqual(copiedCover.metadata[0].extensions,origCover.metadata[0].extensions);
 assert.deepEqual(copyBody.attrs.meta.extensions.vendor,{id:'cover-body'});assert.deepEqual(copiedCover.extensions.vendor,origCover.extensions.vendor);
 const provenance=readManualCoverFlowProvenance(copiedCover.extensions),oldProvenance=readManualCoverFlowProvenance(origCover.extensions);assert.equal(provenance.coverId,copyId);assert.deepEqual(provenance.records,oldProvenance.records);
 const reopened=createManualState({document:decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document});assert.deepEqual(documentFromState(reopened),d);const restored=findManualObject(reopened,copyId).node;let roleCount=0;restored.descendants(n=>{const r=getManualCoverProjection(n.attrs.meta?.extensions);if(r){assert.equal(r.coverId,copyId);assert.equal(r.blockId,n.attrs.id);roleCount++;}});assert.ok(roleCount>=3);const reopenedCopyBody=findCopiedBody(restored);for(const mark of reopenedCopyBody.firstChild.marks)if(mark.type.name==='link'&&mark.attrs.href.startsWith('#'))assert.ok(findManualObject(reopened,mark.attrs.href.slice(1)),'copied scalar link target survives reopen');
 if(config.editable){const marker=getManualCoverProjection([...Array(copy.childCount)].map((_,i)=>copy.child(i)).find(n=>getManualCoverProjection(n.attrs.meta?.extensions)?.role==='metadata').attrs.meta.extensions);assert.equal(marker.editableTable,true);const tableDTO=Object.values(copiedCover.extensions).find(m=>m.kind==='layout'&&m.metadataTable)?.metadataTable;assert.ok(tableDTO);assert.notEqual(tableDTO.id,'custom-table');assert.ok(findManualObject(reopened,tableDTO.id));for(const row of [tableDTO.headers,...tableDTO.rows])for(const cell of row)assert.equal(cell.extensions.rowLayout.rowMinHeightPx,55);}
 const copiedBody=[];copy.descendants(n=>{if(n.type.name==='paragraph')copiedBody.push(n);});assert.ok(copiedBody[0].firstChild.marks.some(m=>m.type.name==='link'&&!!findManualObject(a.state,m.attrs.href.slice(1))));
 if(config.tail){const copiedTail=findManualObject(a.state,a.result.physicalIds[1]).node;assert.equal(manualPaginationMarker(copiedTail.attrs.meta.extensions,'page').rootPageId,copyId);assert.equal(manualPaginationMarker(copiedTail.lastChild.attrs.meta.extensions,'block').rootBlockId,copiedBody[0].attrs.id);}
 const after=a.state;assert.equal(manualCommands.undo(a.state,a.dispatch),true);assert.ok(a.state.doc.eq(a.before.doc));assert.ok(a.state.selection.eq(a.before.selection));assert.equal(manualCommands.redo(a.state,a.dispatch),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));
});
