import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DOMParser,Fragment,Slice} from '@tiptap/pm/model';
import {Plugin} from '@tiptap/pm/state';
import {selectManualBlocks,manualBlockSelectionPlugin} from '../src/redesign/manual-block-selection.mjs';
import {TextSelection,AllSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {decodeDocumentFile,encodeDocumentFile} from '../src/redesign/document-store.mjs';
import {createEmptyManualDocument,validateManualDocument,copyManualDocument,migrateV1Document,isSafeManualAsset} from '../src/redesign/manual-v2.mjs';
import {createManualState,documentFromState,manualSchema,manualCommands as commands,insertManualBlock,findManualObject,updateManualObject,selectManualObject,duplicateManualObject,deleteManualObject,moveManualObject,appendManualStep,addManualTableRow,deleteManualTableRow,replaceManualSelection,addManualTableColumn,deleteManualTableColumn,setManualLink,manualFigureMediaSpec,manualCoverLogoSpec,ensureParagraphAfter,insertParagraphAtGap,getManualSlashTrigger,executeManualBlockCommand,normalizeManualPastedSlice,prepareManualClipboardAssets,rekeyManualPastedAssets} from '../src/redesign/manual-kernel.mjs';
function harness(document=createEmptyManualDocument()){
 let state=createManualState({document});const dispatch=tr=>state=state.applyTransaction(tr).state;
 return {get state(){return state;},get document(){return documentFromState(state);},dispatch,run:cmd=>cmd(state,dispatch),boundary:()=>dispatch(closeHistory(state.tr)),select:pos=>dispatch(state.tr.setSelection(TextSelection.create(state.doc,pos)))};
}
const ids=value=>{const result=[];const visit=v=>{if(!v||typeof v!=='object')return;if(v.id)result.push(v.id);for(const [k,c]of Object.entries(v))if(k!=='extensions'&&c&&typeof c==='object')Array.isArray(c)?c.forEach(visit):visit(c);};visit(value);return result;};
// Small DOM surface for the real PM parser; no browser or extra dependency.
function clipboardElement(tag,attributes={},nodes=[]){
 const dom={nodeType:1,nodeName:tag.toUpperCase(),tagName:tag.toUpperCase(),childNodes:nodes,style:{length:0},getAttribute:key=>attributes[key]??null,matches(selector){return selector.split(',').some(value=>{value=value.trim();const attr=/^(\w+)?\[([\w-]+)(?:="([^"]*)")?\]$/.exec(value);return attr?(!attr[1]||attr[1].toLowerCase()===tag)&&Object.hasOwn(attributes,attr[2])&&(attr[3]===undefined||attributes[attr[2]]===attr[3]):value.toLowerCase()===tag;});}};
 dom.firstChild=nodes[0]||null;dom.lastChild=nodes.at(-1)||null;nodes.forEach((node,index)=>{node.parentNode=dom;node.previousSibling=nodes[index-1]||null;node.nextSibling=nodes[index+1]||null;});return dom;
}
function clipboardDOM(node){
 if(node.isText)return {nodeType:3,nodeName:'#text',nodeValue:node.text};
 function render(spec){const hasAttrs=typeof spec[1]==='object'&&!Array.isArray(spec[1]);return clipboardElement(spec[0],hasAttrs?spec[1]:{},spec.slice(hasAttrs?2:1).flatMap(part=>part===0?Array.from({length:node.childCount},(_,index)=>clipboardDOM(node.child(index))):[Array.isArray(part)?render(part):{nodeType:3,nodeName:'#text',nodeValue:part}]));}
 return render(node.type.spec.toDOM(node));
}
function parseClipboardSlice(slice){return DOMParser.fromSchema(manualSchema).parseSlice(clipboardElement('div',{},Array.from({length:slice.content.childCount},(_,index)=>clipboardDOM(slice.content.child(index)))),{preserveWhitespace:true});}
test('empty draft round trips without optional field injection',()=>{const d=createEmptyManualDocument();assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.equal(validateManualDocument(d),d);});
for(const file of ['compact.json','gallery.json','authoring-guide/manual.json'])test(`v1 ${file} explicit copy migrates and round trips all content`,async()=>{const source=JSON.parse(await readFile(new URL('../../../examples/'+file,import.meta.url),'utf8'));const before=structuredClone(source),result=migrateV1Document(source);assert.deepEqual(source,before);assert.deepEqual(result.source,source);assert.deepEqual(documentFromState(createManualState({document:result.document})),result.document);});
for(const type of ['paragraph','heading','list','procedure','figure','table','callout','quote','mediaGroup'])test(`${type} insertion is valid, unique, undoable`,()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));const before=h.document;assert.equal(h.run(insertManualBlock(type)),true);const d=h.document;assert.equal(d.pages[0].blocks[1].type,type);assert.equal(new Set(ids(d)).size,ids(d).length);h.run(commands.undo);assert.deepEqual(h.document,before);h.run(commands.redo);assert.deepEqual(h.document,d);});
for(const kind of ['callout','quote','toggle','step'])test(`node-selected nested ${kind} paragraph inserts immediately after itself and undoes`,()=>{
 const p=text=>({id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text}]}),first=p('첫 문단'),second=p('둘째 문단'),outside=p('컨테이너 밖'),title=[{type:'text',text:'제목'}],body={id:crypto.randomUUID(),...(kind!=='step'?{type:kind}:{}),blocks:[first,second],...(kind==='quote'?{}:{title}),...(kind==='callout'?{tone:'cautionary'}:kind==='toggle'?{open:true}:{})};
 const container=kind==='step'?{id:crypto.randomUUID(),type:'procedure',start:1,steps:[body]}:body,d=createEmptyManualDocument();d.pages[0].blocks=[container,outside];const h=harness(d);h.run(selectManualObject(first.id,{text:false}));const before=h.state;h.boundary();assert.equal(h.run(insertManualBlock('paragraph')),true);
 const result=h.document,after=kind==='step'?result.pages[0].blocks[0].steps[0]:result.pages[0].blocks[0];assert.equal(result.pages[0].blocks.length,2);assert.equal(after.blocks.length,3);assert.deepEqual(after.blocks[0],first);assert.deepEqual(after.blocks[2],second);assert.deepEqual(after.blocks[1].content,[]);assert.deepEqual(result.pages[0].blocks[1],outside);assert.equal(h.state.selection.$from.parent.attrs.id,after.blocks[1].id);assert.equal(new Set(ids(result)).size,ids(result).length);
 h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));
});
test('page creation and explicit deletion maintain at least one page',()=>{const h=harness(),original=h.document;assert.equal(h.run(deleteManualObject(original.pages[0].id)),false);h.run(insertManualBlock('page'));assert.equal(h.document.pages.length,2);const id=h.document.pages[1].id;h.boundary();h.run(deleteManualObject(id));assert.equal(h.document.pages.length,1);h.run(commands.undo);assert.equal(h.document.pages[1].id,id);});
for(const entry of ['selected page','page menu target','selected cover','cover menu target'])test(`new page follows the ${entry} instead of appending to the document, and one undo restores the original selection`,()=>{
 const afterCover=entry.includes('cover'),menuTarget=entry.endsWith('menu target'),d=createEmptyManualDocument();d.pages.push(createEmptyManualDocument().pages[0],createEmptyManualDocument().pages[0]);d.pages.forEach((page,index)=>{page.title=[{type:'text',text:`페이지 ${index+1}`}];page.extensions={keep:index};page.blocks[0].content=[{type:'text',text:`본문 ${index+1}`,marks:[{type:'strong'}]}];});if(afterCover)d.cover={id:crypto.randomUUID(),title:[{type:'text',text:'표지'}],metadata:[],blocks:[],extensions:{keep:'cover'}};const h=harness(d),targetId=afterCover?d.cover.id:d.pages[0].id;
 h.run(selectManualObject(menuTarget?d.pages[2].blocks[0].id:targetId,{text:menuTarget}));h.boundary();const before=h.state,beforeDocument=h.document,command=menuTarget?executeManualBlockCommand('page',{targetId,mode:'insert',attrs:{title:'새 페이지'}}):insertManualBlock('page',{title:'새 페이지'});assert.equal(command(h.state),true);assert.equal(h.state,before);assert.equal(command(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);assert.equal(h.run(command),true);
 const after=h.document,added=after.pages[afterCover?0:1];assert.deepEqual(after.pages.filter(page=>page.id!==added.id),beforeDocument.pages);assert.deepEqual(after.cover,beforeDocument.cover);assert.deepEqual(added.title,[{type:'text',text:'새 페이지'}]);assert.equal(added.blocks.length,1);assert.deepEqual(added.blocks[0].content,[]);assert.equal(new Set(ids(after)).size,ids(after).length);assert.equal(h.state.selection.$from.parent.type.name,'pageTitle');assert.equal(h.state.selection.$from.node(1).attrs.id,added.id);const afterSelection=h.state.selection;
 h.run(commands.undo);assert.deepEqual(h.document,beforeDocument);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.deepEqual(h.document,after);assert.ok(h.state.selection.eq(afterSelection));
});
test('typing Enter splits paragraphs and gives distinct IDs restored by undo',()=>{const h=harness(),id=h.document.pages[0].blocks[0].id;h.run(selectManualObject(id));h.dispatch(h.state.tr.insertText('첫째😀둘째'));h.boundary();h.select(findManualObject(h.state,id).pos+3);assert.equal(h.run(commands.enter),true);assert.equal(h.document.pages[0].blocks.length,2);assert.equal(new Set(ids(h.document)).size,ids(h.document).length);h.run(commands.undo);assert.equal(h.document.pages[0].blocks.length,1);assert.equal(h.document.pages[0].blocks[0].id,id);});
test('step title Enter enters description and final empty paragraph adds next step',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('procedure'));const proc=h.document.pages[0].blocks[1],s=proc.steps[0];h.run(selectManualObject(s.id));assert.equal(h.state.selection.$from.parent.type.name,'stepTitle');h.run(commands.enter);assert.equal(h.state.selection.$from.parent.type.name,'paragraph');h.boundary();h.run(commands.enter);assert.equal(h.document.pages[0].blocks[1].steps.length,2);h.run(commands.undo);assert.equal(h.document.pages[0].blocks[1].steps.length,1);});
test('table Tab moves cells and adds a row, reversible in one undo',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('table',{rows:0,columns:2}));const table=h.document.pages[0].blocks[1];h.run(selectManualObject(table.headers[1].id));h.boundary();assert.equal(h.run(commands.tab),true);assert.equal(h.document.pages[0].blocks[1].rows.length,1);h.run(commands.undo);assert.equal(h.document.pages[0].blocks[1].rows.length,0);});
test('object metadata edits preserve extension fields and undo',()=>{const d=createEmptyManualDocument();d.pages[0].extensions={vendor:{flag:true}};const h=harness(d);h.run(updateManualObject(d.id,{title:'문서'}));assert.equal(h.document.title,'문서');assert.deepEqual(h.document.pages[0].extensions,d.pages[0].extensions);h.run(commands.undo);assert.deepEqual(h.document,d);});
test('duplicate renews descendant IDs, move preserves them, undo restores',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('procedure'));const id=h.document.pages[0].blocks[1].id;h.boundary();h.run(duplicateManualObject(id));const duplicated=h.document.pages[0].blocks[2];assert.equal(new Set(ids(h.document)).size,ids(h.document).length);h.boundary();h.run(moveManualObject(duplicated.id,{direction:'up'}));assert.equal(h.document.pages[0].blocks[1].id,duplicated.id);h.run(commands.undo);assert.equal(h.document.pages[0].blocks[2].id,duplicated.id);});
test('cross-page move preserves id and all descendant content',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('callout'));const block=h.document.pages[0].blocks[1];h.run(insertManualBlock('page'));const page=h.document.pages[1];h.boundary();assert.equal(h.run(moveManualObject(block.id,{parentId:page.id,index:1})),true);assert.deepEqual(h.document.pages[1].blocks[0],block);h.run(commands.undo);assert.deepEqual(h.document.pages[0].blocks[1],block);});
test('invalid IDs, links, crop, asset names and unknown nodes reject without mutation',()=>{const d=createEmptyManualDocument();for(const modify of [v=>v.pages[0].id=v.id,v=>v.pages[0].blocks[0].content=[{type:'text',text:'x',marks:[{type:'link',href:'javascript:bad'}]}],v=>v.pages[0].blocks[0].type='unknown']){const bad=structuredClone(d);modify(bad);assert.throws(()=>validateManualDocument(bad));}for(const name of ['../x','/x','a\\b','a//b','a/./b','data:x','a\u0000b'])assert.equal(isSafeManualAsset(name),false);assert.equal(isSafeManualAsset('assets/x.png'),true);});
test('copy document renews IDs and internal links while preserving opaque extensions',()=>{const d=createEmptyManualDocument();d.extensions={vendor:{id:'opaque'}};d.pages[0].blocks[0].content=[{type:'text',text:'page',marks:[{type:'link',href:'#'+d.pages[0].id}]}];const copied=copyManualDocument(d);assert.ok(ids(copied).every(id=>!ids(d).includes(id)));assert.equal(copied.pages[0].blocks[0].content[0].marks[0].href,'#'+copied.pages[0].id);assert.deepEqual(copied.extensions,d.extensions);});
test('paragraph heading conversion keeps IDs and extensions, including after list lift',()=>{const d=createEmptyManualDocument();d.pages[0].blocks[0].extensions={custom:'keep'};const h=harness(d),id=d.pages[0].blocks[0].id;h.run(selectManualObject(id));h.run(commands.heading);assert.equal(h.document.pages[0].blocks[0].id,id);assert.deepEqual(h.document.pages[0].blocks[0].extensions,{custom:'keep'});h.run(commands.paragraph);h.run(commands.orderedList);h.run(commands.heading);assert.equal(h.document.pages[0].blocks[0].id,id);assert.deepEqual(h.document.pages[0].blocks[0].extensions,{custom:'keep'});});
test('select all deletion clears contents while preserving all page containers and IDs',()=>{const h=harness();h.run(insertManualBlock('page'));const before=h.document;h.dispatch(h.state.tr.setSelection(new AllSelection(h.state.doc)));h.boundary();assert.equal(h.run(commands.backspace),true);assert.equal(h.document.pages.length,2);assert.deepEqual(h.document.pages.map(p=>p.id),before.pages.map(p=>p.id));h.run(commands.undo);assert.deepEqual(h.document,before);});
test('table Enter uses a hard break and never changes column count',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('table'));h.run(commands.enter);assert.equal(h.document.pages[0].blocks[1].headers.length,2);assert.deepEqual(h.document.pages[0].blocks[1].headers[0].content,[{type:'hardBreak'}]);});
test('insertion rejects invalid image metadata before changing state',()=>{const h=harness(),before=h.state;assert.equal(h.run(insertManualBlock('figure',{asset:'https://outside.invalid/image.png'})),false);assert.equal(h.state,before);});
test('row deletion keeps header, and undo restores cell IDs',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('table',{rows:1}));const table=h.document.pages[0].blocks[1];h.boundary();assert.equal(h.run(deleteManualTableRow(table.id,0)),true);assert.equal(h.document.pages[0].blocks[1].rows.length,0);h.run(commands.undo);assert.deepEqual(h.document.pages[0].blocks[1],table);});
test('optional crop can be explicitly removed on image replacement',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('figure',{asset:'assets/a.png',crop:{x:0,y:0,width:10,height:10,sourceWidth:20,sourceHeight:20}}));const id=h.document.pages[0].blocks[1].id;h.boundary();assert.equal(h.run(updateManualObject(id,{asset:'assets/b.png'},{remove:['crop']})),true);assert.equal(Object.hasOwn(h.document.pages[0].blocks[1],'crop'),false);h.run(commands.undo);assert.equal(h.document.pages[0].blocks[1].crop.width,10);});
test('unhandled raw selection deletion cannot silently remove page IDs',()=>{const h=harness();h.run(insertManualBlock('page'));h.dispatch(h.state.tr.setSelection(new AllSelection(h.state.doc)));const before=h.state;h.dispatch(h.state.tr.deleteSelection());assert.equal(h.state,before);});

test('partial selection replacement across pages preserves boundaries and undo selection',()=>{
 const d=createEmptyManualDocument(),second=createEmptyManualDocument().pages[0];d.pages.push(second);
 d.pages[0].blocks[0].content=[{type:'text',text:'ABC'}];second.blocks[0].content=[{type:'text',text:'DEF'}];
 const h=harness(d),firstPos=findManualObject(h.state,d.pages[0].blocks[0].id).pos+2,lastPos=findManualObject(h.state,second.blocks[0].id).pos+2;
 h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,firstPos,lastPos)));const before=h.state;
 assert.equal(h.run(replaceManualSelection('X')),true);assert.deepEqual(h.document.pages.map(p=>p.id),d.pages.map(p=>p.id));
 assert.equal(h.document.pages[0].blocks[0].content[0].text,'AX');assert.equal(h.document.pages[1].blocks[0].content[0].text,'EF');
 h.run(commands.undo);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));
});
test('whole single page selection can make a list and return to paragraphs without changing page title',()=>{
 const d=createEmptyManualDocument();d.pages[0].title=[{type:'text',text:'제목'}];d.pages[0].blocks[0].content=[{type:'text',text:'내용'}];
 const h=harness(d);h.run(commands.selectAll);assert.equal(h.run(commands.orderedList),true);assert.equal(h.document.pages[0].blocks[0].type,'list');
 assert.equal(h.run(commands.paragraph),true);assert.deepEqual(h.document.pages[0].title,d.pages[0].title);assert.equal(h.document.pages[0].blocks[0].id,d.pages[0].blocks[0].id);
});
test('dry run structural commands are read only and composing blocks mutation',()=>{
 const h=harness(),id=h.document.pages[0].blocks[0].id;h.run(selectManualObject(id));const before=h.state;
 for(const command of [insertManualBlock('procedure'),duplicateManualObject(id),updateManualObject(h.document.id,{title:'X'})]){assert.equal(command(h.state),true);assert.equal(command(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);}
});

test('adding and deleting table columns preserves rectangular shape, IDs and undo',()=>{
 const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('table',{rows:2,columns:2}));const before=h.document.pages[0].blocks[1];h.boundary();
 assert.equal(h.run(addManualTableColumn(before.id)),true);const added=h.document.pages[0].blocks[1];assert.equal(added.headers.length,3);assert.ok(added.rows.every(row=>row.length===3));assert.equal(new Set(ids(h.document)).size,ids(h.document).length);
 assert.deepEqual(added.headers.slice(0,2),before.headers);h.run(commands.undo);assert.deepEqual(h.document.pages[0].blocks[1],before);h.run(commands.redo);assert.deepEqual(h.document.pages[0].blocks[1],added);
 h.boundary();assert.equal(h.run(deleteManualTableColumn(before.id,1)),true);assert.equal(h.document.pages[0].blocks[1].headers.length,2);h.run(commands.undo);assert.deepEqual(h.document.pages[0].blocks[1],added);
});
test('last table column cannot be deleted',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('table',{rows:0,columns:1}));const before=h.state,id=h.document.pages[0].blocks[1].id;assert.equal(h.run(deleteManualTableColumn(id,0)),false);assert.equal(h.state,before);});
test('procedure start and callout tone are represented in editor DOM specs',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('procedure',{start:7}));const procedure=findManualObject(h.state,h.document.pages[0].blocks[1].id).node;assert.equal(procedure.type.spec.toDOM(procedure)[1].start,7);h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('callout',{tone:'cautionary'}));const callout=findManualObject(h.state,h.document.pages[0].blocks[1].id).node;assert.equal(callout.type.spec.toDOM(callout)[1]['data-tone'],'cautionary');});

for(const href of ['https://new.invalid',null])test(`caret link edit ${href??'remove'} updates entire same-link extent and undoes`,()=>{
 const d=createEmptyManualDocument(),link={type:'link',href:'https://old.invalid'};
 d.pages[0].blocks[0].content=[{type:'text',text:'before '},{type:'text',text:'one',marks:[link]},{type:'text',text:'two',marks:[{type:'strong'},link]},{type:'text',text:'three',marks:[link]},{type:'text',text:'different',marks:[{type:'link',href:'https://different.invalid'}]},{type:'text',text:' after'}];
 const h=harness(d),pos=findManualObject(h.state,d.pages[0].blocks[0].id).pos+1;h.select(pos+11);const before=h.state;
 assert.equal(setManualLink(href)(h.state),true);assert.equal(h.state,before);assert.equal(h.run(setManualLink(href)),true);
 const runs=h.document.pages[0].blocks[0].content;
 const links=runs.flatMap(run=>(run.marks||[]).filter(m=>m.type==='link').map(m=>m.href));assert.equal(links.includes(link.href),false);assert.ok(links.includes('https://different.invalid'));
 assert.ok(runs.some(run=>run.text==='two'&&run.marks.some(m=>m.type==='strong')));if(href)assert.equal(links.filter(v=>v===href).length,3);
 assert.equal(h.state.selection.from,before.selection.from);h.run(commands.undo);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));
});
test('link in plain text caret only changes future input and does not rewrite adjacent text',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.dispatch(h.state.tr.insertText('plain'));const before=h.state.doc;h.run(setManualLink('https://new.invalid'));assert.ok(h.state.doc.eq(before));h.dispatch(h.state.tr.insertText('linked'));const runs=h.document.pages[0].blocks[0].content;assert.equal(runs[0].text,'plain');assert.equal(runs[1].marks[0].href,'https://new.invalid');});
for(const range of [false,true])test(`link command rejects code block ${range?'text selection':'caret'} without reporting success or setting stored marks`,()=>{
 const h=harness();h.run(insertManualBlock('codeBlock',{text:'code'}));const code=h.document.pages[0].blocks.find(block=>block.type==='codeBlock');h.run(selectManualObject(code.id));if(range){const pos=findManualObject(h.state,code.id).pos+1;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,pos,pos+4)));}const before=h.state;
 for(const href of ['https://example.invalid',null]){assert.equal(setManualLink(href)(h.state),false);assert.equal(h.run(setManualLink(href)),false);assert.equal(h.state,before);}
});

test('figure presentation preserves crop viewport, original source and optional preview label',()=>{
 const crop={x:12,y:24,width:100,height:80,sourceWidth:400,sourceHeight:300};
 const spec=manualFigureMediaSpec({asset:'assets/a.png',alt:'설명',crop,previewTitle:'자료 화면'},()=> 'data:image/png;base64,AAAA');
 assert.equal(spec[1].contenteditable,'false');assert.equal(spec[1].class,'lds-manual-document-preview');assert.equal(spec[2][2],'자료 화면');
 assert.deepEqual(spec[3][1],{role:'img','aria-label':'설명',viewBox:'12 24 100 80'});assert.deepEqual(spec[3][2][1],{href:'data:image/png;base64,AAAA',width:400,height:300});
 const uncropped=manualFigureMediaSpec({asset:'assets/a.png',alt:'원본'});assert.equal(uncropped[2][0],'img');assert.equal(Object.hasOwn(uncropped[1],'class'),false);
});
test('media group editor DOM carries the selected layout',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('mediaGroup',{layout:'sideBySide'}));const node=findManualObject(h.state,h.document.pages[0].blocks[1].id).node;assert.equal(node.type.spec.toDOM(node)[1]['data-layout'],'sideBySide');});

test('cover logo resolves approved asset with alt text separately from editable content',()=>{const key='@lk-design-system/lds-theme/assets/brand/lk-logo-inline-navy.svg';const spec=manualCoverLogoSpec({logo:{src:key,alt:'LK ROBOTICS'}},value=>value===key?'resolved-brand.svg':null);assert.deepEqual(spec,['img',{class:'lds-manual-logo',contenteditable:'false',alt:'LK ROBOTICS',src:'resolved-brand.svg'}]);assert.equal(manualCoverLogoSpec({})[1].hidden,'');});

for(const type of ['callout','quote','figure','table'])test(`${type} can create and reuse following paragraph with one undo`,()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock(type));const block=h.document.pages[0].blocks[1],before=h.document;h.boundary();assert.equal(h.run(ensureParagraphAfter(block.id)),true);assert.equal(h.state.selection.$from.parent.type.name,'paragraph');assert.equal(h.document.pages[0].blocks.length,3);const id=h.document.pages[0].blocks[2].id;assert.equal(h.run(ensureParagraphAfter(block.id)),true);assert.equal(h.document.pages[0].blocks[2].id,id);h.run(commands.undo);assert.deepEqual(h.document,before);});
test('empty callout paragraph Enter escapes without deleting callout content',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('callout'));const callout=h.document.pages[0].blocks[1];h.run(selectManualObject(callout.blocks[0].id));h.boundary();assert.equal(h.run(commands.enter),true);assert.equal(h.document.pages[0].blocks.length,3);assert.deepEqual(h.document.pages[0].blocks[1],callout);assert.equal(h.state.selection.$from.parent.attrs.id,h.document.pages[0].blocks[2].id);});
test('page-end paragraph is idempotent and gap refuses invalid structural slots',()=>{const h=harness(),page=h.document.pages[0];assert.equal(h.run(ensureParagraphAfter(page.id)),true);assert.equal(h.document.pages[0].blocks.length,1);assert.equal(h.run(insertParagraphAtGap(page.id,0)),false);assert.equal(h.run(insertParagraphAtGap(page.id,2)),true);assert.equal(h.document.pages[0].blocks.length,2);});
for(const type of ['todo','toggle','divider','codeBlock'])test(`new ${type} inserts, round trips and undoes with stable IDs`,()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));const before=h.document;h.run(insertManualBlock(type));const after=h.document;assert.equal(after.pages[0].blocks[1].type,type);assert.deepEqual(documentFromState(createManualState({document:after})),after);h.run(commands.undo);assert.deepEqual(h.document,before);});
for(const level of [1,2,3])test(`heading ${level} conversion preserves id, marks and selection`,()=>{const d=createEmptyManualDocument();d.pages[0].blocks[0].content=[{type:'text',text:'제목',marks:[{type:'strong'}]}];const h=harness(d),id=d.pages[0].blocks[0].id;h.run(selectManualObject(id));const selection=h.state.selection;h.run(commands['heading'+level]);assert.equal(h.document.pages[0].blocks[0].level,level);assert.equal(h.document.pages[0].blocks[0].id,id);assert.deepEqual(h.document.pages[0].blocks[0].content,d.pages[0].blocks[0].content);assert.ok(h.state.selection.eq(selection));h.run(commands.paragraph);assert.equal(h.document.pages[0].blocks[0].id,id);});
test('todo Enter makes an unchecked item and empty todo Enter returns to paragraph',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands.todo);h.dispatch(h.state.tr.insertText('할 일'));const first=h.document.pages[0].blocks[0];h.run(updateManualObject(first.id,{checked:true}));h.run(selectManualObject(first.id));h.select(findManualObject(h.state,first.id).pos+first.content[0].text.length+1);h.boundary();h.run(commands.enter);assert.equal(h.document.pages[0].blocks[1].type,'todo');assert.equal(h.document.pages[0].blocks[1].checked,false);h.run(commands.enter);assert.equal(h.document.pages[0].blocks[1].type,'paragraph');assert.equal(h.document.pages[0].blocks[0].checked,true);});
test('closed toggle retains children and moves hidden caret into its title',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('toggle'));const toggle=h.document.pages[0].blocks[1];h.run(selectManualObject(toggle.blocks[0].id));h.dispatch(h.state.tr.insertText('보존'));h.run(updateManualObject(toggle.id,{open:false}));assert.equal(h.state.selection.$from.parent.type.name,'toggleTitle');assert.equal(h.document.pages[0].blocks[1].blocks[0].content[0].text,'보존');});
test('code block Enter inserts newline and paragraph conversion preserves newlines',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands.codeBlock);h.dispatch(h.state.tr.insertText('one'));h.run(commands.enter);h.dispatch(h.state.tr.insertText('two'));assert.equal(h.document.pages[0].blocks[0].text,'one\ntwo');h.run(commands.paragraph);assert.deepEqual(h.document.pages[0].blocks[0].content,[{type:'text',text:'one'},{type:'hardBreak'},{type:'text',text:'two'}]);});
test('underline and strike marks are stored and survive adapter round trip',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands.underline);h.run(commands.strike);h.dispatch(h.state.tr.insertText('서식'));const d=h.document;assert.deepEqual(d.pages[0].blocks[0].content[0].marks,[{type:'strike'},{type:'underline'}]);assert.deepEqual(documentFromState(createManualState({document:d})),d);});

for(const id of ['paragraph','heading1','heading2','heading3','bulletList','orderedList','todo','toggle','quote','callout','codeBlock','divider','figure','table','procedure','page'])test(`slash ${id} consumes trigger atomically and undo restores typed command`,()=>{
 const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.dispatch(h.state.tr.insertText('/query'));const trigger=getManualSlashTrigger(h.state),before=h.state;
 assert.equal(executeManualBlockCommand(id,{trigger})(h.state),true);assert.equal(h.state,before);assert.equal(h.run(executeManualBlockCommand(id,{trigger})),true);
 assert.equal(h.state.doc.textContent.includes('/query'),false);validateManualDocument(h.document);h.run(commands.undo);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.equal(h.state.doc.textContent.includes('/query'),false);
});
test('slash stale trigger and composition reject without deleting text',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.dispatch(h.state.tr.insertText('/one'));const trigger=getManualSlashTrigger(h.state);h.dispatch(h.state.tr.insertText('two'));const before=h.state;assert.equal(h.run(executeManualBlockCommand('todo',{trigger})),false);assert.equal(executeManualBlockCommand('todo',{trigger:getManualSlashTrigger(h.state)})(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);assert.equal(getManualSlashTrigger(h.state,{composing:true}),null);});
for(const type of ['pageTitle','codeBlock','todo'])test(`slash trigger is not active in ${type}`,()=>{const h=harness();if(type!=='pageTitle'){h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands[type]);}h.dispatch(h.state.tr.insertText('/query'));assert.equal(getManualSlashTrigger(h.state),null);});
test('context conversions preserve text, IDs and marks and refuse destructive non-text targets',()=>{const d=createEmptyManualDocument(),p=d.pages[0].blocks[0];p.content=[{type:'text',text:'keep',marks:[{type:'strong'}]}];const h=harness(d);assert.equal(h.run(executeManualBlockCommand('callout',{targetId:p.id})),true);const callout=h.document.pages[0].blocks[0];assert.equal(callout.id,p.id);assert.deepEqual(callout.blocks[0].content,p.content);assert.equal(h.run(executeManualBlockCommand('paragraph',{targetId:p.id})),false);});
test('insert mode does not convert the reference text block',()=>{const d=createEmptyManualDocument();d.pages[0].blocks[0].content=[{type:'text',text:'keep'}];const h=harness(d);h.run(executeManualBlockCommand('heading1',{targetId:d.pages[0].blocks[0].id,mode:'insert'}));assert.equal(h.document.pages[0].blocks[0].type,'paragraph');assert.equal(h.document.pages[0].blocks[1].level,1);});
for(const kind of ['todo','empty paragraph','first callout paragraph','empty second callout paragraph'])test(`target insert after ${kind} preserves content and restores the original caret with one undo`,()=>{
 const p=text=>({id:crypto.randomUUID(),type:'paragraph',content:text?[{type:'text',text,marks:[{type:'strong'},{type:'link',href:'https://example.invalid'}]}]:[],extensions:{paragraph:{keep:true}}}),d=createEmptyManualDocument(),leading=p('앞 문단'),following=p('뒤 문단'),target=kind==='todo'?{...p('할 일'),type:'todo',checked:true}:p(kind==='first callout paragraph'?'콜아웃 본문':'');
 let container=null,index=1;if(kind.includes('callout')){const other=p('다른 본문');index=kind.startsWith('first')?0:1;container={id:crypto.randomUUID(),type:'callout',tone:'cautionary',title:[{type:'text',text:'안내',marks:[{type:'emphasis'}]}],extensions:{callout:'keep'},blocks:index===0?[target,other]:[other,target]};}
 d.pages[0].blocks=[leading,container||target,following];const otherPage=createEmptyManualDocument().pages[0],elsewhere=p('다른 페이지 커서');otherPage.blocks=[elsewhere];d.pages.push(otherPage);const h=harness(d);h.run(selectManualObject(elsewhere.id));h.select(h.state.selection.from+3);h.dispatch(h.state.tr.setStoredMarks([manualSchema.marks.underline.create()]));h.boundary();const before=h.state,command=executeManualBlockCommand('heading2',{targetId:target.id,mode:'insert',attrs:{extensions:{inserted:'new'}}});
 assert.equal(command(h.state),true);assert.equal(h.state,before);assert.deepEqual(h.document,d);let dispatched=0;assert.equal(command(h.state,tr=>{dispatched++;assert.equal(tr.docChanged,true);assert.equal(tr.steps.length,1);h.dispatch(tr);}),true);assert.equal(dispatched,1);
 const after=h.document,blocks=container?after.pages[0].blocks[1].blocks:after.pages[0].blocks,inserted=blocks[index+1];assert.equal(inserted.type,'heading');assert.equal(inserted.level,2);assert.deepEqual(inserted.content,[]);assert.deepEqual(inserted.extensions,{inserted:'new'});assert.equal(ids(d).includes(inserted.id),false);assert.equal(new Set(ids(after)).size,ids(after).length);assert.deepEqual(blocks[index],target);assert.equal(h.state.selection.$from.parent.attrs.id,inserted.id);assert.equal(h.state.selection.$from.parentOffset,0);assert.equal(h.state.selection.empty,true);
 const preserved=structuredClone(after),originalBlocks=container?preserved.pages[0].blocks[1].blocks:preserved.pages[0].blocks;originalBlocks.splice(index+1,1);assert.deepEqual(preserved,d);const selection=h.state.selection;assert.equal(h.run(commands.undo),true);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(commands.undo),false);assert.equal(h.run(commands.redo),true);assert.deepEqual(h.document,after);assert.ok(h.state.selection.eq(selection));
});
test('target insert rejects a missing target and composition without dispatch or changing state',()=>{
 const h=harness(),before=h.state,command=executeManualBlockCommand('heading2',{targetId:crypto.randomUUID(),mode:'insert'});let dispatched=0;const dispatch=tr=>{dispatched++;h.dispatch(tr);};assert.equal(command(h.state),false);assert.equal(command(h.state,dispatch),false);assert.equal(executeManualBlockCommand('heading2',{targetId:h.document.pages[0].blocks[0].id,mode:'insert'})(h.state,dispatch,{composing:true}),false);assert.equal(dispatched,0);assert.equal(h.state,before);
});
test('code block Tab indentation and keyboard escape use same history',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands.codeBlock);h.boundary();assert.equal(h.run(commands.tab),true);assert.equal(h.document.pages[0].blocks[0].text,'  ');assert.equal(h.run(commands.shiftTab),true);assert.equal(h.document.pages[0].blocks[0].text,'');assert.equal(h.run(commands.exitBlock),true);assert.equal(h.state.selection.$from.parent.type.name,'paragraph');});
function listTabFixture(ordered=false){
 const d=createEmptyManualDocument(),items=['첫째','둘째','셋째'].map(text=>({id:crypto.randomUUID(),extensions:{item:text},blocks:[{id:crypto.randomUUID(),type:'paragraph',extensions:{paragraph:text},content:[{type:'text',text,marks:[{type:'strong'}]}]}]})),list={id:crypto.randomUUID(),type:'list',ordered,...(ordered?{start:7}:{}),extensions:{list:'outer'},items};d.pages[0].blocks=[list];return {d,list,items};
}
for(const ordered of [false,true])test(`${ordered?'ordered':'bullet'} list Tab and ShiftTab preserve items metadata selection and single undo`,()=>{
 const {d,list,items}=listTabFixture(ordered),h=harness(d);h.run(selectManualObject(items[1].blocks[0].id));const before=h.state;h.boundary();assert.equal(h.run(commands.tab),true);
 const indented=h.document,outer=indented.pages[0].blocks[0],nested=outer.items[0].blocks[1];assert.equal(outer.id,list.id);assert.deepEqual(outer.extensions,list.extensions);assert.equal(outer.start,list.start);assert.equal(nested.ordered,ordered);assert.deepEqual(nested.items,[items[1]]);assert.deepEqual(outer.items[0].blocks[0],items[0].blocks[0]);assert.deepEqual(outer.items[1],items[2]);assert.equal(h.state.selection.$from.parent.attrs.id,items[1].blocks[0].id);assert.equal(new Set(ids(indented)).size,ids(indented).length);
 h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.deepEqual(h.document,indented);h.boundary();assert.equal(h.run(commands.shiftTab),true);assert.deepEqual(h.document,d);h.run(commands.undo);assert.deepEqual(h.document,indented);
});
for(const ordered of [false,true])test(`${ordered?'ordered':'bullet'} list Tab reuses existing nested list and ShiftTab restores it`,()=>{
 const {d,list,items}=listTabFixture(ordered),inner={id:crypto.randomUUID(),type:'list',ordered,...(ordered?{start:11}:{}),extensions:{list:'inner'},items:[items[1]]};items[0].blocks.push(inner);list.items=[items[0],items[2]];const h=harness(d);h.run(selectManualObject(items[2].blocks[0].id));h.boundary();assert.equal(h.run(commands.tab),true);
 const indented=h.document,nested=indented.pages[0].blocks[0].items[0].blocks[1];assert.equal(nested.id,inner.id);assert.deepEqual(nested.extensions,inner.extensions);assert.equal(nested.start,inner.start);assert.deepEqual(nested.items,inner.items.concat(items[2]));assert.equal(new Set(ids(indented)).size,ids(indented).length);h.run(commands.undo);assert.deepEqual(h.document,d);h.run(commands.redo);h.boundary();assert.equal(h.run(commands.shiftTab),true);assert.deepEqual(h.document,d);h.run(commands.undo);assert.deepEqual(h.document,indented);
});
for(const ordered of [false,true])test(`${ordered?'ordered':'bullet'} list Tab and ShiftTab move a native range of two items together`,()=>{
 const {d,items}=listTabFixture(ordered),h=harness(d),from=findManualObject(h.state,items[1].blocks[0].id).pos+1,to=findManualObject(h.state,items[2].blocks[0].id).pos+3;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,from,to)));const before=h.state;h.boundary();assert.equal(h.run(commands.tab),true);
 const indented=h.document,outer=indented.pages[0].blocks[0];assert.equal(outer.items.length,1);assert.deepEqual(outer.items[0].blocks[1].items,items.slice(1));assert.equal(h.state.selection.$from.parent.attrs.id,items[1].blocks[0].id);assert.equal(h.state.selection.$to.parent.attrs.id,items[2].blocks[0].id);h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);h.boundary();assert.equal(h.run(commands.shiftTab),true);assert.deepEqual(h.document,d);h.run(commands.undo);assert.deepEqual(h.document,indented);
});
test('first list item Tab consumes the key without changes and root ShiftTab exits the list',()=>{
 const {d,list,items}=listTabFixture(true),h=harness(d);h.run(selectManualObject(items[0].blocks[0].id));const before=h.state;assert.equal(commands.tab(h.state),true);assert.equal(h.run(commands.tab),true);assert.equal(h.state,before);h.boundary();assert.equal(h.run(commands.shiftTab),true);const blocks=h.document.pages[0].blocks;assert.deepEqual(blocks[0],items[0].blocks[0]);assert.equal(blocks[1].id,list.id);assert.equal(blocks[1].start,7);assert.deepEqual(blocks[1].extensions,list.extensions);assert.deepEqual(blocks[1].items,items.slice(1));h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));
});
test('ordinary paragraph Tab and ShiftTab remain unhandled for browser focus traversal',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));const before=h.state;assert.equal(h.run(commands.tab),false);assert.equal(h.run(commands.shiftTab),false);assert.equal(h.state,before);});
test('list Tab and ShiftTab leave composition untouched',()=>{const {d,items}=listTabFixture(),h=harness(d);h.run(selectManualObject(items[1].blocks[0].id));const before=h.state;assert.equal(commands.tab(h.state,h.dispatch,{composing:true}),false);assert.equal(commands.shiftTab(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);});
function manualKey(h,key,modifiers={},composing=false){const event={key,keyCode:key==='Tab'?9:key.toUpperCase().charCodeAt(0),ctrlKey:false,metaKey:false,altKey:false,shiftKey:false,...modifiers},view={get state(){return h.state;},dispatch:h.dispatch,composing};return h.state.plugins.some(plugin=>plugin.props.handleKeyDown?.(view,event));}
const markKeys=[['underline','u',false],['strike','S',true],['code','e',false]];
for(const [mark,key,shiftKey]of markKeys)test(`${mark} keymap shortcut formats only selected text and undoes once`,()=>{
 const d=createEmptyManualDocument(),p=d.pages[0].blocks[0];p.content=[{type:'text',text:'앞 선택 뒤'}];const h=harness(d),pos=findManualObject(h.state,p.id).pos+1;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,pos+2,pos+4)));const before=h.state;h.boundary();assert.equal(manualKey(h,key,{ctrlKey:true,shiftKey}),true);assert.deepEqual(h.document.pages[0].blocks[0].content,[{type:'text',text:'앞 '},{type:'text',text:'선택',marks:[{type:mark}]},{type:'text',text:' 뒤'}]);assert.ok(h.state.selection.eq(before.selection));assert.equal(h.document.pages[0].blocks[0].id,p.id);assert.equal(manualKey(h,'z',{ctrlKey:true}),true);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));
});
for(const [mark,key,shiftKey]of markKeys)test(`${mark} keymap shortcut at caret affects future input with one undo`,()=>{
 const d=createEmptyManualDocument(),p=d.pages[0].blocks[0];p.content=[{type:'text',text:'문장'}];const h=harness(d);h.select(findManualObject(h.state,p.id).pos+3);const before=h.state;h.boundary();assert.equal(manualKey(h,key,{ctrlKey:true,shiftKey}),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));h.dispatch(h.state.tr.insertText('추가'));assert.deepEqual(h.document.pages[0].blocks[0].content,[{type:'text',text:'문장'},{type:'text',text:'추가',marks:[{type:mark}]}]);assert.equal(manualKey(h,'z',{ctrlKey:true}),true);assert.deepEqual(h.document,d);
});
for(const [mark,key,shiftKey]of markKeys)for(const range of [false,true])test(`${mark} keymap shortcut consumes unsupported code block ${range?'range':'caret'} key without changing public command capability`,()=>{
 const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(commands.codeBlock);h.dispatch(h.state.tr.insertText('code'));if(range){const pos=h.state.selection.$from.start();h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,pos,pos+4)));}const before=h.state;assert.equal(commands[mark](h.state),false);assert.equal(manualKey(h,key,{ctrlKey:true,shiftKey}),true);assert.equal(h.state,before);
});
for(const [mark,key,shiftKey]of markKeys)test(`${mark} keymap shortcut rejects composition view event and keyCode guards`,()=>{
 const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));const before=h.state;for(const [event,composing]of [[{},true],[{isComposing:true},false],[{keyCode:229},false]]){assert.equal(manualKey(h,key,{ctrlKey:true,shiftKey,...event},composing),false);assert.equal(h.state,before);}
});
test('manual keymap routes plain and shifted Tab into the list commands',()=>{const {d,items}=listTabFixture(),h=harness(d);h.run(selectManualObject(items[1].blocks[0].id));assert.equal(manualKey(h,'Tab'),true);assert.equal(h.document.pages[0].blocks[0].items[0].blocks[1].items[0].id,items[1].id);h.boundary();assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);assert.deepEqual(h.document,d);});
test('format keymap leaves other modifier combinations unhandled',()=>{const h=harness(),before=h.state;for(const [key,event]of [['u',{}],['u',{ctrlKey:true,altKey:true}],['U',{ctrlKey:true,shiftKey:true}],['s',{ctrlKey:true}],['E',{ctrlKey:true,shiftKey:true}]]){assert.equal(manualKey(h,key,event),false);assert.equal(h.state,before);}});
test('format keymap consumes unsupported selected divider keys without mutation',()=>{const h=harness();h.run(insertManualBlock('divider'));const divider=h.document.pages[0].blocks.find(block=>block.type==='divider');h.run(selectManualObject(divider.id,{text:false}));const before=h.state;for(const [mark,key,shiftKey]of markKeys){assert.equal(commands[mark](h.state),false);assert.equal(manualKey(h,key,{ctrlKey:true,shiftKey}),true);assert.equal(h.state,before);}});
function procedureOutdentFixture(count=3){
 const d=createEmptyManualDocument(),p=text=>({id:crypto.randomUUID(),type:'paragraph',extensions:{body:text},content:[{type:'text',text}]}),steps=Array.from({length:count},(_,i)=>({id:crypto.randomUUID(),title:[{type:'text',text:`제목${i+1}`,marks:[{type:'strong'}]}],extensions:{step:i+1},blocks:[p(`설명${i+1}`)]})),procedure={id:crypto.randomUUID(),type:'procedure',start:4,extensions:{vendor:{keep:true}},steps},tail=p('절차 뒤 본문');d.pages[0].blocks=[procedure,tail];return {d,procedure,steps,tail,p};
}
for(const index of [0,1,2])test(`stepTitle ShiftTab lifts ${['first','middle','last'][index]} step content and preserves continuous procedure numbering`,()=>{
 const {d,procedure,steps,tail}=procedureOutdentFixture(),selected=steps[index];selected.blocks.push({id:crypto.randomUUID(),type:'figure',asset:'assets/screen.png',alt:'화면',widthPreset:'compact',caption:[{type:'text',text:'캡션',marks:[{type:'underline'}]}],extensions:{figure:'keep'}},{id:crypto.randomUUID(),type:'callout',title:[{type:'text',text:'안내'}],tone:'cautionary',extensions:{callout:'keep'},blocks:[{id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'보충 설명'}]}]});const h=harness(d);h.run(selectManualObject(selected.id));h.select(h.state.selection.from+2);h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.underline.create()]));const before=h.state;assert.equal(commands.outdentStep(h.state),true);assert.equal(h.state,before);assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);
 const result=h.document,blocks=result.pages[0].blocks,title=blocks[index?1:0],offset=index?2:1;assert.equal(title.type,'paragraph');assert.equal(title.id,selected.id);assert.deepEqual(title.content,selected.title);assert.deepEqual(title.extensions,selected.extensions);assert.deepEqual(blocks.slice(offset,offset+selected.blocks.length),selected.blocks);assert.deepEqual(blocks.at(-1),tail);
 const residual=blocks.filter(block=>block.type==='procedure');assert.ok(residual.every(block=>block.steps.length));if(index){assert.equal(residual[0].id,procedure.id);assert.equal(residual[0].start,4);assert.deepEqual(residual[0].steps,steps.slice(0,index));}if(index<2){const after=residual.at(-1);assert.equal(after.start,4+index+1);assert.deepEqual(after.steps,steps.slice(index+1));assert.equal(index?after.id!==procedure.id:after.id===procedure.id,true);}for(const block of residual)assert.deepEqual(block.extensions,procedure.extensions);
 assert.equal(h.state.selection.$from.parent.type.name,'paragraph');assert.equal(h.state.selection.$from.parent.attrs.id,selected.id);assert.equal(h.state.selection.$from.parentOffset,2);assert.deepEqual(h.state.storedMarks,before.storedMarks);assert.equal(new Set(ids(result)).size,ids(result).length);h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.deepEqual(h.document,result);assert.equal(h.state.selection.$from.parentOffset,2);
});
test('empty third stepTitle ShiftTab creates editable outside text and retains its empty description',()=>{
 const {d,procedure,steps,tail}=procedureOutdentFixture();steps[2].title=[];steps[2].blocks[0].content=[];const h=harness(d);h.run(selectManualObject(steps[2].id));const before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);const result=h.document,blocks=result.pages[0].blocks;assert.equal(blocks[0].id,procedure.id);assert.deepEqual(blocks[0].steps,steps.slice(0,2));assert.deepEqual(blocks[1],{id:steps[2].id,type:'paragraph',extensions:steps[2].extensions,content:[]});assert.deepEqual(blocks[2],steps[2].blocks[0]);assert.deepEqual(blocks[3],tail);assert.equal(h.state.selection.$from.parent.attrs.id,steps[2].id);assert.equal(h.state.selection.$from.parentOffset,0);h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.deepEqual(h.document,result);h.dispatch(h.state.tr.insertText('절차 밖에서 작성'));assert.equal(h.document.pages[0].blocks[1].content[0].text,'절차 밖에서 작성');assert.equal(h.document.pages[0].blocks[0].steps.length,2);
});
test('sole stepTitle ShiftTab preserves removed procedure provenance without overwriting extension keys',()=>{
 const {d,procedure,steps}=procedureOutdentFixture(1);steps[0].extensions={outdentedProcedure:{custom:'keep'},outdentedProcedure2:'also keep',vendor:{id:'opaque'}};const h=harness(d);h.run(selectManualObject(steps[0].id));const before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);const result=h.document,blocks=result.pages[0].blocks;assert.equal(blocks.some(block=>block.type==='procedure'),false);assert.equal(blocks[0].id,steps[0].id);assert.deepEqual(blocks[0].extensions,{...steps[0].extensions,outdentedProcedure3:{id:procedure.id,start:4,extensions:procedure.extensions}});assert.deepEqual(blocks[1],steps[0].blocks[0]);assert.equal(ids(result).includes(procedure.id),false);assert.equal(new Set(ids(result)).size,ids(result).length);h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));h.run(commands.redo);assert.deepEqual(h.document,result);
});
for(const offset of [0,2,3,5,7])test(`rich stepTitle ShiftTab preserves caret inline offset ${offset}`,()=>{
 const {d,steps}=procedureOutdentFixture(1);steps[0].title=[{type:'text',text:'제목',marks:[{type:'strong'}]},{type:'hardBreak'},{type:'text',text:'😀끝!',marks:[{type:'link',href:'https://example.invalid'}]}];const h=harness(d);h.run(selectManualObject(steps[0].id));h.select(h.state.selection.from+offset);const before=h.state;assert.equal(h.run(commands.shiftTab),true);assert.equal(h.state.selection.$from.parentOffset,offset);assert.deepEqual(h.document.pages[0].blocks[0].content,steps[0].title);h.run(commands.undo);assert.ok(h.state.selection.eq(before.selection));assert.deepEqual(h.document,d);
});
test('stepTitle ShiftTab dry run and composition guards leave document selection and active marks unchanged',()=>{
 const {d,steps}=procedureOutdentFixture(),h=harness(d);h.run(selectManualObject(steps[1].id));h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.emphasis.create()]));const before=h.state;assert.equal(commands.outdentStep(h.state),true);assert.equal(h.state,before);assert.equal(commands.outdentStep(h.state,h.dispatch,{composing:true}),false);assert.equal(commands.shiftTab(h.state,h.dispatch,{composing:true}),false);for(const event of [{isComposing:true},{keyCode:229}])assert.equal(manualKey(h,'Tab',{shiftKey:true,...event}),false);assert.equal(h.state,before);
});
test('stepTitle range and step description ShiftTab remain unhandled without lifting content',()=>{
 const {d,steps}=procedureOutdentFixture(),h=harness(d);h.run(selectManualObject(steps[1].id));const pos=h.state.selection.from;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,pos,pos+2)));let before=h.state;assert.equal(commands.outdentStep(h.state),false);assert.equal(manualKey(h,'Tab',{shiftKey:true}),false);assert.equal(h.state,before);h.run(selectManualObject(steps[1].blocks[0].id));before=h.state;assert.equal(commands.outdentStep(h.state),false);assert.equal(manualKey(h,'Tab',{shiftKey:true}),false);assert.equal(h.state,before);h.run(selectManualObject(d.pages[0].blocks[0].id,{text:false}));before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),false);assert.equal(h.state,before);
});
test('step description list ShiftTab keeps the existing list outdent priority',()=>{
 const {d,procedure,steps}=procedureOutdentFixture(),{list,items}=listTabFixture();steps[1].blocks=[list];const h=harness(d);h.run(selectManualObject(items[1].blocks[0].id));const before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);const result=h.document,after=result.pages[0].blocks[0];assert.equal(after.id,procedure.id);assert.deepEqual(after.steps[1].title,steps[1].title);assert.deepEqual(after.steps[1].blocks[1],items[1].blocks[0]);assert.equal(after.steps.length,3);h.run(commands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before.selection));
});
test('step description code ShiftTab keeps indentation priority and does not lift at its first character',()=>{
 const {d,steps}=procedureOutdentFixture(),code={id:crypto.randomUUID(),type:'codeBlock',text:'  code',language:'js',extensions:{code:'keep'}};steps[1].blocks=[code];const h=harness(d);h.run(selectManualObject(code.id));h.select(h.state.selection.from+2);const before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);assert.equal(h.document.pages[0].blocks[0].steps[1].blocks[0].text,'code');assert.equal(h.state.selection.$from.parent.type.name,'codeBlock');h.run(commands.undo);assert.deepEqual(h.document,d);h.run(selectManualObject(code.id));const first=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),false);assert.equal(h.state,first);
});
test('step description table ShiftTab keeps cell navigation priority and first-cell no-op',()=>{
 const sample=harness();sample.run(insertManualBlock('table',{rows:0}));const table=sample.document.pages[0].blocks.find(block=>block.type==='table'),{d,steps}=procedureOutdentFixture();steps[1].blocks=[{id:crypto.randomUUID(),type:'callout',tone:'signal',title:[],blocks:[table]}];const h=harness(d);h.run(selectManualObject(table.headers[1].id));const before=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),true);assert.ok(h.state.doc.eq(before.doc));assert.equal(h.state.selection.$from.parent.attrs.id,table.headers[0].id);const first=h.state;assert.equal(manualKey(h,'Tab',{shiftKey:true}),false);assert.equal(h.state,first);
});
test('stepTitle outdent fixture round trip preserves rich body IDs metadata and image bytes',async()=>{
 const record=decodeDocumentFile(await readFile(new URL('./fixtures/manual-procedure-outdent.manual.json',import.meta.url),'utf8')),before=structuredClone(record),h=harness(record.document),procedure=record.document.pages[1].blocks.find(block=>block.type==='procedure'),step=procedure.steps[1];h.run(selectManualObject(step.id));assert.equal(h.run(commands.shiftTab),true);const result=h.document,blocks=result.pages[1].blocks,paragraph=blocks.find(block=>block.id===step.id),at=blocks.indexOf(paragraph);assert.deepEqual(paragraph.content,step.title);assert.deepEqual(blocks.slice(at+1,at+1+step.blocks.length),step.blocks);assert.deepEqual(record,before);const decoded=decodeDocumentFile(encodeDocumentFile({document:result,assets:record.assets}));assert.deepEqual(decoded.document,result);assert.deepEqual(decoded.assets,record.assets);h.run(commands.undo);assert.deepEqual(h.document,record.document);
});

test('figure caption Enter escapes to following text and code Shift Enter preserves code block',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('figure'));const figure=h.document.pages[0].blocks[1];assert.equal(h.run(commands.enter),true);assert.equal(h.document.pages[0].blocks[1].id,figure.id);assert.equal(h.document.pages[0].blocks[2].type,'paragraph');h.run(commands.codeBlock);h.run(commands.hardBreak);assert.equal(h.document.pages[0].blocks[2].type,'codeBlock');assert.equal(h.document.pages[0].blocks[2].text,'\n');});

function typeRule(h,prefix,last,{composing=false}={}){h.dispatch(h.state.tr.insertText(prefix));const plugin=h.state.plugins.find(p=>p.spec.isInputRules);return plugin.props.handleTextInput({get state(){return h.state;},dispatch:h.dispatch,composing},h.state.selection.from,h.state.selection.to,last);}
for(const [prefix,type,attribute]of [['##','heading','level'],['-','list','ordered'],['5.','list','start'],['[x]','todo','checked'],['>','toggle','open'],['"','quote',null],['---','divider',null],['```js','codeBlock','language']])test(`input shortcut ${prefix} converts and Backspace restores literal input`,()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));assert.equal(typeRule(h,prefix,' '),true);const block=h.document.pages[0].blocks[0];assert.equal(block.type,type);if(attribute){const expected={level:2,ordered:false,start:5,checked:true,open:true,language:'js'};assert.equal(block[attribute],expected[attribute]);}assert.equal(h.run(commands.backspace),true);assert.equal(h.document.pages[0].blocks[0].type,'paragraph');assert.equal(h.document.pages[0].blocks[0].content[0].text,prefix+' ');});
for(const [prefix,last,mark]of [['**bold*','*','strong'],['*italic','*','emphasis'],['`code','`','code'],['~~gone~','~','strike']])test(`inline ${mark} shortcut preserves plain text and can undo formatting`,()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));assert.equal(typeRule(h,prefix,last),true);assert.equal(h.document.pages[0].blocks[0].content[0].marks[0].type,mark);assert.equal(h.run(commands.backspace),true);assert.equal(h.document.pages[0].blocks[0].content[0].text,prefix+last);});
test('input rules leave composition and code text alone',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));assert.equal(typeRule(h,'#',' ',{composing:true}),false);h.run(commands.codeBlock);assert.equal(typeRule(h,'##',' '),false);});
test('clipboard slice retains semantic blocks and metadata while renewing IDs and internal links',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('callout',{tone:'cautionary'}));h.run(selectManualObject(h.document.pages[0].blocks[1].id,{text:false}));h.run(insertManualBlock('figure',{asset:'assets/a.png',alt:'image',caption:[{type:'text',text:'caption'}]}));const d=h.document;d.pages[0].blocks[0].content=[{type:'text',text:'target',marks:[{type:'link',href:'#'+d.pages[0].blocks[1].id}]}];d.pages[0].blocks[1].extensions={vendor:{keep:true}};const source=createManualState({document:d}),page=source.doc.firstChild;const nodes=[];page.forEach(node=>{if(node.type.name!=='pageTitle')nodes.push(node);});const pasted=normalizeManualPastedSlice(new Slice(Fragment.fromArray(nodes),0,0));const target=createEmptyManualDocument(),targetState=createManualState({document:target});const tr=targetState.tr.insert(targetState.doc.firstChild.nodeSize-1,pasted.content),after=targetState.applyTransaction(tr).state;const result=documentFromState(after),copied=result.pages[0].blocks.slice(1);assert.equal(copied[1].type,'callout');assert.equal(copied[1].tone,'cautionary');assert.deepEqual(copied[1].extensions,{vendor:{keep:true}});assert.equal(copied[2].asset,'assets/a.png');assert.equal(copied[0].content[0].marks[0].href,'#'+copied[1].id);assert.ok(ids(copied).every(id=>!ids(d).includes(id)));});
test('clipboard serialization has typed metadata and rejects unsafe image attributes',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('figure',{asset:'assets/a.png',alt:'safe'}));const node=findManualObject(h.state,h.document.pages[0].blocks[1].id).node,spec=node.type.spec.toDOM(node);assert.equal(spec[1]['data-manual-type'],'figure');const rule=node.type.spec.parseDOM[0],dom={getAttribute:key=>spec[1][key]??null};assert.equal(rule.getAttrs(dom).meta.asset,'assets/a.png');const unsafe={...spec[1],'data-manual-meta':JSON.stringify({asset:'javascript:bad'})};assert.equal(rule.getAttrs({getAttribute:key=>unsafe[key]??null}),false);});
test('copying whole pages flattens source wrappers without creating destination pages',()=>{const d=createEmptyManualDocument();d.pages[0].title=[{type:'text',text:'source'}];d.pages[0].extensions={vendor:true};const state=createManualState({document:d});const pasted=normalizeManualPastedSlice(new Slice(state.doc.content,0,0));assert.equal(pasted.content.firstChild.type.name,'heading');assert.equal(pasted.content.firstChild.textContent,'source');assert.ok(pasted.content.firstChild.attrs.meta.extensions.clipboardContainer.extensions.vendor);});
test('extra plugins are installed before default editor keymaps',()=>{const p=new Plugin({props:{handleKeyDown:()=>true}}),state=createManualState({plugins:[p]});assert.ok(state.plugins.indexOf(p)<state.plugins.findIndex(item=>item.props.handleKeyDown&&item!==p));});

test('pasted image name collision renews key without replacing existing bytes',()=>{const incoming={'assets/a.png':'data:image/png;base64,AAAA'},before=structuredClone(incoming);const result=prepareManualClipboardAssets(incoming,()=> 'data:image/png;base64,BBBB');assert.notEqual(result.mapping['assets/a.png'],'assets/a.png');assert.equal(result.assets[result.mapping['assets/a.png']],incoming['assets/a.png']);assert.deepEqual(incoming,before);const same=prepareManualClipboardAssets(incoming,key=>incoming[key]);assert.equal(same.mapping['assets/a.png'],'assets/a.png');});
test('asset reference remapping preserves figure crop, caption and ID',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('figure',{asset:'assets/a.png',caption:[{type:'text',text:'caption'}],crop:{x:0,y:0,width:10,height:10,sourceWidth:20,sourceHeight:20}}));const node=findManualObject(h.state,h.document.pages[0].blocks[1].id).node,slice=new Slice(Fragment.from(node),0,0),mapped=rekeyManualPastedAssets(slice,{'assets/a.png':'assets/new.png'}),next=mapped.content.firstChild;assert.equal(next.attrs.meta.asset,'assets/new.png');assert.equal(next.attrs.id,node.attrs.id);assert.deepEqual(next.attrs.meta.crop,node.attrs.meta.crop);assert.equal(next.textContent,'caption');assert.equal(node.attrs.meta.asset,'assets/a.png');});
test('clipboard image preparation rejects unsupported bytes and excessive total before callback',()=>{assert.throws(()=>prepareManualClipboardAssets({'assets/a.png':'data:image/svg+xml;base64,AAAA'}));const source='data:image/png;base64,'+'AAAA'.repeat(5*1024*1024);assert.throws(()=>prepareManualClipboardAssets({'assets/a.png':source,'assets/b.png':source,'assets/c.png':source,'assets/d.png':source}));});
test('custom multi-block closed clipboard retains nested semantic blocks and skips page title',()=>{const d=createEmptyManualDocument();d.pages[0].blocks.push({type:'toggle',id:crypto.randomUUID(),open:false,title:[{type:'text',text:'toggle'}],blocks:[{type:'figure',id:crypto.randomUUID(),asset:'assets/a.png',alt:'image',caption:[],widthPreset:'compact',extensions:{vendor:'keep'}}]});let state=createManualState({document:d,plugins:[manualBlockSelectionPlugin()]});const dispatch=tr=>state=state.applyTransaction(tr).state;assert.equal(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[1].id)(state,dispatch),true);const slice=normalizeManualPastedSlice(state.selection.content());assert.equal(slice.openStart,0);assert.equal(slice.content.childCount,2);const toggle=slice.content.child(1);assert.equal(toggle.type.name,'toggle');assert.equal(toggle.attrs.meta.open,false);assert.equal(toggle.child(1).attrs.meta.asset,'assets/a.png');assert.deepEqual(toggle.child(1).attrs.meta.extensions,{vendor:'keep'});assert.notEqual(toggle.attrs.id,d.pages[0].blocks[1].id);});
for(const kind of ['callout','toggle','procedure'])test(`partial text clipboard DOM preserves ${kind} title and body inside its container`,()=>{
 const d=createEmptyManualDocument(),page=d.pages[0],front=page.blocks[0];front.content=[{type:'text',text:'앞문단 시작과 끝'}];
 const body=[{id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'본문 시작과 끝'}]},{id:crypto.randomUUID(),type:'paragraph',content:[]}],title=[{type:'text',text:'구조 제목'}],common={id:crypto.randomUUID(),type:kind,extensions:{vendor:'keep'}};
 const middle=kind==='procedure'?{...common,start:4,steps:[{id:crypto.randomUUID(),title,blocks:body}]}:{...common,title,blocks:body,...(kind==='callout'?{tone:'cautionary'}:{open:false})};
 const back={id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'뒤문단 시작과 끝'}]};page.blocks.push(middle,back);
 const source=harness(d);source.dispatch(source.state.tr.setSelection(TextSelection.create(source.state.doc,findManualObject(source.state,front.id).pos+4,findManualObject(source.state,back.id).pos+4)));
 const slice=normalizeManualPastedSlice(parseClipboardSlice(source.state.selection.content())),target=harness(),before=target.document;target.run(selectManualObject(before.pages[0].blocks[0].id));target.boundary();target.dispatch(target.state.tr.replaceSelection(slice));
 const blocks=target.document.pages[0].blocks;assert.equal(blocks.length,3);assert.deepEqual(blocks[0].content,[{type:'text',text:' 시작과 끝'}]);assert.deepEqual(blocks[2].content,[{type:'text',text:'뒤문단'}]);
 assert.equal(blocks[1].type,kind);assert.deepEqual(blocks[1].extensions,middle.extensions);const nested=kind==='procedure'?blocks[1].steps[0]:blocks[1];assert.deepEqual(nested.title,title);assert.deepEqual(nested.blocks.map(block=>block.content),body.map(block=>block.content));
 if(kind==='callout')assert.equal(blocks[1].tone,'cautionary');if(kind==='toggle')assert.equal(blocks[1].open,false);if(kind==='procedure')assert.equal(blocks[1].start,4);assert.ok(ids(blocks).every(id=>!ids(d).includes(id)));assert.deepEqual(source.document,d);
 target.run(commands.undo);assert.deepEqual(target.document,before);
});
test('generic external clipboard headings and paragraphs retain their ordinary roles',()=>{
 const text=value=>({nodeType:3,nodeName:'#text',nodeValue:value}),dom=clipboardElement('div',{},[clipboardElement('h3',{},[text('제목')]),clipboardElement('p',{},[text('본문')])]),slice=DOMParser.fromSchema(manualSchema).parseSlice(dom);
 assert.equal(slice.content.child(0).type.name,'heading');assert.equal(slice.content.child(0).attrs.level,3);assert.equal(slice.content.child(1).type.name,'paragraph');assert.equal(slice.content.child(1).textContent,'본문');
});
for(const kind of ['callout','toggle','procedure'])test(`partial text clipboard starting in ${kind} body creates a valid container without copying its unselected title`,()=>{
 const d=createEmptyManualDocument(),body={id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'본문 시작과 끝'}]},title=[{type:'text',text:'복사하지 않은 제목'}],middle=kind==='procedure'?{id:crypto.randomUUID(),type:kind,start:2,steps:[{id:crypto.randomUUID(),title,blocks:[body]}]}:{id:crypto.randomUUID(),type:kind,title,blocks:[body],...(kind==='callout'?{tone:'cautionary'}:{open:false})},back={id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'다음문단'}]};d.pages[0].blocks=[middle,back];
 const source=harness(d);source.dispatch(source.state.tr.setSelection(TextSelection.create(source.state.doc,findManualObject(source.state,body.id).pos+3,findManualObject(source.state,back.id).pos+3)));
 for(const copied of [source.state.selection.content(),parseClipboardSlice(source.state.selection.content())]){
  const target=harness(),before=target.document;target.run(selectManualObject(before.pages[0].blocks[0].id));target.boundary();target.dispatch(target.state.tr.replaceSelection(normalizeManualPastedSlice(copied)));target.state.doc.check();
  const blocks=target.document.pages[0].blocks,nested=kind==='procedure'?blocks[0].steps[0]:blocks[0];assert.equal(blocks.length,2);assert.equal(blocks[0].type,kind);assert.deepEqual(nested.title,[]);assert.deepEqual(nested.blocks[0].content,[{type:'text',text:' 시작과 끝'}]);assert.deepEqual(blocks[1].content,[{type:'text',text:'다음'}]);assert.ok(ids(blocks).every(id=>!ids(d).includes(id)));target.run(commands.undo);assert.deepEqual(target.document,before);
 }
});

test('single container duplication remaps internal descendant and self anchors while keeping external links',()=>{
 const d=createEmptyManualDocument(),external=d.pages[0].blocks[0].id,root=crypto.randomUUID(),child=crypto.randomUUID();
 const links=[root,child,external].map((id,index)=>({type:'text',text:String(index),marks:[{type:'link',href:'#'+id}]}));
 d.pages[0].blocks.push({type:'callout',id:root,tone:'signal',title:[],blocks:[{type:'paragraph',id:child,content:links}],extensions:{vendor:{id:root}}});
 const h=harness(d);assert.equal(h.run(duplicateManualObject(root)),true);const copy=h.document.pages[0].blocks[2];
 assert.notEqual(copy.id,root);assert.notEqual(copy.blocks[0].id,child);assert.deepEqual(copy.blocks[0].content.map(run=>run.marks[0].href),['#'+copy.id,'#'+copy.blocks[0].id,'#'+external]);assert.deepEqual(copy.extensions,d.pages[0].blocks[1].extensions);
 h.run(commands.undo);assert.deepEqual(h.document,d);h.run(commands.redo);assert.deepEqual(h.document.pages[0].blocks[2],copy);
});
test('page duplication retains page wrapper and renews links to copied children',()=>{
 const d=createEmptyManualDocument(),id=d.pages[0].blocks[0].id;d.pages[0].title=[{type:'text',text:'page'}];d.pages[0].blocks[0].content=[{type:'text',text:'self',marks:[{type:'link',href:'#'+id}]}];
 const h=harness(d);h.run(duplicateManualObject(d.pages[0].id));assert.equal(h.document.pages.length,2);const page=h.document.pages[1];assert.notEqual(page.id,d.pages[0].id);assert.deepEqual(page.title,d.pages[0].title);assert.equal(page.blocks[0].content[0].marks[0].href,'#'+page.blocks[0].id);
});

for(const nodeSelection of [false,true])test(`image metadata update preserves ${nodeSelection?'node':'caption'} selection before next page`,()=>{
 const d=createEmptyManualDocument(),figure={type:'figure',id:crypto.randomUUID(),asset:'assets/a.png',alt:'image',caption:[{type:'text',text:'caption'}],widthPreset:'full',crop:{x:0,y:0,width:10,height:10,sourceWidth:20,sourceHeight:20}};
 d.pages[0].blocks.push(figure);d.pages.push(createEmptyManualDocument().pages[0]);const h=harness(d);h.run(selectManualObject(figure.id,{text:!nodeSelection}));if(!nodeSelection)h.select(h.state.selection.from+3);const before=h.state;
 assert.equal(h.run(updateManualObject(figure.id,{asset:'assets/b.png'},{remove:['crop']})),true);assert.ok(h.state.selection.eq(before.selection));assert.equal(h.document.pages[0].blocks[1].asset,'assets/b.png');assert.equal(Object.hasOwn(h.document.pages[0].blocks[1],'crop'),false);
 h.run(commands.undo);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));
});
test('callout tone change preserves its body caret and content',()=>{const h=harness();h.run(selectManualObject(h.document.pages[0].blocks[0].id));h.run(insertManualBlock('callout'));const callout=h.document.pages[0].blocks[1];h.run(selectManualObject(callout.blocks[0].id));h.dispatch(h.state.tr.insertText('body'));const before=h.state;h.run(updateManualObject(callout.id,{tone:'negative'}));assert.ok(h.state.selection.eq(before.selection));assert.equal(h.document.pages[0].blocks[1].blocks[0].content[0].text,'body');});

for(const href of ['https://new.invalid',null])test(`multi-page selected blocks link ${href??'remove'} leaves titles leads and unselected blocks unchanged`,()=>{
 const d=createEmptyManualDocument(),second=createEmptyManualDocument().pages[0],run=text=>[{type:'text',text,marks:[{type:'link',href:'https://original.invalid'}]}],p=text=>({type:'paragraph',id:crypto.randomUUID(),content:run(text)});
 d.pages[0].title=run('first title');d.pages[0].lead=run('first lead');d.pages[0].blocks=[p('outside before'),p('selected first')];
 second.title=run('second title');second.lead=run('second lead');second.blocks=[p('selected second'),p('outside after')];d.pages.push(second);
 const h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[1].id,second.blocks[0].id));const before=h.state;assert.equal(h.run(setManualLink(href)),true);
 const result=h.document;for(let i=0;i<2;i++){assert.deepEqual(result.pages[i].title,d.pages[i].title);assert.deepEqual(result.pages[i].lead,d.pages[i].lead);}
 assert.deepEqual(result.pages[0].blocks[0],d.pages[0].blocks[0]);assert.deepEqual(result.pages[1].blocks[1],d.pages[1].blocks[1]);
 for(const block of [result.pages[0].blocks[1],result.pages[1].blocks[0]])assert.deepEqual(block.content[0].marks,href?[{type:'link',href}]:undefined);
 assert.ok(h.state.selection.eq(before.selection));h.run(commands.undo);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));
});
