import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,moveManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
const paragraph=(id,text)=>({id,type:'paragraph',content:[{type:'text',text}],extensions:{vendor:{id}}});
const document={schemaVersion:2,id:'doc',title:'',cover:{id:'cover',logo:{src:'@lk-design-system/lds-theme/assets/brand/lk-logo-inline-navy.svg',alt:'LK'},title:[{type:'text',text:'Title'}],metadata:[{id:'entry',label:[],value:[]}],sectionTitle:[{type:'text',text:'Prep'}],blocks:[paragraph('body','Body')],extensions:{vendor:{cover:1}}},pages:[{id:'page',title:[],blocks:[paragraph('page-body','Page')]}]};
function h(){let state=createManualState({document});const dispatch=tr=>{state=state.applyTransaction(tr).state;};return {get state(){return state;},dispatch,run:command=>command(state,dispatch),role:role=>findManualCoverRole(state,'cover',role)};}
function verify(a,before){const after=a.state,d=documentFromState(after);assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
test('explicit cover header end-gap moves logo after metadata before the required frame in one Undo',()=>{
 const a=h(),logo=a.role('logo').node.attrs.id,cover=findManualObject(a.state,'cover');a.dispatch(a.state.tr.setSelection(NodeSelection.create(a.state.doc,a.role('logo').pos)));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(moveManualObject(logo,{parentId:'cover',index:cover.node.childCount,coverHeader:true})),true);const parent=findManualObject(a.state,'cover').node;assert.deepEqual(Array.from({length:parent.childCount-1},(_,i)=>parent.child(i).attrs.id),['title','metadata','divider','logo'].map(role=>a.role(role).node.attrs.id));assert.equal(parent.lastChild.type.name,'coverSectionFrame');assert.deepEqual(documentFromState(a.state).cover.logo,document.cover.logo);verify(a,before);
});
test('explicit header and legacy cover-body targets move between physical parents while preserving title protection',()=>{
 const a=h(),title=a.role('title').node.attrs.id;a.dispatch(a.state.tr.setSelection(NodeSelection.create(a.state.doc,a.role('title').pos)));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(moveManualObject(title,{parentId:'cover',index:1})),true);assert.equal(findManualObject(a.state,title).parent.type.name,'coverBody');verify(a,before);a.dispatch(closeHistory(a.state.tr));const bodyBefore=a.state;assert.equal(a.run(moveManualObject(title,{parentId:'cover',index:0,coverHeader:true})),true);assert.equal(findManualObject(a.state,title).parent.type.name,'cover');verify(a,bodyBefore);const fixed=a.state;assert.equal(a.run(moveManualObject(title,{parentId:'page',index:1,coverHeader:true})),false);assert.equal(a.state,fixed);
});
test('frame-prefix end gap inserts before the required body wrapper and keeps opaque body metadata',()=>{
 const a=h(),frame=findManualObject(a.state,'cover').node.lastChild;const before=a.state;assert.equal(a.run(moveManualObject('body',{parentId:frame.attrs.id,index:frame.childCount})),true);const moved=findManualObject(a.state,'body');assert.equal(moved.parent.attrs.id,frame.attrs.id);assert.equal(moved.parent.lastChild.type.name,'coverBody');assert.deepEqual(documentFromState(a.state).cover.blocks[0],document.cover.blocks[0]);verify(a,before);
});
