import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {closeHistory,undoDepth} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {validateManualDocument} from '../src/redesign/manual-v2.mjs';
import {withManualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
const inline=text=>[{type:'text',text,marks:[{type:'strong'}]}],paragraph=(id,text)=>({id,type:'paragraph',content:inline(text),extensions:{vendor:{id}}}),figure=id=>({id,type:'figure',asset:'assets/synthetic.png',alt:'Synthetic',caption:inline('Caption'),widthPreset:'full',extensions:{vendor:{id}}});
function fixture({start=1,index=0,count=3,rich=true}={}){return {schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:inline('Task'),blocks:[paragraph('before','Before'),{id:'procedure',type:'procedure',start,extensions:{vendor:{procedure:'keep'}},steps:Array.from({length:count},(_,i)=>({id:`step${i}`,title:i===index?[]:inline(`Title${i}`),blocks:rich?[paragraph(`body${i}`,`Body${i}`),figure(`image${i}`)]:[],extensions:{vendor:{step:i}}}))},paragraph('after','After')]}]};}
function h(document,index=0){let state=createManualState({document}),transactions=[];const dispatch=tr=>{transactions.push(tr);state=state.applyTransaction(tr).state;};const step=()=>findManualObject(state,`step${index}`),view={get state(){return state;},dispatch,dom:{isConnected:true},editable:true,composing:false,props:{},endOfTextblock:()=>true};dispatch(state.tr.setSelection(TextSelection.create(state.doc,step().pos+2)));return {get state(){return state;},get document(){const d=documentFromState(state);validateManualDocument(d);return d;},transactions,dispatch,view,run:(command,v=view)=>command(state,dispatch,v),key(){const event={key:'Backspace',keyCode:8,preventDefault(){}};return state.plugins.some(plugin=>plugin.props.handleKeyDown?.(view,event));}};}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
for(const start of [1,4])for(const index of [0,1,2])test(`public empty step Backspace at index ${index}, start ${start} lifts only that step with exact descendants and numbering`,()=>{
 const d=fixture({start,index}),a=h(d,index);a.dispatch(a.state.tr.setStoredMarks([a.state.schema.marks.emphasis.create()]));const before=a.state,count=a.transactions.length;assert.equal(a.key(),true);assert.equal(a.transactions.length,count+1);const blocks=a.document.pages[0].blocks,converted=blocks.findIndex(block=>block.id===`step${index}`),step=d.pages[0].blocks[1].steps[index];assert.equal(blocks[converted].type,'paragraph');assert.deepEqual(blocks[converted].content,[]);assert.deepEqual(blocks[converted].extensions,step.extensions);assert.deepEqual(blocks.slice(converted+1,converted+3),step.blocks);assert.equal(a.state.selection.$from.parent.attrs.id,step.id);assert.equal(a.state.selection.$from.parentOffset,0);assert.deepEqual(a.state.storedMarks,before.storedMarks);
 const procedures=blocks.filter(block=>block.type==='procedure');if(index===0){assert.equal(procedures.length,1);assert.equal(procedures[0].start,start+1);assert.equal(procedures[0].id,'procedure');assert.deepEqual(procedures[0].steps,d.pages[0].blocks[1].steps.slice(1));}
 else if(index===1){assert.equal(procedures.length,2);assert.equal(procedures[0].id,'procedure');assert.notEqual(procedures[1].id,'procedure');assert.deepEqual(procedures.map(block=>block.start),[start,start+2]);assert.deepEqual(procedures[0].steps,d.pages[0].blocks[1].steps.slice(0,1));assert.deepEqual(procedures[1].steps,d.pages[0].blocks[1].steps.slice(2));}
 else{assert.equal(procedures.length,1);assert.equal(procedures[0].start,start);assert.deepEqual(procedures[0].steps,d.pages[0].blocks[1].steps.slice(0,2));}for(const procedure of procedures)assert.deepEqual(procedure.extensions,d.pages[0].blocks[1].extensions);assert.deepEqual(blocks[0],d.pages[0].blocks[0]);assert.deepEqual(blocks.at(-1),d.pages[0].blocks.at(-1));undoRedo(a,before);
});
for(const rich of [false,true])test(`sole empty step with ${rich?'real descendants':'no body'} preserves procedure provenance and one Undo`,()=>{
 const d=fixture({start:4,count:1,rich}),a=h(d),before=a.state;assert.equal(a.key(),true);const blocks=a.document.pages[0].blocks,converted=blocks[1];assert.equal(converted.type,'paragraph');assert.equal(converted.id,'step0');assert.deepEqual(converted.extensions.vendor,{step:0});const provenance=Object.values(converted.extensions).find(value=>value?.id==='procedure');assert.deepEqual(provenance,{extensions:d.pages[0].blocks[1].extensions,id:'procedure',start:4});assert.deepEqual(blocks.slice(2,-1),d.pages[0].blocks[1].steps[0].blocks);undoRedo(a,before);
});
test('empty-step conversion is separated from prior typing and Redo preserves the same IDs',()=>{
 const d=fixture({index:1}),a=h(d,1),other=findManualObject(a.state,'before');a.dispatch(closeHistory(a.state.tr).insertText('X',other.pos+1));const step=findManualObject(a.state,'step1');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,step.pos+2)));const before=a.state,depth=undoDepth(a.state);assert.equal(a.key(),true);assert.equal(undoDepth(a.state),depth+1);undoRedo(a,before);a.run(manualCommands.undo);assert.equal(findManualObject(a.state,'before').node.textContent,'XBefore');a.run(manualCommands.undo);assert.equal(findManualObject(a.state,'before').node.textContent,'Before');
});
test('readonly, composition, ranges, nonempty titles and offsets leave the structural step unchanged',()=>{
 const a=h(fixture());for(const view of [{...a.view,editable:false},{...a.view,composing:true}]){const before=a.state;assert.equal(a.run(manualCommands.backspace,view),false);assert.equal(a.state,before);}const d=fixture();d.pages[0].blocks[1].steps[0].title=inline('Content');const b=h(d),before=b.state;assert.equal(b.run(manualCommands.backspace),false);assert.equal(b.state,before);const pos=findManualObject(b.state,'step0').pos+2;b.dispatch(b.state.tr.setSelection(TextSelection.create(b.state.doc,pos+2)));const middle=b.state;assert.equal(b.run(manualCommands.backspace),false);assert.equal(b.state,middle);b.dispatch(b.state.tr.setSelection(TextSelection.create(b.state.doc,pos,pos+2)));const range=b.state;const handled=b.run(manualCommands.backspace);assert.equal(handled,true);assert.deepEqual(b.document.pages[0].blocks[1].steps[0],{...d.pages[0].blocks[1].steps[0],title:inline('ntent')});assert.equal(b.document.pages[0].blocks[1].start,1);
});
test('owned step/procedure fragments and referenced roots do not detach their logical pagination families',()=>{
 for(const kind of ['step','procedure','step-root','procedure-root']){const d=fixture(),procedure=d.pages[0].blocks[1],step=procedure.steps[0];if(kind==='step'||kind==='procedure'){const target=kind==='step'?step:procedure;target.extensions=withManualPaginationMarker({extensions:target.extensions},{kind:'block',rootBlockId:'logical-nonempty-root',sourceType:kind,repeatedTitle:true}).extensions;}
 else{d.pages[0].blocks.push({...paragraph('tail','Tail'),...withManualPaginationMarker({}, {kind:'block',rootBlockId:kind==='step-root'?step.id:procedure.id,sourceType:kind==='step-root'?'step':'procedure'})});}const a=h(d),before=a.state;assert.equal(a.key(),false);assert.equal(a.state,before);}
});
test('foreign extension namespaces do not block empty-step conversion; ShiftTab retains its existing contract',()=>{
 const d=fixture();d.pages[0].blocks[1].steps[0].extensions.manualPagination={owner:'vendor',version:1,rootBlockId:'external'};const a=h(d),before=a.state;assert.equal(a.key(),true);assert.deepEqual(a.document.pages[0].blocks.find(block=>block.id==='step0').extensions,d.pages[0].blocks[1].steps[0].extensions);undoRedo(a,before);const nonempty=fixture();nonempty.pages[0].blocks[1].steps[0].title=inline('Content');const b=h(nonempty),original=b.state;assert.equal(b.run(manualCommands.shiftTab),true);assert.equal(b.document.pages[0].blocks.find(block=>block.id==='step0').content[0].text,'Content');undoRedo(b,original);
});
