import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {undoInputRule} from '@tiptap/pm/inputrules';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,findManualPageRole,manualCommands} from '../src/redesign/manual-kernel.mjs';
const inline=text=>text?[{type:'text',text}]:[],paragraph=(id,text='')=>({id,type:'paragraph',content:inline(text),extensions:{vendor:{id}}});
function fixture(text='--'){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:inline('Cover'),metadata:[{id:'entry',label:inline('Label'),value:inline('Value')}],blocks:[]},pages:[{id:'page',title:inline('Page'),blocks:[paragraph('before','Before'),paragraph('body',text),paragraph('next','After')]}]};}
function h(document=fixture(),target='body',offset){let state=createManualState({document}),count=0,last=[];const dispatch=tr=>{count++;const result=state.applyTransaction(tr);last=result.transactions;state=result.state;};const found=findManualObject(state,target);dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+1+(offset??found.node.content.size))));const plugin=state.plugins.find(plugin=>plugin.spec.isInputRules),view={get state(){return state;},dispatch,editable:true,composing:false};return {get state(){return state;},get count(){return count;},get last(){return last;},dispatch,view,fire:(text='-',options={})=>plugin.props.handleTextInput({...view,...options.view},options.from??state.selection.from,options.to??state.selection.to,text),run:command=>command(state,dispatch,view)};}
function restored(a,literal='---'){const node=findManualObject(a.state,'body').node;assert.equal(node.type.name,'paragraph');assert.equal(node.textContent,literal);assert.equal(a.state.selection.$from.parent.attrs.id,'body');assert.equal(a.state.selection.$from.parentOffset,literal.length);assert.deepEqual(node.attrs.meta.extensions,{vendor:{id:'body'}});}
test('third hyphen converts the entire paragraph in one dispatched transaction, preserving its ID/metadata and neighbors; Mod-z/Redo restore complete trigger/caret',()=>{
 const a=h(),before=documentFromState(a.state),count=a.count;assert.equal(a.fire(),true);assert.equal(a.count,count+1);assert.equal(a.last.length,1);assert.equal(findManualObject(a.state,'body').node.type.name,'divider');assert.deepEqual(findManualObject(a.state,'body').node.attrs.meta.extensions,{vendor:{id:'body'}});const converted=a.state,after=documentFromState(a.state);assert.deepEqual(after.cover,before.cover);assert.deepEqual(after.pages[0].title,before.pages[0].title);assert.deepEqual(after.pages[0].blocks[0],before.pages[0].blocks[0]);assert.deepEqual(after.pages[0].blocks[2],before.pages[0].blocks[2]);assert.equal(a.run(manualCommands.undo),true);restored(a);assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(converted.doc));assert.ok(a.state.selection.eq(converted.selection));assert.equal(a.run(manualCommands.undo),true);restored(a);
});
test('direct public undoInputRule restores literal trigger and cursor, separate from ordinary history redo',()=>{
 const a=h();assert.equal(a.fire(),true);assert.equal(a.run(undoInputRule),true);restored(a);
});
test('user Backspace reverses only divider formatting and Redo reapplies it in one command',()=>{
 const a=h();a.fire();const converted=a.state,count=a.count;assert.equal(a.run(manualCommands.backspace),true);assert.equal(a.count,count+1);restored(a);assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(converted.doc));assert.ok(a.state.selection.eq(converted.selection));
});
test('legacy space trigger remains supported with complete literal/caret restoration and redo',()=>{
 const a=h(fixture('---'));assert.equal(a.fire(' '),true);const converted=a.state;assert.equal(a.run(manualCommands.undo),true);restored(a,'--- ');assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(converted.doc));
});
test('readonly/IME/stale/range, inline/trailing text, code/link marks and non-paragraph fields do not convert or dispatch',()=>{
 for(const [text,offset,options]of [['--',2,{view:{editable:false}}],['--',2,{view:{composing:true}}],['--',2,{from:0,to:0}],['x--',3,{}],['--tail',2,{}],['---',3,{}]]){const a=h(fixture(text),'body',offset),before=a.state,count=a.count;assert.equal(a.fire('-',options),false);assert.equal(a.state,before);assert.equal(a.count,count);}
 const range=h();const found=findManualObject(range.state,'body');range.dispatch(range.state.tr.setSelection(TextSelection.create(range.state.doc,found.pos+1,found.pos+3)));const before=range.state,count=range.count;assert.equal(range.fire(),false);assert.equal(range.state,before);assert.equal(range.count,count);
 for(const mark of [{type:'code'},{type:'link',href:'https://example.invalid/'}]){const d=fixture();d.pages[0].blocks[1].content=[{type:'text',text:'--',marks:[mark]}];const a=h(d),state=a.state;assert.equal(a.fire(),false);assert.equal(a.state,state);}
 const d=fixture();d.pages[0].blocks.push({id:'code',type:'codeBlock',language:'',text:'--'},{id:'figure',type:'figure',asset:'',alt:'',caption:inline('--'),widthPreset:'full'},{id:'table',type:'table',label:'Synthetic',headers:[{id:'cell',content:inline('--')}],rows:[]});d.pages[0].title=inline('--');d.cover.title=inline('--');
 const initial=createManualState({document:d}),targets=[findManualPageRole(initial,'page','title'),findManualCoverRole(initial,'cover','title'),findManualObject(initial,'code'),findManualObject(initial,'cell'),{pos:findManualObject(initial,'figure').pos+1,node:findManualObject(initial,'figure').node.firstChild}];
 for(const target of targets){let state=createManualState({document:d}),dispatches=0;state=state.apply(state.tr.setSelection(TextSelection.create(state.doc,target.pos+1+target.node.content.size)));const plugin=state.plugins.find(plugin=>plugin.spec.isInputRules),view={state,editable:true,composing:false,dispatch(){dispatches++;}};assert.equal(plugin.props.handleTextInput(view,state.selection.from,state.selection.to,'-'),false);assert.equal(dispatches,0);}
});
test('schema-allowed nested callout/step paragraphs convert while quote/list first paragraphs remain text',()=>{
 for(const kind of ['callout','procedure']){const d=fixture();d.pages[0].blocks=[kind==='callout'?{id:'container',type:kind,tone:'signal',title:inline('Note'),blocks:[paragraph('body','--'),paragraph('next','After')]}:{id:'container',type:kind,start:3,steps:[{id:'step',title:inline('Step'),blocks:[paragraph('body','--'),paragraph('next','After')]}]}];const a=h(d);assert.equal(a.fire(),true);assert.equal(findManualObject(a.state,'body').node.type.name,'divider');assert.equal(a.run(manualCommands.undo),true);restored(a);assert.equal(a.run(manualCommands.redo),true);assert.equal(findManualObject(a.state,'body').node.type.name,'divider');}
 for(const block of [{id:'quote',type:'quote',blocks:[paragraph('body','--')]},{id:'list',type:'list',ordered:false,items:[{id:'item',blocks:[paragraph('body','--')]}]}]){const d=fixture();d.pages[0].blocks=[block];const a=h(d),before=a.state;assert.equal(a.fire(),false);assert.equal(a.state,before);}
});
test('existing heading/list space shortcuts keep their normal input-rule Backspace behavior under the live guard wrapper',()=>{
 for(const [prefix,type]of [['##','heading'],['-','bulletList']]){const a=h(fixture(prefix));assert.equal(a.fire(' '),true);let found=findManualObject(a.state,'body');if(type==='bulletList')assert.equal(found.parent.type.name,'listItem');else assert.equal(found.node.type.name,type);assert.equal(a.run(manualCommands.backspace),true);found=findManualObject(a.state,'body');assert.equal(found.node.type.name,'paragraph');assert.equal(found.node.textContent,prefix+' ');}
});
