import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {createManualComponents} from '../../../src/components.mjs';
import {createManualState,documentFromState,findManualCoverRole,deleteManualObject,moveManualObject} from '../src/redesign/manual-kernel.mjs';
import {projectManualCover,getManualCoverProjection} from '../src/redesign/manual-cover-legacy-projection.mjs';
const runtime=process.env.LDS_COVER_TEST_RUNTIME||fileURLToPath(new URL('../../../',import.meta.url)),require=createRequire(path.join(runtime,'package.json')),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{ManualCover,ManualDivider,ManualMetadata}=createManualComponents(React,()=>null),h=React.createElement;
function render(cover){const projection=projectManualCover(cover),role=block=>getManualCoverProjection(block.extensions)?.role;const renderBlock=block=>role(block)==='divider'?h(ManualDivider,{key:block.id,id:block.id,cover:true}):role(block)==='metadata'?h('div',{key:block.id,id:block.id,'data-manual-cover-role':'metadata'},h(ManualMetadata,{items:cover.metadata.map(item=>({label:item.label.map(run=>run.text||'').join(''),value:item.value.map(run=>run.text||'').join('')}))})):role(block)==='title'?h('h1',{key:block.id},cover.title.map(run=>run.text||'').join('')):h('p',{key:block.id},block.content?.map(run=>run.text||'').join(''));return renderToStaticMarkup(h(ManualCover,{cover,ordered:true,number:1,total:1},[...projection.headerBlocks.map(renderBlock),...projection.bodyBlocks.map(renderBlock)]));}
test('public ordered cover emits exactly one identified default line, honors its order/omission and retains the legacy one-line markup',()=>{
 const cover={id:'cover',title:[{type:'text',text:'Title'}],metadata:[{id:'entry',label:[{type:'text',text:'Label'}],value:[{type:'text',text:'Value'}]}],blocks:[]};let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',cover,pages:[{id:'page',title:[],blocks:[]}]}});const dispatch=tr=>state=state.applyTransaction(tr).state,id=findManualCoverRole(state,'cover','divider').node.attrs.id,initial=render(documentFromState(state).cover);assert.equal((initial.match(/<hr/g)||[]).length,1);assert.match(initial,new RegExp('<hr id="'+id+'" data-manual-id="'+id+'" data-manual-cover-role="divider"'));assert.ok(initial.indexOf('data-manual-cover-role="metadata"')<initial.indexOf('<hr'));
 assert.equal(moveManualObject(id,{parentId:'cover',index:0,coverHeader:true})(state,dispatch),true);const moved=render(documentFromState(state).cover);assert.equal((moved.match(/<hr/g)||[]).length,1);assert.ok(moved.indexOf('<hr')<moved.indexOf('data-manual-cover-role="metadata"'));assert.equal(deleteManualObject(id)(state,dispatch),true);const deleted=render(documentFromState(state).cover);assert.doesNotMatch(deleted,/<hr/);assert.match(deleted,/data-manual-cover-role="metadata"/);
 const legacy=renderToStaticMarkup(h(ManualCover,{cover:{title:'Legacy',metadata:[],blocks:[]},number:1,total:1}));assert.equal((legacy.match(/<hr/g)||[]).length,1);const legacyDivider=legacy.match(/<hr\b[^>]*>/)?.[0];assert.match(legacyDivider,/data-manual-cover-role="divider"/);assert.match(legacyDivider,/data-manual-divider-variant="emphasis"/);assert.match(legacy,/>Legacy<\/h1>/);
});
