import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const rich=text=>text?[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}]:[];
function harness({level=1,previous=false,text=''}={}){
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:rich('페이지 제목'),blocks:[...(previous?[{type:'paragraph',id:'before',content:rich('앞 내용'),extensions:{opaque:{before:true}}}]:[]),{type:'heading',id:'heading',level,content:rich(text),extensions:{opaque:{keep:[1,2]}}},{type:'paragraph',id:'after',content:rich('뒤 내용')}]}]}}),count=0;
 const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,editable:true,composing:false,dom:{isConnected:true},props:{},endOfTextblock:direction=>direction==='backward'?state.selection.$from.parentOffset===0:state.selection.$from.parentOffset===state.selection.$from.parent.content.size};
 const select=(offset=0)=>dispatch(state.tr.setSelection(TextSelection.create(state.doc,findManualObject(state,'heading').pos+1+offset)));select();
 return {get state(){return state;},get count(){return count;},view,dispatch,select,run:(fn=manualCommands.backspace,v=view)=>fn(state,dispatch,v),key:(event={},v=view)=>state.plugins.at(-2).props.handleKeyDown(v,{key:'Backspace',keyCode:8,shiftKey:false,altKey:false,ctrlKey:false,metaKey:false,...event})};
}
for(const level of [1,2,3])for(const previous of [false,true])for(const binding of [false,true])test(`empty heading ${level} after ${previous?'rich paragraph':'page title'} ${binding?'actual manual key binding':'command'} becomes same-ID paragraph with exact Undo/Redo and reopen`,()=>{
 const h=harness({level,previous}),before=h.state,count=h.count,original=documentFromState(before),node=findManualObject(before,'heading').node;
 assert.equal(manualCommands.backspace(before),true);assert.ok(h.state===before);assert.equal(h.count,count);assert.equal(binding?h.key():h.run(),true);assert.equal(h.count,count+1);const after=h.state,converted=findManualObject(after,'heading').node;
 assert.equal(converted.type.name,'paragraph');assert.equal(converted.attrs.id,'heading');assert.deepEqual(converted.attrs.meta,node.attrs.meta);assert.equal(after.selection.$from.parentOffset,0);assert.equal(after.selection.$from.parent.attrs.id,'heading');
 const expected=structuredClone(original),index=previous?1:0;expected.pages[0].blocks[index]={...expected.pages[0].blocks[index],type:'paragraph'};delete expected.pages[0].blocks[index].level;assert.deepEqual(documentFromState(after),expected);
 const reopened=decodeDocumentFile(encodeDocumentFile({document:expected,assets:{}})).document;assert.deepEqual(documentFromState(createManualState({document:reopened})),expected);
 assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.redo),true);assert.ok(h.state.doc.eq(after.doc));assert.ok(h.state.selection.eq(after.selection));h.dispatch(h.state.tr.insertText('계속 입력'));assert.equal(findManualObject(h.state,'heading').node.textContent,'계속 입력');
});
for(const mode of ['readonly','composing','stale'])test(`${mode} command cannot convert or delete heading`,()=>{const h=harness({previous:true}),before=h.state;let v=h.view;if(mode==='readonly')v={...v,editable:false};if(mode==='composing')v={...v,composing:true};if(mode==='stale')v={...v,state:createManualState({document:documentFromState(h.state)})};h.run(manualCommands.backspace,v);assert.ok(h.state.doc.eq(before.doc));});
for(const event of [{isComposing:true},{keyCode:229}])test(`actual manual key binding respects IME guard ${JSON.stringify(event)}`,()=>{const h=harness({previous:true}),before=h.state;assert.equal(h.key(event),false);assert.ok(h.state===before);});
test('nonempty heading range Backspace deletes only selected text and preserves heading level, marks and siblings',()=>{const h=harness({text:'안녕하세요',previous:true,level:2});const obj=findManualObject(h.state,'heading');h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,obj.pos+4,obj.pos+6)));assert.equal(h.key(),true);const node=findManualObject(h.state,'heading').node;assert.equal(node.type.name,'heading');assert.equal(node.attrs.level,2);assert.equal(node.textContent,'안녕하');assert.deepEqual(node.firstChild.marks,obj.node.firstChild.marks);assert.equal(findManualObject(h.state,'before').node.textContent,'앞 내용');});
test('nonempty heading interior caret keeps browser character deletion contract',()=>{const h=harness({text:'안녕하세요',previous:true});h.select(3);const before=h.state;assert.equal(h.run(),false);assert.ok(h.state===before);});
for(const role of ['title','sectionTitle'])test(`empty owned cover ${role} is preserved at Backspace boundary`,()=>{let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:[],sectionTitle:[],metadata:[],blocks:[]},pages:[{id:'page',title:[],blocks:[]}]}});const found=findManualCoverRole(state,'cover',role);assert.ok(found);state=state.apply(state.tr.setSelection(TextSelection.create(state.doc,found.pos+1)));const before=state,view={get state(){return state;},editable:true,composing:false,dom:{isConnected:true},props:{},endOfTextblock:()=>true,dispatch:tr=>{state=state.applyTransaction(tr).state;}};manualCommands.backspace(state,view.dispatch,view);assert.ok(state.doc.eq(before.doc));assert.ok(findManualCoverRole(state,'cover',role).node.eq(found.node));});
test('heading conversion is one Undo independent of preceding typing and preserves stored marks',()=>{const h=harness({previous:true});const previous=findManualObject(h.state,'before');h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,previous.pos+1)));h.dispatch(h.state.tr.insertText('최근 입력 '));h.select();h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.emphasis.create()]));const before=h.state;assert.equal(h.key(),true);assert.deepEqual(h.state.storedMarks,before.storedMarks);assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));});
