import test from 'node:test';
import assert from 'node:assert/strict';
import {undoDepth} from '@tiptap/pm/history';
import {createManualState,findManualObject,documentFromState,manualCommands,selectManualObject,deleteManualObject,executeManualBlockCommand} from '../src/redesign/manual-kernel.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const p=(id,text='Content')=>({id,type:'paragraph',content:text?[{type:'text',text,marks:[{type:'strong'}]}]:[],extensions:{vendor:{id,keep:true}}}),results=[];
for(const kind of ['quote','listOnly','listNested'])for(const empty of [false,true])test(`required paragraph deletion ${kind} empty=${empty} preserves valid container and Undo`,()=>{
 const para=p('target',empty?'':'Content'),nested={id:'nested',type:'list',ordered:false,items:[{id:'nested-item',blocks:[p('nested-text','Keep nested')]}]},container=kind==='quote'?{id:'container',type:'quote',blocks:[para],extensions:{vendor:'quote'}}:{id:'container',type:'list',ordered:false,items:[{id:'item',blocks:[para,...(kind==='listNested'?[nested]:[])],extensions:{vendor:'item'}}]};
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:[],metadata:[],blocks:[container]},pages:[{id:'page',title:[],blocks:[p('outside','Keep outside')]}]}}),count=0;
 const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};selectManualObject('target',{text:false})(state,dispatch);state=state.apply(state.tr.setStoredMarks([state.schema.marks.emphasis.create()]));const before=state,depth=undoDepth(state),at=findManualObject(state,'target'),startCount=count;
 const enabled=executeManualBlockCommand('delete',{targetId:'target'})(state);assert.equal(enabled,!empty);
 assert.equal(executeManualBlockCommand('delete',{targetId:'target'})(state,dispatch),!empty);
 if(empty){assert.equal(count,startCount);assert.equal(state,before);results.push({kind,empty,noDispatch:true});return;}
 const after=state,node=findManualObject(state,'target').node;assert.deepEqual(node.attrs,at.node.attrs);assert.equal(node.content.size,0);assert.equal(state.selection.$from.parent.attrs.id,'target');assert.equal(state.selection.$from.parentOffset,0);assert.deepEqual(state.storedMarks,before.storedMarks);assert.ok(findManualObject(after,'outside').node.eq(findManualObject(before,'outside').node));if(kind==='listNested')assert.ok(findManualObject(after,'nested').node.eq(findManualObject(before,'nested').node));
 assert.equal(count,startCount+1);assert.equal(undoDepth(after),depth+1);assert.equal(manualCommands.undo(state,dispatch),true);assert.ok(state.doc.eq(before.doc));assert.ok(state.selection.eq(before.selection));assert.equal(manualCommands.redo(state,dispatch),true);assert.ok(state.doc.eq(after.doc));assert.ok(state.selection.eq(after.selection));const dto=documentFromState(after);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:dto,assets:{}})).document,dto);assert.deepEqual(documentFromState(createManualState({document:decodeDocumentFile(encodeDocumentFile({document:dto,assets:{}})).document})),dto);
 results.push({kind,empty,attrsAndIDExact:true,caretInSentinel:true,oneUndoRedoCodec:true});
});
for(const ordered of [false,true])for(const location of ['pageOnly','pageSibling','coverBody','nestedList'])test(`sole ${ordered?'ordered':'bullet'} list item removal ${location} preserves siblings and Undo`,()=>{
 const list={id:'list',type:'list',ordered,items:[{id:'target-item',blocks:[p('item-text')],extensions:{vendor:'target'}}],extensions:{vendor:'list'}},outside=p('outside','Preserve'),container=location==='nestedList'?{id:'outer-list',type:'list',ordered:false,items:[{id:'outer-item',blocks:[p('outer-text','Preserve parent'),list]}]}:list;
 const document={schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:location==='coverBody'?[outside]:[container,...(location==='pageSibling'?[outside]:[])]}]};if(location==='coverBody')document.cover={id:'cover',title:[],metadata:[],blocks:[container]};
 let state=createManualState({document}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};selectManualObject('target-item',{text:false})(state,dispatch);const before=state,depth=undoDepth(state),start=count;assert.equal(executeManualBlockCommand('delete',{targetId:'target-item'})(state),true);assert.equal(executeManualBlockCommand('delete',{targetId:'target-item'})(state,dispatch),true);const after=state;assert.equal(count,start+1);assert.equal(findManualObject(state,'target-item'),null);assert.equal(findManualObject(state,'list'),null);assert.equal(undoDepth(state),depth+1);state.doc.check();assert.ok(state.selection.from>=0&&state.selection.to<=state.doc.content.size);if(location==='pageOnly'){assert.equal(state.selection.$from.parent.type.name,'paragraph');assert.equal(state.selection.$from.parentOffset,0);}if(location==='nestedList')assert.ok(findManualObject(state,'outer-text').node.eq(findManualObject(before,'outer-text').node));if(['pageSibling','coverBody'].includes(location))assert.ok(findManualObject(state,'outside').node.eq(findManualObject(before,'outside').node));assert.equal(manualCommands.undo(state,dispatch),true);assert.ok(state.doc.eq(before.doc));assert.ok(state.selection.eq(before.selection));assert.equal(manualCommands.redo(state,dispatch),true);assert.ok(state.doc.eq(after.doc));assert.ok(state.selection.eq(after.selection));const dto=documentFromState(after);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:dto,assets:{}})).document,dto);assert.deepEqual(documentFromState(createManualState({document:decodeDocumentFile(encodeDocumentFile({document:dto,assets:{}})).document})),dto);results.push({ordered,location,listWrapperRemoved:true,oneUndoRedoCodec:true});
});
test('delete guards reject composition, unknown target and last page while multi-item deletion preserves sibling',()=>{
let state=createManualState({document:{schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:[],blocks:[{id:'quote',type:'quote',blocks:[{id:'target',type:'paragraph',content:[{type:'text',text:'Keep'}]}]}]}]}}),dispatches=0;const dispatch=tr=>{dispatches++;state=state.applyTransaction(tr).state;};const before=state;
assert.equal(deleteManualObject('target')(state,dispatch,{composing:true}),false);assert.equal(state,before);assert.equal(dispatches,0);
assert.equal(deleteManualObject('missing')(state,dispatch),false);assert.equal(state,before);
assert.equal(deleteManualObject('page')(state,dispatch),false);assert.equal(state,before);
state=createManualState({document:{schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:[],blocks:[{id:'list',type:'list',ordered:false,items:[{id:'item1',blocks:[{id:'p1',type:'paragraph',content:[]}]},{id:'item2',blocks:[{id:'p2',type:'paragraph',content:[{type:'text',text:'Keep second'}]}]}]}]}]}});const keep=findManualObject(state,'item2').node;assert.equal(executeManualBlockCommand('delete',{targetId:'item1'})(state,dispatch),true);assert.ok(findManualObject(state,'item2').node.eq(keep));assert.equal(findManualObject(state,'list').node.childCount,1);state.doc.check();
});
