import test from 'node:test';
import assert from 'node:assert/strict';
import {AllSelection,NodeSelection,TextSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {Slice} from '@tiptap/pm/model';
import {createManualState,documentFromState,getManualEditingDocument,findManualObject,findManualCoverRole,manualCommands,selectManualObject,duplicateManualObject,deleteManualObject,moveManualObject,updateManualObject,insertParagraphAtGap,ensureParagraphAfter,normalizeManualPastedSlice} from '../src/redesign/manual-kernel.mjs';
import {manualBlockSelectionPlugin,selectManualBlocks,selectManualBlockIds,deleteSelectedManualBlocks} from '../src/redesign/manual-block-selection.mjs';
import {validateManualDocument,copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {projectManualCover,getManualCoverProjection} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const inline=text=>[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}];
const paragraph=(id,text)=>({id,type:'paragraph',content:inline(text),extensions:{vendor:{id}}});
const scalarInline=text=>inline(text).map(run=>({...run,marks:[...run.marks].reverse()}));
function fixture(){return {schemaVersion:2,id:'document',title:'Synthetic',extensions:{vendor:{keep:true}},cover:{id:'cover',logo:{src:'@lk-design-system/lds-theme/assets/brand/lk-logo-inline-navy.svg',alt:'LK ROBOTICS'},title:scalarInline('Manual'),metadata:[{id:'entry1',label:scalarInline('Version'),value:scalarInline('1.0'),extensions:{vendor:{entry:1}}},{id:'entry2',label:scalarInline('Device'),value:scalarInline('Synthetic')},{id:'entry3',label:scalarInline('Date'),value:[]}],sectionTitle:scalarInline('Before starting'),blocks:[paragraph('body1','First'),paragraph('body2','Second')],extensions:{manualCoverProjection:{foreign:'keep'},vendor:{cover:true}}},pages:[{id:'page',title:inline('Task'),blocks:[paragraph('page-body','Page')]}]};}
function h(document=fixture()){let state=createManualState({document,plugins:[manualBlockSelectionPlugin()]});const dispatch=tr=>{state=state.applyTransaction(tr).state;};return {get state(){return state;},get document(){return documentFromState(state);},dispatch,run:(command,view)=>command(state,dispatch,view),role:role=>findManualCoverRole(state,'cover',role)};}
function roundtrip(a){const d=a.document;validateManualDocument(d);assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const ids=[];a.state.doc.descendants(node=>{if(node.attrs.id)ids.push(node.attrs.id);});assert.equal(new Set(ids).size,ids.length);}
function undoRedo(a,before){const after=a.state;a.run(manualCommands.undo);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));a.run(manualCommands.redo);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));roundtrip(a);}
test('all cover visual roles are ordinary identified blocks inside real transparent layout frames, untouched scalar DTO is exact',()=>{
 const d=fixture(),a=h(d);assert.deepEqual(a.document,d);for(const [role,type]of [['logo','figure'],['title','heading'],['metadata','table'],['sectionTitle','heading']]){const found=a.role(role);assert.equal(found.node.type.name,type);assert.ok(found.node.type.spec.group.split(' ').includes('block'));assert.ok(found.node.attrs.id);assert.equal(a.run(selectManualBlocks(found.node.attrs.id)),true);assert.deepEqual(a.state.selection.ids,[found.node.attrs.id]);}
 const cover=findManualObject(a.state,'cover').node,frame=cover.lastChild;assert.equal(frame.type.name,'coverSectionFrame');assert.equal(frame.firstChild.type.name,'heading');assert.equal(frame.lastChild.type.name,'coverBody');assert.equal(frame.lastChild.child(0).attrs.id,'body1');assert.equal(frame.type.spec.selectable,false);assert.equal(frame.lastChild.type.spec.selectable,false);roundtrip(a);
});
for(const metadata of [[],[{id:'entry1',label:[],value:[],extensions:{}}]])test(`empty/one-entry metadata projects one selectable table and roundtrips ${metadata.length} entry`,()=>{
 const d=fixture();d.cover.metadata=metadata;const a=h(d);assert.equal(a.role('metadata').node.type.name,'table');assert.deepEqual(a.document,d);roundtrip(a);
});
test('initial cover caret targets the title and selecting the logo produces visible NodeSelection',()=>{
 const a=h();assert.equal(a.state.selection.$from.parent.attrs.id,a.role('title').node.attrs.id);a.run(selectManualObject(a.role('logo').node.attrs.id));assert.ok(a.state.selection instanceof NodeSelection);assert.equal(a.state.selection.node.attrs.id,a.role('logo').node.attrs.id);const logo=a.role('logo');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,logo.pos+2)));assert.ok(a.state.selection instanceof NodeSelection);
});
for(const role of ['logo','title','metadata','sectionTitle'])test(`${role} duplicates as a new ordinary block without duplicating scalar content in one Undo`,()=>{
 const a=h(),id=a.role(role).node.attrs.id;a.run(selectManualObject(id,{text:false}));a.dispatch(closeHistory(a.state.tr));const before=a.state,scalar=a.document.cover[role==='sectionTitle'?'sectionTitle':role];assert.equal(a.run(duplicateManualObject(id)),true);const after=a.document;assert.deepEqual(after.cover[role==='sectionTitle'?'sectionTitle':role],scalar);assert.equal(after.cover.blocks.length,3);assert.notEqual(after.cover.blocks[0].id,id);assert.equal(getManualCoverProjection(after.cover.blocks[0].extensions),null);undoRedo(a,before);
});
for(const role of ['logo','metadata','sectionTitle'])test(`${role} deletion stays deleted after save/load, preserves opaque fields and undoes once`,()=>{
 const a=h(),id=a.role(role).node.attrs.id;a.run(selectManualObject(id,{text:false}));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(deleteManualObject(id)),true);const d=a.document;if(role==='metadata')assert.deepEqual(d.cover.metadata,[]);else assert.equal(Object.hasOwn(d.cover,role),false);assert.deepEqual(d.cover.extensions.vendor,fixture().cover.extensions.vendor);assert.equal(findManualCoverRole(createManualState({document:d}),'cover',role),null);undoRedo(a,before);
});
for(const role of ['logo','metadata','sectionTitle'])test(`${role} can move to an ordinary page with data/IDs and one Undo`,()=>{
 const a=h(),node=a.role(role).node,id=node.attrs.id;a.run(selectManualObject(id,{text:false}));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(moveManualObject(id,{parentId:'page',index:1})),true);const d=a.document,moved=d.pages[0].blocks[0];assert.equal(moved.id,id);assert.equal(moved.type,node.type.name);assert.equal(getManualCoverProjection(moved.extensions),null);assert.equal(findManualCoverRole(createManualState({document:d}),'cover',role),null);undoRedo(a,before);
});
test('cover title text edits and same-cover movement retain the role while deletion, foreign moves and ordinary conversion release it',()=>{
 for(const operation of ['delete','move','convert']){const a=h(),id=a.role('title').node.attrs.id;a.run(selectManualObject(id));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(operation==='delete'?deleteManualObject(id):operation==='move'?moveManualObject(id,{parentId:'page',index:1}):manualCommands.paragraph),true);assert.deepEqual(a.document.cover.title,[]);assert.equal(a.role('title'),null);undoRedo(a,before);}
 const a=h(),id=a.role('title').node.attrs.id;a.run(selectManualObject(id));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(updateManualObject(id,{content:inline('Updated')})),true);assert.deepEqual(a.document.cover.title,inline('Updated'));undoRedo(a,before);
 const moveBefore=a.state;a.dispatch(closeHistory(a.state.tr));assert.equal(a.run(moveManualObject(id,{parentId:'cover',index:1})),true);roundtrip(a);assert.equal(findManualCoverRole(createManualState({document:a.document}),'cover','title').parent.type.name,'coverBody');undoRedo(a,moveBefore);
});
test('section heading can move between body blocks and its scalar binding and position survive file/document copies',()=>{
 const a=h(),id=a.role('sectionTitle').node.attrs.id;a.run(selectManualObject(id,{text:false}));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(moveManualObject(id,{parentId:'cover',index:1})),true);assert.deepEqual(a.document.cover.sectionTitle,fixture().cover.sectionTitle);const projected=projectManualCover(a.document.cover);assert.deepEqual(projected.bodyBlocks.map(block=>getManualCoverProjection(block.extensions)?.role||block.id),['body1','sectionTitle','body2']);roundtrip(a);const copy=copyManualDocument(a.document),fresh=projectManualCover(copy.cover);assert.deepEqual(fresh.bodyBlocks.map(block=>getManualCoverProjection(block.extensions)?.role||block.content?.[0]?.text),['First','sectionTitle','Second']);undoRedo(a,before);
});
test('cover-ID gap insertion and block trailing paragraph target the body wrapper with one Undo',()=>{
 const a=h();a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(insertParagraphAtGap('cover',2)),true);assert.equal(a.document.cover.blocks[2].type,'paragraph');assert.equal(a.state.selection.$from.node(a.state.selection.$from.depth-1).type.name,'coverBody');undoRedo(a,before);
 a.run(selectManualObject(a.role('metadata').node.attrs.id,{text:false}));a.dispatch(closeHistory(a.state.tr));const metadataBefore=a.state;assert.equal(a.run(ensureParagraphAfter(a.role('metadata').node.attrs.id)),true);assert.equal(a.state.selection.$from.parent.type.name,'paragraph');undoRedo(a,metadataBefore);
});
test('cross-frame block selection remains exact and title-including deletion removes only the selected identities',()=>{
 const a=h();assert.equal(a.run(selectManualBlocks(a.role('metadata').node.attrs.id,'body2')),true);assert.deepEqual(a.state.selection.ids,[a.role('metadata').node.attrs.id,a.role('divider').node.attrs.id,a.role('sectionTitle').node.attrs.id,'body1','body2']);assert.equal(a.state.selection.ranges.length,3);a.run(selectManualBlockIds([a.role('title').node.attrs.id,'body1']));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(deleteSelectedManualBlocks),true);assert.equal(a.role('title'),null);assert.equal(findManualObject(a.state,'body1'),null);assert.ok(findManualObject(a.state,'body2'));assert.deepEqual(a.document.cover.title,[]);undoRedo(a,before);
});
test('clipboard flattens layout wrappers and renews IDs without copying page frames',()=>{
 const a=h(),cover=findManualObject(a.state,'cover').node,slice=normalizeManualPastedSlice(new Slice(cover.content,0,0)),names=[];slice.content.forEach(node=>names.push(node.type.name));assert.deepEqual(names,['figure','heading','table','divider','heading','paragraph','paragraph']);slice.content.descendants(node=>assert.equal(['coverBody','coverSectionFrame'].includes(node.type.name),false));
});
test('Select All clears cover text while retaining required title ID, page IDs and one Undo',()=>{
 const a=h(),id=a.role('title').node.attrs.id;a.dispatch(a.state.tr.setSelection(new AllSelection(a.state.doc)));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(manualCommands.backspace),true);assert.deepEqual(a.document.cover.title,[]);assert.equal(a.role('title').node.attrs.id,id);assert.equal(a.document.pages[0].id,'page');undoRedo(a,before);
});
test('UI bridge exposes physical layout parents and all role IDs without leaking wrappers into persisted DTO',()=>{
 const a=h(),snapshot=getManualEditingDocument(a.state),frame=snapshot.cover.blocks.at(-1),body=frame.blocks.at(-1);assert.equal(frame.type,'coverSectionFrame');assert.equal(body.type,'coverBody');assert.ok(frame.id);assert.ok(body.id);assert.deepEqual(snapshot.cover.blocks.slice(0,3).map(block=>block.id),['logo','title','metadata'].map(role=>a.role(role).node.attrs.id));assert.equal(findManualObject(a.state,frame.id).node.type.name,'coverSectionFrame');assert.equal(findManualObject(a.state,body.id).node.type.name,'coverBody');assert.equal(a.run(selectManualBlocks(frame.id)),false);assert.equal(a.run(selectManualBlocks(body.id)),false);assert.deepEqual(a.document,fixture());assert.throws(()=>validateManualDocument(snapshot));
 const first=findManualObject(a.state,'body1');a.run(selectManualObject('body1',{text:false}));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(moveManualObject('body1',{parentId:frame.id,index:1})),true);assert.equal(findManualObject(a.state,'body1').parent.attrs.id,frame.id);undoRedo(a,before);
});
test('stable layout IDs avoid all real document IDs and remain absent from save/copy',()=>{
 const d=fixture();d.pages[0].blocks.push(paragraph('manual-cover:cover:layout:body','Collision'));const a=h(d),snapshot=getManualEditingDocument(a.state),frame=snapshot.cover.blocks.at(-1),body=frame.blocks.at(-1);assert.equal(body.id,'manual-cover:cover:layout:body:2');assert.deepEqual(a.document,d);roundtrip(a);const copy=copyManualDocument(a.document),reload=createManualState({document:copy});assert.deepEqual(documentFromState(reload),copy);
});
