import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {validateManualDocument,copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {createManualState,documentFromState,documentToNode,getManualEditingDocument,findManualCoverRole,findManualObject,getManualCoverInsertCommandState,executeManualCoverInsert,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {getManualDocumentCovers,withManualDocumentCovers,getOrderedPageEntries,withManualPageOrder} from '../src/redesign/manual-page-order.mjs';
import {getManualPageGroups} from '../src/redesign/manual-page-groups.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
import {planManualPagination,createManualPaginationTransaction} from '../src/redesign/manual-pagination.mjs';
import {manualPaginationPageParts} from '../src/redesign/manual-page-shape.mjs';
import {closeHistory} from '@tiptap/pm/history';
import {TextSelection} from '@tiptap/pm/state';
const inline=text=>[{type:'text',text,marks:[{type:'strong'}]}],p=(id,text)=>({id,type:'paragraph',content:inline(text),extensions:{vendor:{id}}}),cover=id=>({id,title:inline(id),metadata:[{id:id+'-m',label:inline('Label'),value:inline(id+' value'),extensions:{vendor:{id}}}],sectionTitle:inline('Prepare '+id),blocks:[p(id+'-body',id+' content')],extensions:{vendor:{id}}});
const fixture=()=>withManualPageOrder({schemaVersion:2,id:'doc',title:'Multiple synthetic covers',covers:[cover('c1'),cover('c2')],pages:[{id:'page',title:inline('Body'),blocks:[p('body','Body content')]}],extensions:{vendor:{keep:[null,'한글']}}},['c2','page','c1']);
function ids(doc){const all=[];doc.descendants(n=>{if(n.attrs.id)all.push(n.attrs.id)});assert.equal(new Set(all).size,all.length);return all}
test('cover helpers clone and canonicalize without aliases; mixed/empty/noncanonical cover arrays and duplicate identities reject',()=>{const d=fixture(),saved=structuredClone(d);assert.deepEqual(getManualDocumentCovers(d),d.covers);assert.equal(withManualDocumentCovers(d,[]).cover,undefined);assert.equal(withManualDocumentCovers(d,[]).covers,undefined);const one=withManualDocumentCovers(d,[d.covers[0]]);assert.deepEqual(one.cover,d.covers[0]);assert.equal(one.covers,undefined);const many=withManualDocumentCovers(one,d.covers);assert.deepEqual(many.covers,d.covers);assert.equal(many.cover,undefined);many.covers[0].title[0].text='Changed';assert.deepEqual(d,saved);for(const bad of [{...d,cover:d.covers[0]},{...d,covers:[]},{...d,covers:[d.covers[0]]},{...d,covers:[d.covers[0],d.covers[0]]}])assert.throws(()=>validateManualDocument(bad));});
test('legacy single cover roundtrips exactly; cover-only multiple DTO and ordered codec preserve every content/id/extension',()=>{const d=fixture(),legacy=withManualDocumentCovers({...d,pages:[]},[d.covers[0]]);delete legacy.extensions.manualPageOrder;assert.deepEqual(documentFromState(createManualState({document:legacy})),legacy);for(const candidate of [d,{...d,pages:[],extensions:{vendor:d.extensions.vendor}}]){const state=createManualState({document:candidate});ids(state.doc);const restored=documentFromState(state);assert.deepEqual(restored,candidate);assert.deepEqual(documentFromState(createManualState({document:decodeDocumentFile(encodeDocumentFile({document:restored,assets:{}})).document})),candidate);assert.equal(getManualDocumentCovers(restored).length,2);assert.deepEqual(getManualPageGroups(state.doc).map(g=>g.id),getOrderedPageEntries(candidate).map(p=>p.id));const editing=getManualEditingDocument(state);assert.equal(editing.covers.length,2);for(const c of editing.covers)assert.ok(c.blocks.some(b=>b.type==='coverSectionFrame'));}});
test('copy remaps all independent cover roles and metadata IDs while preserving opaque values and physical order',()=>{const source=documentFromState(createManualState({document:fixture()})),copied=copyManualDocument(source);const before=createManualState({document:source}),after=createManualState({document:copied});const old=new Set(ids(before.doc));for(const id of ids(after.doc))assert.equal(old.has(id),false);assert.equal(copied.cover,undefined);assert.equal(copied.covers.length,2);for(let i=0;i<2;i++){assert.deepEqual(copied.covers[i].extensions.vendor,source.covers[i].extensions.vendor);assert.deepEqual(copied.covers[i].metadata[0].value,source.covers[i].metadata[0].value);for(const role of ['title','metadata','divider','sectionTitle'])assert.ok(findManualCoverRole(after,copied.covers[i].id,role));}assert.deepEqual(getOrderedPageEntries(copied).map(x=>getManualDocumentCovers(copied).includes(x)?'cover':'page'),['cover','page','cover']);});
test('public state accepts an additional independent cover transaction; one Undo/Redo keeps existing content exact',()=>{let state=createManualState({document:fixture()}),before=state;const shell=documentToNode({schemaVersion:2,id:'shell',title:'',cover:cover('c3'),pages:[]}).firstChild;const dispatch=tr=>state=state.applyTransaction(tr).state;dispatch(closeHistory(state.tr).insert(state.doc.content.size,shell));assert.equal(getManualDocumentCovers(documentFromState(state)).length,3);assert.deepEqual(documentFromState(state).covers.slice(0,2),documentFromState(before).covers);const after=state;assert.equal(manualCommands.undo(state,dispatch),true);assert.ok(state.doc.eq(before.doc));assert.equal(manualCommands.redo(state,dispatch),true);assert.ok(state.doc.eq(after.doc));ids(state.doc);});
test('pagination of the second cover retains both cover shells and independent family roots',()=>{const data=fixture();data.covers[1].blocks.push(p('c2-extra','Extra body'));let state=createManualState({document:{...data,extensions:{vendor:{keep:true}}}});const headers=state.doc.content.content.filter(n=>n.type.name==='cover').map(n=>({id:n.attrs.id,title:findManualCoverRole(state,n.attrs.id,'title').node}));const records=[];state.doc.forEach(node=>{const parts=manualPaginationPageParts(node);records.push({id:node.attrs.id,capacity:node.attrs.id==='c2'?25:1000,blocks:parts.blocks.map(b=>({id:b.node.attrs.id,height:20}))})});const plan=planManualPagination(state,{doc:state.doc,revision:1,coverFlow:true,pages:records});assert.equal(plan.status,'ready');const tr=createManualPaginationTransaction(state,plan);assert.ok(tr);state=state.applyTransaction(tr).state;for(const h of headers)assert.ok(findManualCoverRole(state,h.id,'title').node.eq(h.title));assert.equal(getManualDocumentCovers(documentFromState(state)).length,2);ids(state.doc);});
test('actual ManualPrint SSR renders every cover once in requested order with independent metadata and role IDs',async()=>{const runtime=new URL('../../../../lk-design-system/',import.meta.url).pathname,require=createRequire(path.join(runtime,'package.json')),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{build}=require('esbuild');const {storybookHost}=await import('../../../scripts/storybook-host.mjs'),host=storybookHost(runtime),dir=await mkdtemp(path.join(os.tmpdir(),'lds-multicover-print-'));try{const out=path.join(dir,'print.cjs');await build({entryPoints:[new URL('../src/redesign/ManualPrint.jsx',import.meta.url).pathname],bundle:true,platform:'node',format:'cjs',outfile:out,jsx:'automatic',loader:{'.css':'empty','.svg':'dataurl'},plugins:[{name:'public-runtime',setup(b){b.onResolve({filter:/^react(?:\/|$)/},args=>({path:require.resolve(args.path),external:true}));b.onResolve({filter:/^@lk-design-system\/lds-theme\/assets\//},args=>({path:path.join(host.theme,args.path.split('/lds-theme/')[1].replace('?url',''))}));b.onResolve({filter:/^@lk-design-system\/lds-core\/components\//},args=>({path:host.publicCoreModule(args.path.split('/components/')[1])}));}}],logLevel:'silent'});const {ManualPrint}=require(out),d=fixture(),html=renderToStaticMarkup(React.createElement(ManualPrint,{document:d,assets:{},onIssues(){}}));for(const c of d.covers){assert.equal(html.split('id="'+c.id+'" data-page-id').length-1,1);assert.ok(html.includes(c.id+' value'));}assert.ok(html.indexOf('id="c2" data-page-id')<html.indexOf('id="page" data-page-id'));assert.ok(html.indexOf('id="page" data-page-id')<html.indexOf('id="c1" data-page-id'));assert.equal((html.match(/data-manual-cover-role="title"/g)||[]).length,2);}finally{await rm(dir,{recursive:true,force:true})}});

test('existing independent covers do not block ordinary-page role conversion and its exact Undo/Redo',()=>{
 const data=fixture();let state=createManualState({document:data});const body=findManualObject(state,'body');state=state.apply(state.tr.setSelection(TextSelection.create(state.doc,body.pos+1)));const before=state,dispatch=tr=>state=state.applyTransaction(tr).state;
 assert.equal(getManualCoverInsertCommandState(state,{role:'divider'}).enabled,true);
 for(const [options,view,reason]of [[{role:'divider',revision:{}},{},'stale'],[{role:'divider'},{editable:false},'read-only'],[{role:'divider'},{composing:true},'composing']])assert.equal(getManualCoverInsertCommandState(state,options,view).reason,reason);
 assert.equal(executeManualCoverInsert('divider')(state,dispatch),true);const after=state,restored=documentFromState(state);assert.equal(getManualDocumentCovers(restored).length,3);for(const c of data.covers)assert.deepEqual(getManualDocumentCovers(restored).find(x=>x.id===c.id),c);assert.deepEqual(getManualDocumentCovers(restored).find(c=>c.id==='page').blocks.find(b=>b.id==='body'),data.pages[0].blocks[0]);assert.ok(findManualCoverRole(state,'page','divider'));assert.deepEqual(getOrderedPageEntries(restored).map(x=>x.id),['c2','page','c1']);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:restored,assets:{}})).document,restored);assert.equal(manualCommands.undo(state,dispatch),true);assert.ok(state.doc.eq(before.doc));assert.equal(manualCommands.redo(state,dispatch),true);assert.ok(state.doc.eq(after.doc));ids(state.doc);
});
