import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {createManualState,documentFromState,findManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {deleteManualToggleTitleBackward} from '../src/redesign/manual-toggle-commands.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const rich=text=>text?[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}]:[];
const paragraph=(id,text='본문')=>({type:'paragraph',id,content:rich(text),extensions:{vendor:{id}}});
function harness({open=true,title='안녕하세요',nested=false}={}){
 const toggle={type:'toggle',id:'toggle',open,title:rich(title),blocks:[paragraph('body')],extensions:{vendor:{keep:[1,2]}}};
 const document={schemaVersion:2,id:'document',title:'Synthetic',cover:{id:'cover',title:[],metadata:[],blocks:[]},pages:[{id:'page',title:rich('제목'),blocks:[paragraph('before'),nested?{type:'toggle',id:'outer',open:true,title:rich('바깥 제목'),blocks:[toggle],extensions:{vendor:{outer:true}}}:toggle,paragraph('after')]}]};
 let state=createManualState({document}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};
 const view={get state(){return state;},dispatch,editable:true,composing:false,endOfTextblock:()=>true,dom:{isConnected:true},props:{}};
 function select(offset){const obj=findManualObject(state,'toggle');dispatch(state.tr.setSelection(TextSelection.create(state.doc,obj.pos+2+offset)));}
 function key(event={},v=view){return state.plugins.some(plugin=>plugin.props.handleKeyDown?.(v,{key:'Backspace',keyCode:8,shiftKey:false,altKey:false,ctrlKey:false,metaKey:false,...event}));}
 return {get state(){return state;},get count(){return count;},get document(){return documentFromState(state);},view,dispatch,select,key,run:command=>command(state,dispatch,view)};
}
function exact(h,before,after){assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.redo),true);assert.ok(h.state.doc.eq(after.doc));assert.ok(h.state.selection.eq(after.selection));}
for(const open of [false,true])for(const nested of [false,true])test(`${open?'expanded':'collapsed'} ${nested?'nested':'direct'} actual keymap deletes Korean title character with exact undo/redo and file reopen`,()=>{
 const h=harness({open,nested});h.select(5);const before=h.state,original=h.document,count=h.count;
 assert.equal(h.key(),true);assert.equal(h.count,count+1);const after=h.state,obj=findManualObject(after,'toggle');
 assert.equal(obj.node.firstChild.textContent,'안녕하세');assert.equal(after.selection.$from.parent.type.name,'toggleTitle');assert.equal(after.selection.$from.parentOffset,4);assert.equal(obj.node.attrs.id,'toggle');assert.deepEqual(obj.node.attrs,before.doc.nodeAt(findManualObject(before,'toggle').pos).attrs);assert.deepEqual(obj.node.firstChild.firstChild.marks,before.selection.$from.parent.firstChild.marks);
 const expected=structuredClone(original),saved=nested?expected.pages[0].blocks[1].blocks[0]:expected.pages[0].blocks[1];saved.title=rich('안녕하세');assert.deepEqual(h.document,expected);
 const reopened=decodeDocumentFile(encodeDocumentFile({document:h.document,assets:{}})).document;assert.deepEqual(documentFromState(createManualState({document:reopened})),expected);exact(h,before,after);
});
for(const title of ['가나다','가나','앞👨‍👩‍👧‍👦','앞é'])test(`title deletion respects grapheme for ${title}`,()=>{const h=harness({title});h.select(title.length);assert.equal(h.key(),true);const expected=[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(title)].slice(0,-1).map(item=>item.segment).join('');assert.equal(findManualObject(h.state,'toggle').node.firstChild.textContent,expected);});
test('all Korean characters can be removed without deleting toggle, body, metadata or title slot',()=>{const h=harness({open:false});h.select(5);const attrs=findManualObject(h.state,'toggle').node.attrs;for(let i=4;i>=0;i--){assert.equal(h.key(),true);assert.equal(h.state.selection.$from.parentOffset,i);}const toggle=findManualObject(h.state,'toggle');assert.deepEqual(toggle.node.attrs,attrs);assert.equal(toggle.node.firstChild.type.name,'toggleTitle');assert.equal(toggle.node.firstChild.content.size,0);assert.equal(findManualObject(h.state,'body').node.textContent,'본문');});
for(const title of ['안녕하세요'])for(const nested of [false,true])test(`title start preserves existing boundary ${JSON.stringify(title)} ${nested}`,()=>{const h=harness({title,nested});h.select(0);const before=h.state;h.key();assert.ok(h.state.doc.eq(before.doc));assert.ok(findManualObject(h.state,'toggle'));});
for(const mode of ['composing','event-composing','ime229','read-only','stale'])test(`${mode} guard does not remove title characters`,()=>{const h=harness();h.select(5);const before=h.state;let v=h.view,event={};if(mode==='composing')v={...v,composing:true};if(mode==='event-composing')event.isComposing=true;if(mode==='ime229')event.keyCode=229;if(mode==='read-only')v={...v,editable:false};if(mode==='stale')v={...v,state:createManualState({document:h.document})};if(mode==='node')h.dispatch(h.state.tr.setSelection(NodeSelection.create(h.state.doc,findManualObject(h.state,'toggle').pos)));h.key(event,v);assert.ok(h.state.doc.eq(before.doc));});
test('title text range keeps ordinary range deletion behavior and marks',()=>{const h=harness();h.select(5);const end=h.state.selection.from;h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,end-2,end)));assert.equal(h.key(),true);assert.equal(findManualObject(h.state,'toggle').node.firstChild.textContent,'안녕하');});

test('title command supports dry-run, stored formatting and middle caret without relying on endOfTextblock',()=>{const h=harness();h.select(3);h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.emphasis.create()]));const before=h.state,count=h.count;assert.equal(deleteManualToggleTitleBackward(before),true);assert.equal(h.state,before);assert.equal(h.count,count);assert.equal(h.key(),true);assert.equal(findManualObject(h.state,'toggle').node.firstChild.textContent,'안녕세요');assert.equal(h.state.selection.$from.parentOffset,2);assert.deepEqual(h.state.storedMarks,before.storedMarks);});
test('title command leaves node selections and ordinary body native deletion to their existing commands',()=>{const h=harness();h.dispatch(h.state.tr.setSelection(NodeSelection.create(h.state.doc,findManualObject(h.state,'toggle').pos)));assert.equal(deleteManualToggleTitleBackward(h.state,h.dispatch,h.view),false);const body=findManualObject(h.state,'body');h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,body.pos+2)));assert.equal(deleteManualToggleTitleBackward(h.state,h.dispatch,h.view),false);});
