import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {undoDepth,redoDepth,closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
const text=s=>[{type:'text',text:s}],paragraph=(id,s)=>({id,type:'paragraph',content:text(s)});
function fixture({divider=false,end=false}={}){return {schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:[],blocks:[paragraph('before','Before'),...(divider?[{id:'preDivider',type:'divider'}]:[]),{id:'table',type:'table',label:'',headers:[{id:'first',content:text('First')},{id:'second',content:text('Second')}],rows:[[{id:'third',content:text('Third')},{id:'last',content:text('Last')}]]},...(divider?[{id:'postDivider',type:'divider'}]:[]),...(end?[]:[paragraph('after','After')])]}]};}
function h(options){let state=createManualState({document:fixture(options)});const transactions=[],dispatch=tr=>{transactions.push(tr);state=state.applyTransaction(tr).state;},view={get state(){return state},dispatch,props:{},dom:{isConnected:true},editable:true,composing:false,endOfTextblock:()=>true};return {get state(){return state},transactions,dispatch,view,select(id,offset=0,to){const found=findManualObject(state,id);dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+1+offset,to===undefined?undefined:found.pos+1+to)));},key(key,patch={}){const event={key,keyCode:key==='ArrowRight'?39:37,preventDefault(){},...patch};return state.plugins.some(plugin=>plugin.props.handleKeyDown?.(view,event));}};}
function unchanged(a,before){assert.equal(a.state.doc,before.doc);assert.deepEqual(documentFromState(a.state),documentFromState(before));assert.deepEqual(a.state.storedMarks,before.storedMarks);assert.equal(undoDepth(a.state),undoDepth(before));assert.equal(redoDepth(a.state),redoDepth(before));}
for(const divider of [false,true])for(const [id,offset,key,target,targetOffset]of [['last',4,'ArrowRight','after',0],['first',0,'ArrowLeft','before',6]])test(`${key} outside table edge ${divider?'skips dividers':'moves to existing text'}`,()=>{const a=h({divider});a.select(id,offset);a.dispatch(a.state.tr.setStoredMarks([a.state.schema.marks.emphasis.create()]));const before=a.state;assert.equal(a.key(key),true);assert.equal(a.state.selection.$from.parent.attrs.id,target);assert.equal(a.state.selection.$from.parentOffset,targetOffset);unchanged(a,before);assert.equal(a.transactions.at(-1).docChanged,false);});
test('last table consumes Right at document end without insertion',()=>{const a=h({end:true});a.select('last',4);const before=a.state,n=a.transactions.length;assert.equal(a.key('ArrowRight'),true);assert.equal(a.state,before);assert.equal(a.transactions.length,n);});
test('first table consumes Left at actual document start without insertion',()=>{const a=h();const table=findManualObject(a.state,'table').node;const page=a.state.doc.firstChild.copy(table.content.constructor.from(table));const doc=a.state.doc.copy(table.content.constructor.from(page));a.dispatch(a.state.tr.replaceWith(0,a.state.doc.content.size,doc.content));a.select('first');const before=a.state,n=a.transactions.length;assert.equal(a.key('ArrowLeft'),true);assert.equal(a.state,before);assert.equal(a.transactions.length,n);});
for(const [id,offset,key]of [['last',2,'ArrowRight'],['first',2,'ArrowLeft'],['second',6,'ArrowRight'],['third',0,'ArrowLeft']])test(`${id} interior/non-edge ${key} remains native`,()=>{const a=h();a.select(id,offset);const before=a.state;assert.equal(a.key(key),false);assert.equal(a.state,before);});
for(const patch of [{shiftKey:true},{ctrlKey:true},{metaKey:true},{altKey:true},{isComposing:true},{keyCode:229}])test(`key modifier/composition ${JSON.stringify(patch)} cannot leave the table`,()=>{const a=h();a.select('last',4);const before=a.state;assert.equal(a.key('ArrowRight',patch),false);assert.equal(a.state,before);});
for(const patch of [{editable:false},{composing:true},{props:{manualTableSelectionEnabled:false}},{props:{manualTableSelectionEnabled:()=>false}}])test(`host guard ${JSON.stringify(patch)} blocks direct public horizontal command`,()=>{const a=h();a.select('last',4);const before=a.state;assert.equal(manualCommands.arrowRight(a.state,a.dispatch,{...a.view,...patch}),false);assert.equal(a.state,before);});
test('range selection remains native and public command does not dispatch',()=>{const a=h();a.select('last',1,4);const before=a.state;assert.equal(a.key('ArrowRight'),false);assert.equal(manualCommands.arrowRight(a.state,a.dispatch,a.view),false);assert.equal(a.state,before);});
test('horizontal exit preserves prior typing as a single undo entry',()=>{const a=h();a.select('last',4);a.dispatch(closeHistory(a.state.tr).insertText('X'));const before=a.state;assert.equal(a.key('ArrowRight'),true);unchanged(a,before);assert.equal(manualCommands.undo(a.state,a.dispatch,a.view),true);assert.equal(findManualObject(a.state,'last').node.textContent,'Last');assert.equal(manualCommands.redo(a.state,a.dispatch,a.view),true);assert.equal(findManualObject(a.state,'last').node.textContent,'LastX');});
