import test from 'node:test';
import assert from 'node:assert/strict';
import {Fragment} from '@tiptap/pm/model';
import {TextSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,manualCommands,manualSchema,findManualObject} from '../src/redesign/manual-kernel.mjs';
import {createEmptyManualDocument} from '../src/redesign/manual-v2.mjs';
import {installManualPaginationRuntime,measureManualPagination} from '../src/redesign/manual-pagination-runtime.mjs';
import {withManualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {manualPaginationPageParts} from '../src/redesign/manual-page-shape.mjs';
function events(){const listeners=new Map();return {addEventListener(type,fn){const set=listeners.get(type)||new Set();set.add(fn);listeners.set(type,set);},removeEventListener(type,fn){listeners.get(type)?.delete(fn);},emit(type){for(const fn of listeners.get(type)||[])fn({type});},count:()=>[...listeners.values()].reduce((sum,set)=>sum+set.size,0)};}
function harness(options={}){
 const d=createEmptyManualDocument();d.pages[0].title=[{type:'text',text:'TITLE'}];d.pages[0].blocks=[{id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'A'}]},{id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:'B'}]}];
 const surface=events(),dom=events(),frames=new Map(),timers=new Map(),results=[];let frameId=0,timerId=0,generation=0,enabled=true,current=null,runtime=null;
 dom.isConnected=true;dom.ownerDocument={defaultView:surface};dom.querySelectorAll=()=>[];
 const editor={dom,editable:true,composing:false,state:createManualState({document:d}),dispatch(tr){this.state=this.state.applyTransaction(tr).state;runtime?.changed(tr);}};current=editor;
 const standardMeasure=(editor,{revision})=>{const pages=[];editor.state.doc.forEach(node=>{if(node.type.name!=='page')return;const blocks=[];node.forEach(block=>{if(!['pageTitle','pageLead'].includes(block.type.name))blocks.push({id:block.attrs.id,height:40});});pages.push({id:node.attrs.id,capacity:100,blocks});});return {doc:editor.state.doc,revision,pages};};
 runtime=installManualPaginationRuntime({editor,getEditor:()=>current,getGeneration:()=>generation,isEnabled:()=>enabled,onResult:result=>results.push(result),surface,requestFrame:callback=>{frames.set(++frameId,callback);return frameId;},cancelFrame:id=>frames.delete(id),setTimer:callback=>{timers.set(++timerId,callback);return timerId;},clearTimer:id=>timers.delete(id),measure:standardMeasure,...options});
 const tick=()=>{const next=frames.entries().next().value;if(!next)return false;frames.delete(next[0]);next[1]();return true;},run=()=>{let count=0;while(tick())assert.ok(++count<20,'bounded scheduler');};
 return {d,editor,runtime,results,surface,dom,frames,timers,tick,run,get generation(){return generation;},set generation(value){generation=value;},set enabled(value){enabled=value;},set current(value){current=value;},get document(){return documentFromState(editor.state);},append(count=1){const at=editor.state.doc.firstChild.nodeSize-1,blocks=Array.from({length:count},()=>manualSchema.nodes.paragraph.create({id:crypto.randomUUID(),meta:{extensions:{keep:true}}}));editor.dispatch(closeHistory(editor.state.tr));const before=editor.state,tr=editor.state.tr.insert(at,Fragment.fromArray(blocks));tr.setSelection(TextSelection.create(tr.doc,at+(count-1)*2+1));editor.dispatch(tr);return {before,tr};}};
}
test('initial measurement never writes a loaded document; user Enter arms one bounded flow and one undo/redo restores all content, IDs and caret',()=>{
 const h=harness();h.append(0);h.runtime.reset();const original=h.editor.state;h.runtime.request();h.run();assert.equal(h.editor.state,original);const {before}=h.append(3);h.run();const after=h.document,selection=h.editor.state.selection;assert.equal(after.pages.length,3);assert.equal(h.runtime.getState().status,'stable');assert.equal(h.runtime.getState().pass,2);assert.ok(h.results.some(result=>result.status==='flowing'));manualCommands.undo(h.editor.state,h.editor.dispatch.bind(h.editor));h.run();assert.deepEqual(h.document,documentFromState(before));assert.ok(h.editor.state.selection.eq(before.selection));manualCommands.redo(h.editor.state,h.editor.dispatch.bind(h.editor));h.run();assert.deepEqual(h.document,after);assert.ok(h.editor.state.selection.eq(selection));h.runtime.dispose();
});
test('initial normalization paginates immediately without adding undo history, and identifies its stable baseline for the UI storage gate',()=>{
 const h=harness(),document=structuredClone(h.d);document.pages[0].blocks.push(...Array.from({length:4},(_,index)=>({id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:`loaded ${index}`}]})));h.editor.state=createManualState({document});h.runtime.normalize();assert.equal(h.runtime.getState().normalizing,true);h.run();assert.equal(h.document.pages.length,3);assert.equal(h.runtime.getState().normalizing,false);assert.equal(h.results.at(-1).origin,'initial');assert.equal(h.results.at(-1).status,'stable');assert.deepEqual(h.document.pages.flatMap(page=>page.blocks),document.pages[0].blocks);assert.equal(manualCommands.undo(h.editor.state,h.editor.dispatch.bind(h.editor)),false);h.runtime.dispose();
});
test('flow keeps the user caret visible without scrolling initial normalization or later layout reflow',()=>{
 const capture=h=>{const transactions=[],dispatch=h.editor.dispatch.bind(h.editor);h.editor.dispatch=tr=>{transactions.push(tr);dispatch(tr);};return transactions;};
 const user=harness(),userTransactions=capture(user),{before}=user.append(3);user.run();const after=user.document,selection=user.editor.state.selection,flows=userTransactions.filter(tr=>tr.getMeta('manualPagination'));assert.equal(flows.length,2);assert.ok(flows.every(tr=>tr.scrolledIntoView&&tr.getMeta('manualPagination').origin==='user'));manualCommands.undo(user.editor.state,user.editor.dispatch.bind(user.editor));user.run();assert.deepEqual(user.document,documentFromState(before));manualCommands.redo(user.editor.state,user.editor.dispatch.bind(user.editor));user.run();assert.deepEqual(user.document,after);assert.ok(user.editor.state.selection.eq(selection));user.runtime.dispose();
 const initial=harness(),initialTransactions=capture(initial);initial.append(3);initial.runtime.normalize();initial.run();const initialFlows=initialTransactions.filter(tr=>tr.getMeta('manualPagination'));assert.equal(initialFlows.length,2);assert.ok(initialFlows.every(tr=>!tr.scrolledIntoView&&tr.getMeta('manualPagination').origin==='initial'));initial.runtime.dispose();
 let capacity=100;const layout=harness({measure(editor,{revision}){const pages=[];editor.state.doc.forEach((page,pos)=>{const blocks=manualPaginationPageParts(page,pos).blocks.map(({node:block})=>({id:block.attrs.id,height:40}));pages.push({id:page.attrs.id,capacity,blocks});});return {doc:editor.state.doc,revision,pages};}}),layoutTransactions=capture(layout);layout.runtime.normalize();layout.run();capacity=40;layout.runtime.request();layout.run();const layoutFlows=layoutTransactions.filter(tr=>tr.getMeta('manualPagination'));assert.equal(layoutFlows.length,1);assert.equal(layout.document.pages.length,2);assert.ok(layoutFlows.every(tr=>!tr.scrolledIntoView&&tr.getMeta('manualPagination').origin==='layout'));layout.runtime.dispose();
});
test('composing input waits for composition completion, then measures a fresh doc without busy polling',()=>{
 const h=harness();h.editor.composing=true;h.append();h.run();assert.equal(h.document.pages.length,1);assert.equal(h.runtime.getState().status,'composing');assert.equal(h.frames.size,0);h.dom.emit('compositionend');assert.equal(h.timers.size,1);h.editor.composing=false;for(const [id,fn]of h.timers){h.timers.delete(id);fn();}h.run();assert.equal(h.document.pages.length,2);assert.equal(h.runtime.getState().status,'stable');h.runtime.dispose();
});
test('replacement generations and old editors invalidate a scheduled flow; a fresh edit resets its epoch',()=>{
 const h=harness();h.append();const state=h.editor.state;h.generation++;h.run();assert.equal(h.editor.state,state);assert.equal(h.runtime.getState().status,'stale');h.append();h.run();assert.equal(h.document.pages.length,2);h.runtime.request();h.current={};const latest=h.editor.state;h.run();assert.equal(h.editor.state,latest);assert.equal(h.runtime.getState().status,'stale');h.runtime.dispose();
});
test('busy/printing gates retain the input history source and resume only on an explicit request',()=>{
 const h=harness();h.enabled=false;h.append();h.run();assert.equal(h.runtime.getState().status,'paused');assert.equal(h.document.pages.length,1);h.enabled=true;h.runtime.request();h.run();assert.equal(h.document.pages.length,2);h.runtime.dispose();
});
test('font and image waits are event driven and stop callbacks from disposed runtimes',async()=>{
 const h=harness();let resolve;h.dom.ownerDocument.fonts={status:'loading',ready:new Promise(done=>resolve=done)};h.append();h.run();assert.equal(h.runtime.getState().status,'waiting-fonts');assert.equal(h.frames.size,0);h.dom.ownerDocument.fonts.status='loaded';resolve();await Promise.resolve();h.dom.querySelectorAll=()=>[{complete:false}];h.run();assert.equal(h.runtime.getState().status,'waiting-images');h.dom.querySelectorAll=()=>[{complete:true}];h.dom.emit('load');h.run();assert.equal(h.document.pages.length,2);h.runtime.dispose();assert.equal(h.dom.count(),0);assert.equal(h.surface.count(),0);h.dom.emit('load');h.surface.emit('resize');assert.equal(h.frames.size,0);
});
test('a stale measurement is discarded before applying a plan',()=>{
 let changed=false;const h=harness({measure(editor,{revision}){const doc=editor.state.doc,pages=[];doc.forEach((page,pos)=>{const blocks=manualPaginationPageParts(page,pos).blocks.map(({node:block})=>({id:block.attrs.id,height:40}));pages.push({id:page.attrs.id,capacity:100,blocks});});if(!changed){changed=true;editor.dispatch(editor.state.tr.insertText('x',findManualObject(editor.state,documentFromState(editor.state).pages[0].blocks[0].id).pos+1));}return {doc,revision,pages};}});h.append();h.tick();assert.equal(h.document.pages.length,1);h.run();assert.equal(h.document.pages.length,2);h.runtime.dispose();
});
test('bounded passes stop an unfinished overflow rather than creating unlimited auto pages',()=>{
 const h=harness({maxPasses:1});h.append(5);h.run();assert.equal(h.runtime.getState().status,'limit');assert.equal(h.document.pages.length,2);assert.equal(h.frames.size,0);assert.ok(h.results.at(-1).diagnostics.some(item=>item.reason==='pass-limit'));h.runtime.dispose();
});
for(const action of ['title','remove-empty'])test(`distinct continuation targets allow repeated ${action} actions without a false progress collision`,()=>{
 const h=harness({measure(editor,{revision}){const pages=[];editor.state.doc.forEach((page,pos)=>{const blocks=manualPaginationPageParts(page,pos).blocks.map(({node:block})=>({id:block.attrs.id,height:80}));pages.push({id:page.attrs.id,capacity:100,blocks});});return {doc:editor.state.doc,revision,pages};}}),d=structuredClone(h.d),root=d.pages[0];root.title=[{type:'text',text:'NEW'}];root.blocks=root.blocks.slice(0,1);
 for(let i=0;i<2;i++)d.pages.push({id:crypto.randomUUID(),title:[{type:'text',text:action==='title'?'OLD':'NEW'}],blocks:action==='title'?[{id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text:String(i)}]}]:[],extensions:withManualPaginationMarker({},{kind:'page',rootPageId:root.id}).extensions});h.editor.state=createManualState({document:d});h.runtime.normalize();h.run();assert.equal(h.runtime.getState().status,'stable');assert.equal(h.runtime.getState().pass,2);assert.deepEqual(h.results.filter(r=>r.action).map(r=>r.action.type),[action,action]);assert.equal(h.document.pages.length,action==='title'?3:1);assert.ok(h.document.pages.every(page=>page.title[0].text==='NEW'));assert.deepEqual(h.document.pages[0],root);assert.equal(manualCommands.undo(h.editor.state,h.editor.dispatch.bind(h.editor)),false);h.runtime.dispose();
});
test('a fully fitting document at the pass boundary is stable rather than falsely reported as unfinished',()=>{
 const h=harness({maxPasses:1});h.append(1);h.run();assert.equal(h.runtime.getState().pass,1);assert.equal(h.runtime.getState().status,'stable');assert.equal(h.document.pages.length,2);assert.ok(h.document.pages.every(page=>page.blocks.length<=2));assert.deepEqual(h.results.filter(r=>r.action).map(r=>r.action.type),['push']);assert.equal(h.frames.size,0);h.runtime.dispose();
});
test('contradictory geometry is stopped by the progress guard without dropping original content',()=>{
 const h=harness({measure(editor,{revision}){const count=editor.state.doc.childCount,pages=[];editor.state.doc.forEach((page,pos)=>{const blocks=manualPaginationPageParts(page,pos).blocks.map(({node:block})=>({id:block.attrs.id,height:count===1?80:20}));pages.push({id:page.attrs.id,capacity:100,blocks});});return {doc:editor.state.doc,revision,pages};}});h.append(1);h.run();assert.equal(h.runtime.getState().status,'limit');assert.ok(h.results.at(-1).diagnostics.some(item=>item.reason==='no-progress'));assert.equal(h.document.pages.flatMap(page=>page.blocks).length,3);h.runtime.dispose();
});
test('measuring canonical page coordinates normalizes CSS scaling and spacing without mutating the editor',()=>{
 const d=createEmptyManualDocument();d.pages[0].title=[{type:'text',text:'TITLE'}];d.pages[0].blocks=[{id:'a',type:'paragraph',content:[]},{id:'b',type:'paragraph',content:[]}];const state=createManualState({document:d}),rect=(top,height)=>({top,bottom:top+height,width:200,height}),document={defaultView:{getComputedStyle:()=>({marginBottom:'5px',width:'100px'})}},content={getBoundingClientRect:()=>rect(0,200)},page={offsetWidth:100,ownerDocument:document,getBoundingClientRect:()=>rect(0,200),querySelector:()=>content},header={getBoundingClientRect:()=>rect(0,20)},a={ownerDocument:document,getBoundingClientRect:()=>rect(20,60)},b={ownerDocument:document,getBoundingClientRect:()=>rect(100,60)},positions=new Map([[0,page],[1,header],[findManualObject(state,'a').pos,a],[findManualObject(state,'b').pos,b]]),editor={state,dom:{isConnected:true,ownerDocument:document},nodeDOM:pos=>positions.get(pos)};
 const measured=measureManualPagination(editor,{revision:3});assert.equal(measured.doc,state.doc);assert.equal(measured.revision,3);assert.equal(measured.pages[0].capacity,90);assert.deepEqual(measured.pages[0].blocks,[{id:'a',height:40},{id:'b',height:35}]);assert.equal(editor.state,state);
});
function joinGeometry(h,{paragraphHeight=()=>44,calloutHeight=()=>28}={}){
 const rect=(top,height)=>({top,bottom:top+height,width:100,height});let activeProbes=0;
 const document={defaultView:h.surface};h.surface.getComputedStyle=element=>({marginBottom:`${element.marginBottom||0}px`,width:'100px'});
 class Element{
  constructor(kind,height=0,top=null){this.kind=kind;this.height=height;this.top=top;this.marginBottom=kind==='callout'?16:kind==='paragraph'?12:0;this.marginTop=kind==='callout'?16:0;this.ownerDocument=document;this.style={};this.children=[];this.offsetWidth=100;}
  setAttribute(){}removeAttribute(){}querySelectorAll(){return [];}querySelector(){return this.children.find(child=>child.kind==='content');}
  replaceChildren(...children){this.children=children;children.forEach(child=>child.parentElement=this);}append(child){this.children.push(child);child.parentElement=this;}remove(){if(this.attached){activeProbes--;this.attached=false;}}
  cloneNode(deep){const copy=new Element(this.kind,this.height);if(deep)copy.replaceChildren(...this.children.map(child=>child.cloneNode(true)));return copy;}
  getBoundingClientRect(){
   if(this.top!==null)return rect(this.top,this.height);if(this.kind==='paper')return rect(0,200);if(this.kind==='content')return rect(0,136);if(this.kind==='title')return rect(0,20);
   let y=20,previous=0,index=0;for(const child of this.parentElement.children){if(child.kind==='title')continue;const top=y+(index++===0?16+child.marginTop:Math.max(previous,child.marginTop));if(child===this)return rect(top,child.height);y=top+child.height;previous=child.marginBottom;}throw new Error('Missing probe child');
  }
 }
 document.createElement=()=>new Element('host');h.dom.ownerDocument=document;h.dom.parentElement={append(host){host.attached=true;activeProbes++;}};
 const measure=(editor,options)=>{
  const positions=new Map();editor.state.doc.forEach((page,pos)=>{
   const paper=new Element('paper',200,0),content=new Element('content',136,0),title=new Element('title',20,0);paper.replaceChildren(content);content.replaceChildren(title);positions.set(pos,paper);positions.set(pos+1,title);let y=20,previous=0;
   page.forEach((block,offset,index)=>{if(index===0)return;const kind=block.type.name,height=kind==='callout'?calloutHeight():paragraphHeight(),element=new Element(kind,height),top=y+(index===1?16+element.marginTop:Math.max(previous,element.marginTop));element.top=top;content.append(element);const at=pos+1+offset;positions.set(at,element);block.descendants((child,childPos)=>positions.set(at+1+childPos,new Element(child.type.name,10,top+4)));y=top+height;previous=element.marginBottom;});
  });editor.nodeDOM=pos=>positions.get(pos);return measureManualPagination(editor,options);
 };return {measure,get activeProbes(){return activeProbes;}};
}
test('actual join measurement prevents paragraph/callout margin collapse from cycling between push and pull, then permits fitting backfill',()=>{
 let paragraphHeight=44;const h=harness(),first={id:'before-callout',type:'paragraph',content:[]},callout={id:'callout',type:'callout',tone:'signal',title:[],blocks:[{id:'inner',type:'paragraph',content:[]}]};h.d.pages[0].title=[];h.d.pages[0].blocks=[first,callout];h.editor.state=createManualState({document:h.d});h.runtime.dispose();const geometry=joinGeometry(h,{paragraphHeight:()=>paragraphHeight}),results=[];h.runtime=installManualPaginationRuntime({editor:h.editor,surface:h.surface,measure:geometry.measure,onResult:r=>results.push(r),requestFrame:fn=>{h.frames.set(1,fn);return 1;},cancelFrame:id=>h.frames.delete(id)});h.runtime.normalize();h.run();assert.equal(h.runtime.getState().status,'stable');assert.equal(h.document.pages.length,2);assert.deepEqual(h.document.pages.flatMap(page=>page.blocks),[first,callout]);assert.deepEqual(results.filter(r=>r.action).map(r=>r.action.type),['push']);assert.equal(geometry.measure(h.editor,{revision:1}).pages[0].pullGap,4);assert.equal(geometry.activeProbes,0);
 paragraphHeight=40;h.runtime.request();h.run();assert.equal(h.runtime.getState().status,'stable');assert.equal(h.document.pages.length,1);assert.deepEqual(h.document.pages[0].blocks,[first,callout]);assert.equal(geometry.activeProbes,0);h.runtime.dispose();
});
test('an empty earlier page measures title-to-first-block spacing before backfill instead of repeatedly pulling an oversized callout',()=>{
 const h=harness(),callout={id:'callout',type:'callout',tone:'signal',title:[],blocks:[{id:'inner',type:'paragraph',content:[]}]};h.d.pages[0].title=[];h.d.pages[0].blocks=[];h.d.pages.push({id:'continuation',title:[],blocks:[callout],extensions:withManualPaginationMarker({},{kind:'page',rootPageId:h.d.pages[0].id}).extensions});h.editor.state=createManualState({document:h.d});h.runtime.dispose();const geometry=joinGeometry(h,{calloutHeight:()=>70}),before=h.editor.state,measurement=geometry.measure(h.editor,{revision:1});assert.equal(measurement.pages[0].capacity,116);assert.equal(measurement.pages[0].pullGap,32);assert.equal(h.editor.state,before);assert.equal(geometry.activeProbes,0);h.runtime=installManualPaginationRuntime({editor:h.editor,surface:h.surface,measure:geometry.measure,requestFrame:fn=>{h.frames.set(1,fn);return 1;},cancelFrame:id=>h.frames.delete(id)});h.runtime.normalize();h.run();assert.equal(h.runtime.getState().status,'blocked');assert.equal(h.document.pages.length,2);assert.deepEqual(h.document.pages[1].blocks,[callout]);assert.equal(h.runtime.getState().pass,0);assert.equal(geometry.activeProbes,0);h.runtime.dispose();
});
