import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {createManualState,findManualObject,documentFromState,manualCommands,updateManualObject} from '../src/redesign/manual-kernel.mjs';
import {createManualTodoNodeView} from '../src/redesign/manual-todo-view.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.listeners={};}append(...nodes){this.children.push(...nodes);}contains(node){return node===this||this.children.some(child=>child.contains(node));}setAttribute(key,value){this.attrs[key]=value;}addEventListener(key,fn){this.listeners[key]=fn;}}
const owner={createElement:tag=>new Element(tag)};
function harness(checked=false){
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:[{type:'todo',id:'todo',checked,content:[{type:'text',text:'안녕하세요',marks:[{type:'strong'}]}],extensions:{vendor:{keep:true}}},{type:'paragraph',id:'body',content:[]}]}]}}),count=0;
 const dispatch=tr=>{state=state.applyTransaction(tr).state;count++;},editor={get state(){return state;},dispatch,editable:true,composing:false,dom:{isConnected:true},props:{},endOfTextblock:()=>true};
 const found=findManualObject(state,'todo');dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+6)));const nv=createManualTodoNodeView(found.node,editor,owner);nv.dom.isConnected=true;const checkbox=nv.dom.children[0];
 return {get state(){return state;},get count(){return count;},editor,nv,checkbox,dispatch,event:extra=>({type:'change',defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...extra}),change(event){checkbox.checked=!checkbox.checked;checkbox.listeners.change(event);},run:fn=>fn(state,dispatch,editor)};
}
for(const checked of [false,true])for(const pending of ['figure','table','outline','margin'])test(`pending ${pending} restores native checkbox ${checked} and blocks real PM update`,()=>{const h=harness(checked),before=h.state,count=h.count,event=h.event();let called=0;h.editor.props.manualTableSelectionGestureBlocked=(view,e)=>{called++;assert.equal(view,h.editor);assert.equal(e,event);return true;};h.change(event);assert.equal(called,1);assert.ok(h.state===before);assert.equal(h.count,count);assert.equal(h.checkbox.checked,checked);assert.equal(h.nv.dom.dataset.checked,String(checked));assert.equal(event.defaultPrevented,true);});
for(const mode of ['readonly','view-composing','detached','boolean-guard','removed','retyped'])test(`${mode} restores native checkbox without transaction`,()=>{const h=harness();if(mode==='readonly')h.editor.editable=false;if(mode==='view-composing')h.editor.composing=true;if(mode==='detached')h.nv.dom.isConnected=false;if(mode==='boolean-guard')h.editor.props.manualTableSelectionGestureBlocked=true;if(mode==='removed'||mode==='retyped'){const found=findManualObject(h.state,'todo');h.dispatch(mode==='removed'?h.state.tr.delete(found.pos,found.pos+found.node.nodeSize):h.state.tr.setNodeMarkup(found.pos,h.state.schema.nodes.paragraph,{id:'todo',meta:{}}));}const before=h.state,count=h.count;h.change(h.event());assert.ok(h.state===before);assert.equal(h.count,count);assert.equal(h.checkbox.checked,false);});
for(const [label,event]of [['prevented',{defaultPrevented:true}],['IME',{isComposing:true}],['229',{keyCode:229}]])test(`${label} checkbox event restores native visual value`,()=>{const h=harness(),before=h.state;h.change(h.event(event));assert.ok(h.state===before);assert.equal(h.checkbox.checked,false);});
test('blocked stale NodeView restores latest actual checkbox state',()=>{const h=harness();h.run(updateManualObject('todo',{checked:true}));h.editor.props.manualTableSelectionGestureBlocked=()=>true;h.checkbox.checked=false;h.checkbox.listeners.change(h.event());assert.equal(h.checkbox.checked,true);assert.equal(h.nv.dom.dataset.checked,'true');assert.equal(findManualObject(h.state,'todo').node.attrs.meta.checked,true);});
for(const detail of [0,1])test(`normal ${detail?'click':'keyboard'} checkbox activation keeps marks, metadata, caret and exact UndoRedo/reopen`,()=>{const h=harness(),before=h.state,count=h.count;h.editor.props.manualTableSelectionGestureBlocked=()=>false;h.change(h.event({detail}));assert.equal(h.count,count+1);const after=h.state,old=findManualObject(before,'todo').node,node=findManualObject(after,'todo').node;assert.equal(node.attrs.meta.checked,true);assert.ok(node.content.eq(old.content));assert.deepEqual(node.attrs.meta.extensions,old.attrs.meta.extensions);assert.ok(after.selection.eq(before.selection));assert.equal(h.nv.update(node),true);assert.equal(h.checkbox.checked,true);assert.equal(h.nv.dom.dataset.checked,'true');const out=documentFromState(after);assert.deepEqual(documentFromState(createManualState({document:decodeDocumentFile(encodeDocumentFile({document:out,assets:{}})).document})),out);assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.redo),true);assert.ok(h.state.doc.eq(after.doc));assert.ok(h.state.selection.eq(after.selection));});
test('todo contentDOM forwards editable text mutation and key events',()=>{const h=harness(),text=owner.createElement('span');h.nv.contentDOM.append(text);assert.equal(h.nv.contentDOM.contentEditable,undefined);assert.equal(h.nv.stopEvent({target:text}),false);assert.equal(h.nv.stopEvent({target:h.checkbox}),true);assert.equal(h.nv.ignoreMutation({type:'characterData',target:text}),false);assert.equal(h.nv.ignoreMutation({type:'selection',target:h.checkbox}),false);});

test('native change Event has no mouse modifiers and still respects pending gesture rollback',()=>{const h=harness(),before=h.state;h.editor.props.manualTableSelectionGestureBlocked=()=>true;const event=new Event('change');assert.equal(event.ctrlKey,undefined);assert.equal(event.button,undefined);h.change(event);assert.ok(h.state===before);assert.equal(h.checkbox.checked,false);});
test('normal native change Event remains supported',()=>{const h=harness();h.change(new Event('change'));assert.equal(findManualObject(h.state,'todo').node.attrs.meta.checked,true);});
