import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,findManualPageRole,selectManualObject,moveManualObject,getManualCoverInsertCommandState,executeManualCoverInsert,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {manualPaginationPageParts,manualPageRole} from '../src/redesign/manual-page-shape.mjs';
import {planManualPagination,createManualPaginationTransaction} from '../src/redesign/manual-pagination.mjs';
import {manualPaginationMarker,withManualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {getManualPageGroups} from '../src/redesign/manual-page-groups.mjs';
import {getOrderedPageEntries} from '../src/redesign/manual-page-order.mjs';
import {readManualCoverFlowProvenance} from '../src/redesign/manual-cover-flow-provenance.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const inline=text=>text?[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}]:[];
const paragraph=(id,text='')=>({id,type:'paragraph',content:inline(text)});
function fixture({tail=false,block=paragraph('source','AAAABBBBCCCC'),title=''}={}){const doc={schemaVersion:2,id:'doc',title:'Synthetic',extensions:{vendor:{keep:'doc'}},pages:[{id:'before',title:[],blocks:[paragraph('before-body')]},{id:'root',title:inline(title),blocks:[block],extensions:{vendor:{root:true}}},{id:'last',title:[],blocks:[paragraph('last-body')]}]};if(tail)doc.pages.splice(2,0,{id:'tail',title:inline(title),blocks:[{...paragraph('fragment','DDDDEEEE'),...withManualPaginationMarker({}, {kind:'block',rootBlockId:'source',sourceType:'paragraph'})}],...withManualPaginationMarker({extensions:{vendor:{tail:true}}},{kind:'page',rootPageId:'root'})});return doc;}
function h(document=fixture()){let state=createManualState({document}),count=0,last=null;const dispatch=tr=>{last=tr;count++;state=state.applyTransaction(tr).state;};return {get state(){return state;},get count(){return count;},get last(){return last;},get document(){return documentFromState(state);},dispatch,run:command=>command(state,dispatch),select(id){return this.run(selectManualObject(id));},boundary(){dispatch(closeHistory(state.tr));}};}
function exact(a){const d=a.document;assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const ids=new Set([a.state.doc.attrs.meta.id]);a.state.doc.descendants(node=>{if(node.attrs.id){assert.equal(ids.has(node.attrs.id),false);ids.add(node.attrs.id);}});return d;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
function insert(a,role='divider',target='source'){a.select(target);a.boundary();const before=a.state;assert.equal(a.run(executeManualCoverInsert(role,role==='logo'?{logoVariantId:'logo-inline-navy'}:{})),true);return before;}
function measurement(a,capacity=30,overrides={}){const pages=[];a.state.doc.forEach((node,pos)=>{const parts=manualPaginationPageParts(node,pos);pages.push({id:node.attrs.id,capacity:node.attrs.id==='root'?capacity:100,blocks:parts.blocks.map(({node:child})=>({id:child.attrs.id,height:child.type.name==='paragraph'?child.content.size*5:0,...overrides[child.attrs.id]}))});});return {doc:a.state.doc,coverFlow:true,revision:1,pages};}
function flow(a,m,options={}){const plan=planManualPagination(a.state,m);assert.equal(plan.status,'ready',JSON.stringify(plan.diagnostics));const tr=createManualPaginationTransaction(a.state,plan,options);assert.ok(tr,JSON.stringify(plan.action));a.dispatch(tr);return plan;}

test('all five elements convert a valid paginated root from its tail with same root ID/order and retained body/tail metadata',()=>{
 for(const role of ['logo','title','metadata','divider','sectionTitle']){const a=h(fixture({tail:true,title:'Authored'})),tailTitle=findManualPageRole(a.state,'tail','title'),before=insert(a,role,'fragment');assert.equal(getManualPageGroups(a.state.doc)[1].kind,'cover');assert.deepEqual(getManualPageGroups(a.state.doc)[1].pageIds,['root','tail']);assert.equal(a.state.doc.childCount,4);const d=exact(a);assert.deepEqual(getOrderedPageEntries(d).map(page=>page.id),['before','root','tail','last']);assert.equal(d.cover.id,'root');assert.equal(findManualObject(a.state,'source').node.textContent,'AAAABBBBCCCC');assert.equal(findManualObject(a.state,'fragment').node.textContent,'DDDDEEEE');assert.deepEqual(d.pages.find(page=>page.id==='tail').extensions.vendor,{tail:true});assert.equal(manualPaginationMarker(d.pages.find(page=>page.id==='tail').extensions,'page').rootPageId,'root');const history=readManualCoverFlowProvenance(d.cover.extensions);assert.equal(history.coverId,'root');assert.ok(history.records.some(record=>record.id===tailTitle.node.attrs.id));const repeated=findManualPageRole(a.state,'tail','title');assert.equal(!!repeated,role==='title');if(repeated){assert.equal(manualPageRole(repeated.node).derivedFrom,'root');assert.equal(repeated.node.textContent,'');}undoRedo(a,before);}
});

test('cover text split creates an ordinary A4 continuation and preserves exact moved caret and inline marks',()=>{
 const a=h();insert(a);const source=findManualObject(a.state,'source');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,source.pos+9)));a.boundary();const before=a.state;const plan=flow(a,measurement(a,30,{source:{splits:[{kind:'text',at:6,headHeight:30,tailHeight:30}]}}));assert.equal(plan.action.type,'push');const group=getManualPageGroups(a.state.doc)[1];assert.equal(group.kind,'cover');assert.equal(group.pageIds.length,2);const tail=findManualObject(a.state,group.pageIds[1]);assert.equal(tail.node.type.name,'page');const fragment=tail.node.lastChild;assert.equal(fragment.textContent,'BBCCCC');assert.equal(findManualObject(a.state,'source').node.textContent,'AAAABB');assert.equal(manualPaginationMarker(fragment.attrs.meta.extensions,'block').rootBlockId,'source');assert.equal(a.state.selection.$from.parent.attrs.id,fragment.attrs.id);assert.equal(a.state.selection.$from.parentOffset,2);assert.deepEqual(fragment.firstChild.marks.map(mark=>mark.type.name),['strong','underline']);exact(a);undoRedo(a,before);
});

test('user cover conversion and appended automatic flow undo together to the original physical topology and selection',()=>{
 const a=h(),source=findManualObject(a.state,'source');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,source.pos+9)));a.boundary();const before=a.state;assert.equal(a.run(executeManualCoverInsert('metadata')),true);const event=a.last,plan=planManualPagination(a.state,measurement(a,30,{source:{splits:[{kind:'text',at:6,headHeight:30,tailHeight:30}]}}));assert.equal(plan.status,'ready');const tr=createManualPaginationTransaction(a.state,plan,{historyTransaction:event});assert.ok(tr);tr.setTime(event.time+1000);a.dispatch(tr);assert.equal(a.state.doc.childCount,4);assert.equal(getManualPageGroups(a.state.doc)[1].kind,'cover');exact(a);undoRedo(a,before);
});

test('cover pull merges logical text and records removed derived IDs and opaque tail metadata without registering historical IDs',()=>{
 const a=h(fixture({tail:true}));insert(a);const fragment=findManualObject(a.state,'fragment');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,fragment.pos+3)));a.boundary();const before=a.state;flow(a,measurement(a,200));assert.equal(findManualObject(a.state,'tail'),null);assert.equal(findManualObject(a.state,'fragment'),null);const source=findManualObject(a.state,'source');assert.equal(source.node.textContent,'AAAABBBBCCCCDDDDEEEE');assert.equal(a.state.selection.$from.parent.attrs.id,'source');assert.equal(a.state.selection.$from.parentOffset,14);const d=exact(a),history=readManualCoverFlowProvenance(d.cover.extensions);assert.ok(history.records.some(record=>record.id==='tail'&&record.attrs.meta.extensions.vendor.tail===true));assert.ok(history.records.some(record=>record.id==='fragment'));assert.deepEqual(getManualPageGroups(a.state.doc)[1].pageIds,['root']);undoRedo(a,before);
});

test('list, procedure and table fragments flow to ordinary pages and merge while preserving authored child IDs and repeated header provenance',()=>{
 const blocks=[{id:'source',type:'list',ordered:false,items:[1,2,3].map(n=>({id:`item-${n}`,blocks:[paragraph(`item-body-${n}`,String(n))]}))},{id:'source',type:'procedure',start:1,steps:[1,2,3].map(n=>({id:`step-${n}`,title:[],blocks:[paragraph(`step-body-${n}`,String(n))]}))},{id:'source',type:'table',label:'',headers:[{id:'header-a',content:inline('A')},{id:'header-b',content:inline('B')}],rows:[1,2,3].map(n=>[{id:`cell-${n}-a`,content:inline(String(n)),extensions:{vendor:{cell:n}}},{id:`cell-${n}-b`,content:[]}])}];
 for(const block of blocks){const a=h(fixture({block}));insert(a);const beforeIds=[];findManualObject(a.state,'source').node.descendants(node=>{if(node.attrs.id)beforeIds.push(node.attrs.id);});const pushed=flow(a,measurement(a,40,{source:{height:60,splits:[{kind:'child',at:2,headHeight:40,tailHeight:20}]}}));assert.equal(pushed.action.type,'push');const group=getManualPageGroups(a.state.doc)[1];assert.equal(group.pageIds.length,2);const right=findManualObject(a.state,group.pageIds[1]).node.lastChild,derivedId=right.attrs.id;assert.equal(manualPaginationMarker(right.attrs.meta.extensions,'block').rootBlockId,'source');for(const id of beforeIds)assert.ok(findManualObject(a.state,id));exact(a);const m=measurement(a,200,{source:{height:40},[derivedId]:{height:20}});flow(a,m);assert.equal(findManualObject(a.state,derivedId),null);for(const id of beforeIds)assert.ok(findManualObject(a.state,id));const d=exact(a);assert.ok(readManualCoverFlowProvenance(d.cover.extensions).records.some(record=>record.id===derivedId));if(block.type==='table')assert.deepEqual(d.cover.blocks.find(value=>value.id==='source').rows,block.rows);}
});

test('continuation title synchronization is derived from the cover and preserves its bound title and divider',()=>{
 const a=h(fixture({tail:true}));insert(a);a.select('fragment');assert.equal(a.run(executeManualCoverInsert('title')),true);const title=findManualCoverRole(a.state,'root','title');a.dispatch(a.state.tr.insertText('Cover title',title.pos+1));const plan=flow(a,measurement(a,60));assert.equal(plan.action.type,'title');const repeated=findManualPageRole(a.state,'tail','title');assert.equal(repeated.node.textContent,'Cover title');assert.equal(manualPageRole(repeated.node).derivedFrom,'root');assert.equal(findManualCoverRole(a.state,'root','title').node.attrs.id,title.node.attrs.id);assert.equal(findManualCoverRole(a.state,'root','divider').parent.type.name,'cover');exact(a);
});

test('fixed cover roles moved into the body remain on the authored cover while ordinary text flows across A4 boundaries',()=>{
 for(const role of ['logo','title','metadata','divider','sectionTitle']){const a=h();insert(a,role);const found=findManualCoverRole(a.state,'root',role),id=found.node.attrs.id,body=manualPaginationPageParts(findManualObject(a.state,'root').node).body;assert.equal(a.run(moveManualObject(id,{parentId:'root',index:body.node.childCount})),true);const shape=manualPaginationPageParts(findManualObject(a.state,'root').node);assert.ok(shape.bodyHeaders.some(entry=>entry.node.attrs.id===id));assert.equal(shape.blocks.some(entry=>entry.node.attrs.id===id),false);const content=findManualObject(a.state,id).node;flow(a,measurement(a,30,{source:{splits:[{kind:'text',at:6,headHeight:30,tailHeight:30}]}}));assert.ok(findManualCoverRole(a.state,'root',role).node.eq(content));assert.equal(findManualCoverRole(a.state,'root',role).parent.type.name,'coverBody');assert.equal(getManualPageGroups(a.state.doc)[1].pageIds.length,2);exact(a);}
});

test('file copies remap current cover, tail, fragment and physical order references while keeping provenance historical and independent',()=>{
 const a=h(fixture({tail:true,title:'Original'}));insert(a,'metadata','fragment');const original=exact(a),copy=copyManualDocument(original),state=createManualState({document:copy}),restored=documentFromState(state),root=copy.cover.id,tail=copy.pages.find(page=>manualPaginationMarker(page.extensions,'page'));
 assert.notEqual(root,'root');assert.notEqual(tail.id,'tail');assert.equal(manualPaginationMarker(tail.extensions,'page').rootPageId,root);const source=copy.cover.blocks.find(block=>block.type==='paragraph'),fragment=tail.blocks[0];assert.notEqual(source.id,'source');assert.notEqual(fragment.id,'fragment');assert.equal(manualPaginationMarker(fragment.extensions,'block').rootBlockId,source.id);assert.deepEqual(getManualPageGroups(state.doc)[1].pageIds,[root,tail.id]);assert.equal(readManualCoverFlowProvenance(restored.cover.extensions).coverId,root);assert.deepEqual(readManualCoverFlowProvenance(restored.cover.extensions).records,readManualCoverFlowProvenance(original.cover.extensions).records);assert.deepEqual(documentFromState(createManualState({document:restored})),restored);assert.deepEqual(getOrderedPageEntries(copy).map(page=>page.id),[copy.pages[0].id,root,tail.id,copy.pages.at(-1).id]);
});

test('nonconsecutive/orphan fragments and stale measurement are rejected without mutation or false cover creation',()=>{
 const source=fixture({tail:true});source.pages.push({...source.pages[2],id:'orphan',blocks:[paragraph('orphan-body')]});const a=h(source);a.select('source');const before=a.state,count=a.count;assert.equal(getManualCoverInsertCommandState(a.state,{role:'divider'}).reason,'incomplete-group');assert.equal(a.run(executeManualCoverInsert('divider')),false);assert.equal(a.state,before);assert.equal(a.count,count);const b=h();insert(b);const stale=measurement(b);b.dispatch(b.state.tr.insertText('X',findManualObject(b.state,'source').pos+1));assert.equal(planManualPagination(b.state,stale).status,'stale');assert.equal(createManualPaginationTransaction(b.state,{status:'ready',doc:stale.doc,action:{type:'push',pageId:'root',blockId:'source'}}),null);
});

test('fixed headers consuming A4 capacity return a blocked diagnostic and never move body into an infinite continuation',()=>{
 const a=h();insert(a,'metadata');const before=a.state,count=a.count,plan=planManualPagination(a.state,measurement(a,0));assert.equal(plan.status,'blocked');assert.deepEqual(plan.diagnostics,[{pageId:'root',reason:'fixed-header-overflow'}]);assert.equal(createManualPaginationTransaction(a.state,plan),null);assert.equal(a.state,before);assert.equal(a.count,count);assert.equal(planManualPagination(a.state,measurement(a,-1)).status,'invalid');const corrupt=measurement(a,0);corrupt.pages.find(page=>page.id==='root').blocks.push({id:'foreign',height:10});assert.equal(planManualPagination(a.state,corrupt).status,'invalid');
});
