import test from 'node:test';import assert from 'node:assert/strict';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {createManualState,documentFromState,findManualCoverRole,findManualObject} from '../src/redesign/manual-kernel.mjs';
import {projectManualCover,getManualCoverProjection,getManualCoverEditableTable} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const owner='@lk-design-system/manual-cover-projection',text=s=>[{type:'text',text:s}],cover=id=>({id,title:text('Title'),metadata:[],blocks:[{id:id+'-body',type:'paragraph',content:text('Link')}],extensions:{opaque:{href:'#manual-cover:'+id+':title'}}});
for(const mode of ['basic-two-covers','collision-role-id','layout-custom-alias-slots','omitted-role','saved-editable-table'])test(`public cover copy resolves scalar links: ${mode}`,()=>{
 const a=cover('a'),b=cover('b');if(mode==='collision-role-id')a.blocks.push({id:'manual-cover:a:title',type:'paragraph',content:text('Primary')});
 if(mode==='layout-custom-alias-slots')a.extensions.layout={owner,version:1,kind:'layout',roleIds:{title:'historic-title'},roleSlots:{title:{group:'body',index:0}},headerOrder:[],bodyOrder:['historic-title','a-body']};
 if(mode==='omitted-role')a.extensions.layout={owner,version:1,kind:'layout',roleIds:{title:'historic-title'},headerOrder:[],bodyOrder:['a-body'],omittedRoles:['title']};
 if(mode==='saved-editable-table'){a.extensions.layout={owner,version:1,kind:'layout',roleIds:{metadata:'actual-grid'},headerOrder:['actual-grid'],bodyOrder:['a-body'],metadataTable:{id:'actual-grid',type:'table',label:'문서 정보',headers:Array.from({length:4},(_,i)=>({id:'actual-cell-'+i,content:[]})),rows:[]}};}
 const input={schemaVersion:2,id:'doc',title:'Copies',covers:[a,b],pages:[]},sourceState=createManualState({document:input}),source=structuredClone(input);for(const c of source.covers){const title=findManualCoverRole(sourceState,c.id,'title');c.blocks.find(x=>x.id===c.id+'-body').content=[{type:'text',text:'Link',marks:[{type:'link',href:title?'#'+title.node.attrs.id:'#omitted-title'}]}];if(mode==='saved-editable-table'&&c.id==='a')c.blocks[0].content.push({type:'text',text:'Grid',marks:[{type:'link',href:'#actual-cell-0'}]});}
 const copied=copyManualDocument(source),state=createManualState({document:copied});for(let i=0;i<2;i++){const c=copied.covers[i],title=findManualCoverRole(state,c.id,'title'),href=c.blocks[0].content[0].marks[0].href;assert.equal(href,title?'#'+title.node.attrs.id:'#omitted-title');assert.deepEqual(c.extensions.opaque,source.covers[i].extensions.opaque);}
 if(mode==='collision-role-id'){const primary=copied.covers[0].blocks[1];assert.ok(findManualObject(state,primary.id));assert.notEqual(primary.id,findManualCoverRole(state,copied.covers[0].id,'title').node.attrs.id)}
 if(mode==='saved-editable-table'){const grid=getManualCoverEditableTable(copied.covers[0].extensions);assert.equal(copied.covers[0].blocks[0].content[1].marks[0].href,'#'+grid.headers[0].id);assert.ok(findManualObject(state,grid.headers[0].id));}
 const restored=documentFromState(state);assert.deepEqual(documentFromState(createManualState({document:decodeDocumentFile(encodeDocumentFile({document:restored,assets:{}})).document})),restored);
 if(mode==='basic-two-covers')for(const guard of ['foreign-marker','wrong-block-marker','ineligible-marker','duplicate-valid-role']){
  const opaque={id:'opaque',type:'heading',level:1,content:text('Opaque'),extensions:{marker:{owner,version:1,kind:'role',coverId:guard==='foreign-marker'?'foreign':'c',blockId:guard==='wrong-block-marker'?'wrong':'opaque',role:'title'}}};if(guard==='ineligible-marker'){opaque.type='paragraph';delete opaque.level}
  const original={schemaVersion:2,id:'guard-doc',title:'Copy',cover:{id:'c',title:text('Title'),metadata:[],blocks:[{id:'body',type:'paragraph',content:[{type:'text',text:'Link',marks:[{type:'link',href:'#manual-cover:c:title'}]}]},opaque]},pages:[]},copy=copyManualDocument(original),projection=projectManualCover(copy.cover),scalar=projection.headerBlocks.find(block=>getManualCoverProjection(block.extensions)?.role==='title');assert.equal(copy.cover.blocks[0].content[0].marks[0].href,guard==='duplicate-valid-role'?'#manual-cover:c:title':'#'+scalar.id,guard);assert.deepEqual(copy.cover.blocks[1].extensions,original.cover.blocks[1].extensions);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:copy,assets:{}})).document,copy);
 }
});
