import test from 'node:test';
import assert from 'node:assert/strict';
import {Fragment,Slice} from '@tiptap/pm/model';
import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,getManualEditingDocument,findManualObject,findManualPageRole,selectManualObject,moveManualObject,deleteManualObject,duplicateManualObject,executeManualBlockCommand,manualCommands,updateManualObject,normalizeManualPastedSlice} from '../src/redesign/manual-kernel.mjs';
import {selectManualBlocks,moveSelectedManualBlocks,duplicateSelectedManualBlocks,deleteSelectedManualBlocks} from '../src/redesign/manual-block-selection.mjs';
import {projectManualPage,restoreManualPage,getManualPageProjection,MANUAL_PAGE_PROJECTION_OWNER} from '../src/redesign/manual-page-projection.mjs';
import {manualPageParts} from '../src/redesign/manual-page-shape.mjs';
import {manualDragLayout} from '../src/redesign/manual-drag-layout.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
import {planManualPagination,createManualPaginationTransaction} from '../src/redesign/manual-pagination.mjs';
import {manualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {repeatedManualPaginationHeaders} from '../src/redesign/manual-pagination-selection.mjs';
const runs=[{type:'text',text:'Page',marks:[{type:'strong'},{type:'underline'}]},{type:'hardBreak'},{type:'text',text:' title'}];
const paragraph=(id,text=id)=>({id,type:'paragraph',content:[{type:'text',text}],extensions:{vendor:{id}}});
function fixture(){return {schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:runs,lead:[{type:'text',text:'Lead'}],blocks:[paragraph('a'),paragraph('b')],extensions:{vendor:{page:1}}},{id:'other',title:[{type:'text',text:'Other'}],blocks:[paragraph('c')]}]};}
function h(document=fixture()){let state=createManualState({document});const dispatch=tr=>state=state.applyTransaction(tr).state;return {get state(){return state;},get document(){return documentFromState(state);},dispatch,run:command=>command(state,dispatch),field:role=>findManualPageRole(state,'page',role),boundary:()=>dispatch(closeHistory(state.tr))};}
function exact(a){const d=a.document;assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);return d;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
function measurement(state,heights,capacity=100){const pages=[];state.doc.forEach((page,pos)=>{if(page.type.name!=='page')return;const blocks=manualPageParts(page,pos).blocks;pages.push({id:page.attrs.id,capacity,blocks:blocks.map((item,index)=>({id:item.node.attrs.id,height:heights[pages.length]?.[index]??10}))});});return {doc:state.doc,revision:1,pages};}
function flow(a,heights,capacity){const plan=planManualPagination(a.state,measurement(a.state,heights,capacity));assert.equal(plan.status,'ready');const tr=createManualPaginationTransaction(a.state,plan);assert.ok(tr,JSON.stringify(plan.action));a.dispatch(tr);return plan;}
test('legacy title and lead become identified actual selectable rail blocks without changing their DTO or inline marks',()=>{
 const source=fixture(),a=h(source),title=a.field('title'),lead=a.field('lead');assert.equal(title.node.type.name,'pageTitle');assert.equal(lead.node.type.name,'pageLead');assert.notEqual(title.node.attrs.id,lead.node.attrs.id);assert.deepEqual(a.document,source);
 assert.equal(a.run(selectManualObject(title.node.attrs.id,{text:false})),true);assert.ok(a.state.selection instanceof NodeSelection);assert.equal(a.run(selectManualBlocks(title.node.attrs.id,lead.node.attrs.id)),true);assert.deepEqual(a.state.selection.ids,[title.node.attrs.id,lead.node.attrs.id]);
 const paths=[...manualDragLayout(a.state).paths.values()];assert.ok(paths.includes(title.node.attrs.id));assert.ok(paths.includes(lead.node.attrs.id));assert.deepEqual(getManualEditingDocument(a.state).pages[0].blocks.map(block=>block.id),[title.node.attrs.id,lead.node.attrs.id,'a','b']);exact(a);
});
test('same-page title movement preserves its scalar binding, saved order and one Undo including node selection',()=>{
 const a=h(),id=a.field('title').node.attrs.id;a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(moveManualObject(id,{parentId:'page',index:3})),true);assert.equal(a.field('title').index,2);assert.deepEqual(a.document.pages[0].title,runs);assert.deepEqual(projectManualPage(exact(a).pages[0]).blocks.map(block=>block.id),[a.field('lead').node.attrs.id,'a',id,'b']);undoRedo(a,before);
});
test('title duplication is an ordinary heading with new identity and exact inline content, through scalar and multi-block commands',()=>{
 for(const multi of [false,true]){const a=h(),id=a.field('title').node.attrs.id;if(multi)a.run(selectManualBlocks(id));else a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(multi?duplicateSelectedManualBlocks:duplicateManualObject(id)),true);const copy=a.document.pages[0].blocks[0];assert.equal(copy.type,'heading');assert.equal(copy.level,2);assert.notEqual(copy.id,id);assert.deepEqual(copy.content,runs);assert.equal(getManualPageProjection(copy.extensions),null);assert.equal(findManualObject(a.state,copy.id).node.type.name,'heading');exact(a);undoRedo(a,before);}
});
test('foreign page move releases the scalar role instead of replacing the destination title',()=>{
 for(const multi of [false,true]){const a=h(),id=a.field('title').node.attrs.id;a.run(multi?selectManualBlocks(id):selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(multi?moveSelectedManualBlocks({parentId:'other',index:1}):moveManualObject(id,{parentId:'other',index:1})),true);assert.deepEqual(a.document.pages[0].title,[]);assert.deepEqual(a.document.pages[1].title,fixture().pages[1].title);assert.equal(findManualObject(a.state,id).node.type.name,'heading');assert.deepEqual(a.document.pages[1].blocks[0].content,runs);assert.equal(projectManualPage(exact(a).pages[0]).blocks.some(block=>getManualPageProjection(block.extensions)?.role==='title'),false);undoRedo(a,before);}
});
test('delete title, delete lead and remove every field leave valid scalar semantics and an editable empty page',()=>{
 for(const role of ['title','lead']){const a=h(),id=a.field(role).node.attrs.id;a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(deleteManualObject(id)),true);if(role==='title')assert.deepEqual(a.document.pages[0].title,[]);else assert.equal(Object.hasOwn(a.document.pages[0],'lead'),false);assert.equal(projectManualPage(exact(a).pages[0]).blocks.some(block=>getManualPageProjection(block.extensions)?.role===role),false);undoRedo(a,before);}
 const single=fixture();single.pages=[{id:'page',title:[],blocks:[]}];const a=h(single),id=a.field('title').node.attrs.id;assert.equal(a.run(deleteManualObject(id)),true);assert.equal(a.state.selection.$from.parent.type.name,'paragraph');assert.equal(a.document.pages[0].blocks.length,1);exact(a);
 const b=h(single);b.run(selectManualBlocks(b.field('title').node.attrs.id));assert.equal(b.run(deleteSelectedManualBlocks),true);assert.equal(b.state.selection.$from.parent.type.name,'paragraph');exact(b);
});
test('public format commands convert scalar title/lead to body content with text and marks preserved, with one Undo',()=>{
 for(const [role,kind]of [['title','heading3'],['title','paragraph'],['title','bulletList'],['title','quote'],['lead','heading2']]){const a=h(),id=a.field(role).node.attrs.id;a.run(selectManualObject(id));a.boundary();const before=a.state;assert.equal(a.run(executeManualBlockCommand(kind,{targetId:id,mode:'convert'})),true);const page=exact(a).pages[0];if(role==='title')assert.deepEqual(page.title,[]);else assert.equal(Object.hasOwn(page,'lead'),false);const block=page.blocks[0],content=kind==='bulletList'?block.items[0].blocks[0].content:kind==='quote'?block.blocks[0].content:block.content;assert.deepEqual(content,role==='title'?runs:fixture().pages[0].lead);undoRedo(a,before);}
});
test('owned role ID collisions preserve moved-title order and foreign layout payload',()=>{
 const projected=projectManualPage(fixture().pages[0]),title=projected.blocks[0];const meta={id:'page',extensions:{vendor:{keep:true},manualPageProjection:{owner:'foreign',data:1}}};const saved=restoreManualPage(meta,[projected.blocks[2],title,projected.blocks[3],projected.blocks[1]]),layout=Object.values(saved.extensions).find(value=>value.owner===MANUAL_PAGE_PROJECTION_OWNER);layout.future={keep:2};const next=projectManualPage(saved,{usedIds:[title.id]});assert.deepEqual(next.blocks.map(block=>getManualPageProjection(block.extensions)?.role||block.id),['a','title','b','lead']);assert.notEqual(next.blocks[1].id,title.id);const restored=restoreManualPage({id:'page',extensions:saved.extensions},next.blocks);assert.deepEqual(restored.extensions.manualPageProjection,saved.extensions.manualPageProjection);assert.deepEqual(Object.values(restored.extensions).find(value=>value.owner===MANUAL_PAGE_PROJECTION_OWNER).future,{keep:2});
});
test('whole-page and file copies retain field roles, while standalone clipboard title copies release them',()=>{
 const a=h(),id=a.field('title').node.attrs.id;a.run(moveManualObject(id,{parentId:'page',index:3}));const copied=copyManualDocument(a.document),b=h(copied);exact(b);const pageId=copied.pages[0].id,role=findManualPageRole(b.state,pageId,'title');assert.ok(role);assert.notEqual(role.node.attrs.id,id);assert.notEqual(findManualPageRole(b.state,pageId,'lead').node.attrs.id,a.field('lead').node.attrs.id);assert.equal(getManualPageProjection(role.node.attrs.meta.extensions).pageId,pageId);assert.deepEqual(projectManualPage(copied.pages[0]).blocks.map(block=>getManualPageProjection(block.extensions)?.role||block.type),['lead','paragraph','title','paragraph']);
 const slice=normalizeManualPastedSlice(new Slice(Fragment.from(a.field('title').node),0,0)),block=slice.content.firstChild;assert.equal(block.type.name,'heading');assert.notEqual(block.attrs.id,id);assert.equal(getManualPageProjection(block.attrs.meta.extensions),null);assert.ok(block.content.eq(a.field('title').node.content));
});
test('moved-title reflow keeps root ownership, unique physical title IDs, caret and automatic family provenance through one Undo',()=>{
 const a=h(),id=a.field('title').node.attrs.id;a.run(moveManualObject(id,{parentId:'page',index:3}));const b=findManualObject(a.state,'b');a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,b.pos+2)));a.boundary();const before=a.state;const plan=flow(a,[[40,70],[10]],100);assert.equal(plan.action.type,'push');const d=exact(a),auto=d.pages[1],rootTitle=a.field('title'),autoTitle=findManualPageRole(a.state,auto.id,'title');assert.equal(manualPaginationMarker(auto.extensions,'page').rootPageId,'page');assert.notEqual(autoTitle.node.attrs.id,rootTitle.node.attrs.id);assert.equal(getManualPageProjection(autoTitle.node.attrs.meta.extensions).derivedFrom,'page');assert.deepEqual(d.pages[0].title,runs);assert.equal(a.state.selection.$from.parent.attrs.id,'b');assert.equal(a.state.selection.$from.parentOffset,1);assert.ok(repeatedManualPaginationHeaders(a.state.doc).some(header=>header.from===autoTitle.pos));assert.equal([...manualDragLayout(a.state).paths.values()].includes(autoTitle.node.attrs.id),false);assert.equal(a.run(deleteManualObject(autoTitle.node.attrs.id)),false);undoRedo(a,before);
 a.dispatch(a.state.tr.insertText('New ',a.field('title').pos+1));const autoId=autoTitle.node.attrs.id;assert.equal(flow(a,[[40],[70],[10]],100).action.type,'title');assert.equal(findManualPageRole(a.state,auto.id,'title').node.attrs.id,autoId);assert.deepEqual(exact(a).pages[1].title,a.document.pages[0].title);
});
test('deleted title propagates to automatic pages and backfill preserves body IDs and the authored page identity',()=>{
 const a=h();flow(a,[[40,70],[10]],100);const autoId=a.document.pages[1].id;assert.equal(a.run(deleteManualObject(a.field('title').node.attrs.id)),true);assert.equal(flow(a,[[40],[70],[10]],100).action.type,'title');assert.equal(findManualPageRole(a.state,autoId,'title'),null);exact(a);assert.equal(flow(a,[[40],[70],[10]],300).action.type,'pull');assert.deepEqual(exact(a).pages[0].blocks,fixture().pages[0].blocks);assert.equal(a.document.pages[0].id,'page');assert.equal(a.document.pages.length,2);
});
