import test from 'node:test';
import assert from 'node:assert/strict';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualObject,executeManualCoverInsert,selectManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {getManualPageGroupActionState,applyManualPageGroupAction} from '../src/redesign/manual-page-group-actions.mjs';
import {insertManualPageTemplate} from '../src/redesign/manual-page-templates.mjs';
import {getOrderedPageEntries} from '../src/redesign/manual-page-order.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';

function h(){let state=createManualState({document:{schemaVersion:2,id:'synthetic-doc',title:'Synthetic',extensions:{vendor:{future:true}},pages:[{id:'surface',title:[],blocks:[{id:'body',type:'paragraph',content:[{type:'text',text:'Body',marks:[{type:'strong'}]}],extensions:{vendor:{body:true}}}]}]}}),count=0,transactions=[];const dispatch=tr=>{count++;const result=state.applyTransaction(tr);transactions=result.transactions;state=result.state;};const a={get state(){return state;},get count(){return count;},get transactions(){return transactions;},get document(){return documentFromState(state);},dispatch,run:(command,view)=>command(state,dispatch,view),boundary:()=>dispatch(closeHistory(state.tr))};a.run(selectManualObject('body'));a.run(executeManualCoverInsert('divider'));return a;}
function exact(a){const d=a.document;assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const copy=copyManualDocument(d),copyState=createManualState({document:copy}),normalized=documentFromState(copyState);assert.deepEqual(documentFromState(createManualState({document:normalized})),normalized);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:copy,assets:{}})).document,copy);const sourceIds=new Set([a.state.doc.attrs.meta.id]);a.state.doc.descendants(node=>{if(node.attrs.id)sourceIds.add(node.attrs.id);});assert.equal(sourceIds.has(copyState.doc.attrs.meta.id),false);copyState.doc.descendants(node=>{if(node.attrs.id)assert.equal(sourceIds.has(node.attrs.id),false);});return d;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}

test('beforeFirstPage template insertion uses the first actual cover surface with one Undo and unchanged original body',()=>{
 const a=h(),coverBefore=a.state.doc.firstChild;assert.deepEqual(a.document.pages,[]);a.boundary();const before=a.state,count=a.count;assert.equal(insertManualPageTemplate('body',{beforeFirstPage:true})(a.state),true);assert.equal(a.count,count);assert.equal(a.run(insertManualPageTemplate('body',{beforeFirstPage:true})),true);assert.equal(a.count,count+1);assert.equal(a.transactions.length,1);const d=exact(a);assert.equal(a.state.doc.firstChild.type.name,'page');assert.ok(a.state.doc.child(1).eq(coverBefore));assert.deepEqual(getOrderedPageEntries(d).map(page=>page.id),[d.pages[0].id,'surface']);assert.deepEqual(d.extensions.vendor,{future:true});assert.deepEqual(d.cover.blocks.at(-1).extensions,{vendor:{body:true}});undoRedo(a,before);
 const b=h(),unchanged=b.state,mutations=b.count;for(const [options,view]of [[{beforeFirstPage:true,cancelled:true},{}],[{beforeFirstPage:true,revision:{}},{}],[{beforeFirstPage:true,readOnly:true},{}],[{beforeFirstPage:true},{composing:true}],[{beforeFirstPage:true},{editable:false}]]){assert.equal(b.run(insertManualPageTemplate('body',options),view),false);assert.equal(b.state,unchanged);assert.equal(b.count,mutations);}
});

test('actual batch deletion permits the last body when cover remains and protects only the last surface',()=>{
 const a=h();assert.equal(a.run(insertManualPageTemplate('body',{afterPageId:'surface'})),true);const pageId=a.document.pages[0].id,body=findManualObject(a.state,pageId).node.lastChild.attrs.id;a.run(selectManualObject(body));a.boundary();const before=a.state,count=a.count,options={action:'delete',sourceIds:[pageId]};assert.equal(getManualPageGroupActionState(a.state,options).enabled,true);assert.equal(a.run(applyManualPageGroupAction(options)),true);assert.equal(a.count,count+1);assert.equal(a.transactions.length,1);assert.deepEqual(exact(a).pages,[]);assert.equal(a.state.doc.firstChild.attrs.id,'surface');assert.ok(a.state.selection.$from.pos>=0);undoRedo(a,before);const unchanged=a.state,mutations=a.count,last={action:'delete',sourceIds:['surface']};assert.equal(getManualPageGroupActionState(a.state,last).reason,'last-item');assert.equal(a.run(applyManualPageGroupAction(last)),false);assert.equal(a.state,unchanged);assert.equal(a.count,mutations);
 const b=h();assert.equal(b.run(insertManualPageTemplate('body',{afterPageId:'surface'})),true);b.run(selectManualObject('body'));b.boundary();const both=b.state;assert.equal(b.run(applyManualPageGroupAction({action:'delete',sourceIds:['surface']})),true);assert.equal(b.document.cover,undefined);assert.equal(b.document.pages.length,1);exact(b);undoRedo(b,both);
});
