import test from 'node:test';
import assert from 'node:assert/strict';
import {DOMParser,DOMSerializer,Slice} from '@tiptap/pm/model';
import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {closeHistory,undoDepth} from '@tiptap/pm/history';
import {TableMap} from '@tiptap/pm/tables';
import {createManualState,documentFromState,manualSchema,findManualCoverRole,findManualObject,manualCommands,duplicateManualObject,moveManualObject,deleteManualObject,addManualTableRow,addManualTableColumn,deleteManualTableColumn,normalizeManualPastedSlice} from '../src/redesign/manual-kernel.mjs';
import {getManualCoverProjection,projectManualCover} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {getManualTableLayout,setManualTableRowHeight,setManualTableColumnWidths} from '../src/redesign/manual-table-layout.mjs';
import {selectManualTableCells} from '../src/redesign/manual-table-selection.mjs';
import {validateManualDocument,copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const inline=text=>[{type:'text',text,marks:[{type:'underline'},{type:'strong'}]}];
function fixture(count=5){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:inline('Title'),metadata:Array.from({length:count},(_,i)=>({id:`entry${i}`,label:inline(`Label${i}`),value:inline(`Value${i}`),extensions:{vendor:{entry:i}}})),blocks:[],extensions:{manualCoverProjection:{foreign:true},vendor:{keep:'cover'}}},pages:[{id:'page',title:[],blocks:[]}]};}
function h(document=fixture()){let state=createManualState({document}),transactions=[];const dispatch=tr=>{transactions.push(tr);state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,props:{},dom:{isConnected:true},editable:true,composing:false,endOfTextblock:()=>true};return {get state(){return state;},get document(){return documentFromState(state);},transactions,dispatch,view,run:(command,v=view)=>command(state,dispatch,v),get table(){return findManualCoverRole(state,'cover','metadata')?.node;},select(id,offset=0){const found=findManualObject(state,id);dispatch(state.tr.setSelection(TextSelection.create(state.doc,found.pos+1+offset)));}};}
function roundtrip(a){const d=a.document;validateManualDocument(d);assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));roundtrip(a);}
for(const count of [1,3,5])test(`metadata ${count} entries uses actual two-cell odd row/span3, logical four columns and exact legacy scalar roundtrip`,()=>{
 const d=fixture(count),a=h(d),table=a.table;assert.equal(table.lastChild.childCount,2);assert.equal(table.lastChild.child(1).attrs.colspan,3);assert.equal(table.lastChild.child(0).attrs.id,`entry${count-1}`);assert.equal(TableMap.get(table).width,4);assert.deepEqual(TableMap.get(table).problems,null);assert.deepEqual(a.document,d);assert.equal(getManualTableLayout(table).columnWeights.length,4);assert.ok(getManualTableLayout(table).columnPercentages.every((value,index)=>Math.abs(value-[20,30,20,30][index])<1e-9));assert.equal(getManualTableLayout(table).hasColumnWeights,false);roundtrip(a);const copied=copyManualDocument(d);assert.deepEqual(documentFromState(createManualState({document:copied})),copied);
});
test('empty and even metadata retain their ordinary rectangular PM rows without span or injected layout',()=>{
 for(const count of [0,2,4]){const d=fixture(count),a=h(d);a.table.forEach(row=>{assert.equal(row.childCount,4);row.forEach(cell=>assert.equal(cell.attrs.colspan,1));});assert.deepEqual(a.document,d);}
});
test('odd label/value Tab uses only real visible fields, and ArrowDown follows the logical column into the spanning value',()=>{
 const a=h(),table=a.table,last=table.lastChild,value=last.child(1);a.select(last.child(0).attrs.id);const before=a.state;assert.equal(a.run(manualCommands.tab),true);assert.equal(a.state.selection.$from.parent.attrs.id,value.attrs.id);assert.equal(a.state.doc,before.doc);const source=table.child(1).child(3);a.select(source.attrs.id,2);const arrowBefore=a.state;assert.equal(a.run(manualCommands.arrowDown),true);assert.equal(a.state.selection.$from.parent.attrs.id,value.attrs.id);assert.equal(a.state.doc,arrowBefore.doc);assert.equal(undoDepth(a.state),undoDepth(arrowBefore));
});
test('rectangular cell deletion through a spanning value preserves all entry IDs and one exact Undo',()=>{
 const a=h(),table=a.table,start=table.child(1).child(3),value=table.lastChild.child(1);a.run(selectManualTableCells(start.attrs.id,value.attrs.id));const before=a.state;assert.equal(a.run(manualCommands.backspace),true);assert.deepEqual(a.document.cover.metadata.map(entry=>entry.id),fixture().cover.metadata.map(entry=>entry.id));assert.equal(a.table.lastChild.childCount,2);assert.equal(a.table.lastChild.child(1).attrs.colspan,3);assert.deepEqual(a.document.cover.metadata[4].label,fixture().cover.metadata[4].label);assert.deepEqual(a.document.cover.metadata[4].value,[]);undoRedo(a,before);
});
test('metadata row height keeps the actual span and persists as owned cover presentation, not duplicated scalar blocks',()=>{
 const a=h(),id=a.table.attrs.id;a.select(a.table.lastChild.child(1).attrs.id,2);a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(setManualTableRowHeight({tableId:id,rowIndex:2,rowMinHeightPx:61,revision:before.doc})),true);assert.equal(a.table.lastChild.childCount,2);assert.equal(a.table.lastChild.child(1).attrs.colspan,3);assert.deepEqual(a.document.cover.metadata,fixture().cover.metadata);assert.deepEqual(a.document.cover.blocks,[]);assert.deepEqual(getManualTableLayout(a.table).rowMinHeightsPx,[null,null,61]);roundtrip(a);const reloaded=createManualState({document:a.document});assert.equal(findManualCoverRole(reloaded,'cover','metadata').node.lastChild.child(1).attrs.colspan,3);assert.deepEqual(getManualTableLayout(findManualCoverRole(reloaded,'cover','metadata').node).rowMinHeightsPx,[null,null,61]);const projected=projectManualCover(a.document.cover).headerBlocks.find(block=>block.type==='table');assert.deepEqual(getManualTableLayout(projected).rowMinHeightsPx,[null,null,61]);undoRedo(a,before);
});
test('duplicate and ordinary-page move expand into valid rectangular DTOs while keeping real cell values and IDs',()=>{
 const a=h(),id=a.table.attrs.id,scalar=a.document.cover.metadata;a.dispatch(a.state.tr.setSelection(NodeSelection.create(a.state.doc,findManualObject(a.state,id).pos)));a.dispatch(closeHistory(a.state.tr));const before=a.state;assert.equal(a.run(duplicateManualObject(id)),true);const clone=a.document.cover.blocks[0];assert.equal(clone.type,'table');assert.equal(getManualCoverProjection(clone.extensions),null);assert.equal(clone.headers.length,4);assert.ok(clone.rows.every(row=>row.length===4));assert.deepEqual(a.document.cover.metadata,scalar);const reloaded=createManualState({document:a.document});assert.equal(findManualObject(reloaded,clone.id).node.lastChild.childCount,4);undoRedo(a,before);
 const b=h(),original=b.table,moveId=original.attrs.id;b.dispatch(b.state.tr.setSelection(NodeSelection.create(b.state.doc,findManualObject(b.state,moveId).pos)));b.dispatch(closeHistory(b.state.tr));const moveBefore=b.state;assert.equal(b.run(moveManualObject(moveId,{parentId:'page',index:1})),true);const moved=b.document.pages[0].blocks[0];assert.equal(moved.id,moveId);assert.equal(moved.rows.at(-1)[0].id,original.lastChild.child(0).attrs.id);assert.equal(moved.rows.at(-1)[1].id,original.lastChild.child(1).attrs.id);assert.deepEqual(b.document.cover.metadata,[]);assert.equal(findManualCoverRole(createManualState({document:b.document}),'cover','metadata'),null);undoRedo(b,moveBefore);
});
for(const [name,command]of [['add row',addManualTableRow],['add column',addManualTableColumn],['delete logical column 3',id=>deleteManualTableColumn(id,3)]])test(`merged metadata ${name} unmerges and releases the scalar role before editing in one transaction/Undo`,()=>{
 const a=h(),id=a.table.attrs.id;a.select(a.table.lastChild.child(1).attrs.id,2);a.dispatch(closeHistory(a.state.tr));const before=a.state,count=a.transactions.length;assert.equal(a.run(command(id)),true);assert.equal(a.transactions.length,count+1);assert.deepEqual(a.document.cover.metadata,[]);const table=findManualObject(a.state,id).node;table.forEach(row=>row.forEach(cell=>assert.equal(cell.attrs.colspan,1)));const dto=a.document.cover.blocks.find(block=>block.id===id);assert.ok(dto);assert.ok(dto.rows.every(row=>row.length===dto.headers.length));assert.deepEqual(dto.rows[1][0].content,fixture().cover.metadata[4].label.map(run=>({...run,marks:[{type:'strong'},{type:'underline'}]})));undoRedo(a,before);
});
test('column resize consumes original revision once, unmerges to four logical weights and restores the original cell selection on Undo',()=>{
 const a=h(),id=a.table.attrs.id;a.run(selectManualTableCells(a.table.lastChild.child(0).attrs.id,a.table.lastChild.child(1).attrs.id));const before=a.state,count=a.transactions.length;assert.equal(a.run(setManualTableColumnWidths({tableId:id,columnWeights:[1,4,2,3],revision:before.doc})),true);assert.equal(a.transactions.length,count+1);assert.deepEqual(getManualTableLayout(findManualObject(a.state,id).node).columnWeights,[1,4,2,3]);assert.deepEqual(a.document.cover.metadata,[]);undoRedo(a,before);
});
test('padding identities avoid real document, block and cell IDs; readonly, stale and IME structural edits are no-ops',()=>{
 const d=fixture(1),valueId='manual-cover:cover:metadata:0:1';d.id=`manual-cover-padding:${valueId}:0`;d.pages[0].blocks=[{id:`manual-cover-padding:${valueId}:1`,type:'paragraph',content:[]}];const a=h(d),id=a.table.attrs.id;assert.deepEqual(a.document,d);assert.equal(a.run(moveManualObject(id,{parentId:'page',index:1})),true);roundtrip(a);const b=h();for(const view of [{...b.view,editable:false},{...b.view,composing:true}]){const before=b.state;assert.equal(b.run(addManualTableColumn(b.table.attrs.id),view),false);assert.equal(b.state,before);}const before=b.state;assert.equal(b.run(setManualTableColumnWidths({tableId:b.table.attrs.id,columnWeights:[1,1,1,1],revision:createManualState({document:b.document}).doc})),false);assert.equal(b.state,before);
});
// Minimal DOM surface for the real PM parser; no browser or new dependency.
function element(tag,attributes={},nodes=[]){const dom={nodeType:1,nodeName:tag.toUpperCase(),tagName:tag.toUpperCase(),childNodes:nodes,style:{length:0},getAttribute:key=>attributes[key]===undefined?null:String(attributes[key]),setAttribute(key,value){attributes[key]=String(value);},appendChild(node){nodes.push(node);link();return node;},matches(selector){return selector.split(',').some(value=>{value=value.trim();const attr=/^(\w+)?\[([\w-]+)(?:="([^"]*)")?\]$/.exec(value);return attr?(!attr[1]||attr[1].toLowerCase()===tag)&&Object.hasOwn(attributes,attr[2])&&(attr[3]===undefined||attributes[attr[2]]===attr[3]):value.toLowerCase()===tag;});}};function link(){dom.firstChild=nodes[0]||null;dom.lastChild=nodes.at(-1)||null;nodes.forEach((node,index)=>{node.parentNode=dom;node.previousSibling=nodes[index-1]||null;node.nextSibling=nodes[index+1]||null;});}link();return dom;}
function clipboardDOM(node){if(node.isText)return {nodeType:3,nodeName:'#text',nodeValue:node.text};function render(spec){const attrs=typeof spec[1]==='object'&&!Array.isArray(spec[1]);return element(spec[0],attrs?spec[1]:{},spec.slice(attrs?2:1).flatMap(part=>part===0?Array.from({length:node.childCount},(_,i)=>clipboardDOM(node.child(i))):[Array.isArray(part)?render(part):{nodeType:3,nodeName:'#text',nodeValue:part}]));}return render(node.type.spec.toDOM(node));}
test('semantic clipboard HTML carries actual colspan3, and normalized pasted copies serialize as valid ordinary v2 tables',()=>{
 const a=h(fixture(1)),table=a.table,spec=table.lastChild.child(1).type.spec.toDOM(table.lastChild.child(1));assert.equal(spec[1].colspan,3);
 const owner={createElement:tag=>element(tag),createTextNode:value=>({nodeType:3,nodeName:'#text',nodeValue:value}),createDocumentFragment:()=>Object.assign(element('fragment'),{nodeType:11})};
 const html=DOMSerializer.fromSchema(manualSchema).serializeFragment(Slice.fromJSON(manualSchema,{content:[table.toJSON()]}).content,{document:owner});
 const parsed=DOMParser.fromSchema(manualSchema).parseSlice(element('div',{},html.childNodes),{preserveWhitespace:true});assert.equal(parsed.content.firstChild.lastChild.child(1).attrs.colspan,3);
 const copied=normalizeManualPastedSlice(parsed),copy=copied.content.firstChild;for(let column=0;column<2;column++)assert.ok(copy.firstChild.child(column).content.eq(table.firstChild.child(column).content));
 const originalIds=new Set([table.attrs.id,...Array.from({length:2},(_,index)=>table.firstChild.child(index).attrs.id)]);assert.equal(originalIds.has(copy.attrs.id),false);copy.descendants(node=>{if(node.attrs.id)assert.equal(originalIds.has(node.attrs.id),false);});
 const page=findManualObject(a.state,'page'),pos=page.pos+page.node.nodeSize-1;a.dispatch(a.state.tr.insert(pos,copied.content));const dto=a.document.pages[0].blocks[0];assert.equal(dto.type,'table');assert.equal(dto.headers.length,4);assert.deepEqual(dto.headers.slice(0,2).map(cell=>cell.content),[inline('Label0'),inline('Value0')].map(runs=>runs.map(run=>({...run,marks:[{type:'strong'},{type:'underline'}]}))));assert.deepEqual(dto.headers.slice(2).map(cell=>cell.content),[[],[]]);assert.ok(dto.headers.every(cell=>!originalIds.has(cell.id)));assert.equal(getManualCoverProjection(dto.extensions),null);roundtrip(a);
});
