import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {createManualState,documentFromState,findManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {deleteEmptyManualToggleAtStart} from '../src/redesign/manual-toggle-boundary.mjs';
import {withManualPaginationMarker} from '../src/redesign/manual-pagination-meta.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const rich=text=>text?[{type:'text',text,marks:[{type:'strong'},{type:'underline'}]}]:[];
const p=(id,text='')=>({type:'paragraph',id,content:rich(text),extensions:{vendor:{id}}});
function harness({open=true,nested=false,prior=false,body=[p('placeholder')],title='',tail=true}={}){
 const toggle={type:'toggle',id:'toggle',open,title:rich(title),blocks:body,extensions:{unknown:{keep:[1,2]},convertedManualBlock:{vendor:'existing'}}};
 const document={schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:rich('페이지 제목'),blocks:[...(prior?[p('previous','이전 본문')]:[]),nested?{type:'toggle',id:'outer',open:true,title:rich('바깥 제목'),blocks:[toggle],extensions:{vendor:true}}:toggle,...(tail?[p('after','이후 본문')]:[])]}]};
 let state=createManualState({document}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};
 const view={get state(){return state;},dispatch,editable:true,composing:false,dom:{isConnected:true},props:{},endOfTextblock:()=>true};
 const select=()=>{const obj=findManualObject(state,'toggle');dispatch(state.tr.setSelection(TextSelection.create(state.doc,obj.pos+2)));};select();
 const key=(event={},v=view)=>state.plugins.some(plugin=>plugin.props.handleKeyDown?.(v,{key:'Backspace',keyCode:8,shiftKey:false,altKey:false,ctrlKey:false,metaKey:false,...event}));
 return {get state(){return state;},get document(){return documentFromState(state);},get count(){return count;},dispatch,view,key,select,run:command=>command(state,dispatch,view)};
}
for(const open of [false,true])for(const nested of [false,true])for(const prior of [false,true])test(`empty title Backspace ${open?'expanded':'collapsed'} ${nested?'nested':'direct'} ${prior?'after paragraph':'after page title'} converts placeholder with exact undo/reopen`,()=>{
 const h=harness({open,nested,prior}),before=h.state,original=h.document,count=h.count,old=findManualObject(before,'toggle').node;
 assert.equal(deleteEmptyManualToggleAtStart(before),true);assert.equal(h.state,before);assert.equal(h.count,count);assert.equal(h.key(),true);assert.equal(h.count,count+1);
 const after=h.state,node=findManualObject(after,'toggle').node;assert.equal(node.type.name,'paragraph');assert.equal(node.content.size,0);assert.equal(after.selection.$from.parent.attrs.id,'toggle');assert.equal(after.selection.$from.parentOffset,0);assert.deepEqual(node.attrs.meta.extensions.unknown,old.attrs.meta.extensions.unknown);assert.deepEqual(node.attrs.meta.extensions.convertedManualBlock,{vendor:'existing'});assert.deepEqual(node.attrs.meta.extensions.convertedManualBlock2.blocks,[old.child(1).toJSON()]);
 assert.deepEqual(h.document.pages[0].title,original.pages[0].title);assert.equal(findManualObject(after,'after').node.textContent,'이후 본문');if(prior)assert.equal(findManualObject(after,'previous').node.textContent,'이전 본문');if(nested)assert.equal(findManualObject(after,'outer').node.firstChild.textContent,'바깥 제목');
 const out=h.document,reopened=decodeDocumentFile(encodeDocumentFile({document:out,assets:{}})).document;assert.deepEqual(documentFromState(createManualState({document:reopened})),out);
 assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));assert.equal(h.run(manualCommands.redo),true);assert.ok(h.state.doc.eq(after.doc));assert.ok(h.state.selection.eq(after.selection));h.dispatch(h.state.tr.insertText('계속'));assert.equal(findManualObject(h.state,'toggle').node.textContent,'계속');
});
for(const body of [[],[p('one'),p('two')]])test(`bodyless/multiple empty placeholders convert without losing identities`,()=>{const h=harness({body});assert.equal(h.key(),true);const provenance=findManualObject(h.state,'toggle').node.attrs.meta.extensions.convertedManualBlock2;assert.deepEqual(provenance.blocks.map(node=>node.attrs.id),body.map(node=>node.id));});
const meaningful=[['rich text',[p('body','내용')]],['whitespace',[p('body',' ')]],['hard break',[{type:'paragraph',id:'body',content:[{type:'hardBreak'}]}]],['figure',[{type:'figure',id:'figure',asset:'assets/synthetic.png',alt:'synthetic',caption:[],widthPreset:'full'}]],['list',[{type:'list',id:'list',ordered:false,items:[{id:'item',blocks:[p('body','목록')]}]}]],['callout',[{type:'callout',id:'callout',tone:'signal',title:rich('안내'),blocks:[p('body')]}]],['nested toggle',[{type:'toggle',id:'child',title:[],open:false,blocks:[p('body')]}]]];
for(const open of [false,true])for(const [label,body] of meaningful)test(`empty title with ${label} ${open?'expanded':'collapsed'} selects whole toggle and preserves every byte`,()=>{const h=harness({open,body}),before=h.state,original=h.document,count=h.count;assert.equal(h.key(),true);assert.equal(h.count,count+1);assert.ok(h.state.doc.eq(before.doc));assert.deepEqual(h.document,original);assert.ok(h.state.selection instanceof NodeSelection);assert.equal(h.state.selection.node.attrs.id,'toggle');});
for(const mode of ['composing','event-composing','ime229','read-only','stale'])test(`${mode} empty-title key guard preserves wrapper and body`,()=>{const h=harness(),before=h.state;let v=h.view,event={};if(mode==='composing')v={...v,composing:true};if(mode==='event-composing')event.isComposing=true;if(mode==='ime229')event.keyCode=229;if(mode==='read-only')v={...v,editable:false};if(mode==='stale')v={...v,state:createManualState({document:h.document})};h.key(event,v);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));});
test('nonempty title start remains unchanged and internal characters remain owned by character deletion',()=>{const h=harness({title:'안녕하세요'}),before=h.state;assert.equal(deleteEmptyManualToggleAtStart(before,h.dispatch,h.view),false);h.key();assert.ok(h.state.doc.eq(before.doc));h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,findManualObject(h.state,'toggle').pos+7)));assert.equal(h.key(),true);assert.equal(findManualObject(h.state,'toggle').node.firstChild.textContent,'안녕하세');});
test('conversion is one undo independently of preceding paragraph typing',()=>{const h=harness({prior:true});const previous=findManualObject(h.state,'previous');h.dispatch(h.state.tr.setSelection(TextSelection.create(h.state.doc,previous.pos+1)));h.dispatch(h.state.tr.insertText('직전 입력 '));h.select();const before=h.state;assert.equal(h.key(),true);assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));});

for(const open of [false,true])test(`only page body ${open?'expanded':'collapsed'} exits into same-ID editable paragraph`,()=>{const h=harness({open,tail:false}),before=h.state;h.dispatch(h.state.tr.setStoredMarks([h.state.schema.marks.strong.create()]));const marks=h.state.storedMarks;assert.equal(h.key(),true);assert.equal(findManualObject(h.state,'toggle').node.type.name,'paragraph');assert.deepEqual(h.state.storedMarks,marks);assert.equal(h.document.pages[0].blocks.length,1);assert.equal(h.run(manualCommands.undo),true);assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection.eq(before.selection));});
test('owned pagination root is selected rather than converted or orphaned',()=>{const h=harness();const current=findManualObject(h.state,'toggle');const meta=withManualPaginationMarker(current.node.attrs.meta,{kind:'block',rootBlockId:'root',sourceType:'toggle'});h.dispatch(h.state.tr.setNodeMarkup(current.pos,undefined,{...current.node.attrs,meta}));const before=h.state;h.key();assert.ok(h.state.doc.eq(before.doc));assert.ok(h.state.selection instanceof NodeSelection);});
