import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeSelection} from '@tiptap/pm/state';
import {closeHistory} from '@tiptap/pm/history';
import {createManualState,documentFromState,findManualCoverRole,findManualObject,selectManualObject,deleteManualObject,moveManualObject,duplicateManualObject,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {selectManualBlocks,moveSelectedManualBlocks} from '../src/redesign/manual-block-selection.mjs';
import {projectManualCover,getManualCoverProjection,MANUAL_COVER_PROJECTION_OWNER} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {manualDragLayout} from '../src/redesign/manual-drag-layout.mjs';
import {copyManualDocument} from '../src/redesign/manual-v2.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const inline=text=>[{type:'text',text,marks:[{type:'underline'},{type:'strong'}]}],paragraph=(id,text=id)=>({id,type:'paragraph',content:inline(text).map(run=>({...run,marks:[...run.marks].reverse()})),extensions:{vendor:{id}}});
function fixture(){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',title:inline('Title'),metadata:[{id:'entry',label:inline('Label'),value:inline('Value'),extensions:{vendor:{entry:1}}}],logo:{src:'@lk-design-system/lds-theme/assets/brand/lk-logo-inline-navy.svg',alt:'LK'},sectionTitle:inline('Section'),blocks:[paragraph('body')],extensions:{manualCoverProjection:{owner:'foreign',keep:1},vendor:{cover:1}}},pages:[{id:'page',title:[],blocks:[paragraph('page-body')]}]};}
function h(document=fixture()){let state=createManualState({document}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};return {get state(){return state;},get count(){return count;},get document(){return documentFromState(state);},dispatch,run:command=>command(state,dispatch),role:role=>findManualCoverRole(state,'cover',role),boundary:()=>dispatch(closeHistory(state.tr))};}
function exact(a){const d=a.document;assert.deepEqual(documentFromState(createManualState({document:d})),d);assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const ids=[a.state.doc.attrs.meta.id];a.state.doc.descendants(node=>{if(node.attrs.id)ids.push(node.attrs.id);});assert.equal(new Set(ids).size,ids.length);return d;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
const roles=blocks=>blocks.map(block=>getManualCoverProjection(block.extensions)?.role||block.id);
test('legacy cover projects exactly one independent divider after metadata with stable ID, real selection/rail and unchanged scalar DTO',()=>{
 const source=fixture(),a=h(source),divider=a.role('divider'),metadata=a.role('metadata');assert.equal(divider.node.type.name,'divider');assert.equal(divider.node.isAtom,true);assert.equal(divider.index,metadata.index+1);assert.notEqual(divider.node.attrs.id,metadata.node.attrs.id);assert.equal(divider.node.attrs.id,'manual-cover:cover:divider');assert.deepEqual(exact(a),source);assert.equal(a.run(selectManualObject(divider.node.attrs.id,{text:false})),true);assert.ok(a.state.selection instanceof NodeSelection);assert.equal(a.state.selection.node.attrs.id,divider.node.attrs.id);assert.equal(a.run(selectManualBlocks(divider.node.attrs.id)),true);assert.deepEqual(a.state.selection.ids,[divider.node.attrs.id]);assert.ok([...manualDragLayout(a.state).paths.values()].includes(divider.node.attrs.id));const projected=projectManualCover(source.cover);assert.equal(projected.headerBlocks.filter(block=>getManualCoverProjection(block.extensions)?.role==='divider').length,1);assert.deepEqual(roles(projected.headerBlocks),['logo','title','metadata','divider']);
});
test('divider deletion persists omission independently of metadata and restores the exact selection in one Undo',()=>{
 const a=h(),id=a.role('divider').node.attrs.id;a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state,count=a.count;assert.equal(deleteManualObject(id)(a.state),true);assert.equal(a.count,count);assert.equal(a.run(deleteManualObject(id)),true);assert.equal(a.count,count+1);assert.deepEqual(a.document.cover.metadata,fixture().cover.metadata);assert.ok(a.role('metadata'));assert.equal(a.role('divider'),null);const d=exact(a),layout=Object.values(d.cover.extensions).find(value=>value.owner===MANUAL_COVER_PROJECTION_OWNER);assert.ok(layout.omittedRoles.includes('divider'));assert.equal(projectManualCover(d.cover).headerBlocks.some(block=>getManualCoverProjection(block.extensions)?.role==='divider'),false);assert.deepEqual(d.cover.extensions.vendor,fixture().cover.extensions.vendor);undoRedo(a,before);
});
test('metadata deletion does not delete or regenerate the independently selected divider',()=>{
 const a=h(),dividerId=a.role('divider').node.attrs.id,metadataId=a.role('metadata').node.attrs.id;a.run(selectManualObject(metadataId,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(deleteManualObject(metadataId)),true);assert.deepEqual(a.document.cover.metadata,[]);assert.equal(a.role('divider').node.attrs.id,dividerId);const projected=projectManualCover(exact(a).cover);assert.equal(projected.headerBlocks.some(block=>getManualCoverProjection(block.extensions)?.role==='metadata'),false);assert.equal(projected.headerBlocks.filter(block=>getManualCoverProjection(block.extensions)?.role==='divider').length,1);undoRedo(a,before);
});
test('divider header reorder and body movement use ordinary scalar and block-range commands while keeping metadata unchanged',()=>{
 const a=h(),id=a.role('divider').node.attrs.id;a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(moveManualObject(id,{parentId:'cover',index:0,coverHeader:true})),true);assert.equal(a.role('divider').index,0);assert.deepEqual(roles(projectManualCover(exact(a).cover).headerBlocks),['divider','logo','title','metadata']);assert.deepEqual(a.document.cover.metadata,fixture().cover.metadata);undoRedo(a,before);
 a.run(selectManualBlocks(id));a.boundary();const bodyBefore=a.state;assert.equal(a.run(moveSelectedManualBlocks({parentId:'cover',index:1})),true);assert.equal(a.role('divider').parent.type.name,'coverBody');const d=exact(a),projected=projectManualCover(d.cover);assert.deepEqual(roles(projected.headerBlocks),['logo','title','metadata']);assert.deepEqual(roles(projected.bodyBlocks),['sectionTitle','body','divider']);assert.deepEqual(d.cover.blocks,fixture().cover.blocks);assert.deepEqual(d.cover.metadata,fixture().cover.metadata);undoRedo(a,bodyBefore);
});
test('divider duplication is an ordinary new-ID block and foreign movement releases the role without changing its identity',()=>{
 const a=h(),id=a.role('divider').node.attrs.id;a.run(selectManualObject(id,{text:false}));a.boundary();const before=a.state;assert.equal(a.run(duplicateManualObject(id)),true);const clone=exact(a).cover.blocks[0];assert.equal(clone.type,'divider');assert.notEqual(clone.id,id);assert.equal(getManualCoverProjection(clone.extensions),null);assert.equal(a.role('divider').node.attrs.id,id);undoRedo(a,before);
 const b=h(),originalId=b.role('divider').node.attrs.id;b.run(selectManualObject(originalId,{text:false}));b.boundary();const moveBefore=b.state;assert.equal(b.run(moveManualObject(originalId,{parentId:'page',index:1})),true);const moved=exact(b).pages[0].blocks[0];assert.equal(moved.type,'divider');assert.equal(moved.id,originalId);assert.equal(getManualCoverProjection(moved.extensions),null);assert.equal(b.role('divider'),null);assert.deepEqual(b.document.cover.metadata,fixture().cover.metadata);undoRedo(b,moveBefore);
});
test('divider identity collisions, saved role order and full file copy renewals preserve existing body IDs and foreign payload',()=>{
 const source=fixture();source.cover.blocks.push(paragraph('manual-cover:cover:divider'));const a=h(source),divider=a.role('divider');assert.equal(divider.node.attrs.id,'manual-cover:cover:divider:2');assert.deepEqual(exact(a),source);a.run(moveManualObject(divider.node.attrs.id,{parentId:'cover',index:0,coverHeader:true}));const d=exact(a),copy=copyManualDocument(d),b=h(copy),copied=findManualCoverRole(b.state,copy.cover.id,'divider');assert.notEqual(copied.node.attrs.id,divider.node.attrs.id);assert.equal(copied.index,0);assert.deepEqual(copy.cover.extensions.manualCoverProjection,source.cover.extensions.manualCoverProjection);assert.deepEqual(copy.cover.extensions.vendor,source.cover.extensions.vendor);assert.equal(findManualObject(a.state,'manual-cover:cover:divider').node.type.name,'paragraph');exact(b);
});
test('legacy owned order keeps the newly independent default line immediately after metadata even when metadata is in the body',()=>{
 const source=fixture();source.cover.extensions.manualCoverProjection2={owner:MANUAL_COVER_PROJECTION_OWNER,version:1,kind:'layout',headerOrder:['manual-cover:cover:logo','manual-cover:cover:title'],bodyOrder:['manual-cover:cover:sectionTitle','manual-cover:cover:metadata','body'],roleIds:{logo:'manual-cover:cover:logo',title:'manual-cover:cover:title',metadata:'manual-cover:cover:metadata',sectionTitle:'manual-cover:cover:sectionTitle'},future:{keep:2}};const projected=projectManualCover(source.cover);assert.deepEqual(roles(projected.headerBlocks),['logo','title']);assert.deepEqual(roles(projected.bodyBlocks),['sectionTitle','metadata','divider','body']);const a=h(source);assert.equal(a.role('divider').parent.type.name,'coverBody');assert.equal(a.role('divider').index,a.role('metadata').index+1);const d=exact(a);assert.deepEqual(d.cover.metadata,source.cover.metadata);assert.deepEqual(d.cover.extensions.manualCoverProjection2.future,{keep:2});
});
test('saved role alias collision distinguishes header divider ownership from the real body block and explicit body role slots',()=>{
 const source=fixture(),raw='manual-cover:cover:divider';source.cover.blocks=[paragraph(raw,'Body collision'),paragraph('after')];source.cover.extensions.manualCoverProjection2={owner:MANUAL_COVER_PROJECTION_OWNER,version:1,kind:'layout',headerOrder:['manual-cover:cover:logo','manual-cover:cover:title','manual-cover:cover:metadata',raw],bodyOrder:['manual-cover:cover:sectionTitle',raw,'after'],roleIds:{divider:raw},future:{keep:2}};const projected=projectManualCover(source.cover);assert.deepEqual(roles(projected.headerBlocks),['logo','title','metadata','divider']);assert.equal(projected.headerBlocks.at(-1).id,raw+':2');assert.deepEqual(roles(projected.bodyBlocks),['sectionTitle',raw,'after']);assert.deepEqual(projected.bodyBlocks[1],source.cover.blocks[0]);
 source.cover.extensions.manualCoverProjection2.headerOrder=['manual-cover:cover:logo','manual-cover:cover:title','manual-cover:cover:metadata'];source.cover.extensions.manualCoverProjection2.bodyOrder=['manual-cover:cover:sectionTitle',raw,raw,'after'];source.cover.extensions.manualCoverProjection2.roleSlots={divider:{group:'body',index:1,future:{keep:3}}};const moved=projectManualCover(source.cover);assert.deepEqual(roles(moved.headerBlocks),['logo','title','metadata']);assert.deepEqual(roles(moved.bodyBlocks),['sectionTitle','divider',raw,'after']);assert.equal(moved.bodyBlocks[1].id,raw+':2');assert.deepEqual(moved.bodyBlocks[2],source.cover.blocks[0]);const a=h(source),d=exact(a),layout=Object.values(d.cover.extensions).find(value=>value.owner===MANUAL_COVER_PROJECTION_OWNER);assert.deepEqual(layout.roleSlots.divider,{group:'body',index:1,future:{keep:3}});assert.deepEqual(layout.future,{keep:2});
 const copy=copyManualDocument(source),copyProjection=projectManualCover(copy.cover);assert.deepEqual(roles(copyProjection.bodyBlocks),['sectionTitle','divider',copy.cover.blocks[0].id,copy.cover.blocks[1].id]);assert.notEqual(copy.cover.blocks[0].id,raw);assert.deepEqual(copyProjection.bodyBlocks[2],copy.cover.blocks[0]);assert.deepEqual(copy.cover.extensions.manualCoverProjection2.roleSlots.divider.future,{keep:3});
});
