import test from 'node:test';import assert from 'node:assert/strict';
import {NodeSelection,TextSelection} from '@tiptap/pm/state';
import {undoDepth,closeHistory} from '@tiptap/pm/history';
import {MANUAL_DIVIDER_STYLE_OWNER,readManualDividerStyle,resolveManualDividerStyle,withManualDividerStyle,setManualDividerStyle} from '../src/redesign/manual-divider-style.mjs';
import {createManualState,documentFromState,findManualObject,findManualCoverRole,manualCommands} from '../src/redesign/manual-kernel.mjs';
import {selectManualBlocks} from '../src/redesign/manual-block-selection.mjs';
import {createManualPageTemplate} from '../src/redesign/manual-page-templates.mjs';
import {projectManualCover,MANUAL_COVER_PROJECTION_OWNER,getManualCoverProjection} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const t=text=>[{type:'text',text,marks:[{type:'strong'}]}],p=id=>({id,type:'paragraph',content:t(id),extensions:{vendor:{id}}});
function h({cover=false,extensions}={}){
 const doc={schemaVersion:2,id:'doc',title:'',pages:[{id:'page',title:t('Page'),blocks:[p('before'),{id:'divider',type:'divider',...(extensions!==undefined?{extensions}:{})},p('after')]}],...(cover?{cover:{id:'cover',title:t('Cover'),metadata:[],sectionTitle:t('Section'),blocks:[p('cover-body')],extensions:{vendor:{keep:1}}}}:{})};
 let state=createManualState({document:doc}),count=0;const dispatch=tr=>{count++;state=state.applyTransaction(tr).state;};
 const id=cover?findManualCoverRole(state,'cover','divider').node.attrs.id:'divider',select=()=>dispatch(state.tr.setSelection(NodeSelection.create(state.doc,findManualObject(state,id).pos)));select();
 const view={get state(){return state;},editable:true,composing:false,props:{}};
 return {get state(){return state;},get count(){return count;},get document(){return documentFromState(state);},id,dispatch,select,view,run:(options={},v=view)=>manualCommands.setDividerStyle({dividerId:id,variant:'emphasis',...options})(state,dispatch,v)};
}
function roundtrip(a){const d=a.document;assert.deepEqual(decodeDocumentFile(encodeDocumentFile({document:d,assets:{}})).document,d);const restored=createManualState({document:d});assert.deepEqual(documentFromState(restored),d);return restored;}
for(const cover of [false,true])for(const variant of ['default','emphasis'])test(`style ${variant} cover=${cover} preserves exact selection marks IDs scalar roles and one Undo`,()=>{
 const a=h({cover});a.dispatch(a.state.tr.setStoredMarks([a.state.schema.marks.emphasis.create()]));const b=a.state,n=a.count,d=a.document,depth=undoDepth(b);assert.equal(a.run({variant,revision:b.doc}),true);assert.equal(a.count,n+1);assert.equal(undoDepth(a.state),depth+1);assert.ok(a.state.selection.eq(b.selection));assert.deepEqual(a.state.storedMarks,b.storedMarks);assert.equal(findManualObject(a.state,a.id).node.attrs.id,a.id);assert.deepEqual(readManualDividerStyle(findManualObject(a.state,a.id).node.attrs.meta.extensions),{variant});
 if(cover){assert.equal(findManualCoverRole(a.state,'cover','divider').node.attrs.id,a.id);assert.deepEqual(a.document.cover.title,d.cover.title);assert.deepEqual(a.document.cover.metadata,d.cover.metadata);assert.deepEqual(a.document.cover.blocks,d.cover.blocks);assert.deepEqual(a.document.cover.extensions.vendor,d.cover.extensions.vendor);}else assert.deepEqual(a.document.pages[0].blocks.filter(x=>x.id!=='divider'),d.pages[0].blocks.filter(x=>x.id!=='divider'));
 const restored=roundtrip(a),target=cover?findManualCoverRole(restored,'cover','divider'):findManualObject(restored,'divider');assert.equal(resolveManualDividerStyle(target.node.attrs.meta.extensions,{cover}),variant);const after=a.state;assert.equal(manualCommands.undo(a.state,a.dispatch),true);assert.ok(a.state.doc.eq(b.doc));assert.ok(a.state.selection.eq(b.selection));assert.equal(manualCommands.redo(a.state,a.dispatch),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));const same=a.state;assert.equal(a.run({variant}),false);assert.equal(a.state,same);
});
test('pure style helper validates packets keeps collision/future/empty extensions and does not mutate input',()=>{
 const foreign={manualDividerStyle:{owner:'vendor',variant:'emphasis',id:'opaque'},manualDividerStyle2:{owner:MANUAL_DIVIDER_STYLE_OWNER,version:2,kind:'divider-style',variant:'emphasis'}};const before=structuredClone(foreign),out=withManualDividerStyle({extensions:foreign},'default');assert.deepEqual(foreign,before);assert.deepEqual(out.extensions.manualDividerStyle,before.manualDividerStyle);assert.deepEqual(out.extensions.manualDividerStyle2,before.manualDividerStyle2);assert.equal(readManualDividerStyle(out.extensions).variant,'default');assert.equal(out.extensions.manualDividerStyle3.variant,'default');assert.equal(withManualDividerStyle({extensions:{}},'emphasis').extensions.manualDividerStyle.preserveEmptyExtensions,true);
 const future=withManualDividerStyle({},'default');future.extensions.manualDividerStyle.future={id:'opaque'};assert.deepEqual(withManualDividerStyle(future,'emphasis').extensions.manualDividerStyle.future,{id:'opaque'});
 for(const variant of ['emphasized','future',null])assert.throws(()=>withManualDividerStyle({},variant),TypeError);
 assert.equal(resolveManualDividerStyle(foreign),'default');assert.equal(resolveManualDividerStyle(foreign,{cover:true}),'emphasis');
});
for(const mode of ['readOnly','cancelled','ime','noneditable','staleRevision','staleView','gateFalse','gateFunction','wrongId','wrongVariant','text','multi'])test(`${mode} cannot change a divider`,()=>{
 const a=h(),opts={},v={...a.view};if(['readOnly','cancelled'].includes(mode))opts[mode]=true;if(mode==='ime')v.composing=true;if(mode==='noneditable')v.editable=false;if(mode==='staleRevision')opts.revision=createManualState({document:a.document}).doc;if(mode==='staleView')v.state=createManualState({document:a.document});if(mode==='gateFalse')v.props={manualDividerStyleEnabled:false};if(mode==='gateFunction')v.props={manualDividerStyleEnabled:()=>false};if(mode==='wrongId')opts.dividerId='before';if(mode==='wrongVariant')opts.variant='future';if(mode==='text')a.dispatch(a.state.tr.setSelection(TextSelection.create(a.state.doc,findManualObject(a.state,'after').pos+1)));if(mode==='multi')selectManualBlocks('before','after')(a.state,a.dispatch);const b=a.state,n=a.count;assert.equal(a.run(opts,v),false);assert.equal(a.state,b);assert.equal(a.count,n);
});
test('single block selection and optional allowed callback succeed; no-dispatch is pure',()=>{
 const a=h();selectManualBlocks('divider','divider')(a.state,a.dispatch);const b=a.state,n=a.count;assert.equal(setManualDividerStyle({dividerId:a.id,variant:'emphasis'})(a.state,undefined,a.view),true);assert.equal(a.state,b);assert.equal(a.count,n);assert.equal(a.run({}, {...a.view,props:{manualDividerStyleEnabled:()=>true}}),true);assert.equal(a.state.selection.manualBlockSelection,true);roundtrip(a);
});
test('divider style is its own Undo event separate from prior typing',()=>{
 const a=h();a.dispatch(closeHistory(a.state.tr).insertText('X',findManualObject(a.state,'before').pos+1));a.select();const typed=a.state;assert.equal(a.run(),true);assert.equal(manualCommands.undo(a.state,a.dispatch),true);assert.ok(a.state.doc.eq(typed.doc));assert.equal(manualCommands.undo(a.state,a.dispatch),true);assert.equal(findManualObject(a.state,'before').node.textContent,'before');
});
test('legacy cover stays style-free and new cover template carries explicit emphasis through reopen',()=>{
 const old=h({cover:true});assert.equal(readManualDividerStyle(findManualCoverRole(old.state,'cover','divider').node.attrs.meta.extensions),null);const oldDto=old.document;assert.equal(Object.values(oldDto.cover.extensions).some(x=>x.owner===MANUAL_COVER_PROJECTION_OWNER),false);const fresh=createManualPageTemplate('cover'),doc={schemaVersion:2,id:'fresh',title:'',cover:fresh,pages:[]},state=createManualState({document:doc}),divider=findManualCoverRole(state,fresh.id,'divider');assert.deepEqual(readManualDividerStyle(divider.node.attrs.meta.extensions),{variant:'emphasis'});assert.deepEqual(documentFromState(state),doc);assert.deepEqual(documentFromState(createManualState({document:documentFromState(state)})),doc);
});
test('unknown nested divider layout packet is opaque while recognized styles stay role eligible',()=>{
 const a=h({cover:true});assert.equal(a.run({variant:'default'}),true);const dto=a.document,layout=Object.values(dto.cover.extensions).find(x=>x.owner===MANUAL_COVER_PROJECTION_OWNER&&x.kind==='layout');layout.dividerLayout.future={owner:MANUAL_DIVIDER_STYLE_OWNER,version:2,kind:'divider-style',variant:'future',id:'opaque'};const state=createManualState({document:dto}),out=documentFromState(state);assert.deepEqual(Object.values(out.cover.extensions).find(x=>x.kind==='layout'&&x.owner===MANUAL_COVER_PROJECTION_OWNER).dividerLayout.future,layout.dividerLayout.future);assert.ok(findManualCoverRole(state,'cover','divider'));const projection=projectManualCover(out.cover),div=projection.headerBlocks.find(x=>getManualCoverProjection(x.extensions)?.role==='divider');assert.equal(readManualDividerStyle(div.extensions).variant,'default');
});
