import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeSelection} from '@tiptap/pm/state';
import {createManualState,documentFromState,findManualCoverRole,findManualObject,manualCommands,moveManualObject,duplicateManualObject} from '../src/redesign/manual-kernel.mjs';
import {setManualFigureWidth,resetManualFigureWidth,readManualFigureLayout,withManualFigureWidth} from '../src/redesign/manual-figure-layout.mjs';
import {projectManualCover,getManualCoverProjection} from '../src/redesign/manual-cover-legacy-projection.mjs';
import {encodeDocumentFile,decodeDocumentFile} from '../src/redesign/document-store.mjs';
const asset='assets/logo.png',bytes='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZasAAAAASUVORK5CYII=';
function fixture(extensions={vendor:{keep:1}}){return {schemaVersion:2,id:'doc',title:'Synthetic',cover:{id:'cover',logo:{src:asset,alt:'Logo'},title:[{type:'text',text:'Title'}],metadata:[],blocks:[],extensions},pages:[{id:'page',title:[],blocks:[]}]};}
function h(document=fixture()){let state=createManualState({document}),transactions=[];const dispatch=tr=>{transactions.push(tr);state=state.applyTransaction(tr).state;};const view={get state(){return state;},dispatch,composing:false,editable:true,props:{}};return {get state(){return state;},get document(){return documentFromState(state);},dispatch,transactions,view,run:(command,v=view)=>command(state,dispatch,v),logo:()=>findManualCoverRole(state,'cover','logo')};}
function exact(a){const document=a.document,record=decodeDocumentFile(encodeDocumentFile({document,assets:{[asset]:bytes}}));assert.deepEqual(record.document,document);assert.deepEqual(record.assets,{[asset]:bytes});assert.deepEqual(documentFromState(createManualState({document})),document);return document;}
function undoRedo(a,before){const after=a.state;assert.equal(a.run(manualCommands.undo),true);assert.ok(a.state.doc.eq(before.doc));assert.ok(a.state.selection.eq(before.selection));assert.equal(a.run(manualCommands.redo),true);assert.ok(a.state.doc.eq(after.doc));assert.ok(a.state.selection.eq(after.selection));}
test('bound logo resize uses one public figure transaction and preserves its scalar source, IDs, selection, asset bytes and saved physical width',()=>{
 const a=h(),found=a.logo(),id=found.node.attrs.id;a.dispatch(a.state.tr.setSelection(NodeSelection.create(a.state.doc,found.pos)).setStoredMarks([a.state.schema.marks.emphasis.create()]));const before=a.state,count=a.transactions.length;assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:235.5,revision:before.doc,minWidthPx:24,maxWidthPx:680})),true);assert.equal(a.transactions.length,count+1);assert.equal(a.logo().node.attrs.id,id);assert.deepEqual(a.document.cover.logo,fixture().cover.logo);assert.deepEqual(a.document.cover.extensions.vendor,{keep:1});assert.deepEqual(a.state.storedMarks,before.storedMarks);assert.ok(a.state.selection.eq(before.selection));assert.equal(readManualFigureLayout(a.logo().node.attrs.meta.extensions).widthPx,235.5);const d=exact(a),projected=projectManualCover(d.cover).headerBlocks.find(block=>getManualCoverProjection(block.extensions)?.role==='logo');assert.equal(readManualFigureLayout(projected.extensions).widthPx,235.5);assert.equal(projected.asset,asset);assert.deepEqual(projected.caption,[]);undoRedo(a,before);
});
test('reset restores the exact legacy logo DTO/default-width metadata and keeps unknown owned width payload',()=>{
 for(const extensions of [{vendor:{keep:1}},{}]){const source=fixture(extensions),a=h(source),id=a.logo().node.attrs.id;assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:180})),true);const before=a.state;assert.equal(a.run(resetManualFigureWidth({figureId:id})),true);assert.equal(readManualFigureLayout(a.logo().node.attrs.meta.extensions),null);assert.deepEqual(exact(a),source);undoRedo(a,before);}
 const a=h(),logo=a.logo(),meta=withManualFigureWidth(logo.node.attrs.meta,180),packet=readManualFigureLayout(meta.extensions);meta.extensions[packet.key].future={keep:2};a.dispatch(a.state.tr.setNodeMarkup(logo.pos,undefined,{...logo.node.attrs,meta}));const d=exact(a),layout=Object.values(d.cover.extensions).find(value=>value.owner==='@lk-design-system/manual-cover-projection');layout.futureLayout={keep:3};const b=h(d),id=b.logo().node.attrs.id;assert.equal(b.run(resetManualFigureWidth({figureId:id})),true);const restored=exact(b),projected=projectManualCover(restored.cover).headerBlocks.find(block=>getManualCoverProjection(block.extensions)?.role==='logo'),owned=readManualFigureLayout(projected.extensions);assert.equal(owned.widthPx,undefined);assert.deepEqual(projected.extensions[owned.key].future,{keep:2});assert.deepEqual(Object.values(restored.cover.extensions).find(value=>value.owner==='@lk-design-system/manual-cover-projection').futureLayout,{keep:3});assert.deepEqual(restored.cover.logo,fixture().cover.logo);
});
test('logo width guards reject invalid, stale, readonly, composed, cancelled and blocked commits without a transaction',()=>{
 const a=h(),id=a.logo().node.attrs.id,before=a.state,count=a.transactions.length;for(const widthPx of [0,-1,NaN,Infinity,'100'])assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx})),false);
 for(const options of [{revision:{}},{readOnly:true},{cancelled:true},{minWidthPx:200},{maxWidthPx:50}])assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:100,...options})),false);
 for(const view of [{editable:false},{composing:true},{props:{manualFigureResizeEnabled:false}},{props:{manualFigureResizeEnabled:()=>false}}])assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:100}),view),false);assert.equal(a.state,before);assert.equal(a.transactions.length,count);assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:100})),true);const sized=a.state;assert.equal(a.run(setManualFigureWidth({figureId:id,widthPx:100})),false);assert.equal(a.state,sized);
});
test('duplicated and foreign-moved logos retain custom width as ordinary figures without hijacking the cover scalar role',()=>{
 const a=h(),id=a.logo().node.attrs.id;a.run(setManualFigureWidth({figureId:id,widthPx:155}));assert.equal(a.run(duplicateManualObject(id)),true);const copied=a.document.cover.blocks[0];assert.equal(copied.type,'figure');assert.notEqual(copied.id,id);assert.equal(getManualCoverProjection(copied.extensions),null);assert.equal(readManualFigureLayout(copied.extensions).widthPx,155);assert.deepEqual(a.document.cover.logo,fixture().cover.logo);exact(a);
 const b=h();const logoId=b.logo().node.attrs.id;b.run(setManualFigureWidth({figureId:logoId,widthPx:155}));assert.equal(b.run(moveManualObject(logoId,{parentId:'page',index:1})),true);assert.equal(Object.hasOwn(b.document.cover,'logo'),false);const moved=b.document.pages[0].blocks[0];assert.equal(moved.id,logoId);assert.equal(moved.asset,asset);assert.equal(readManualFigureLayout(moved.extensions).widthPx,155);assert.equal(getManualCoverProjection(moved.extensions),null);assert.equal(findManualObject(b.state,logoId).node.type.name,'figure');exact(b);
});
