import test from 'node:test';
import assert from 'node:assert/strict';
import {Slice,Fragment} from '@tiptap/pm/model';
import {Selection,TextSelection} from '@tiptap/pm/state';
import {createEmptyManualDocument,validateManualDocument} from '../src/redesign/manual-v2.mjs';
import {createManualState,documentFromState,manualCommands,findManualObject,selectManualObject} from '../src/redesign/manual-kernel.mjs';
import {ManualBlockSelection,selectManualBlocks,selectCurrentManualBlock,editSelectedManualBlocks,extendManualBlockSelection,deleteSelectedManualBlocks,duplicateSelectedManualBlocks,moveSelectedManualBlocks,manualBlockSelectionPlugin} from '../src/redesign/manual-block-selection.mjs';
import {MANUAL_PAGINATION_OWNER} from '../src/redesign/manual-pagination-meta.mjs';
const paragraph=text=>({id:crypto.randomUUID(),type:'paragraph',content:[{type:'text',text,marks:[{type:'strong'}]}]});
function fixture(){const d=createEmptyManualDocument();d.pages[0].title=[{type:'text',text:'Page one'}];d.pages[0].blocks=[paragraph('one'),{id:crypto.randomUUID(),type:'callout',tone:'signal',title:[{type:'text',text:'Callout'}],blocks:[paragraph('inside')]},paragraph('three'),paragraph('four')];d.pages.push({id:crypto.randomUUID(),title:[{type:'text',text:'Page two'}],blocks:[paragraph('five'),paragraph('six')]});return d;}
function harness(d=fixture()){let state=createManualState({document:d,plugins:[manualBlockSelectionPlugin()]});const dispatch=tr=>state=state.applyTransaction(tr).state;return {get state(){return state;},get document(){const document=documentFromState(state);validateManualDocument(document);return document;},run:cmd=>cmd(state,dispatch),dispatch};}
function ids(value){const result=[];const walk=x=>{if(!x||typeof x!=='object')return;if(x.id)result.push(x.id);for(const [key,next]of Object.entries(x))if(key!=='extensions'&&typeof next==='object')Array.isArray(next)?next.forEach(walk):walk(next);};walk(value);return result;}

function paginationCopyFixture(){const d=fixture(),head=paragraph('head'),tail=paragraph('tail');head.extensions={vendor:{keep:true}};tail.extensions={vendor:{literalRef:head.id},manualPagination:{owner:MANUAL_PAGINATION_OWNER,version:1,kind:'block',rootBlockId:head.id,sourceType:'paragraph'}};d.pages[0].blocks=[head,tail,paragraph('outside')];return {d,head,tail};}
test('pagination fragment duplicate rewrites its copied root while preserving opaque extensions',()=>{
 const {d,head,tail}=paginationCopyFixture(),h=harness(d);h.run(selectManualBlocks(head.id,tail.id));h.run(duplicateSelectedManualBlocks);
 const [copyHead,copyTail]=h.document.pages[0].blocks.slice(2,4);assert.notEqual(copyHead.id,head.id);assert.notEqual(copyTail.id,tail.id);assert.equal(copyTail.extensions.manualPagination.rootBlockId,copyHead.id);assert.equal(copyTail.extensions.vendor.literalRef,head.id);assert.deepEqual(copyHead.extensions,head.extensions);assert.deepEqual(copyTail.content,tail.content);assert.deepEqual(h.document.pages[0].blocks.slice(0,2),[head,tail]);h.run(manualCommands.undo);assert.deepEqual(h.document,d);
});
test('pagination fragment duplicate without its root becomes an independent block',()=>{
 const {d,head,tail}=paginationCopyFixture(),h=harness(d);h.run(selectManualBlocks(tail.id));h.run(duplicateSelectedManualBlocks);
 const copy=h.document.pages[0].blocks[2];assert.notEqual(copy.id,tail.id);assert.deepEqual(copy.extensions,{vendor:{literalRef:head.id}});assert.deepEqual(copy.content,tail.content);assert.deepEqual(h.document.pages[0].blocks.slice(0,2),[head,tail]);h.run(manualCommands.undo);assert.deepEqual(h.document,d);
});

test('selects whole siblings with marks and nested objects, not page titles',()=>{const d=fixture(),h=harness(d);assert.equal(h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[2].id)),true);assert.ok(h.state.selection instanceof ManualBlockSelection);assert.equal(h.state.selection.content().content.childCount,3);assert.equal(h.state.selection.content().openStart,0);assert.deepEqual(h.document,d);assert.deepEqual(h.state.selection.ids,d.pages[0].blocks.slice(0,3).map(b=>b.id));assert.deepEqual(Selection.fromJSON(h.state.doc,h.state.selection.toJSON()).toJSON(),h.state.selection.toJSON());});
test('backward range selection extends and shrinks without changing the anchor block',()=>{const d=fixture(),h=harness(d),[a,b,c,e]=d.pages[0].blocks;h.run(selectManualBlocks(c.id,b.id));assert.ok(h.state.selection.anchor>h.state.selection.head);h.run(extendManualBlockSelection(-1));assert.deepEqual(h.state.selection.ids,[a.id,b.id,c.id]);assert.equal(h.state.selection.anchorId,c.id);h.run(extendManualBlockSelection(1));assert.deepEqual(h.state.selection.ids,[b.id,c.id]);h.run(extendManualBlockSelection(1));assert.deepEqual(h.state.selection.ids,[c.id]);h.run(extendManualBlockSelection(1));assert.deepEqual(h.state.selection.ids,[c.id,e.id]);});
test('multi-page content contains only selected blocks; cut preserves every page and title and is one undo',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[2].id,d.pages[1].blocks[0].id));assert.equal(h.state.selection.ranges.length,2);assert.equal(h.state.selection.content().content.childCount,3);const selected=h.state.selection.toJSON();h.dispatch(h.state.tr.deleteSelection().setMeta('uiEvent','cut'));const next=h.document;assert.equal(next.pages.length,2);assert.deepEqual(next.pages.map(p=>p.title),d.pages.map(p=>p.title));assert.equal(next.pages[0].blocks.length,2);assert.equal(next.pages[1].blocks.length,1);h.run(manualCommands.undo);assert.deepEqual(h.document,d);assert.deepEqual(h.state.selection.toJSON(),selected);});
test('deletes full block contents, retains page boundaries, and restores selected range with undo/redo',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[1].blocks.at(-1).id));const before=h.state.selection;h.run(deleteSelectedManualBlocks);assert.equal(h.document.pages[0].blocks.length,0);assert.equal(h.document.pages[1].blocks.length,0);assert.deepEqual(h.document.pages.map(p=>p.title),d.pages.map(p=>p.title));h.run(manualCommands.undo);assert.deepEqual(h.document,d);assert.ok(h.state.selection.eq(before));h.run(manualCommands.redo);assert.equal(h.document.pages[0].blocks.length,0);});
test('nested paragraph deletion retains callout title and does not delete the container',()=>{const d=fixture(),h=harness(d),callout=d.pages[0].blocks[1];h.run(selectManualBlocks(callout.blocks[0].id));h.run(deleteSelectedManualBlocks);assert.equal(h.document.pages[0].blocks[1].id,callout.id);assert.deepEqual(h.document.pages[0].blocks[1].title,callout.title);assert.equal(h.document.pages[0].blocks[1].blocks.length,0);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('deleting every quote paragraph inserts a valid empty paragraph, preserving the quote',()=>{const d=fixture();d.pages[0].blocks=[{id:crypto.randomUUID(),type:'quote',blocks:[paragraph('quote')]}];const h=harness(d),quote=d.pages[0].blocks[0];h.run(selectManualBlocks(quote.blocks[0].id));h.run(deleteSelectedManualBlocks);assert.equal(h.document.pages[0].blocks[0].id,quote.id);assert.deepEqual(h.document.pages[0].blocks[0].blocks[0].content,[]);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('duplicate range preserves all content with fresh descendant IDs and one undo',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[1].id));h.run(duplicateSelectedManualBlocks);const next=h.document;assert.equal(next.pages[0].blocks.length,6);assert.equal(next.pages[0].blocks[2].content[0].text,'one');assert.equal(next.pages[0].blocks[3].blocks[0].content[0].text,'inside');assert.equal(new Set(ids(next)).size,ids(next).length);assert.equal(h.state.selection.ids.length,2);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('multi-page duplicate produces one complete group at the end of the selected range',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks.at(-1).id,d.pages[1].blocks[0].id));h.run(duplicateSelectedManualBlocks);assert.deepEqual(h.document.pages[1].blocks.map(b=>b.content[0].text),['five','four','five','six']);assert.equal(new Set(ids(h.document)).size,ids(h.document).length);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('moves a group with stable IDs and one undo, refuses destinations inside the group',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[1].id));const before=h.state;assert.equal(h.run(moveSelectedManualBlocks({parentId:d.pages[0].id,index:2})),false);assert.equal(h.state,before);h.run(moveSelectedManualBlocks({direction:'down'}));assert.deepEqual(h.document.pages[0].blocks.map(b=>b.id),[d.pages[0].blocks[2].id,d.pages[0].blocks[0].id,d.pages[0].blocks[1].id,d.pages[0].blocks[3].id]);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('moves a multi-page group into another page without deleting page titles or changing IDs',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[2].id,d.pages[1].blocks[0].id));h.run(moveSelectedManualBlocks({parentId:d.pages[1].id,index:3}));assert.deepEqual(h.document.pages[1].blocks.map(b=>b.content[0].text),['six','three','four','five']);assert.deepEqual(h.document.pages.map(p=>p.title),d.pages.map(p=>p.title));assert.equal(new Set(ids(h.document)).size,ids(h.document).length);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('typing over selected blocks creates an editable paragraph and preserves surrounding content',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[1].id));h.dispatch(h.state.tr.insertText('replacement'));assert.equal(h.document.pages[0].blocks[0].content[0].text,'replacement');assert.equal(h.document.pages[0].blocks.length,3);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('paste over selected blocks preserves page titles and accepts complete block slices',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[2].id,d.pages[1].blocks[0].id));const node=h.state.schema.nodes.paragraph.create({id:crypto.randomUUID()},h.state.schema.text('pasted'));h.dispatch(h.state.tr.replaceSelection(new Slice(Fragment.from(node),0,0)));assert.equal(h.document.pages[0].blocks.at(-1).content[0].text,'pasted');assert.deepEqual(h.document.pages.map(p=>p.title),d.pages.map(p=>p.title));h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('Escape selects current nested text block then returns to a caret, composition blocks commands',()=>{const d=fixture(),h=harness(d),id=d.pages[0].blocks[1].blocks[0].id;h.run(selectManualObject(id));h.run(selectCurrentManualBlock);assert.deepEqual(h.state.selection.ids,[id]);h.run(selectCurrentManualBlock);assert.ok(h.state.selection instanceof TextSelection);const before=h.state;assert.equal(selectManualBlocks(id)(h.state,h.dispatch,{composing:true}),false);assert.equal(h.state,before);});
test('selection maps stable IDs through edits, and missing blocks collapse safely',()=>{const d=fixture(),h=harness(d),[one,,three]=d.pages[0].blocks;h.run(selectManualBlocks(one.id,three.id));const found=findManualObject(h.state,one.id);h.dispatch(h.state.tr.insertText('edit',found.pos+1));assert.deepEqual(h.state.selection.ids,[one.id,d.pages[0].blocks[1].id,three.id]);h.run(deleteSelectedManualBlocks);assert.ok(!(h.state.selection instanceof ManualBlockSelection));});
test('ShiftArrow crosses logical page boundaries and refuses selecting titles',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks.at(-1).id));h.run(extendManualBlockSelection(1));assert.equal(h.state.selection.ranges.length,2);const before=h.state;assert.equal(h.run(selectManualBlocks(d.pages[0].id)),false);assert.equal(h.state,before);});
test('dry run commands and invalid target ranges leave the document and selection untouched',()=>{const d=fixture(),h=harness(d);h.run(selectManualBlocks(d.pages[0].blocks[0].id,d.pages[0].blocks[1].id));const before=h.state;for(const command of [deleteSelectedManualBlocks,duplicateSelectedManualBlocks,moveSelectedManualBlocks({direction:'down'})])assert.equal(command(h.state),true);assert.equal(h.state,before);assert.equal(h.run(moveSelectedManualBlocks({parentId:'missing',index:0})),false);assert.equal(h.run(selectManualBlocks('missing')),false);assert.equal(h.state,before);});
test('deleting all selected steps keeps a valid procedure and restores the full range in one undo',()=>{const d=fixture(),steps=[{id:crypto.randomUUID(),title:[{type:'text',text:'first'}],blocks:[paragraph('one')]},{id:crypto.randomUUID(),title:[{type:'text',text:'second'}],blocks:[paragraph('two')]}];d.pages[0].blocks=[{id:crypto.randomUUID(),type:'procedure',start:4,steps}];const h=harness(d);h.run(selectManualBlocks(steps[0].id,steps[1].id));h.run(deleteSelectedManualBlocks);assert.equal(h.document.pages[0].blocks[0].id,d.pages[0].blocks[0].id);assert.equal(h.document.pages[0].blocks[0].steps.length,1);assert.equal(h.document.pages[0].blocks[0].start,4);assert.deepEqual(h.document.pages[0].blocks[0].steps[0].title,[]);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('a nested-to-outside range promotes its containing block and copies the visible selected objects',()=>{const d=fixture(),h=harness(d),callout=d.pages[0].blocks[1];h.run(selectManualBlocks(callout.blocks[0].id,d.pages[0].blocks[2].id));assert.deepEqual(h.state.selection.ids,[callout.id,d.pages[0].blocks[2].id]);assert.equal(h.state.selection.content().content.firstChild.type.name,'callout');});
test('duplicate rewrites internal anchors across the copied group and preserves links to outside blocks',()=>{const d=fixture(),[first,callout,outside]=d.pages[0].blocks;first.content=[{type:'text',text:'inside group',marks:[{type:'link',href:'#'+callout.blocks[0].id}]},{type:'text',text:'outside group',marks:[{type:'link',href:'#'+outside.id}]}];callout.extensions={vendor:{keep:'metadata'}};const h=harness(d);h.run(selectManualBlocks(first.id,callout.id));h.run(duplicateSelectedManualBlocks);const copy=h.document.pages[0].blocks.slice(2,4);assert.equal(copy[0].content[0].marks[0].href,'#'+copy[1].blocks[0].id);assert.equal(copy[0].content[1].marks[0].href,'#'+outside.id);assert.deepEqual(copy[1].extensions,callout.extensions);assert.equal(h.document.pages[0].blocks[0].content[0].marks[0].href,'#'+callout.blocks[0].id);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
test('Enter after a selected divider continues in a paragraph, while Escape only clears selection',()=>{const d=fixture(),divider={id:crypto.randomUUID(),type:'divider'};d.pages[0].blocks=[divider];const h=harness(d);h.run(selectManualBlocks(divider.id));h.run(selectCurrentManualBlock);assert.deepEqual(h.document,d);h.run(selectManualBlocks(divider.id));h.run(editSelectedManualBlocks);assert.equal(h.document.pages[0].blocks[1].type,'paragraph');assert.equal(h.state.selection.$from.parent.type.name,'paragraph');h.run(selectManualBlocks(divider.id));h.run(editSelectedManualBlocks);assert.equal(h.document.pages[0].blocks.length,2);h.run(manualCommands.undo);assert.deepEqual(h.document,d);});
