import test from 'node:test';
import assert from 'node:assert/strict';
import {TextSelection} from '@tiptap/pm/state';
import {createManualState,findManualObject,getManualSlashTrigger,executeManualBlockCommand} from '../src/redesign/manual-kernel.mjs';
import {installManualSlashCompositionChoice} from '../src/redesign/manual-slash-composition-choice.mjs';
function harness(){
 let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:[{type:'paragraph',id:'body',content:[{type:'text',text:'/표ㅈ'}]},{type:'paragraph',id:'other',content:[]}]}]}}),epoch=1,enabled=true,menu,ready=[],currentEditor;
 const body=findManualObject(state,'body');state=state.apply(state.tr.setSelection(TextSelection.create(state.doc,body.pos+1+body.node.content.size)));
 const surface=new EventTarget();surface.activeElement=null;const dom=new EventTarget(),editor={dom,composing:true,get state(){return state;}};currentEditor=editor;
 const button={isConnected:true,ownerDocument:surface,contains:target=>target===button};
 const refresh=()=>{menu={mode:'slash',editor,revision:state.doc,generation:epoch,selection:state.selection,trigger:getManualSlashTrigger(state)};};refresh();
 const helper=installManualSlashCompositionChoice({editor,getEditor:()=>currentEditor,getGeneration:()=>epoch,getMenu:()=>menu,isEnabled:()=>enabled,onReady:request=>ready.push(request),surface});
 const request=()=>helper.request({id:'cover',compositionChoice:true},button);
 // These deterministic source events exercise registered callbacks. They are
 // not browser/OS IME evidence and the product never dispatches such events.
 const end=()=>{editor.composing=false;dom.dispatchEvent(new Event('compositionend'));};
 return {helper,editor,surface,button,ready,request,end,refresh,get state(){return state;},get menu(){return menu;},setEnabled:value=>enabled=value,setEpoch:value=>epoch=value,setMode:value=>menu={...menu,mode:value},replaceEditor:()=>currentEditor={},apply(tr){state=state.applyTransaction(tr).state;helper.observe(state,tr);refresh();},focusButton(){surface.activeElement=button;},dispose:()=>helper.dispose()};
}
test('request writes nothing, waits for actual end callback and settled completion, then delivers final trigger once',()=>{const h=harness();try{const before=h.state;assert.equal(h.request(),true);assert.ok(h.state===before);h.focusButton();assert.equal(h.helper.finish(),false);assert.equal(h.ready.length,0);assert.equal(h.request(),true);const at=h.state.selection.from;h.apply(h.state.tr.insertText('지',at-1,at).setMeta('composition',7));h.end();assert.equal(h.ready.length,0);assert.equal(h.helper.finish(),false);assert.equal(h.ready.length,0);assert.equal(h.helper.confirm({id:'cover'},h.button),true);assert.equal(h.ready.length,1);assert.equal(h.ready[0].trigger.query,'표지');assert.equal(h.ready[0].doc,h.state.doc);assert.equal(h.helper.finish(),false);}finally{h.dispose();}});
for(const variant of ['unrelated','unmarked','selection','readonly','epoch','editor','mode','focus','disconnect'])test(`${variant} change cancels pending request`,()=>{const h=harness();try{h.request();h.focusButton();if(variant==='unrelated'){const other=findManualObject(h.state,'other');h.apply(h.state.tr.insertText('external',other.pos+1).setMeta('composition',7));}if(variant==='unmarked')h.apply(h.state.tr.insertText('X'));if(variant==='selection')h.apply(h.state.tr.setSelection(TextSelection.create(h.state.doc,findManualObject(h.state,'other').pos+1)));if(variant==='readonly')h.setEnabled(false);if(variant==='epoch')h.setEpoch(2);if(variant==='editor')h.replaceEditor();if(variant==='mode')h.setMode('block');if(variant==='focus')h.surface.activeElement={};if(variant==='disconnect')h.button.isConnected=false;h.end();assert.equal(h.helper.finish(),false);assert.equal(h.ready.length,0);}finally{h.dispose();}});
for(const eventName of ['pointerdown','focusin','keydown'])test(`${eventName} outside/Escape cancels pending request`,()=>{const h=harness();try{h.request();h.focusButton();const event=new Event(eventName);if(eventName==='keydown')Object.defineProperty(event,'key',{value:'Escape'});h.surface.dispatchEvent(event);h.end();assert.equal(h.helper.finish(),false);}finally{h.dispose();}});
test('unavailable/readonly requests do not alter composing or dispatch a command',()=>{const h=harness();try{h.setEnabled(false);const before=h.state;assert.equal(h.request(),false);assert.ok(h.state===before);assert.equal(h.editor.composing,true);assert.equal(executeManualBlockCommand('paragraph',{trigger:getManualSlashTrigger(h.state)})(h.state,()=>assert.fail('no dispatch'),h.editor),false);}finally{h.dispose();}});

test('settlement without a confirmed row click must not execute',()=>{const h=harness();try{h.request();h.focusButton();h.end();h.helper.finish();assert.equal(h.ready.length,0);}finally{h.dispose();}});
test('release outside the row after settlement must not execute',()=>{const h=harness();try{h.request();h.focusButton();h.end();h.helper.finish();h.surface.dispatchEvent(new Event('pointerup'));assert.equal(h.ready.length,0);}finally{h.dispose();}});

for(const order of ['click-first','settle-first'])test(`${order}: actual click confirmation plus settled composition delivers once`,()=>{const h=harness();try{h.request();h.focusButton();if(order==='click-first'){assert.equal(h.helper.confirm({id:'cover'},h.button),true);assert.equal(h.ready.length,0);}h.end();h.helper.finish();if(order==='settle-first'){assert.equal(h.ready.length,0);h.helper.confirm({id:'cover'},h.button);}assert.equal(h.ready.length,1);assert.equal(h.helper.confirm({id:'cover'},h.button),false);assert.equal(h.helper.finish(),false);assert.equal(h.ready.length,1);}finally{h.dispose();}});
