import test from 'node:test';import assert from 'node:assert/strict';import {Slice,Fragment} from '@tiptap/pm/model';import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {createManualState,findManualObject} from '../src/redesign/manual-kernel.mjs';import {selectManualTableCells} from '../src/redesign/manual-table-selection.mjs';import {selectManualBlocks} from '../src/redesign/manual-block-selection.mjs';
const text=t=>[{type:'text',text:t,marks:[{type:'strong'}]}],cell=(id,t)=>({id,content:Array.isArray(t)?t:text(t),extensions:{opaque:{keep:id}}});
function harness(contents=[['A','B','E'],['C','D','F']]){const rows=contents.map((row,r)=>row.map((value,c)=>cell(`c${r}${c}`,value))),table={id:'table',type:'table',label:'Synthetic',headers:rows[0],rows:rows.slice(1),extensions:{opaque:'table'}};let state=createManualState({document:{schemaVersion:2,id:'doc',title:'Synthetic',pages:[{id:'page',title:[],blocks:[table,{id:'p',type:'paragraph',content:text('ordinary')}]}]}});const dispatch=tr=>state=state.applyTransaction(tr).state;return {get state(){return state},dispatch,select(a='c00',b='c11',mode='rectangle'){assert(selectManualTableCells(a,b,{mode})(state,dispatch))},serialize(slice=state.selection.content()){const fn=state.plugins.find(p=>p.props.clipboardTextSerializer)?.props.clipboardTextSerializer;assert.equal(typeof fn,'function');return fn(slice,{state})}};}
for(const [mode,a,b,expected] of [['rectangle','c00','c11','A\tB\nC\tD'],['row','c10','c10','C\tD\tF'],['column','c01','c01','B\nD']])test(`actual plugin ${mode} copy preserves selected row/column delimiters and immutable HTML slice`,()=>{const h=harness();h.select(a,b,mode);const before=h.state,selected=before.selection.toJSON(),slice=before.selection.content(),snapshot=slice.toJSON();assert.equal(h.serialize(slice),expected);assert.deepEqual(slice.toJSON(),snapshot);assert.equal(h.state,before);assert.deepEqual(h.state.selection.toJSON(),selected);});
test('actual table serializer quotes embedded tab, newline, quote and hardBreak without changing content',()=>{const h=harness([['A\tB','say "yes"'],[[{type:'text',text:'top'},{type:'hardBreak'},{type:'text',text:'bottom'}],'last']]);h.select();assert.equal(h.serialize(),'"A\tB"\t"say ""yes"""\n"top\nbottom"\tlast');});
test('ordinary caret, node and block selections retain PM default plain text behavior',()=>{const h=harness();for(const kind of ['text','node','block']){const found=findManualObject(h.state,'p');if(kind==='block')selectManualBlocks('p')(h.state,h.dispatch);else h.dispatch(h.state.tr.setSelection(kind==='node'?NodeSelection.create(h.state.doc,found.pos):TextSelection.create(h.state.doc,found.pos+1,found.pos+found.node.nodeSize-1)));assert.equal(h.serialize(),null);}});
test('non-table and multi-node clipboard slices retain PM fallback even during cell selection',()=>{const h=harness();h.select();const p=findManualObject(h.state,'p').node;assert.equal(h.serialize(new Slice(Fragment.from(p),0,0)),null);assert.equal(h.serialize(new Slice(Fragment.fromArray([h.state.selection.content().content.firstChild,p]),0,0)),null);});
test('empty cells still retain rectangular dimensions in plain text',()=>{const h=harness([[[],[]],[[],[]]]);h.select();assert.equal(h.serialize(),'\t\n\t');});
